package net.mlcoder.unicode.category;

import javax.annotation.Nullable;
import java.util.ArrayList;
import java.util.List;


public class Arrow implements UniCode {
    public static final List<UniCode> symbols = new ArrayList<>();

    public final String desc;
    public final int codePoint;
    public final String chars;
    public final String generalCategory;
    public final int combiningClass;

    @Nullable
    public final String latex;

    @Override
    public String desc() {
        return desc;
    }

    @Override
    public int codePoint() {
        return codePoint;
    }

    @Override
    public String chars() {
        return chars;
    }

    @Override
    public String generalCategory() {
        return generalCategory;
    }

    @Override
    public int combiningClass() {
        return combiningClass;
    }

    @Override @Nullable
    public String latex() {
        return latex;
    }

    Arrow(String desc, int codePoint, String chars, String generalCategory, int combiningClass) {
        this(desc, codePoint, chars, generalCategory, combiningClass, null);
    }

    Arrow(String desc, int codePoint, String chars, String generalCategory, int combiningClass, String latex) {
        this.desc = desc;
        this.codePoint = codePoint;
        this.generalCategory = generalCategory;
        this.combiningClass = combiningClass;
        this.chars = chars;
        this.latex = latex;
    }

    @Override
    public String toString() {
        return "Arrow{" +
            "desc='" + desc + '\'' +
            ", codePoint=" + codePoint +
            ", chars='" + chars + '\'' +
            ", generalCategory='" + generalCategory + '\'' +
            ", combiningClass=" + combiningClass +
            ", latex='" + latex + '\'' +
            '}';
    }

    static {

        symbols.add(new Arrow("leftwards arrow", 0x2190, "←", "Sm", 0, "\\leftarrow"));
        symbols.add(new Arrow("upwards arrow", 0x2191, "↑", "Sm", 0, "\\uparrow"));
        symbols.add(new Arrow("rightwards arrow", 0x2192, "→", "Sm", 0, "\\rightarrow"));
        symbols.add(new Arrow("downwards arrow", 0x2193, "↓", "Sm", 0, "\\downarrow"));
        symbols.add(new Arrow("left right arrow", 0x2194, "↔", "Sm", 0, "\\leftrightarrow"));
        symbols.add(new Arrow("up down arrow", 0x2195, "↕", "So", 0, "\\updownarrow"));
        symbols.add(new Arrow("north west arrow", 0x2196, "↖", "So", 0, "\\nwarrow"));
        symbols.add(new Arrow("north east arrow", 0x2197, "↗", "So", 0, "\\nearrow"));
        symbols.add(new Arrow("south east arrow", 0x2198, "↘", "So", 0, "\\searrow"));
        symbols.add(new Arrow("south west arrow", 0x2199, "↙", "So", 0, "\\swarrow"));
        symbols.add(new Arrow("leftwards arrow with stroke", 0x219a, "↚", "Sm", 0, "\\nleftarrow"));
        symbols.add(new Arrow("rightwards arrow with stroke", 0x219b, "↛", "Sm", 0, "\\nrightarrow"));
        symbols.add(new Arrow("leftwards wave arrow", 0x219c, "↜", "So", 0, "\\leftwavearrow"));
        symbols.add(new Arrow("rightwards wave arrow", 0x219d, "↝", "So", 0, "\\rightwavearrow"));
        symbols.add(new Arrow("leftwards two headed arrow", 0x219e, "↞", "So", 0, "\\twoheadleftarrow"));
        symbols.add(new Arrow("upwards two headed arrow", 0x219f, "↟", "So", 0, "\\twoheaduparrow"));
        symbols.add(new Arrow("rightwards two headed arrow", 0x21a0, "↠", "Sm", 0, "\\twoheadrightarrow"));
        symbols.add(new Arrow("downwards two headed arrow", 0x21a1, "↡", "So", 0, "\\twoheaddownarrow"));
        symbols.add(new Arrow("leftwards arrow with tail", 0x21a2, "↢", "So", 0, "\\leftarrowtail"));
        symbols.add(new Arrow("rightwards arrow with tail", 0x21a3, "↣", "Sm", 0, "\\rightarrowtail"));
        symbols.add(new Arrow("leftwards arrow from bar", 0x21a4, "↤", "So", 0, "\\mapsfrom"));
        symbols.add(new Arrow("upwards arrow from bar", 0x21a5, "↥", "So", 0, "\\mapsup"));
        symbols.add(new Arrow("rightwards arrow from bar", 0x21a6, "↦", "Sm", 0, "\\mapsto"));
        symbols.add(new Arrow("downwards arrow from bar", 0x21a7, "↧", "So", 0, "\\mapsdown"));
        symbols.add(new Arrow("up down arrow with base", 0x21a8, "↨", "So", 0, "\\updownarrowbar"));
        symbols.add(new Arrow("leftwards arrow with hook", 0x21a9, "↩", "So", 0, "\\hookleftarrow"));
        symbols.add(new Arrow("rightwards arrow with hook", 0x21aa, "↪", "So", 0, "\\hookrightarrow"));
        symbols.add(new Arrow("leftwards arrow with loop", 0x21ab, "↫", "So", 0, "\\looparrowleft"));
        symbols.add(new Arrow("rightwards arrow with loop", 0x21ac, "↬", "So", 0, "\\looparrowright"));
        symbols.add(new Arrow("left right wave arrow", 0x21ad, "↭", "So", 0, "\\leftrightsquigarrow"));
        symbols.add(new Arrow("left right arrow with stroke", 0x21ae, "↮", "Sm", 0, "\\nleftrightarrow"));
        symbols.add(new Arrow("downwards zigzag arrow", 0x21af, "↯", "So", 0, "\\downzigzagarrow"));
        symbols.add(new Arrow("upwards arrow with tip leftwards", 0x21b0, "↰", "So", 0, "\\Lsh"));
        symbols.add(new Arrow("upwards arrow with tip rightwards", 0x21b1, "↱", "So", 0, "\\Rsh"));
        symbols.add(new Arrow("downwards arrow with tip leftwards", 0x21b2, "↲", "So", 0, "\\Ldsh"));
        symbols.add(new Arrow("downwards arrow with tip rightwards", 0x21b3, "↳", "So", 0, "\\Rdsh"));
        symbols.add(new Arrow("rightwards arrow with corner downwards", 0x21b4, "↴", "So", 0, "\\linefeed"));
        symbols.add(new Arrow("downwards arrow with corner leftwards", 0x21b5, "↵", "So", 0, "\\carriagereturn"));
        symbols.add(new Arrow("anticlockwise top semicircle arrow", 0x21b6, "↶", "So", 0, "\\curvearrowleft"));
        symbols.add(new Arrow("clockwise top semicircle arrow", 0x21b7, "↷", "So", 0, "\\curvearrowright"));
        symbols.add(new Arrow("north west arrow to long bar", 0x21b8, "↸", "So", 0, "\\barovernorthwestarrow"));
        symbols.add(new Arrow("leftwards arrow to bar over rightwards arrow to bar", 0x21b9, "↹", "So", 0, "\\barleftarrowrightarrowbar"));
        symbols.add(new Arrow("anticlockwise open circle arrow", 0x21ba, "↺", "So", 0, "\\acwopencirclearrow"));
        symbols.add(new Arrow("clockwise open circle arrow", 0x21bb, "↻", "So", 0, "\\cwopencirclearrow"));
        symbols.add(new Arrow("leftwards harpoon with barb upwards", 0x21bc, "↼", "So", 0, "\\leftharpoonup"));
        symbols.add(new Arrow("leftwards harpoon with barb downwards", 0x21bd, "↽", "So", 0, "\\leftharpoondown"));
        symbols.add(new Arrow("upwards harpoon with barb rightwards", 0x21be, "↾", "So", 0, "\\upharpoonright"));
        symbols.add(new Arrow("upwards harpoon with barb leftwards", 0x21bf, "↿", "So", 0, "\\upharpoonleft"));
        symbols.add(new Arrow("rightwards harpoon with barb upwards", 0x21c0, "⇀", "So", 0, "\\rightharpoonup"));
        symbols.add(new Arrow("rightwards harpoon with barb downwards", 0x21c1, "⇁", "So", 0, "\\rightharpoondown"));
        symbols.add(new Arrow("downwards harpoon with barb rightwards", 0x21c2, "⇂", "So", 0, "\\downharpoonright"));
        symbols.add(new Arrow("downwards harpoon with barb leftwards", 0x21c3, "⇃", "So", 0, "\\downharpoonleft"));
        symbols.add(new Arrow("rightwards arrow over leftwards arrow", 0x21c4, "⇄", "So", 0, "\\rightleftarrows"));
        symbols.add(new Arrow("upwards arrow leftwards of downwards arrow", 0x21c5, "⇅", "So", 0, "\\updownarrows"));
        symbols.add(new Arrow("leftwards arrow over rightwards arrow", 0x21c6, "⇆", "So", 0, "\\leftrightarrows"));
        symbols.add(new Arrow("leftwards paired arrows", 0x21c7, "⇇", "So", 0, "\\leftleftarrows"));
        symbols.add(new Arrow("upwards paired arrows", 0x21c8, "⇈", "So", 0, "\\upuparrows"));
        symbols.add(new Arrow("rightwards paired arrows", 0x21c9, "⇉", "So", 0, "\\rightrightarrows"));
        symbols.add(new Arrow("downwards paired arrows", 0x21ca, "⇊", "So", 0, "\\downdownarrows"));
        symbols.add(new Arrow("leftwards harpoon over rightwards harpoon", 0x21cb, "⇋", "So", 0, "\\leftrightharpoons"));
        symbols.add(new Arrow("rightwards harpoon over leftwards harpoon", 0x21cc, "⇌", "So", 0, "\\rightleftharpoons"));
        symbols.add(new Arrow("leftwards double arrow with stroke", 0x21cd, "⇍", "So", 0, "\\nLeftarrow"));
        symbols.add(new Arrow("left right double arrow with stroke", 0x21ce, "⇎", "Sm", 0, "\\nLeftrightarrow"));
        symbols.add(new Arrow("rightwards double arrow with stroke", 0x21cf, "⇏", "Sm", 0, "\\nRightarrow"));
        symbols.add(new Arrow("leftwards double arrow", 0x21d0, "⇐", "So", 0, "\\Leftarrow"));
        symbols.add(new Arrow("upwards double arrow", 0x21d1, "⇑", "So", 0, "\\Uparrow"));
        symbols.add(new Arrow("rightwards double arrow", 0x21d2, "⇒", "Sm", 0, "\\Rightarrow"));
        symbols.add(new Arrow("downwards double arrow", 0x21d3, "⇓", "So", 0, "\\Downarrow"));
        symbols.add(new Arrow("left right double arrow", 0x21d4, "⇔", "Sm", 0, "\\Leftrightarrow"));
        symbols.add(new Arrow("up down double arrow", 0x21d5, "⇕", "So", 0, "\\Updownarrow"));
        symbols.add(new Arrow("north west double arrow", 0x21d6, "⇖", "So", 0, "\\Nwarrow"));
        symbols.add(new Arrow("north east double arrow", 0x21d7, "⇗", "So", 0, "\\Nearrow"));
        symbols.add(new Arrow("south east double arrow", 0x21d8, "⇘", "So", 0, "\\Searrow"));
        symbols.add(new Arrow("south west double arrow", 0x21d9, "⇙", "So", 0, "\\Swarrow"));
        symbols.add(new Arrow("leftwards triple arrow", 0x21da, "⇚", "So", 0, "\\Lleftarrow"));
        symbols.add(new Arrow("rightwards triple arrow", 0x21db, "⇛", "So", 0, "\\Rrightarrow"));
        symbols.add(new Arrow("leftwards squiggle arrow", 0x21dc, "⇜", "So", 0, "\\leftsquigarrow"));
        symbols.add(new Arrow("rightwards squiggle arrow", 0x21dd, "⇝", "So", 0, "\\rightsquigarrow"));
        symbols.add(new Arrow("upwards arrow with double stroke", 0x21de, "⇞", "So", 0, "\\nHuparrow"));
        symbols.add(new Arrow("downwards arrow with double stroke", 0x21df, "⇟", "So", 0, "\\nHdownarrow"));
        symbols.add(new Arrow("leftwards dashed arrow", 0x21e0, "⇠", "So", 0, "\\leftdasharrow"));
        symbols.add(new Arrow("upwards dashed arrow", 0x21e1, "⇡", "So", 0, "\\updasharrow"));
        symbols.add(new Arrow("rightwards dashed arrow", 0x21e2, "⇢", "So", 0, "\\rightdasharrow"));
        symbols.add(new Arrow("downwards dashed arrow", 0x21e3, "⇣", "So", 0, "\\downdasharrow"));
        symbols.add(new Arrow("leftwards arrow to bar", 0x21e4, "⇤", "So", 0, "\\barleftarrow"));
        symbols.add(new Arrow("rightwards arrow to bar", 0x21e5, "⇥", "So", 0, "\\rightarrowbar"));
        symbols.add(new Arrow("leftwards white arrow", 0x21e6, "⇦", "So", 0, "\\leftwhitearrow"));
        symbols.add(new Arrow("upwards white arrow", 0x21e7, "⇧", "So", 0, "\\upwhitearrow"));
        symbols.add(new Arrow("rightwards white arrow", 0x21e8, "⇨", "So", 0, "\\rightwhitearrow"));
        symbols.add(new Arrow("downwards white arrow", 0x21e9, "⇩", "So", 0, "\\downwhitearrow"));
        symbols.add(new Arrow("upwards white arrow from bar", 0x21ea, "⇪", "So", 0, "\\whitearrowupfrombar"));
        symbols.add(new Arrow("upwards white arrow on pedestal", 0x21eb, "⇫", "So", 0));
        symbols.add(new Arrow("upwards white arrow on pedestal with horizontal bar", 0x21ec, "⇬", "So", 0));
        symbols.add(new Arrow("upwards white arrow on pedestal with vertical bar", 0x21ed, "⇭", "So", 0));
        symbols.add(new Arrow("upwards white double arrow", 0x21ee, "⇮", "So", 0));
        symbols.add(new Arrow("upwards white double arrow on pedestal", 0x21ef, "⇯", "So", 0));
        symbols.add(new Arrow("rightwards white arrow from wall", 0x21f0, "⇰", "So", 0));
        symbols.add(new Arrow("north west arrow to corner", 0x21f1, "⇱", "So", 0));
        symbols.add(new Arrow("south east arrow to corner", 0x21f2, "⇲", "So", 0));
        symbols.add(new Arrow("up down white arrow", 0x21f3, "⇳", "So", 0));
        symbols.add(new Arrow("right arrow with circle", 0x21f4, "⇴", "Sm", 0, "\\circleonrightarrow"));
        symbols.add(new Arrow("downwards arrow leftwards of upwards arrow", 0x21f5, "⇵", "Sm", 0, "\\downuparrows"));
        symbols.add(new Arrow("three rightwards arrows", 0x21f6, "⇶", "Sm", 0, "\\rightthreearrows"));
        symbols.add(new Arrow("leftwards arrow with vertical stroke", 0x21f7, "⇷", "Sm", 0, "\\nvleftarrow"));
        symbols.add(new Arrow("rightwards arrow with vertical stroke", 0x21f8, "⇸", "Sm", 0, "\\nvrightarrow"));
        symbols.add(new Arrow("left right arrow with vertical stroke", 0x21f9, "⇹", "Sm", 0, "\\nvleftrightarrow"));
        symbols.add(new Arrow("leftwards arrow with double vertical stroke", 0x21fa, "⇺", "Sm", 0, "\\nVleftarrow"));
        symbols.add(new Arrow("rightwards arrow with double vertical stroke", 0x21fb, "⇻", "Sm", 0, "\\nVrightarrow"));
        symbols.add(new Arrow("left right arrow with double vertical stroke", 0x21fc, "⇼", "Sm", 0, "\\nVleftrightarrow"));
        symbols.add(new Arrow("leftwards open-headed arrow", 0x21fd, "⇽", "Sm", 0, "\\leftarrowtriangle"));
        symbols.add(new Arrow("rightwards open-headed arrow", 0x21fe, "⇾", "Sm", 0, "\\rightarrowtriangle"));
        symbols.add(new Arrow("left right open-headed arrow", 0x21ff, "⇿", "Sm", 0, "\\leftrightarrowtriangle"));
        symbols.add(new Arrow("upwards quadruple arrow", 0x27f0, "⟰", "Sm", 0, "\\UUparrow"));
        symbols.add(new Arrow("downwards quadruple arrow", 0x27f1, "⟱", "Sm", 0, "\\DDownarrow"));
        symbols.add(new Arrow("anticlockwise gapped circle arrow", 0x27f2, "⟲", "Sm", 0, "\\acwgapcirclearrow"));
        symbols.add(new Arrow("clockwise gapped circle arrow", 0x27f3, "⟳", "Sm", 0, "\\cwgapcirclearrow"));
        symbols.add(new Arrow("right arrow with circled plus", 0x27f4, "⟴", "Sm", 0, "\\rightarrowonoplus"));
        symbols.add(new Arrow("long leftwards arrow", 0x27f5, "⟵", "Sm", 0, "\\longleftarrow"));
        symbols.add(new Arrow("long rightwards arrow", 0x27f6, "⟶", "Sm", 0, "\\longrightarrow"));
        symbols.add(new Arrow("long left right arrow", 0x27f7, "⟷", "Sm", 0, "\\longleftrightarrow"));
        symbols.add(new Arrow("long leftwards double arrow", 0x27f8, "⟸", "Sm", 0, "\\Longleftarrow"));
        symbols.add(new Arrow("long rightwards double arrow", 0x27f9, "⟹", "Sm", 0, "\\Longrightarrow"));
        symbols.add(new Arrow("long left right double arrow", 0x27fa, "⟺", "Sm", 0, "\\Longleftrightarrow"));
        symbols.add(new Arrow("long leftwards arrow from bar", 0x27fb, "⟻", "Sm", 0, "\\longmapsfrom"));
        symbols.add(new Arrow("long rightwards arrow from bar", 0x27fc, "⟼", "Sm", 0, "\\longmapsto"));
        symbols.add(new Arrow("long leftwards double arrow from bar", 0x27fd, "⟽", "Sm", 0, "\\Longmapsfrom"));
        symbols.add(new Arrow("long rightwards double arrow from bar", 0x27fe, "⟾", "Sm", 0, "\\Longmapsto"));
        symbols.add(new Arrow("long rightwards squiggle arrow", 0x27ff, "⟿", "Sm", 0, "\\longrightsquigarrow"));
        symbols.add(new Arrow("rightwards two-headed arrow with vertical stroke", 0x2900, "⤀", "Sm", 0, "\\nvtwoheadrightarrow"));
        symbols.add(new Arrow("rightwards two-headed arrow with double vertical stroke", 0x2901, "⤁", "Sm", 0, "\\nVtwoheadrightarrow"));
        symbols.add(new Arrow("leftwards double arrow with vertical stroke", 0x2902, "⤂", "Sm", 0, "\\nvLeftarrow"));
        symbols.add(new Arrow("rightwards double arrow with vertical stroke", 0x2903, "⤃", "Sm", 0, "\\nvRightarrow"));
        symbols.add(new Arrow("left right double arrow with vertical stroke", 0x2904, "⤄", "Sm", 0, "\\nvLeftrightarrow"));
        symbols.add(new Arrow("rightwards two-headed arrow from bar", 0x2905, "⤅", "Sm", 0, "\\twoheadmapsto"));
        symbols.add(new Arrow("leftwards double arrow from bar", 0x2906, "⤆", "Sm", 0, "\\Mapsfrom"));
        symbols.add(new Arrow("rightwards double arrow from bar", 0x2907, "⤇", "Sm", 0, "\\Mapsto"));
        symbols.add(new Arrow("downwards arrow with horizontal stroke", 0x2908, "⤈", "Sm", 0, "\\downarrowbarred"));
        symbols.add(new Arrow("upwards arrow with horizontal stroke", 0x2909, "⤉", "Sm", 0, "\\uparrowbarred"));
        symbols.add(new Arrow("upwards triple arrow", 0x290a, "⤊", "Sm", 0, "\\Uuparrow"));
        symbols.add(new Arrow("downwards triple arrow", 0x290b, "⤋", "Sm", 0, "\\Ddownarrow"));
        symbols.add(new Arrow("leftwards double dash arrow", 0x290c, "⤌", "Sm", 0, "\\leftbkarrow"));
        symbols.add(new Arrow("rightwards double dash arrow", 0x290d, "⤍", "Sm", 0, "\\rightbkarrow"));
        symbols.add(new Arrow("leftwards triple dash arrow", 0x290e, "⤎", "Sm", 0, "\\leftdbkarrow"));
        symbols.add(new Arrow("rightwards triple dash arrow", 0x290f, "⤏", "Sm", 0, "\\dbkarrow"));
        symbols.add(new Arrow("rightwards two-headed triple dash arrow", 0x2910, "⤐", "Sm", 0, "\\drbkarrow"));
        symbols.add(new Arrow("rightwards arrow with dotted stem", 0x2911, "⤑", "Sm", 0, "\\rightdotarrow"));
        symbols.add(new Arrow("upwards arrow to bar", 0x2912, "⤒", "Sm", 0, "\\baruparrow"));
        symbols.add(new Arrow("downwards arrow to bar", 0x2913, "⤓", "Sm", 0, "\\downarrowbar"));
        symbols.add(new Arrow("rightwards arrow with tail with vertical stroke", 0x2914, "⤔", "Sm", 0, "\\nvrightarrowtail"));
        symbols.add(new Arrow("rightwards arrow with tail with double vertical stroke", 0x2915, "⤕", "Sm", 0, "\\nVrightarrowtail"));
        symbols.add(new Arrow("rightwards two-headed arrow with tail", 0x2916, "⤖", "Sm", 0, "\\twoheadrightarrowtail"));
        symbols.add(new Arrow("rightwards two-headed arrow with tail with vertical stroke", 0x2917, "⤗", "Sm", 0, "\\nvtwoheadrightarrowtail"));
        symbols.add(new Arrow("rightwards two-headed arrow with tail with double vertical stroke", 0x2918, "⤘", "Sm", 0, "\\nVtwoheadrightarrowtail"));
        symbols.add(new Arrow("leftwards arrow-tail", 0x2919, "⤙", "Sm", 0, "\\lefttail"));
        symbols.add(new Arrow("rightwards arrow-tail", 0x291a, "⤚", "Sm", 0, "\\righttail"));
        symbols.add(new Arrow("leftwards double arrow-tail", 0x291b, "⤛", "Sm", 0, "\\leftdbltail"));
        symbols.add(new Arrow("rightwards double arrow-tail", 0x291c, "⤜", "Sm", 0, "\\rightdbltail"));
        symbols.add(new Arrow("leftwards arrow to black diamond", 0x291d, "⤝", "Sm", 0, "\\diamondleftarrow"));
        symbols.add(new Arrow("rightwards arrow to black diamond", 0x291e, "⤞", "Sm", 0, "\\rightarrowdiamond"));
        symbols.add(new Arrow("leftwards arrow from bar to black diamond", 0x291f, "⤟", "Sm", 0, "\\diamondleftarrowbar"));
        symbols.add(new Arrow("rightwards arrow from bar to black diamond", 0x2920, "⤠", "Sm", 0, "\\barrightarrowdiamond"));
        symbols.add(new Arrow("north west and south east arrow", 0x2921, "⤡", "Sm", 0, "\\nwsearrow"));
        symbols.add(new Arrow("north east and south west arrow", 0x2922, "⤢", "Sm", 0, "\\neswarrow"));
        symbols.add(new Arrow("north west arrow with hook", 0x2923, "⤣", "Sm", 0, "\\hknwarrow"));
        symbols.add(new Arrow("north east arrow with hook", 0x2924, "⤤", "Sm", 0, "\\hknearrow"));
        symbols.add(new Arrow("south east arrow with hook", 0x2925, "⤥", "Sm", 0, "\\hksearrow"));
        symbols.add(new Arrow("south west arrow with hook", 0x2926, "⤦", "Sm", 0, "\\hkswarrow"));
        symbols.add(new Arrow("north west arrow and north east arrow", 0x2927, "⤧", "Sm", 0, "\\tona"));
        symbols.add(new Arrow("north east arrow and south east arrow", 0x2928, "⤨", "Sm", 0, "\\toea"));
        symbols.add(new Arrow("south east arrow and south west arrow", 0x2929, "⤩", "Sm", 0, "\\tosa"));
        symbols.add(new Arrow("south west arrow and north west arrow", 0x292a, "⤪", "Sm", 0, "\\towa"));
        symbols.add(new Arrow("rising diagonal crossing falling diagonal", 0x292b, "⤫", "Sm", 0, "\\rdiagovfdiag"));
        symbols.add(new Arrow("falling diagonal crossing rising diagonal", 0x292c, "⤬", "Sm", 0, "\\fdiagovrdiag"));
        symbols.add(new Arrow("south east arrow crossing north east arrow", 0x292d, "⤭", "Sm", 0, "\\seovnearrow"));
        symbols.add(new Arrow("north east arrow crossing south east arrow", 0x292e, "⤮", "Sm", 0, "\\neovsearrow"));
        symbols.add(new Arrow("falling diagonal crossing north east arrow", 0x292f, "⤯", "Sm", 0, "\\fdiagovnearrow"));
        symbols.add(new Arrow("rising diagonal crossing south east arrow", 0x2930, "⤰", "Sm", 0, "\\rdiagovsearrow"));
        symbols.add(new Arrow("north east arrow crossing north west arrow", 0x2931, "⤱", "Sm", 0, "\\neovnwarrow"));
        symbols.add(new Arrow("north west arrow crossing north east arrow", 0x2932, "⤲", "Sm", 0, "\\nwovnearrow"));
        symbols.add(new Arrow("wave arrow pointing directly right", 0x2933, "⤳", "Sm", 0, "\\rightcurvedarrow"));
        symbols.add(new Arrow("arrow pointing rightwards then curving upwards", 0x2934, "⤴", "Sm", 0, "\\uprightcurvearrow"));
        symbols.add(new Arrow("arrow pointing rightwards then curving downwards", 0x2935, "⤵", "Sm", 0, "\\downrightcurvedarrow"));
        symbols.add(new Arrow("arrow pointing downwards then curving leftwards", 0x2936, "⤶", "Sm", 0, "\\leftdowncurvedarrow"));
        symbols.add(new Arrow("arrow pointing downwards then curving rightwards", 0x2937, "⤷", "Sm", 0, "\\rightdowncurvedarrow"));
        symbols.add(new Arrow("right-side arc clockwise arrow", 0x2938, "⤸", "Sm", 0, "\\cwrightarcarrow"));
        symbols.add(new Arrow("left-side arc anticlockwise arrow", 0x2939, "⤹", "Sm", 0, "\\acwleftarcarrow"));
        symbols.add(new Arrow("top arc anticlockwise arrow", 0x293a, "⤺", "Sm", 0, "\\acwoverarcarrow"));
        symbols.add(new Arrow("bottom arc anticlockwise arrow", 0x293b, "⤻", "Sm", 0, "\\acwunderarcarrow"));
        symbols.add(new Arrow("top arc clockwise arrow with minus", 0x293c, "⤼", "Sm", 0, "\\curvearrowrightminus"));
        symbols.add(new Arrow("top arc anticlockwise arrow with plus", 0x293d, "⤽", "Sm", 0, "\\curvearrowleftplus"));
        symbols.add(new Arrow("lower right semicircular clockwise arrow", 0x293e, "⤾", "Sm", 0, "\\cwundercurvearrow"));
        symbols.add(new Arrow("lower left semicircular anticlockwise arrow", 0x293f, "⤿", "Sm", 0, "\\ccwundercurvearrow"));
        symbols.add(new Arrow("anticlockwise closed circle arrow", 0x2940, "⥀", "Sm", 0, "\\acwcirclearrow"));
        symbols.add(new Arrow("clockwise closed circle arrow", 0x2941, "⥁", "Sm", 0, "\\cwcirclearrow"));
        symbols.add(new Arrow("rightwards arrow above short leftwards arrow", 0x2942, "⥂", "Sm", 0, "\\rightarrowshortleftarrow"));
        symbols.add(new Arrow("leftwards arrow above short rightwards arrow", 0x2943, "⥃", "Sm", 0, "\\leftarrowshortrightarrow"));
        symbols.add(new Arrow("short rightwards arrow above leftwards arrow", 0x2944, "⥄", "Sm", 0, "\\shortrightarrowleftarrow"));
        symbols.add(new Arrow("rightwards arrow with plus below", 0x2945, "⥅", "Sm", 0, "\\rightarrowplus"));
        symbols.add(new Arrow("leftwards arrow with plus below", 0x2946, "⥆", "Sm", 0, "\\leftarrowplus"));
        symbols.add(new Arrow("rightwards arrow through x", 0x2947, "⥇", "Sm", 0, "\\rightarrowx"));
        symbols.add(new Arrow("left right arrow through circle", 0x2948, "⥈", "Sm", 0, "\\leftrightarrowcircle"));
        symbols.add(new Arrow("upwards two-headed arrow from circle", 0x2949, "⥉", "Sm", 0, "\\twoheaduparrowcircle"));
        symbols.add(new Arrow("left barb up right barb down harpoon", 0x294a, "⥊", "Sm", 0, "\\leftrightharpoonupdown"));
        symbols.add(new Arrow("left barb down right barb up harpoon", 0x294b, "⥋", "Sm", 0, "\\leftrightharpoondownup"));
        symbols.add(new Arrow("up barb right down barb left harpoon", 0x294c, "⥌", "Sm", 0, "\\updownharpoonrightleft"));
        symbols.add(new Arrow("up barb left down barb right harpoon", 0x294d, "⥍", "Sm", 0, "\\updownharpoonleftright"));
        symbols.add(new Arrow("left barb up right barb up harpoon", 0x294e, "⥎", "Sm", 0, "\\leftrightharpoonupup"));
        symbols.add(new Arrow("up barb right down barb right harpoon", 0x294f, "⥏", "Sm", 0, "\\updownharpoonrightright"));
        symbols.add(new Arrow("left barb down right barb down harpoon", 0x2950, "⥐", "Sm", 0, "\\leftrightharpoondowndown"));
        symbols.add(new Arrow("up barb left down barb left harpoon", 0x2951, "⥑", "Sm", 0, "\\updownharpoonleftleft"));
        symbols.add(new Arrow("leftwards harpoon with barb up to bar", 0x2952, "⥒", "Sm", 0, "\\barleftharpoonup"));
        symbols.add(new Arrow("rightwards harpoon with barb up to bar", 0x2953, "⥓", "Sm", 0, "\\rightharpoonupbar"));
        symbols.add(new Arrow("upwards harpoon with barb right to bar", 0x2954, "⥔", "Sm", 0, "\\barupharpoonright"));
        symbols.add(new Arrow("downwards harpoon with barb right to bar", 0x2955, "⥕", "Sm", 0, "\\downharpoonrightbar"));
        symbols.add(new Arrow("leftwards harpoon with barb down to bar", 0x2956, "⥖", "Sm", 0, "\\barleftharpoondown"));
        symbols.add(new Arrow("rightwards harpoon with barb down to bar", 0x2957, "⥗", "Sm", 0, "\\rightharpoondownbar"));
        symbols.add(new Arrow("upwards harpoon with barb left to bar", 0x2958, "⥘", "Sm", 0, "\\barupharpoonleft"));
        symbols.add(new Arrow("downwards harpoon with barb left to bar", 0x2959, "⥙", "Sm", 0, "\\downharpoonleftbar"));
        symbols.add(new Arrow("leftwards harpoon with barb up from bar", 0x295a, "⥚", "Sm", 0, "\\leftharpoonupbar"));
        symbols.add(new Arrow("rightwards harpoon with barb up from bar", 0x295b, "⥛", "Sm", 0, "\\barrightharpoonup"));
        symbols.add(new Arrow("upwards harpoon with barb right from bar", 0x295c, "⥜", "Sm", 0, "\\upharpoonrightbar"));
        symbols.add(new Arrow("downwards harpoon with barb right from bar", 0x295d, "⥝", "Sm", 0, "\\bardownharpoonright"));
        symbols.add(new Arrow("leftwards harpoon with barb down from bar", 0x295e, "⥞", "Sm", 0, "\\leftharpoondownbar"));
        symbols.add(new Arrow("rightwards harpoon with barb down from bar", 0x295f, "⥟", "Sm", 0, "\\barrightharpoondown"));
        symbols.add(new Arrow("upwards harpoon with barb left from bar", 0x2960, "⥠", "Sm", 0, "\\upharpoonleftbar"));
        symbols.add(new Arrow("downwards harpoon with barb left from bar", 0x2961, "⥡", "Sm", 0, "\\bardownharpoonleft"));
        symbols.add(new Arrow("leftwards harpoon with barb up above leftwards harpoon with barb down", 0x2962, "⥢", "Sm", 0, "\\leftharpoonsupdown"));
        symbols.add(new Arrow("upwards harpoon with barb left beside upwards harpoon with barb right", 0x2963, "⥣", "Sm", 0, "\\upharpoonsleftright"));
        symbols.add(new Arrow("rightwards harpoon with barb up above rightwards harpoon with barb down", 0x2964, "⥤", "Sm", 0, "\\rightharpoonsupdown"));
        symbols.add(new Arrow("downwards harpoon with barb left beside downwards harpoon with barb right", 0x2965, "⥥", "Sm", 0, "\\downharpoonsleftright"));
        symbols.add(new Arrow("leftwards harpoon with barb up above rightwards harpoon with barb up", 0x2966, "⥦", "Sm", 0, "\\leftrightharpoonsup"));
        symbols.add(new Arrow("leftwards harpoon with barb down above rightwards harpoon with barb down", 0x2967, "⥧", "Sm", 0, "\\leftrightharpoonsdown"));
        symbols.add(new Arrow("rightwards harpoon with barb up above leftwards harpoon with barb up", 0x2968, "⥨", "Sm", 0, "\\rightleftharpoonsup"));
        symbols.add(new Arrow("rightwards harpoon with barb down above leftwards harpoon with barb down", 0x2969, "⥩", "Sm", 0, "\\rightleftharpoonsdown"));
        symbols.add(new Arrow("leftwards harpoon with barb up above long dash", 0x296a, "⥪", "Sm", 0, "\\leftharpoonupdash"));
        symbols.add(new Arrow("leftwards harpoon with barb down below long dash", 0x296b, "⥫", "Sm", 0, "\\dashleftharpoondown"));
        symbols.add(new Arrow("rightwards harpoon with barb up above long dash", 0x296c, "⥬", "Sm", 0, "\\rightharpoonupdash"));
        symbols.add(new Arrow("rightwards harpoon with barb down below long dash", 0x296d, "⥭", "Sm", 0, "\\dashrightharpoondown"));
        symbols.add(new Arrow("upwards harpoon with barb left beside downwards harpoon with barb right", 0x296e, "⥮", "Sm", 0, "\\updownharpoonsleftright"));
        symbols.add(new Arrow("downwards harpoon with barb left beside upwards harpoon with barb right", 0x296f, "⥯", "Sm", 0, "\\downupharpoonsleftright"));
        symbols.add(new Arrow("right double arrow with rounded head", 0x2970, "⥰", "Sm", 0, "\\rightimply"));
        symbols.add(new Arrow("equals sign above rightwards arrow", 0x2971, "⥱", "Sm", 0, "\\equalrightarrow"));
        symbols.add(new Arrow("tilde operator above rightwards arrow", 0x2972, "⥲", "Sm", 0, "\\similarrightarrow"));
        symbols.add(new Arrow("leftwards arrow above tilde operator", 0x2973, "⥳", "Sm", 0, "\\leftarrowsimilar"));
        symbols.add(new Arrow("rightwards arrow above tilde operator", 0x2974, "⥴", "Sm", 0, "\\rightarrowsimilar"));
        symbols.add(new Arrow("rightwards arrow above almost equal to", 0x2975, "⥵", "Sm", 0, "\\rightarrowapprox"));
        symbols.add(new Arrow("less-than above leftwards arrow", 0x2976, "⥶", "Sm", 0, "\\ltlarr"));
        symbols.add(new Arrow("leftwards arrow through less-than", 0x2977, "⥷", "Sm", 0, "\\leftarrowless"));
        symbols.add(new Arrow("greater-than above rightwards arrow", 0x2978, "⥸", "Sm", 0, "\\gtrarr"));
        symbols.add(new Arrow("subset above rightwards arrow", 0x2979, "⥹", "Sm", 0, "\\subrarr"));
        symbols.add(new Arrow("leftwards arrow through subset", 0x297a, "⥺", "Sm", 0, "\\leftarrowsubset"));
        symbols.add(new Arrow("superset above leftwards arrow", 0x297b, "⥻", "Sm", 0, "\\suplarr"));
        symbols.add(new Arrow("left fish tail", 0x297c, "⥼", "Sm", 0, "\\leftfishtail"));
        symbols.add(new Arrow("right fish tail", 0x297d, "⥽", "Sm", 0, "\\rightfishtail"));
        symbols.add(new Arrow("up fish tail", 0x297e, "⥾", "Sm", 0, "\\upfishtail"));
        symbols.add(new Arrow("down fish tail", 0x297f, "⥿", "Sm", 0, "\\downfishtail"));
        symbols.add(new Arrow("north east white arrow", 0x2b00, "⬀", "So", 0));
        symbols.add(new Arrow("north west white arrow", 0x2b01, "⬁", "So", 0));
        symbols.add(new Arrow("south east white arrow", 0x2b02, "⬂", "So", 0));
        symbols.add(new Arrow("south west white arrow", 0x2b03, "⬃", "So", 0));
        symbols.add(new Arrow("left right white arrow", 0x2b04, "⬄", "So", 0));
        symbols.add(new Arrow("leftwards black arrow", 0x2b05, "⬅", "So", 0));
        symbols.add(new Arrow("upwards black arrow", 0x2b06, "⬆", "So", 0));
        symbols.add(new Arrow("downwards black arrow", 0x2b07, "⬇", "So", 0));
        symbols.add(new Arrow("north east black arrow", 0x2b08, "⬈", "So", 0));
        symbols.add(new Arrow("north west black arrow", 0x2b09, "⬉", "So", 0));
        symbols.add(new Arrow("south east black arrow", 0x2b0a, "⬊", "So", 0));
        symbols.add(new Arrow("south west black arrow", 0x2b0b, "⬋", "So", 0));
        symbols.add(new Arrow("left right black arrow", 0x2b0c, "⬌", "So", 0));
        symbols.add(new Arrow("up down black arrow", 0x2b0d, "⬍", "So", 0));
        symbols.add(new Arrow("rightwards arrow with tip downwards", 0x2b0e, "⬎", "So", 0));
        symbols.add(new Arrow("rightwards arrow with tip upwards", 0x2b0f, "⬏", "So", 0));
        symbols.add(new Arrow("leftwards arrow with tip downwards", 0x2b10, "⬐", "So", 0));
        symbols.add(new Arrow("leftwards arrow with tip upwards", 0x2b11, "⬑", "So", 0));
        symbols.add(new Arrow("square with top half black", 0x2b12, "⬒", "So", 0, "\\squaretopblack"));
        symbols.add(new Arrow("square with bottom half black", 0x2b13, "⬓", "So", 0, "\\squarebotblack"));
        symbols.add(new Arrow("square with upper right diagonal half black", 0x2b14, "⬔", "So", 0, "\\squareurblack"));
        symbols.add(new Arrow("square with lower left diagonal half black", 0x2b15, "⬕", "So", 0, "\\squarellblack"));
        symbols.add(new Arrow("diamond with left half black", 0x2b16, "⬖", "So", 0, "\\diamondleftblack"));
        symbols.add(new Arrow("diamond with right half black", 0x2b17, "⬗", "So", 0, "\\diamondrightblack"));
        symbols.add(new Arrow("diamond with top half black", 0x2b18, "⬘", "So", 0, "\\diamondtopblack"));
        symbols.add(new Arrow("diamond with bottom half black", 0x2b19, "⬙", "So", 0, "\\diamondbotblack"));
        symbols.add(new Arrow("dotted square", 0x2b1a, "⬚", "So", 0, "\\dottedsquare"));
        symbols.add(new Arrow("black large square", 0x2b1b, "⬛", "So", 0, "\\lgblksquare"));
        symbols.add(new Arrow("white large square", 0x2b1c, "⬜", "So", 0, "\\lgwhtsquare"));
        symbols.add(new Arrow("black very square", 0x2b1d, "⬝", "So", 0, "\\vysmblksquare"));
        symbols.add(new Arrow("white very square", 0x2b1e, "⬞", "So", 0, "\\vysmwhtsquare"));
        symbols.add(new Arrow("black pentagon", 0x2b1f, "⬟", "So", 0, "\\pentagonblack"));
        symbols.add(new Arrow("white pentagon", 0x2b20, "⬠", "So", 0, "\\pentagon"));
        symbols.add(new Arrow("white hexagon", 0x2b21, "⬡", "So", 0, "\\varhexagon"));
        symbols.add(new Arrow("black hexagon", 0x2b22, "⬢", "So", 0, "\\varhexagonblack"));
        symbols.add(new Arrow("horizontal black hexagon", 0x2b23, "⬣", "So", 0, "\\hexagonblack"));
        symbols.add(new Arrow("black large circle", 0x2b24, "⬤", "So", 0, "\\lgblkcircle"));
        symbols.add(new Arrow("black medium diamond", 0x2b25, "⬥", "So", 0, "\\mdblkdiamond"));
        symbols.add(new Arrow("white medium diamond", 0x2b26, "⬦", "So", 0, "\\mdwhtdiamond"));
        symbols.add(new Arrow("black medium lozenge", 0x2b27, "⬧", "So", 0, "\\mdblklozenge"));
        symbols.add(new Arrow("white medium lozenge", 0x2b28, "⬨", "So", 0, "\\mdwhtlozenge"));
        symbols.add(new Arrow("black diamond", 0x2b29, "⬩", "So", 0, "\\smblkdiamond"));
        symbols.add(new Arrow("black lozenge", 0x2b2a, "⬪", "So", 0, "\\smblklozenge"));
        symbols.add(new Arrow("white lozenge", 0x2b2b, "⬫", "So", 0, "\\smwhtlozenge"));
        symbols.add(new Arrow("black horizontal ellipse", 0x2b2c, "⬬", "So", 0, "\\blkhorzoval"));
        symbols.add(new Arrow("white horizontal ellipse", 0x2b2d, "⬭", "So", 0, "\\whthorzoval"));
        symbols.add(new Arrow("black vertical ellipse", 0x2b2e, "⬮", "So", 0, "\\blkvertoval"));
        symbols.add(new Arrow("white vertical ellipse", 0x2b2f, "⬯", "So", 0, "\\whtvertoval"));
        symbols.add(new Arrow("left arrow with circle", 0x2b30, "⬰", "Sm", 0, "\\circleonleftarrow"));
        symbols.add(new Arrow("three leftwards arrows", 0x2b31, "⬱", "Sm", 0, "\\leftthreearrows"));
        symbols.add(new Arrow("left arrow with circled plus", 0x2b32, "⬲", "Sm", 0, "\\leftarrowonoplus"));
        symbols.add(new Arrow("long leftwards squiggle arrow", 0x2b33, "⬳", "Sm", 0, "\\longleftsquigarrow"));
        symbols.add(new Arrow("leftwards two-headed arrow with vertical stroke", 0x2b34, "⬴", "Sm", 0, "\\nvtwoheadleftarrow"));
        symbols.add(new Arrow("leftwards two-headed arrow with double vertical stroke", 0x2b35, "⬵", "Sm", 0, "\\nVtwoheadleftarrow"));
        symbols.add(new Arrow("leftwards two-headed arrow from bar", 0x2b36, "⬶", "Sm", 0, "\\twoheadmapsfrom"));
        symbols.add(new Arrow("leftwards two-headed triple dash arrow", 0x2b37, "⬷", "Sm", 0, "\\twoheadleftdbkarrow"));
        symbols.add(new Arrow("leftwards arrow with dotted stem", 0x2b38, "⬸", "Sm", 0, "\\leftdotarrow"));
        symbols.add(new Arrow("leftwards arrow with tail with vertical stroke", 0x2b39, "⬹", "Sm", 0, "\\nvleftarrowtail"));
        symbols.add(new Arrow("leftwards arrow with tail with double vertical stroke", 0x2b3a, "⬺", "Sm", 0, "\\nVleftarrowtail"));
        symbols.add(new Arrow("leftwards two-headed arrow with tail", 0x2b3b, "⬻", "Sm", 0, "\\twoheadleftarrowtail"));
        symbols.add(new Arrow("leftwards two-headed arrow with tail with vertical stroke", 0x2b3c, "⬼", "Sm", 0, "\\nvtwoheadleftarrowtail"));
        symbols.add(new Arrow("leftwards two-headed arrow with tail with double vertical stroke", 0x2b3d, "⬽", "Sm", 0, "\\nVtwoheadleftarrowtail"));
        symbols.add(new Arrow("leftwards arrow through x", 0x2b3e, "⬾", "Sm", 0, "\\leftarrowx"));
        symbols.add(new Arrow("wave arrow pointing directly left", 0x2b3f, "⬿", "Sm", 0, "\\leftcurvedarrow"));
        symbols.add(new Arrow("equals sign above leftwards arrow", 0x2b40, "⭀", "Sm", 0, "\\equalleftarrow"));
        symbols.add(new Arrow("reverse tilde operator above leftwards arrow", 0x2b41, "⭁", "Sm", 0, "\\bsimilarleftarrow"));
        symbols.add(new Arrow("leftwards arrow above reverse almost equal to", 0x2b42, "⭂", "Sm", 0, "\\leftarrowbackapprox"));
        symbols.add(new Arrow("rightwards arrow through greater-than", 0x2b43, "⭃", "Sm", 0, "\\rightarrowgtr"));
        symbols.add(new Arrow("rightwards arrow through superset", 0x2b44, "⭄", "Sm", 0, "\\rightarrowsupset"));
        symbols.add(new Arrow("leftwards quadruple arrow", 0x2b45, "⭅", "So", 0, "\\LLeftarrow"));
        symbols.add(new Arrow("rightwards quadruple arrow", 0x2b46, "⭆", "So", 0, "\\RRightarrow"));
        symbols.add(new Arrow("reverse tilde operator above rightwards arrow", 0x2b47, "⭇", "Sm", 0, "\\bsimilarrightarrow"));
        symbols.add(new Arrow("rightwards arrow above reverse almost equal to", 0x2b48, "⭈", "Sm", 0, "\\rightarrowbackapprox"));
        symbols.add(new Arrow("tilde operator above leftwards arrow", 0x2b49, "⭉", "Sm", 0, "\\similarleftarrow"));
        symbols.add(new Arrow("leftwards arrow above almost equal to", 0x2b4a, "⭊", "Sm", 0, "\\leftarrowapprox"));
        symbols.add(new Arrow("leftwards arrow above reverse tilde operator", 0x2b4b, "⭋", "Sm", 0, "\\leftarrowbsimilar"));
        symbols.add(new Arrow("rightwards arrow above reverse tilde operator", 0x2b4c, "⭌", "Sm", 0, "\\rightarrowbsimilar"));
        symbols.add(new Arrow("downwards triangle-headed zigzag arrow", 0x2b4d, "⭍", "So", 0));
        symbols.add(new Arrow("short slanted north arrow", 0x2b4e, "⭎", "So", 0));
        symbols.add(new Arrow("short backslanted south arrow", 0x2b4f, "⭏", "So", 0));
        symbols.add(new Arrow("white medium star", 0x2b50, "⭐", "So", 0, "\\medwhitestar"));
        symbols.add(new Arrow("black star", 0x2b51, "⭑", "So", 0, "\\medblackstar"));
        symbols.add(new Arrow("white star", 0x2b52, "⭒", "So", 0, "\\smwhitestar"));
        symbols.add(new Arrow("black right-pointing pentagon", 0x2b53, "⭓", "So", 0, "\\rightpentagonblack"));
        symbols.add(new Arrow("white right-pointing pentagon", 0x2b54, "⭔", "So", 0, "\\rightpentagon"));
        symbols.add(new Arrow("heavy large circle", 0x2b55, "⭕", "So", 0));
        symbols.add(new Arrow("heavy oval with oval inside", 0x2b56, "⭖", "So", 0));
        symbols.add(new Arrow("heavy circle with circle inside", 0x2b57, "⭗", "So", 0));
        symbols.add(new Arrow("heavy circle", 0x2b58, "⭘", "So", 0));
        symbols.add(new Arrow("heavy circled saltire", 0x2b59, "⭙", "So", 0));
        symbols.add(new Arrow("slanted north arrow with hooked head", 0x2b5a, "⭚", "So", 0));
        symbols.add(new Arrow("backslanted south arrow with hooked tail", 0x2b5b, "⭛", "So", 0));
        symbols.add(new Arrow("slanted north arrow with horizontal tail", 0x2b5c, "⭜", "So", 0));
        symbols.add(new Arrow("backslanted south arrow with horizontal tail", 0x2b5d, "⭝", "So", 0));
        symbols.add(new Arrow("bent arrow pointing downwards then north east", 0x2b5e, "⭞", "So", 0));
        symbols.add(new Arrow("short bent arrow pointing downwards then north east", 0x2b5f, "⭟", "So", 0));
        symbols.add(new Arrow("leftwards triangle-headed arrow", 0x2b60, "⭠", "So", 0));
        symbols.add(new Arrow("upwards triangle-headed arrow", 0x2b61, "⭡", "So", 0));
        symbols.add(new Arrow("rightwards triangle-headed arrow", 0x2b62, "⭢", "So", 0));
        symbols.add(new Arrow("downwards triangle-headed arrow", 0x2b63, "⭣", "So", 0));
        symbols.add(new Arrow("left right triangle-headed arrow", 0x2b64, "⭤", "So", 0));
        symbols.add(new Arrow("up down triangle-headed arrow", 0x2b65, "⭥", "So", 0));
        symbols.add(new Arrow("north west triangle-headed arrow", 0x2b66, "⭦", "So", 0));
        symbols.add(new Arrow("north east triangle-headed arrow", 0x2b67, "⭧", "So", 0));
        symbols.add(new Arrow("south east triangle-headed arrow", 0x2b68, "⭨", "So", 0));
        symbols.add(new Arrow("south west triangle-headed arrow", 0x2b69, "⭩", "So", 0));
        symbols.add(new Arrow("leftwards triangle-headed dashed arrow", 0x2b6a, "⭪", "So", 0));
        symbols.add(new Arrow("upwards triangle-headed dashed arrow", 0x2b6b, "⭫", "So", 0));
        symbols.add(new Arrow("rightwards triangle-headed dashed arrow", 0x2b6c, "⭬", "So", 0));
        symbols.add(new Arrow("downwards triangle-headed dashed arrow", 0x2b6d, "⭭", "So", 0));
        symbols.add(new Arrow("clockwise triangle-headed open circle arrow", 0x2b6e, "⭮", "So", 0));
        symbols.add(new Arrow("anticlockwise triangle-headed open circle arrow", 0x2b6f, "⭯", "So", 0));
        symbols.add(new Arrow("leftwards triangle-headed arrow to bar", 0x2b70, "⭰", "So", 0));
        symbols.add(new Arrow("upwards triangle-headed arrow to bar", 0x2b71, "⭱", "So", 0));
        symbols.add(new Arrow("rightwards triangle-headed arrow to bar", 0x2b72, "⭲", "So", 0));
        symbols.add(new Arrow("downwards triangle-headed arrow to bar", 0x2b73, "⭳", "So", 0));
        symbols.add(new Arrow("north west triangle-headed arrow to bar", 0x2b76, "⭶", "So", 0));
        symbols.add(new Arrow("north east triangle-headed arrow to bar", 0x2b77, "⭷", "So", 0));
        symbols.add(new Arrow("south east triangle-headed arrow to bar", 0x2b78, "⭸", "So", 0));
        symbols.add(new Arrow("south west triangle-headed arrow to bar", 0x2b79, "⭹", "So", 0));
        symbols.add(new Arrow("leftwards triangle-headed arrow with double horizontal stroke", 0x2b7a, "⭺", "So", 0));
        symbols.add(new Arrow("upwards triangle-headed arrow with double horizontal stroke", 0x2b7b, "⭻", "So", 0));
        symbols.add(new Arrow("rightwards triangle-headed arrow with double horizontal stroke", 0x2b7c, "⭼", "So", 0));
        symbols.add(new Arrow("downwards triangle-headed arrow with double horizontal stroke", 0x2b7d, "⭽", "So", 0));
        symbols.add(new Arrow("horizontal tab key", 0x2b7e, "⭾", "So", 0));
        symbols.add(new Arrow("vertical tab key", 0x2b7f, "⭿", "So", 0));
        symbols.add(new Arrow("leftwards triangle-headed arrow over rightwards triangle-headed arrow", 0x2b80, "⮀", "So", 0));
        symbols.add(new Arrow("upwards triangle-headed arrow leftwards of downwards triangle-headed arrow", 0x2b81, "⮁", "So", 0));
        symbols.add(new Arrow("rightwards triangle-headed arrow over leftwards triangle-headed arrow", 0x2b82, "⮂", "So", 0));
        symbols.add(new Arrow("downwards triangle-headed arrow leftwards of upwards triangle-headed arrow", 0x2b83, "⮃", "So", 0));
        symbols.add(new Arrow("leftwards triangle-headed paired arrows", 0x2b84, "⮄", "So", 0));
        symbols.add(new Arrow("upwards triangle-headed paired arrows", 0x2b85, "⮅", "So", 0));
        symbols.add(new Arrow("rightwards triangle-headed paired arrows", 0x2b86, "⮆", "So", 0));
        symbols.add(new Arrow("downwards triangle-headed paired arrows", 0x2b87, "⮇", "So", 0));
        symbols.add(new Arrow("leftwards black circled white arrow", 0x2b88, "⮈", "So", 0));
        symbols.add(new Arrow("upwards black circled white arrow", 0x2b89, "⮉", "So", 0));
        symbols.add(new Arrow("rightwards black circled white arrow", 0x2b8a, "⮊", "So", 0));
        symbols.add(new Arrow("downwards black circled white arrow", 0x2b8b, "⮋", "So", 0));
        symbols.add(new Arrow("anticlockwise triangle-headed right u-shaped arrow", 0x2b8c, "⮌", "So", 0));
        symbols.add(new Arrow("anticlockwise triangle-headed bottom u-shaped arrow", 0x2b8d, "⮍", "So", 0));
        symbols.add(new Arrow("anticlockwise triangle-headed left u-shaped arrow", 0x2b8e, "⮎", "So", 0));
        symbols.add(new Arrow("anticlockwise triangle-headed top u-shaped arrow", 0x2b8f, "⮏", "So", 0));
        symbols.add(new Arrow("return left", 0x2b90, "⮐", "So", 0));
        symbols.add(new Arrow("return right", 0x2b91, "⮑", "So", 0));
        symbols.add(new Arrow("newline left", 0x2b92, "⮒", "So", 0));
        symbols.add(new Arrow("newline right", 0x2b93, "⮓", "So", 0));
        symbols.add(new Arrow("four corner arrows circling anticlockwise", 0x2b94, "⮔", "So", 0));
        symbols.add(new Arrow("rightwards black arrow", 0x2b95, "⮕", "So", 0));
        symbols.add(new Arrow("for type a electronics", 0x2b97, "⮗", "So", 0));
        symbols.add(new Arrow("three-d top-lighted leftwards equilateral arrowhead", 0x2b98, "⮘", "So", 0));
        symbols.add(new Arrow("three-d right-lighted upwards equilateral arrowhead", 0x2b99, "⮙", "So", 0));
        symbols.add(new Arrow("three-d top-lighted rightwards equilateral arrowhead", 0x2b9a, "⮚", "So", 0));
        symbols.add(new Arrow("three-d left-lighted downwards equilateral arrowhead", 0x2b9b, "⮛", "So", 0));
        symbols.add(new Arrow("black leftwards equilateral arrowhead", 0x2b9c, "⮜", "So", 0));
        symbols.add(new Arrow("black upwards equilateral arrowhead", 0x2b9d, "⮝", "So", 0));
        symbols.add(new Arrow("black rightwards equilateral arrowhead", 0x2b9e, "⮞", "So", 0));
        symbols.add(new Arrow("black downwards equilateral arrowhead", 0x2b9f, "⮟", "So", 0));
        symbols.add(new Arrow("downwards triangle-headed arrow with long tip leftwards", 0x2ba0, "⮠", "So", 0));
        symbols.add(new Arrow("downwards triangle-headed arrow with long tip rightwards", 0x2ba1, "⮡", "So", 0));
        symbols.add(new Arrow("upwards triangle-headed arrow with long tip leftwards", 0x2ba2, "⮢", "So", 0));
        symbols.add(new Arrow("upwards triangle-headed arrow with long tip rightwards", 0x2ba3, "⮣", "So", 0));
        symbols.add(new Arrow("leftwards triangle-headed arrow with long tip upwards", 0x2ba4, "⮤", "So", 0));
        symbols.add(new Arrow("rightwards triangle-headed arrow with long tip upwards", 0x2ba5, "⮥", "So", 0));
        symbols.add(new Arrow("leftwards triangle-headed arrow with long tip downwards", 0x2ba6, "⮦", "So", 0));
        symbols.add(new Arrow("rightwards triangle-headed arrow with long tip downwards", 0x2ba7, "⮧", "So", 0));
        symbols.add(new Arrow("black curved downwards and leftwards arrow", 0x2ba8, "⮨", "So", 0));
        symbols.add(new Arrow("black curved downwards and rightwards arrow", 0x2ba9, "⮩", "So", 0));
        symbols.add(new Arrow("black curved upwards and leftwards arrow", 0x2baa, "⮪", "So", 0));
        symbols.add(new Arrow("black curved upwards and rightwards arrow", 0x2bab, "⮫", "So", 0));
        symbols.add(new Arrow("black curved leftwards and upwards arrow", 0x2bac, "⮬", "So", 0));
        symbols.add(new Arrow("black curved rightwards and upwards arrow", 0x2bad, "⮭", "So", 0));
        symbols.add(new Arrow("black curved leftwards and downwards arrow", 0x2bae, "⮮", "So", 0));
        symbols.add(new Arrow("black curved rightwards and downwards arrow", 0x2baf, "⮯", "So", 0));
        symbols.add(new Arrow("ribbon arrow down left", 0x2bb0, "⮰", "So", 0));
        symbols.add(new Arrow("ribbon arrow down right", 0x2bb1, "⮱", "So", 0));
        symbols.add(new Arrow("ribbon arrow up left", 0x2bb2, "⮲", "So", 0));
        symbols.add(new Arrow("ribbon arrow up right", 0x2bb3, "⮳", "So", 0));
        symbols.add(new Arrow("ribbon arrow left up", 0x2bb4, "⮴", "So", 0));
        symbols.add(new Arrow("ribbon arrow right up", 0x2bb5, "⮵", "So", 0));
        symbols.add(new Arrow("ribbon arrow left down", 0x2bb6, "⮶", "So", 0));
        symbols.add(new Arrow("ribbon arrow right down", 0x2bb7, "⮷", "So", 0));
        symbols.add(new Arrow("upwards white arrow from bar with horizontal bar", 0x2bb8, "⮸", "So", 0));
        symbols.add(new Arrow("up arrowhead in a rectangle box", 0x2bb9, "⮹", "So", 0));
        symbols.add(new Arrow("overlapping white squares", 0x2bba, "⮺", "So", 0));
        symbols.add(new Arrow("overlapping white and black squares", 0x2bbb, "⮻", "So", 0));
        symbols.add(new Arrow("overlapping black squares", 0x2bbc, "⮼", "So", 0));
        symbols.add(new Arrow("ballot box with light x", 0x2bbd, "⮽", "So", 0));
        symbols.add(new Arrow("circled x", 0x2bbe, "⮾", "So", 0));
        symbols.add(new Arrow("circled bold x", 0x2bbf, "⮿", "So", 0));
        symbols.add(new Arrow("black square centred", 0x2bc0, "⯀", "So", 0));
        symbols.add(new Arrow("black diamond centred", 0x2bc1, "⯁", "So", 0));
        symbols.add(new Arrow("turned black pentagon", 0x2bc2, "⯂", "So", 0));
        symbols.add(new Arrow("horizontal black octagon", 0x2bc3, "⯃", "So", 0));
        symbols.add(new Arrow("black octagon", 0x2bc4, "⯄", "So", 0));
        symbols.add(new Arrow("black medium up-pointing triangle centred", 0x2bc5, "⯅", "So", 0));
        symbols.add(new Arrow("black medium down-pointing triangle centred", 0x2bc6, "⯆", "So", 0));
        symbols.add(new Arrow("black medium left-pointing triangle centred", 0x2bc7, "⯇", "So", 0));
        symbols.add(new Arrow("black medium right-pointing triangle centred", 0x2bc8, "⯈", "So", 0));
        symbols.add(new Arrow("neptune form two", 0x2bc9, "⯉", "So", 0));
        symbols.add(new Arrow("top half black circle", 0x2bca, "⯊", "So", 0));
        symbols.add(new Arrow("bottom half black circle", 0x2bcb, "⯋", "So", 0));
        symbols.add(new Arrow("light four pointed black cusp", 0x2bcc, "⯌", "So", 0));
        symbols.add(new Arrow("rotated light four pointed black cusp", 0x2bcd, "⯍", "So", 0));
        symbols.add(new Arrow("white four pointed cusp", 0x2bce, "⯎", "So", 0));
        symbols.add(new Arrow("rotated white four pointed cusp", 0x2bcf, "⯏", "So", 0));
        symbols.add(new Arrow("square position indicator", 0x2bd0, "⯐", "So", 0));
        symbols.add(new Arrow("uncertainty sign", 0x2bd1, "⯑", "So", 0));
        symbols.add(new Arrow("group mark", 0x2bd2, "⯒", "So", 0));
        symbols.add(new Arrow("pluto form two", 0x2bd3, "⯓", "So", 0));
        symbols.add(new Arrow("pluto form three", 0x2bd4, "⯔", "So", 0));
        symbols.add(new Arrow("pluto form four", 0x2bd5, "⯕", "So", 0));
        symbols.add(new Arrow("pluto form five", 0x2bd6, "⯖", "So", 0));
        symbols.add(new Arrow("transpluto", 0x2bd7, "⯗", "So", 0));
        symbols.add(new Arrow("proserpina", 0x2bd8, "⯘", "So", 0));
        symbols.add(new Arrow("astraea", 0x2bd9, "⯙", "So", 0));
        symbols.add(new Arrow("hygiea", 0x2bda, "⯚", "So", 0));
        symbols.add(new Arrow("pholus", 0x2bdb, "⯛", "So", 0));
        symbols.add(new Arrow("nessus", 0x2bdc, "⯜", "So", 0));
        symbols.add(new Arrow("white moon selena", 0x2bdd, "⯝", "So", 0));
        symbols.add(new Arrow("black diamond on cross", 0x2bde, "⯞", "So", 0));
        symbols.add(new Arrow("true light moon arta", 0x2bdf, "⯟", "So", 0));
        symbols.add(new Arrow("cupido", 0x2be0, "⯠", "So", 0));
        symbols.add(new Arrow("hades", 0x2be1, "⯡", "So", 0));
        symbols.add(new Arrow("zeus", 0x2be2, "⯢", "So", 0));
        symbols.add(new Arrow("kronos", 0x2be3, "⯣", "So", 0));
        symbols.add(new Arrow("apollon", 0x2be4, "⯤", "So", 0));
        symbols.add(new Arrow("admetos", 0x2be5, "⯥", "So", 0));
        symbols.add(new Arrow("vulcanus", 0x2be6, "⯦", "So", 0));
        symbols.add(new Arrow("poseidon", 0x2be7, "⯧", "So", 0));
        symbols.add(new Arrow("left half black star", 0x2be8, "⯨", "So", 0));
        symbols.add(new Arrow("right half black star", 0x2be9, "⯩", "So", 0));
        symbols.add(new Arrow("star with left half black", 0x2bea, "⯪", "So", 0));
        symbols.add(new Arrow("star with right half black", 0x2beb, "⯫", "So", 0));
        symbols.add(new Arrow("leftwards two-headed arrow with triangle arrowheads", 0x2bec, "⯬", "So", 0));
        symbols.add(new Arrow("upwards two-headed arrow with triangle arrowheads", 0x2bed, "⯭", "So", 0));
        symbols.add(new Arrow("rightwards two-headed arrow with triangle arrowheads", 0x2bee, "⯮", "So", 0));
        symbols.add(new Arrow("downwards two-headed arrow with triangle arrowheads", 0x2bef, "⯯", "So", 0));
        symbols.add(new Arrow("eris form one", 0x2bf0, "⯰", "So", 0));
        symbols.add(new Arrow("eris form two", 0x2bf1, "⯱", "So", 0));
        symbols.add(new Arrow("sedna", 0x2bf2, "⯲", "So", 0));
        symbols.add(new Arrow("russian astrological vigintile", 0x2bf3, "⯳", "So", 0));
        symbols.add(new Arrow("russian astrological novile", 0x2bf4, "⯴", "So", 0));
        symbols.add(new Arrow("russian astrological quintile", 0x2bf5, "⯵", "So", 0));
        symbols.add(new Arrow("russian astrological binovile", 0x2bf6, "⯶", "So", 0));
        symbols.add(new Arrow("russian astrological sentagon", 0x2bf7, "⯷", "So", 0));
        symbols.add(new Arrow("russian astrological tredecile", 0x2bf8, "⯸", "So", 0));
        symbols.add(new Arrow("equals sign with infinity below", 0x2bf9, "⯹", "So", 0));
        symbols.add(new Arrow("united symbol", 0x2bfa, "⯺", "So", 0));
        symbols.add(new Arrow("separated symbol", 0x2bfb, "⯻", "So", 0));
        symbols.add(new Arrow("doubled symbol", 0x2bfc, "⯼", "So", 0));
        symbols.add(new Arrow("passed symbol", 0x2bfd, "⯽", "So", 0));
        symbols.add(new Arrow("reversed right angle", 0x2bfe, "⯾", "So", 0));
        symbols.add(new Arrow("hellschreiber pause symbol", 0x2bff, "⯿", "So", 0));
        symbols.add(new Arrow("leftwards arrow with triangle arrowhead", 0x1f800, "🠀", "So", 0));
        symbols.add(new Arrow("upwards arrow with triangle arrowhead", 0x1f801, "🠁", "So", 0));
        symbols.add(new Arrow("rightwards arrow with triangle arrowhead", 0x1f802, "🠂", "So", 0));
        symbols.add(new Arrow("downwards arrow with triangle arrowhead", 0x1f803, "🠃", "So", 0));
        symbols.add(new Arrow("leftwards arrow with medium triangle arrowhead", 0x1f804, "🠄", "So", 0));
        symbols.add(new Arrow("upwards arrow with medium triangle arrowhead", 0x1f805, "🠅", "So", 0));
        symbols.add(new Arrow("rightwards arrow with medium triangle arrowhead", 0x1f806, "🠆", "So", 0));
        symbols.add(new Arrow("downwards arrow with medium triangle arrowhead", 0x1f807, "🠇", "So", 0));
        symbols.add(new Arrow("leftwards arrow with large triangle arrowhead", 0x1f808, "🠈", "So", 0));
        symbols.add(new Arrow("upwards arrow with large triangle arrowhead", 0x1f809, "🠉", "So", 0));
        symbols.add(new Arrow("rightwards arrow with large triangle arrowhead", 0x1f80a, "🠊", "So", 0));
        symbols.add(new Arrow("downwards arrow with large triangle arrowhead", 0x1f80b, "🠋", "So", 0));
        symbols.add(new Arrow("leftwards arrow with equilateral arrowhead", 0x1f810, "🠐", "So", 0));
        symbols.add(new Arrow("upwards arrow with equilateral arrowhead", 0x1f811, "🠑", "So", 0));
        symbols.add(new Arrow("rightwards arrow with equilateral arrowhead", 0x1f812, "🠒", "So", 0));
        symbols.add(new Arrow("downwards arrow with equilateral arrowhead", 0x1f813, "🠓", "So", 0));
        symbols.add(new Arrow("leftwards arrow with equilateral arrowhead", 0x1f814, "🠔", "So", 0));
        symbols.add(new Arrow("upwards arrow with equilateral arrowhead", 0x1f815, "🠕", "So", 0));
        symbols.add(new Arrow("rightwards arrow with equilateral arrowhead", 0x1f816, "🠖", "So", 0));
        symbols.add(new Arrow("downwards arrow with equilateral arrowhead", 0x1f817, "🠗", "So", 0));
        symbols.add(new Arrow("heavy leftwards arrow with equilateral arrowhead", 0x1f818, "🠘", "So", 0));
        symbols.add(new Arrow("heavy upwards arrow with equilateral arrowhead", 0x1f819, "🠙", "So", 0));
        symbols.add(new Arrow("heavy rightwards arrow with equilateral arrowhead", 0x1f81a, "🠚", "So", 0));
        symbols.add(new Arrow("heavy downwards arrow with equilateral arrowhead", 0x1f81b, "🠛", "So", 0));
        symbols.add(new Arrow("heavy leftwards arrow with large equilateral arrowhead", 0x1f81c, "🠜", "So", 0));
        symbols.add(new Arrow("heavy upwards arrow with large equilateral arrowhead", 0x1f81d, "🠝", "So", 0));
        symbols.add(new Arrow("heavy rightwards arrow with large equilateral arrowhead", 0x1f81e, "🠞", "So", 0));
        symbols.add(new Arrow("heavy downwards arrow with large equilateral arrowhead", 0x1f81f, "🠟", "So", 0));
        symbols.add(new Arrow("leftwards triangle-headed arrow with narrow shaft", 0x1f820, "🠠", "So", 0));
        symbols.add(new Arrow("upwards triangle-headed arrow with narrow shaft", 0x1f821, "🠡", "So", 0));
        symbols.add(new Arrow("rightwards triangle-headed arrow with narrow shaft", 0x1f822, "🠢", "So", 0));
        symbols.add(new Arrow("downwards triangle-headed arrow with narrow shaft", 0x1f823, "🠣", "So", 0));
        symbols.add(new Arrow("leftwards triangle-headed arrow with medium shaft", 0x1f824, "🠤", "So", 0));
        symbols.add(new Arrow("upwards triangle-headed arrow with medium shaft", 0x1f825, "🠥", "So", 0));
        symbols.add(new Arrow("rightwards triangle-headed arrow with medium shaft", 0x1f826, "🠦", "So", 0));
        symbols.add(new Arrow("downwards triangle-headed arrow with medium shaft", 0x1f827, "🠧", "So", 0));
        symbols.add(new Arrow("leftwards triangle-headed arrow with bold shaft", 0x1f828, "🠨", "So", 0));
        symbols.add(new Arrow("upwards triangle-headed arrow with bold shaft", 0x1f829, "🠩", "So", 0));
        symbols.add(new Arrow("rightwards triangle-headed arrow with bold shaft", 0x1f82a, "🠪", "So", 0));
        symbols.add(new Arrow("downwards triangle-headed arrow with bold shaft", 0x1f82b, "🠫", "So", 0));
        symbols.add(new Arrow("leftwards triangle-headed arrow with heavy shaft", 0x1f82c, "🠬", "So", 0));
        symbols.add(new Arrow("upwards triangle-headed arrow with heavy shaft", 0x1f82d, "🠭", "So", 0));
        symbols.add(new Arrow("rightwards triangle-headed arrow with heavy shaft", 0x1f82e, "🠮", "So", 0));
        symbols.add(new Arrow("downwards triangle-headed arrow with heavy shaft", 0x1f82f, "🠯", "So", 0));
        symbols.add(new Arrow("leftwards triangle-headed arrow with very heavy shaft", 0x1f830, "🠰", "So", 0));
        symbols.add(new Arrow("upwards triangle-headed arrow with very heavy shaft", 0x1f831, "🠱", "So", 0));
        symbols.add(new Arrow("rightwards triangle-headed arrow with very heavy shaft", 0x1f832, "🠲", "So", 0));
        symbols.add(new Arrow("downwards triangle-headed arrow with very heavy shaft", 0x1f833, "🠳", "So", 0));
        symbols.add(new Arrow("leftwards finger-post arrow", 0x1f834, "🠴", "So", 0));
        symbols.add(new Arrow("upwards finger-post arrow", 0x1f835, "🠵", "So", 0));
        symbols.add(new Arrow("rightwards finger-post arrow", 0x1f836, "🠶", "So", 0));
        symbols.add(new Arrow("downwards finger-post arrow", 0x1f837, "🠷", "So", 0));
        symbols.add(new Arrow("leftwards squared arrow", 0x1f838, "🠸", "So", 0));
        symbols.add(new Arrow("upwards squared arrow", 0x1f839, "🠹", "So", 0));
        symbols.add(new Arrow("rightwards squared arrow", 0x1f83a, "🠺", "So", 0));
        symbols.add(new Arrow("downwards squared arrow", 0x1f83b, "🠻", "So", 0));
        symbols.add(new Arrow("leftwards compressed arrow", 0x1f83c, "🠼", "So", 0));
        symbols.add(new Arrow("upwards compressed arrow", 0x1f83d, "🠽", "So", 0));
        symbols.add(new Arrow("rightwards compressed arrow", 0x1f83e, "🠾", "So", 0));
        symbols.add(new Arrow("downwards compressed arrow", 0x1f83f, "🠿", "So", 0));
        symbols.add(new Arrow("leftwards heavy compressed arrow", 0x1f840, "🡀", "So", 0));
        symbols.add(new Arrow("upwards heavy compressed arrow", 0x1f841, "🡁", "So", 0));
        symbols.add(new Arrow("rightwards heavy compressed arrow", 0x1f842, "🡂", "So", 0));
        symbols.add(new Arrow("downwards heavy compressed arrow", 0x1f843, "🡃", "So", 0));
        symbols.add(new Arrow("leftwards heavy arrow", 0x1f844, "🡄", "So", 0));
        symbols.add(new Arrow("upwards heavy arrow", 0x1f845, "🡅", "So", 0));
        symbols.add(new Arrow("rightwards heavy arrow", 0x1f846, "🡆", "So", 0));
        symbols.add(new Arrow("downwards heavy arrow", 0x1f847, "🡇", "So", 0));
        symbols.add(new Arrow("leftwards sans-serif arrow", 0x1f850, "🡐", "So", 0));
        symbols.add(new Arrow("upwards sans-serif arrow", 0x1f851, "🡑", "So", 0));
        symbols.add(new Arrow("rightwards sans-serif arrow", 0x1f852, "🡒", "So", 0));
        symbols.add(new Arrow("downwards sans-serif arrow", 0x1f853, "🡓", "So", 0));
        symbols.add(new Arrow("north west sans-serif arrow", 0x1f854, "🡔", "So", 0));
        symbols.add(new Arrow("north east sans-serif arrow", 0x1f855, "🡕", "So", 0));
        symbols.add(new Arrow("south east sans-serif arrow", 0x1f856, "🡖", "So", 0));
        symbols.add(new Arrow("south west sans-serif arrow", 0x1f857, "🡗", "So", 0));
        symbols.add(new Arrow("left right sans-serif arrow", 0x1f858, "🡘", "So", 0));
        symbols.add(new Arrow("up down sans-serif arrow", 0x1f859, "🡙", "So", 0));
        symbols.add(new Arrow("wide-headed leftwards light barb arrow", 0x1f860, "🡠", "So", 0));
        symbols.add(new Arrow("wide-headed upwards light barb arrow", 0x1f861, "🡡", "So", 0));
        symbols.add(new Arrow("wide-headed rightwards light barb arrow", 0x1f862, "🡢", "So", 0));
        symbols.add(new Arrow("wide-headed downwards light barb arrow", 0x1f863, "🡣", "So", 0));
        symbols.add(new Arrow("wide-headed north west light barb arrow", 0x1f864, "🡤", "So", 0));
        symbols.add(new Arrow("wide-headed north east light barb arrow", 0x1f865, "🡥", "So", 0));
        symbols.add(new Arrow("wide-headed south east light barb arrow", 0x1f866, "🡦", "So", 0));
        symbols.add(new Arrow("wide-headed south west light barb arrow", 0x1f867, "🡧", "So", 0));
        symbols.add(new Arrow("wide-headed leftwards barb arrow", 0x1f868, "🡨", "So", 0));
        symbols.add(new Arrow("wide-headed upwards barb arrow", 0x1f869, "🡩", "So", 0));
        symbols.add(new Arrow("wide-headed rightwards barb arrow", 0x1f86a, "🡪", "So", 0));
        symbols.add(new Arrow("wide-headed downwards barb arrow", 0x1f86b, "🡫", "So", 0));
        symbols.add(new Arrow("wide-headed north west barb arrow", 0x1f86c, "🡬", "So", 0));
        symbols.add(new Arrow("wide-headed north east barb arrow", 0x1f86d, "🡭", "So", 0));
        symbols.add(new Arrow("wide-headed south east barb arrow", 0x1f86e, "🡮", "So", 0));
        symbols.add(new Arrow("wide-headed south west barb arrow", 0x1f86f, "🡯", "So", 0));
        symbols.add(new Arrow("wide-headed leftwards medium barb arrow", 0x1f870, "🡰", "So", 0));
        symbols.add(new Arrow("wide-headed upwards medium barb arrow", 0x1f871, "🡱", "So", 0));
        symbols.add(new Arrow("wide-headed rightwards medium barb arrow", 0x1f872, "🡲", "So", 0));
        symbols.add(new Arrow("wide-headed downwards medium barb arrow", 0x1f873, "🡳", "So", 0));
        symbols.add(new Arrow("wide-headed north west medium barb arrow", 0x1f874, "🡴", "So", 0));
        symbols.add(new Arrow("wide-headed north east medium barb arrow", 0x1f875, "🡵", "So", 0));
        symbols.add(new Arrow("wide-headed south east medium barb arrow", 0x1f876, "🡶", "So", 0));
        symbols.add(new Arrow("wide-headed south west medium barb arrow", 0x1f877, "🡷", "So", 0));
        symbols.add(new Arrow("wide-headed leftwards heavy barb arrow", 0x1f878, "🡸", "So", 0));
        symbols.add(new Arrow("wide-headed upwards heavy barb arrow", 0x1f879, "🡹", "So", 0));
        symbols.add(new Arrow("wide-headed rightwards heavy barb arrow", 0x1f87a, "🡺", "So", 0));
        symbols.add(new Arrow("wide-headed downwards heavy barb arrow", 0x1f87b, "🡻", "So", 0));
        symbols.add(new Arrow("wide-headed north west heavy barb arrow", 0x1f87c, "🡼", "So", 0));
        symbols.add(new Arrow("wide-headed north east heavy barb arrow", 0x1f87d, "🡽", "So", 0));
        symbols.add(new Arrow("wide-headed south east heavy barb arrow", 0x1f87e, "🡾", "So", 0));
        symbols.add(new Arrow("wide-headed south west heavy barb arrow", 0x1f87f, "🡿", "So", 0));
        symbols.add(new Arrow("wide-headed leftwards very heavy barb arrow", 0x1f880, "🢀", "So", 0));
        symbols.add(new Arrow("wide-headed upwards very heavy barb arrow", 0x1f881, "🢁", "So", 0));
        symbols.add(new Arrow("wide-headed rightwards very heavy barb arrow", 0x1f882, "🢂", "So", 0));
        symbols.add(new Arrow("wide-headed downwards very heavy barb arrow", 0x1f883, "🢃", "So", 0));
        symbols.add(new Arrow("wide-headed north west very heavy barb arrow", 0x1f884, "🢄", "So", 0));
        symbols.add(new Arrow("wide-headed north east very heavy barb arrow", 0x1f885, "🢅", "So", 0));
        symbols.add(new Arrow("wide-headed south east very heavy barb arrow", 0x1f886, "🢆", "So", 0));
        symbols.add(new Arrow("wide-headed south west very heavy barb arrow", 0x1f887, "🢇", "So", 0));
        symbols.add(new Arrow("leftwards triangle arrowhead", 0x1f890, "🢐", "So", 0));
        symbols.add(new Arrow("upwards triangle arrowhead", 0x1f891, "🢑", "So", 0));
        symbols.add(new Arrow("rightwards triangle arrowhead", 0x1f892, "🢒", "So", 0));
        symbols.add(new Arrow("downwards triangle arrowhead", 0x1f893, "🢓", "So", 0));
        symbols.add(new Arrow("leftwards white arrow within triangle arrowhead", 0x1f894, "🢔", "So", 0));
        symbols.add(new Arrow("upwards white arrow within triangle arrowhead", 0x1f895, "🢕", "So", 0));
        symbols.add(new Arrow("rightwards white arrow within triangle arrowhead", 0x1f896, "🢖", "So", 0));
        symbols.add(new Arrow("downwards white arrow within triangle arrowhead", 0x1f897, "🢗", "So", 0));
        symbols.add(new Arrow("leftwards arrow with notched tail", 0x1f898, "🢘", "So", 0));
        symbols.add(new Arrow("upwards arrow with notched tail", 0x1f899, "🢙", "So", 0));
        symbols.add(new Arrow("rightwards arrow with notched tail", 0x1f89a, "🢚", "So", 0));
        symbols.add(new Arrow("downwards arrow with notched tail", 0x1f89b, "🢛", "So", 0));
        symbols.add(new Arrow("heavy arrow shaft width one", 0x1f89c, "🢜", "So", 0));
        symbols.add(new Arrow("heavy arrow shaft width two thirds", 0x1f89d, "🢝", "So", 0));
        symbols.add(new Arrow("heavy arrow shaft width one half", 0x1f89e, "🢞", "So", 0));
        symbols.add(new Arrow("heavy arrow shaft width one third", 0x1f89f, "🢟", "So", 0));
        symbols.add(new Arrow("leftwards bottom-shaded white arrow", 0x1f8a0, "🢠", "So", 0));
        symbols.add(new Arrow("rightwards bottom shaded white arrow", 0x1f8a1, "🢡", "So", 0));
        symbols.add(new Arrow("leftwards top shaded white arrow", 0x1f8a2, "🢢", "So", 0));
        symbols.add(new Arrow("rightwards top shaded white arrow", 0x1f8a3, "🢣", "So", 0));
        symbols.add(new Arrow("leftwards left-shaded white arrow", 0x1f8a4, "🢤", "So", 0));
        symbols.add(new Arrow("rightwards right-shaded white arrow", 0x1f8a5, "🢥", "So", 0));
        symbols.add(new Arrow("leftwards right-shaded white arrow", 0x1f8a6, "🢦", "So", 0));
        symbols.add(new Arrow("rightwards left-shaded white arrow", 0x1f8a7, "🢧", "So", 0));
        symbols.add(new Arrow("leftwards back-tilted shadowed white arrow", 0x1f8a8, "🢨", "So", 0));
        symbols.add(new Arrow("rightwards back-tilted shadowed white arrow", 0x1f8a9, "🢩", "So", 0));
        symbols.add(new Arrow("leftwards front-tilted shadowed white arrow", 0x1f8aa, "🢪", "So", 0));
        symbols.add(new Arrow("rightwards front-tilted shadowed white arrow", 0x1f8ab, "🢫", "So", 0));
        symbols.add(new Arrow("white arrow shaft width one", 0x1f8ac, "🢬", "So", 0));
        symbols.add(new Arrow("white arrow shaft width two thirds", 0x1f8ad, "🢭", "So", 0));
        symbols.add(new Arrow("arrow pointing upwards then north west", 0x1f8b0, "🢰", "So", 0));
        symbols.add(new Arrow("arrow pointing rightwards then curving south west", 0x1f8b1, "🢱", "So", 0));
    }
}