package net.mlcoder.unicode.category;

import javax.annotation.Nullable;
import java.util.ArrayList;
import java.util.List;


public class Shapes implements UniCode {
    public static final List<UniCode> symbols = new ArrayList<>();

    public final String desc;
    public final int codePoint;
    public final String chars;
    public final String generalCategory;
    public final int combiningClass;

    @Nullable
    public final String latex;

    @Override
    public String desc() {
        return desc;
    }

    @Override
    public int codePoint() {
        return codePoint;
    }

    @Override
    public String chars() {
        return chars;
    }

    @Override
    public String generalCategory() {
        return generalCategory;
    }

    @Override
    public int combiningClass() {
        return combiningClass;
    }

    @Override @Nullable
    public String latex() {
        return latex;
    }

    Shapes(String desc, int codePoint, String chars, String generalCategory, int combiningClass) {
        this(desc, codePoint, chars, generalCategory, combiningClass, null);
    }

    Shapes(String desc, int codePoint, String chars, String generalCategory, int combiningClass, String latex) {
        this.desc = desc;
        this.codePoint = codePoint;
        this.generalCategory = generalCategory;
        this.combiningClass = combiningClass;
        this.chars = chars;
        this.latex = latex;
    }

    @Override
    public String toString() {
        return "Shapes{" +
            "desc='" + desc + '\'' +
            ", codePoint=" + codePoint +
            ", chars='" + chars + '\'' +
            ", generalCategory='" + generalCategory + '\'' +
            ", combiningClass=" + combiningClass +
            ", latex='" + latex + '\'' +
            '}';
    }

    static {

        symbols.add(new Shapes("box drawings light horizontal", 0x2500, "─", "So", 0));
        symbols.add(new Shapes("box drawings heavy horizontal", 0x2501, "━", "So", 0));
        symbols.add(new Shapes("box drawings light vertical", 0x2502, "│", "So", 0));
        symbols.add(new Shapes("box drawings heavy vertical", 0x2503, "┃", "So", 0));
        symbols.add(new Shapes("box drawings light triple dash horizontal", 0x2504, "┄", "So", 0));
        symbols.add(new Shapes("box drawings heavy triple dash horizontal", 0x2505, "┅", "So", 0));
        symbols.add(new Shapes("box drawings light triple dash vertical", 0x2506, "┆", "So", 0, "\\bdtriplevdash"));
        symbols.add(new Shapes("box drawings heavy triple dash vertical", 0x2507, "┇", "So", 0));
        symbols.add(new Shapes("box drawings light quadruple dash horizontal", 0x2508, "┈", "So", 0));
        symbols.add(new Shapes("box drawings heavy quadruple dash horizontal", 0x2509, "┉", "So", 0));
        symbols.add(new Shapes("box drawings light quadruple dash vertical", 0x250a, "┊", "So", 0));
        symbols.add(new Shapes("box drawings heavy quadruple dash vertical", 0x250b, "┋", "So", 0));
        symbols.add(new Shapes("box drawings light down and right", 0x250c, "┌", "So", 0));
        symbols.add(new Shapes("box drawings down light and right heavy", 0x250d, "┍", "So", 0));
        symbols.add(new Shapes("box drawings down heavy and right light", 0x250e, "┎", "So", 0));
        symbols.add(new Shapes("box drawings heavy down and right", 0x250f, "┏", "So", 0));
        symbols.add(new Shapes("box drawings light down and left", 0x2510, "┐", "So", 0));
        symbols.add(new Shapes("box drawings down light and left heavy", 0x2511, "┑", "So", 0));
        symbols.add(new Shapes("box drawings down heavy and left light", 0x2512, "┒", "So", 0));
        symbols.add(new Shapes("box drawings heavy down and left", 0x2513, "┓", "So", 0));
        symbols.add(new Shapes("box drawings light up and right", 0x2514, "└", "So", 0));
        symbols.add(new Shapes("box drawings up light and right heavy", 0x2515, "┕", "So", 0));
        symbols.add(new Shapes("box drawings up heavy and right light", 0x2516, "┖", "So", 0));
        symbols.add(new Shapes("box drawings heavy up and right", 0x2517, "┗", "So", 0));
        symbols.add(new Shapes("box drawings light up and left", 0x2518, "┘", "So", 0));
        symbols.add(new Shapes("box drawings up light and left heavy", 0x2519, "┙", "So", 0));
        symbols.add(new Shapes("box drawings up heavy and left light", 0x251a, "┚", "So", 0));
        symbols.add(new Shapes("box drawings heavy up and left", 0x251b, "┛", "So", 0));
        symbols.add(new Shapes("box drawings light vertical and right", 0x251c, "├", "So", 0));
        symbols.add(new Shapes("box drawings vertical light and right heavy", 0x251d, "┝", "So", 0));
        symbols.add(new Shapes("box drawings up heavy and right down light", 0x251e, "┞", "So", 0));
        symbols.add(new Shapes("box drawings down heavy and right up light", 0x251f, "┟", "So", 0));
        symbols.add(new Shapes("box drawings vertical heavy and right light", 0x2520, "┠", "So", 0));
        symbols.add(new Shapes("box drawings down light and right up heavy", 0x2521, "┡", "So", 0));
        symbols.add(new Shapes("box drawings up light and right down heavy", 0x2522, "┢", "So", 0));
        symbols.add(new Shapes("box drawings heavy vertical and right", 0x2523, "┣", "So", 0));
        symbols.add(new Shapes("box drawings light vertical and left", 0x2524, "┤", "So", 0));
        symbols.add(new Shapes("box drawings vertical light and left heavy", 0x2525, "┥", "So", 0));
        symbols.add(new Shapes("box drawings up heavy and left down light", 0x2526, "┦", "So", 0));
        symbols.add(new Shapes("box drawings down heavy and left up light", 0x2527, "┧", "So", 0));
        symbols.add(new Shapes("box drawings vertical heavy and left light", 0x2528, "┨", "So", 0));
        symbols.add(new Shapes("box drawings down light and left up heavy", 0x2529, "┩", "So", 0));
        symbols.add(new Shapes("box drawings up light and left down heavy", 0x252a, "┪", "So", 0));
        symbols.add(new Shapes("box drawings heavy vertical and left", 0x252b, "┫", "So", 0));
        symbols.add(new Shapes("box drawings light down and horizontal", 0x252c, "┬", "So", 0));
        symbols.add(new Shapes("box drawings left heavy and right down light", 0x252d, "┭", "So", 0));
        symbols.add(new Shapes("box drawings right heavy and left down light", 0x252e, "┮", "So", 0));
        symbols.add(new Shapes("box drawings down light and horizontal heavy", 0x252f, "┯", "So", 0));
        symbols.add(new Shapes("box drawings down heavy and horizontal light", 0x2530, "┰", "So", 0));
        symbols.add(new Shapes("box drawings right light and left down heavy", 0x2531, "┱", "So", 0));
        symbols.add(new Shapes("box drawings left light and right down heavy", 0x2532, "┲", "So", 0));
        symbols.add(new Shapes("box drawings heavy down and horizontal", 0x2533, "┳", "So", 0));
        symbols.add(new Shapes("box drawings light up and horizontal", 0x2534, "┴", "So", 0));
        symbols.add(new Shapes("box drawings left heavy and right up light", 0x2535, "┵", "So", 0));
        symbols.add(new Shapes("box drawings right heavy and left up light", 0x2536, "┶", "So", 0));
        symbols.add(new Shapes("box drawings up light and horizontal heavy", 0x2537, "┷", "So", 0));
        symbols.add(new Shapes("box drawings up heavy and horizontal light", 0x2538, "┸", "So", 0));
        symbols.add(new Shapes("box drawings right light and left up heavy", 0x2539, "┹", "So", 0));
        symbols.add(new Shapes("box drawings left light and right up heavy", 0x253a, "┺", "So", 0));
        symbols.add(new Shapes("box drawings heavy up and horizontal", 0x253b, "┻", "So", 0));
        symbols.add(new Shapes("box drawings light vertical and horizontal", 0x253c, "┼", "So", 0));
        symbols.add(new Shapes("box drawings left heavy and right vertical light", 0x253d, "┽", "So", 0));
        symbols.add(new Shapes("box drawings right heavy and left vertical light", 0x253e, "┾", "So", 0));
        symbols.add(new Shapes("box drawings vertical light and horizontal heavy", 0x253f, "┿", "So", 0));
        symbols.add(new Shapes("box drawings up heavy and down horizontal light", 0x2540, "╀", "So", 0));
        symbols.add(new Shapes("box drawings down heavy and up horizontal light", 0x2541, "╁", "So", 0));
        symbols.add(new Shapes("box drawings vertical heavy and horizontal light", 0x2542, "╂", "So", 0));
        symbols.add(new Shapes("box drawings left up heavy and right down light", 0x2543, "╃", "So", 0));
        symbols.add(new Shapes("box drawings right up heavy and left down light", 0x2544, "╄", "So", 0));
        symbols.add(new Shapes("box drawings left down heavy and right up light", 0x2545, "╅", "So", 0));
        symbols.add(new Shapes("box drawings right down heavy and left up light", 0x2546, "╆", "So", 0));
        symbols.add(new Shapes("box drawings down light and up horizontal heavy", 0x2547, "╇", "So", 0));
        symbols.add(new Shapes("box drawings up light and down horizontal heavy", 0x2548, "╈", "So", 0));
        symbols.add(new Shapes("box drawings right light and left vertical heavy", 0x2549, "╉", "So", 0));
        symbols.add(new Shapes("box drawings left light and right vertical heavy", 0x254a, "╊", "So", 0));
        symbols.add(new Shapes("box drawings heavy vertical and horizontal", 0x254b, "╋", "So", 0));
        symbols.add(new Shapes("box drawings light double dash horizontal", 0x254c, "╌", "So", 0));
        symbols.add(new Shapes("box drawings heavy double dash horizontal", 0x254d, "╍", "So", 0));
        symbols.add(new Shapes("box drawings light double dash vertical", 0x254e, "╎", "So", 0));
        symbols.add(new Shapes("box drawings heavy double dash vertical", 0x254f, "╏", "So", 0));
        symbols.add(new Shapes("box drawings double horizontal", 0x2550, "═", "So", 0));
        symbols.add(new Shapes("box drawings double vertical", 0x2551, "║", "So", 0));
        symbols.add(new Shapes("box drawings down single and right double", 0x2552, "╒", "So", 0));
        symbols.add(new Shapes("box drawings down double and right single", 0x2553, "╓", "So", 0));
        symbols.add(new Shapes("box drawings double down and right", 0x2554, "╔", "So", 0));
        symbols.add(new Shapes("box drawings down single and left double", 0x2555, "╕", "So", 0));
        symbols.add(new Shapes("box drawings down double and left single", 0x2556, "╖", "So", 0));
        symbols.add(new Shapes("box drawings double down and left", 0x2557, "╗", "So", 0));
        symbols.add(new Shapes("box drawings up single and right double", 0x2558, "╘", "So", 0));
        symbols.add(new Shapes("box drawings up double and right single", 0x2559, "╙", "So", 0));
        symbols.add(new Shapes("box drawings double up and right", 0x255a, "╚", "So", 0));
        symbols.add(new Shapes("box drawings up single and left double", 0x255b, "╛", "So", 0));
        symbols.add(new Shapes("box drawings up double and left single", 0x255c, "╜", "So", 0));
        symbols.add(new Shapes("box drawings double up and left", 0x255d, "╝", "So", 0));
        symbols.add(new Shapes("box drawings vertical single and right double", 0x255e, "╞", "So", 0));
        symbols.add(new Shapes("box drawings vertical double and right single", 0x255f, "╟", "So", 0));
        symbols.add(new Shapes("box drawings double vertical and right", 0x2560, "╠", "So", 0));
        symbols.add(new Shapes("box drawings vertical single and left double", 0x2561, "╡", "So", 0));
        symbols.add(new Shapes("box drawings vertical double and left single", 0x2562, "╢", "So", 0));
        symbols.add(new Shapes("box drawings double vertical and left", 0x2563, "╣", "So", 0));
        symbols.add(new Shapes("box drawings down single and horizontal double", 0x2564, "╤", "So", 0));
        symbols.add(new Shapes("box drawings down double and horizontal single", 0x2565, "╥", "So", 0));
        symbols.add(new Shapes("box drawings double down and horizontal", 0x2566, "╦", "So", 0));
        symbols.add(new Shapes("box drawings up single and horizontal double", 0x2567, "╧", "So", 0));
        symbols.add(new Shapes("box drawings up double and horizontal single", 0x2568, "╨", "So", 0));
        symbols.add(new Shapes("box drawings double up and horizontal", 0x2569, "╩", "So", 0));
        symbols.add(new Shapes("box drawings vertical single and horizontal double", 0x256a, "╪", "So", 0));
        symbols.add(new Shapes("box drawings vertical double and horizontal single", 0x256b, "╫", "So", 0));
        symbols.add(new Shapes("box drawings double vertical and horizontal", 0x256c, "╬", "So", 0));
        symbols.add(new Shapes("box drawings light arc down and right", 0x256d, "╭", "So", 0));
        symbols.add(new Shapes("box drawings light arc down and left", 0x256e, "╮", "So", 0));
        symbols.add(new Shapes("box drawings light arc up and left", 0x256f, "╯", "So", 0));
        symbols.add(new Shapes("box drawings light arc up and right", 0x2570, "╰", "So", 0));
        symbols.add(new Shapes("box drawings light diagonal upper right to lower left", 0x2571, "╱", "So", 0));
        symbols.add(new Shapes("box drawings light diagonal upper left to lower right", 0x2572, "╲", "So", 0));
        symbols.add(new Shapes("box drawings light diagonal cross", 0x2573, "╳", "So", 0));
        symbols.add(new Shapes("box drawings light left", 0x2574, "╴", "So", 0));
        symbols.add(new Shapes("box drawings light up", 0x2575, "╵", "So", 0));
        symbols.add(new Shapes("box drawings light right", 0x2576, "╶", "So", 0));
        symbols.add(new Shapes("box drawings light down", 0x2577, "╷", "So", 0));
        symbols.add(new Shapes("box drawings heavy left", 0x2578, "╸", "So", 0));
        symbols.add(new Shapes("box drawings heavy up", 0x2579, "╹", "So", 0));
        symbols.add(new Shapes("box drawings heavy right", 0x257a, "╺", "So", 0));
        symbols.add(new Shapes("box drawings heavy down", 0x257b, "╻", "So", 0));
        symbols.add(new Shapes("box drawings light left and heavy right", 0x257c, "╼", "So", 0));
        symbols.add(new Shapes("box drawings light up and heavy down", 0x257d, "╽", "So", 0));
        symbols.add(new Shapes("box drawings heavy left and light right", 0x257e, "╾", "So", 0));
        symbols.add(new Shapes("box drawings heavy up and light down", 0x257f, "╿", "So", 0));
        symbols.add(new Shapes("upper half block", 0x2580, "▀", "So", 0, "\\blockuphalf"));
        symbols.add(new Shapes("lower one eighth block", 0x2581, "▁", "So", 0));
        symbols.add(new Shapes("lower one quarter block", 0x2582, "▂", "So", 0));
        symbols.add(new Shapes("lower three eighths block", 0x2583, "▃", "So", 0));
        symbols.add(new Shapes("lower half block", 0x2584, "▄", "So", 0, "\\blocklowhalf"));
        symbols.add(new Shapes("lower five eighths block", 0x2585, "▅", "So", 0));
        symbols.add(new Shapes("lower three quarters block", 0x2586, "▆", "So", 0));
        symbols.add(new Shapes("lower seven eighths block", 0x2587, "▇", "So", 0));
        symbols.add(new Shapes("full block", 0x2588, "█", "So", 0, "\\blockfull"));
        symbols.add(new Shapes("left seven eighths block", 0x2589, "▉", "So", 0));
        symbols.add(new Shapes("left three quarters block", 0x258a, "▊", "So", 0));
        symbols.add(new Shapes("left five eighths block", 0x258b, "▋", "So", 0));
        symbols.add(new Shapes("left half block", 0x258c, "▌", "So", 0, "\\blocklefthalf"));
        symbols.add(new Shapes("left three eighths block", 0x258d, "▍", "So", 0));
        symbols.add(new Shapes("left one quarter block", 0x258e, "▎", "So", 0));
        symbols.add(new Shapes("left one eighth block", 0x258f, "▏", "So", 0));
        symbols.add(new Shapes("right half block", 0x2590, "▐", "So", 0, "\\blockrighthalf"));
        symbols.add(new Shapes("light shade", 0x2591, "░", "So", 0, "\\blockqtrshaded"));
        symbols.add(new Shapes("medium shade", 0x2592, "▒", "So", 0, "\\blockhalfshaded"));
        symbols.add(new Shapes("dark shade", 0x2593, "▓", "So", 0, "\\blockthreeqtrshaded"));
        symbols.add(new Shapes("upper one eighth block", 0x2594, "▔", "So", 0));
        symbols.add(new Shapes("right one eighth block", 0x2595, "▕", "So", 0));
        symbols.add(new Shapes("quadrant lower left", 0x2596, "▖", "So", 0));
        symbols.add(new Shapes("quadrant lower right", 0x2597, "▗", "So", 0));
        symbols.add(new Shapes("quadrant upper left", 0x2598, "▘", "So", 0));
        symbols.add(new Shapes("quadrant upper left and lower left and lower right", 0x2599, "▙", "So", 0));
        symbols.add(new Shapes("quadrant upper left and lower right", 0x259a, "▚", "So", 0));
        symbols.add(new Shapes("quadrant upper left and upper right and lower left", 0x259b, "▛", "So", 0));
        symbols.add(new Shapes("quadrant upper left and upper right and lower right", 0x259c, "▜", "So", 0));
        symbols.add(new Shapes("quadrant upper right", 0x259d, "▝", "So", 0));
        symbols.add(new Shapes("quadrant upper right and lower left", 0x259e, "▞", "So", 0));
        symbols.add(new Shapes("quadrant upper right and lower left and lower right", 0x259f, "▟", "So", 0));
        symbols.add(new Shapes("black square", 0x25a0, "■", "So", 0, "\\mdlgblksquare"));
        symbols.add(new Shapes("white square", 0x25a1, "□", "So", 0, "\\mdlgwhtsquare"));
        symbols.add(new Shapes("white square with rounded corners", 0x25a2, "▢", "So", 0, "\\squoval"));
        symbols.add(new Shapes("white square containing black square", 0x25a3, "▣", "So", 0, "\\blackinwhitesquare"));
        symbols.add(new Shapes("square with horizontal fill", 0x25a4, "▤", "So", 0, "\\squarehfill"));
        symbols.add(new Shapes("square with vertical fill", 0x25a5, "▥", "So", 0, "\\squarevfill"));
        symbols.add(new Shapes("square with orthogonal crosshatch fill", 0x25a6, "▦", "So", 0, "\\squarehvfill"));
        symbols.add(new Shapes("square with upper left to lower right fill", 0x25a7, "▧", "So", 0, "\\squarenwsefill"));
        symbols.add(new Shapes("square with upper right to lower left fill", 0x25a8, "▨", "So", 0, "\\squareneswfill"));
        symbols.add(new Shapes("square with diagonal crosshatch fill", 0x25a9, "▩", "So", 0, "\\squarecrossfill"));
        symbols.add(new Shapes("black square", 0x25aa, "▪", "So", 0, "\\smblksquare"));
        symbols.add(new Shapes("white square", 0x25ab, "▫", "So", 0, "\\smwhtsquare"));
        symbols.add(new Shapes("black rectangle", 0x25ac, "▬", "So", 0, "\\hrectangleblack"));
        symbols.add(new Shapes("white rectangle", 0x25ad, "▭", "So", 0, "\\hrectangle"));
        symbols.add(new Shapes("black vertical rectangle", 0x25ae, "▮", "So", 0, "\\vrectangleblack"));
        symbols.add(new Shapes("white vertical rectangle", 0x25af, "▯", "So", 0, "\\vrectangle"));
        symbols.add(new Shapes("black parallelogram", 0x25b0, "▰", "So", 0, "\\parallelogramblack"));
        symbols.add(new Shapes("white parallelogram", 0x25b1, "▱", "So", 0, "\\parallelogram"));
        symbols.add(new Shapes("black up-pointing triangle", 0x25b2, "▲", "So", 0, "\\bigblacktriangleup"));
        symbols.add(new Shapes("white up-pointing triangle", 0x25b3, "△", "So", 0, "\\bigtriangleup"));
        symbols.add(new Shapes("black up-pointing triangle", 0x25b4, "▴", "So", 0, "\\blacktriangle"));
        symbols.add(new Shapes("white up-pointing triangle", 0x25b5, "▵", "So", 0, "\\vartriangle"));
        symbols.add(new Shapes("black right-pointing triangle", 0x25b6, "▶", "So", 0, "\\blacktriangleright"));
        symbols.add(new Shapes("white right-pointing triangle", 0x25b7, "▷", "Sm", 0, "\\triangleright"));
        symbols.add(new Shapes("black right-pointing triangle", 0x25b8, "▸", "So", 0, "\\smallblacktriangleright"));
        symbols.add(new Shapes("white right-pointing triangle", 0x25b9, "▹", "So", 0, "\\smalltriangleright"));
        symbols.add(new Shapes("black right-pointing pointer", 0x25ba, "►", "So", 0, "\\blackpointerright"));
        symbols.add(new Shapes("white right-pointing pointer", 0x25bb, "▻", "So", 0, "\\whitepointerright"));
        symbols.add(new Shapes("black down-pointing triangle", 0x25bc, "▼", "So", 0, "\\bigblacktriangledown"));
        symbols.add(new Shapes("white down-pointing triangle", 0x25bd, "▽", "So", 0, "\\bigtriangledown"));
        symbols.add(new Shapes("black down-pointing triangle", 0x25be, "▾", "So", 0, "\\blacktriangledown"));
        symbols.add(new Shapes("white down-pointing triangle", 0x25bf, "▿", "So", 0, "\\triangledown"));
        symbols.add(new Shapes("black left-pointing triangle", 0x25c0, "◀", "So", 0, "\\blacktriangleleft"));
        symbols.add(new Shapes("white left-pointing triangle", 0x25c1, "◁", "Sm", 0, "\\triangleleft"));
        symbols.add(new Shapes("black left-pointing triangle", 0x25c2, "◂", "So", 0, "\\smallblacktriangleleft"));
        symbols.add(new Shapes("white left-pointing triangle", 0x25c3, "◃", "So", 0, "\\smalltriangleleft"));
        symbols.add(new Shapes("black left-pointing pointer", 0x25c4, "◄", "So", 0, "\\blackpointerleft"));
        symbols.add(new Shapes("white left-pointing pointer", 0x25c5, "◅", "So", 0, "\\whitepointerleft"));
        symbols.add(new Shapes("black diamond", 0x25c6, "◆", "So", 0, "\\mdlgblkdiamond"));
        symbols.add(new Shapes("white diamond", 0x25c7, "◇", "So", 0, "\\mdlgwhtdiamond"));
        symbols.add(new Shapes("white diamond containing black diamond", 0x25c8, "◈", "So", 0, "\\blackinwhitediamond"));
        symbols.add(new Shapes("fisheye", 0x25c9, "◉", "So", 0, "\\fisheye"));
        symbols.add(new Shapes("lozenge", 0x25ca, "◊", "So", 0, "\\mdlgwhtlozenge"));
        symbols.add(new Shapes("white circle", 0x25cb, "○", "So", 0, "\\mdlgwhtcircle"));
        symbols.add(new Shapes("dotted circle", 0x25cc, "◌", "So", 0, "\\dottedcircle"));
        symbols.add(new Shapes("circle with vertical fill", 0x25cd, "◍", "So", 0, "\\circlevertfill"));
        symbols.add(new Shapes("bullseye", 0x25ce, "◎", "So", 0, "\\bullseye"));
        symbols.add(new Shapes("black circle", 0x25cf, "●", "So", 0, "\\mdlgblkcircle"));
        symbols.add(new Shapes("circle with left half black", 0x25d0, "◐", "So", 0, "\\circlelefthalfblack"));
        symbols.add(new Shapes("circle with right half black", 0x25d1, "◑", "So", 0, "\\circlerighthalfblack"));
        symbols.add(new Shapes("circle with lower half black", 0x25d2, "◒", "So", 0, "\\circlebottomhalfblack"));
        symbols.add(new Shapes("circle with upper half black", 0x25d3, "◓", "So", 0, "\\circletophalfblack"));
        symbols.add(new Shapes("circle with upper right quadrant black", 0x25d4, "◔", "So", 0, "\\circleurquadblack"));
        symbols.add(new Shapes("circle with all but upper left quadrant black", 0x25d5, "◕", "So", 0, "\\blackcircleulquadwhite"));
        symbols.add(new Shapes("left half black circle", 0x25d6, "◖", "So", 0, "\\blacklefthalfcircle"));
        symbols.add(new Shapes("right half black circle", 0x25d7, "◗", "So", 0, "\\blackrighthalfcircle"));
        symbols.add(new Shapes("inverse bullet", 0x25d8, "◘", "So", 0, "\\inversebullet"));
        symbols.add(new Shapes("inverse white circle", 0x25d9, "◙", "So", 0, "\\inversewhitecircle"));
        symbols.add(new Shapes("upper half inverse white circle", 0x25da, "◚", "So", 0, "\\invwhiteupperhalfcircle"));
        symbols.add(new Shapes("lower half inverse white circle", 0x25db, "◛", "So", 0, "\\invwhitelowerhalfcircle"));
        symbols.add(new Shapes("upper left quadrant circular arc", 0x25dc, "◜", "So", 0, "\\ularc"));
        symbols.add(new Shapes("upper right quadrant circular arc", 0x25dd, "◝", "So", 0, "\\urarc"));
        symbols.add(new Shapes("lower right quadrant circular arc", 0x25de, "◞", "So", 0, "\\lrarc"));
        symbols.add(new Shapes("lower left quadrant circular arc", 0x25df, "◟", "So", 0, "\\llarc"));
        symbols.add(new Shapes("upper half circle", 0x25e0, "◠", "So", 0, "\\topsemicircle"));
        symbols.add(new Shapes("lower half circle", 0x25e1, "◡", "So", 0, "\\botsemicircle"));
        symbols.add(new Shapes("black lower right triangle", 0x25e2, "◢", "So", 0, "\\lrblacktriangle"));
        symbols.add(new Shapes("black lower left triangle", 0x25e3, "◣", "So", 0, "\\llblacktriangle"));
        symbols.add(new Shapes("black upper left triangle", 0x25e4, "◤", "So", 0, "\\ulblacktriangle"));
        symbols.add(new Shapes("black upper right triangle", 0x25e5, "◥", "So", 0, "\\urblacktriangle"));
        symbols.add(new Shapes("white bullet", 0x25e6, "◦", "So", 0, "\\smwhtcircle"));
        symbols.add(new Shapes("square with left half black", 0x25e7, "◧", "So", 0, "\\squareleftblack"));
        symbols.add(new Shapes("square with right half black", 0x25e8, "◨", "So", 0, "\\squarerightblack"));
        symbols.add(new Shapes("square with upper left diagonal half black", 0x25e9, "◩", "So", 0, "\\squareulblack"));
        symbols.add(new Shapes("square with lower right diagonal half black", 0x25ea, "◪", "So", 0, "\\squarelrblack"));
        symbols.add(new Shapes("white square with vertical bisecting line", 0x25eb, "◫", "So", 0, "\\boxbar"));
        symbols.add(new Shapes("white up-pointing triangle with dot", 0x25ec, "◬", "So", 0, "\\trianglecdot"));
        symbols.add(new Shapes("up-pointing triangle with left half black", 0x25ed, "◭", "So", 0, "\\triangleleftblack"));
        symbols.add(new Shapes("up-pointing triangle with right half black", 0x25ee, "◮", "So", 0, "\\trianglerightblack"));
        symbols.add(new Shapes("large circle", 0x25ef, "◯", "So", 0, "\\lgwhtcircle"));
        symbols.add(new Shapes("white square with upper left quadrant", 0x25f0, "◰", "So", 0, "\\squareulquad"));
        symbols.add(new Shapes("white square with lower left quadrant", 0x25f1, "◱", "So", 0, "\\squarellquad"));
        symbols.add(new Shapes("white square with lower right quadrant", 0x25f2, "◲", "So", 0, "\\squarelrquad"));
        symbols.add(new Shapes("white square with upper right quadrant", 0x25f3, "◳", "So", 0, "\\squareurquad"));
        symbols.add(new Shapes("white circle with upper left quadrant", 0x25f4, "◴", "So", 0, "\\circleulquad"));
        symbols.add(new Shapes("white circle with lower left quadrant", 0x25f5, "◵", "So", 0, "\\circlellquad"));
        symbols.add(new Shapes("white circle with lower right quadrant", 0x25f6, "◶", "So", 0, "\\circlelrquad"));
        symbols.add(new Shapes("white circle with upper right quadrant", 0x25f7, "◷", "So", 0, "\\circleurquad"));
        symbols.add(new Shapes("upper left triangle", 0x25f8, "◸", "Sm", 0, "\\ultriangle"));
        symbols.add(new Shapes("upper right triangle", 0x25f9, "◹", "Sm", 0, "\\urtriangle"));
        symbols.add(new Shapes("lower left triangle", 0x25fa, "◺", "Sm", 0, "\\lltriangle"));
        symbols.add(new Shapes("white medium square", 0x25fb, "◻", "Sm", 0, "\\mdwhtsquare"));
        symbols.add(new Shapes("black medium square", 0x25fc, "◼", "Sm", 0, "\\mdblksquare"));
        symbols.add(new Shapes("white medium square", 0x25fd, "◽", "Sm", 0, "\\mdsmwhtsquare"));
        symbols.add(new Shapes("black medium square", 0x25fe, "◾", "Sm", 0, "\\mdsmblksquare"));
        symbols.add(new Shapes("lower right triangle", 0x25ff, "◿", "Sm", 0, "\\lrtriangle"));
        symbols.add(new Shapes("black safety scissors", 0x2700, "✀", "So", 0));
        symbols.add(new Shapes("upper blade scissors", 0x2701, "✁", "So", 0));
        symbols.add(new Shapes("black scissors", 0x2702, "✂", "So", 0));
        symbols.add(new Shapes("lower blade scissors", 0x2703, "✃", "So", 0));
        symbols.add(new Shapes("white scissors", 0x2704, "✄", "So", 0));
        symbols.add(new Shapes("white heavy check mark", 0x2705, "✅", "So", 0));
        symbols.add(new Shapes("telephone location sign", 0x2706, "✆", "So", 0));
        symbols.add(new Shapes("tape drive", 0x2707, "✇", "So", 0));
        symbols.add(new Shapes("airplane", 0x2708, "✈", "So", 0));
        symbols.add(new Shapes("envelope", 0x2709, "✉", "So", 0));
        symbols.add(new Shapes("raised fist", 0x270a, "✊", "So", 0));
        symbols.add(new Shapes("raised hand", 0x270b, "✋", "So", 0));
        symbols.add(new Shapes("victory hand", 0x270c, "✌", "So", 0));
        symbols.add(new Shapes("writing hand", 0x270d, "✍", "So", 0));
        symbols.add(new Shapes("lower right pencil", 0x270e, "✎", "So", 0));
        symbols.add(new Shapes("pencil", 0x270f, "✏", "So", 0));
        symbols.add(new Shapes("upper right pencil", 0x2710, "✐", "So", 0));
        symbols.add(new Shapes("white nib", 0x2711, "✑", "So", 0));
        symbols.add(new Shapes("black nib", 0x2712, "✒", "So", 0));
        symbols.add(new Shapes("check mark", 0x2713, "✓", "So", 0, "\\checkmark"));
        symbols.add(new Shapes("heavy check mark", 0x2714, "✔", "So", 0));
        symbols.add(new Shapes("multiplication x", 0x2715, "✕", "So", 0));
        symbols.add(new Shapes("heavy multiplication x", 0x2716, "✖", "So", 0));
        symbols.add(new Shapes("ballot x", 0x2717, "✗", "So", 0));
        symbols.add(new Shapes("heavy ballot x", 0x2718, "✘", "So", 0));
        symbols.add(new Shapes("outlined cross", 0x2719, "✙", "So", 0));
        symbols.add(new Shapes("heavy cross", 0x271a, "✚", "So", 0));
        symbols.add(new Shapes("open centre cross", 0x271b, "✛", "So", 0));
        symbols.add(new Shapes("heavy open centre cross", 0x271c, "✜", "So", 0));
        symbols.add(new Shapes("latin cross", 0x271d, "✝", "So", 0));
        symbols.add(new Shapes("shadowed white latin cross", 0x271e, "✞", "So", 0));
        symbols.add(new Shapes("outlined latin cross", 0x271f, "✟", "So", 0));
        symbols.add(new Shapes("maltese cross", 0x2720, "✠", "So", 0, "\\maltese"));
        symbols.add(new Shapes("star of david", 0x2721, "✡", "So", 0));
        symbols.add(new Shapes("four teardrop-spoked asterisk", 0x2722, "✢", "So", 0));
        symbols.add(new Shapes("four balloon-spoked asterisk", 0x2723, "✣", "So", 0));
        symbols.add(new Shapes("heavy four balloon-spoked asterisk", 0x2724, "✤", "So", 0));
        symbols.add(new Shapes("four club-spoked asterisk", 0x2725, "✥", "So", 0));
        symbols.add(new Shapes("black four pointed star", 0x2726, "✦", "So", 0));
        symbols.add(new Shapes("white four pointed star", 0x2727, "✧", "So", 0));
        symbols.add(new Shapes("sparkles", 0x2728, "✨", "So", 0));
        symbols.add(new Shapes("stress outlined white star", 0x2729, "✩", "So", 0));
        symbols.add(new Shapes("circled white star", 0x272a, "✪", "So", 0, "\\circledstar"));
        symbols.add(new Shapes("open centre black star", 0x272b, "✫", "So", 0));
        symbols.add(new Shapes("black centre white star", 0x272c, "✬", "So", 0));
        symbols.add(new Shapes("outlined black star", 0x272d, "✭", "So", 0));
        symbols.add(new Shapes("heavy outlined black star", 0x272e, "✮", "So", 0));
        symbols.add(new Shapes("pinwheel star", 0x272f, "✯", "So", 0));
        symbols.add(new Shapes("shadowed white star", 0x2730, "✰", "So", 0));
        symbols.add(new Shapes("heavy asterisk", 0x2731, "✱", "So", 0));
        symbols.add(new Shapes("open centre asterisk", 0x2732, "✲", "So", 0));
        symbols.add(new Shapes("eight spoked asterisk", 0x2733, "✳", "So", 0));
        symbols.add(new Shapes("eight pointed black star", 0x2734, "✴", "So", 0));
        symbols.add(new Shapes("eight pointed pinwheel star", 0x2735, "✵", "So", 0));
        symbols.add(new Shapes("six pointed black star", 0x2736, "✶", "So", 0, "\\varstar"));
        symbols.add(new Shapes("eight pointed rectilinear black star", 0x2737, "✷", "So", 0));
        symbols.add(new Shapes("heavy eight pointed rectilinear black star", 0x2738, "✸", "So", 0));
        symbols.add(new Shapes("twelve pointed black star", 0x2739, "✹", "So", 0));
        symbols.add(new Shapes("sixteen pointed asterisk", 0x273a, "✺", "So", 0));
        symbols.add(new Shapes("teardrop-spoked asterisk", 0x273b, "✻", "So", 0));
        symbols.add(new Shapes("open centre teardrop-spoked asterisk", 0x273c, "✼", "So", 0));
        symbols.add(new Shapes("heavy teardrop-spoked asterisk", 0x273d, "✽", "So", 0, "\\dingasterisk"));
        symbols.add(new Shapes("six petalled black and white florette", 0x273e, "✾", "So", 0));
        symbols.add(new Shapes("black florette", 0x273f, "✿", "So", 0));
        symbols.add(new Shapes("white florette", 0x2740, "❀", "So", 0));
        symbols.add(new Shapes("eight petalled outlined black florette", 0x2741, "❁", "So", 0));
        symbols.add(new Shapes("circled open centre eight pointed star", 0x2742, "❂", "So", 0));
        symbols.add(new Shapes("heavy teardrop-spoked pinwheel asterisk", 0x2743, "❃", "So", 0));
        symbols.add(new Shapes("snowflake", 0x2744, "❄", "So", 0));
        symbols.add(new Shapes("tight trifoliate snowflake", 0x2745, "❅", "So", 0));
        symbols.add(new Shapes("heavy chevron snowflake", 0x2746, "❆", "So", 0));
        symbols.add(new Shapes("sparkle", 0x2747, "❇", "So", 0));
        symbols.add(new Shapes("heavy sparkle", 0x2748, "❈", "So", 0));
        symbols.add(new Shapes("balloon-spoked asterisk", 0x2749, "❉", "So", 0));
        symbols.add(new Shapes("eight teardrop-spoked propeller asterisk", 0x274a, "❊", "So", 0));
        symbols.add(new Shapes("heavy eight teardrop-spoked propeller asterisk", 0x274b, "❋", "So", 0));
        symbols.add(new Shapes("cross mark", 0x274c, "❌", "So", 0));
        symbols.add(new Shapes("shadowed white circle", 0x274d, "❍", "So", 0));
        symbols.add(new Shapes("negative squared cross mark", 0x274e, "❎", "So", 0));
        symbols.add(new Shapes("lower right drop-shadowed white square", 0x274f, "❏", "So", 0));
        symbols.add(new Shapes("upper right drop-shadowed white square", 0x2750, "❐", "So", 0));
        symbols.add(new Shapes("lower right shadowed white square", 0x2751, "❑", "So", 0));
        symbols.add(new Shapes("upper right shadowed white square", 0x2752, "❒", "So", 0));
        symbols.add(new Shapes("black question mark ornament", 0x2753, "❓", "So", 0));
        symbols.add(new Shapes("white question mark ornament", 0x2754, "❔", "So", 0));
        symbols.add(new Shapes("white exclamation mark ornament", 0x2755, "❕", "So", 0));
        symbols.add(new Shapes("black diamond minus white x", 0x2756, "❖", "So", 0));
        symbols.add(new Shapes("heavy exclamation mark symbol", 0x2757, "❗", "So", 0));
        symbols.add(new Shapes("light vertical bar", 0x2758, "❘", "So", 0));
        symbols.add(new Shapes("medium vertical bar", 0x2759, "❙", "So", 0));
        symbols.add(new Shapes("heavy vertical bar", 0x275a, "❚", "So", 0));
        symbols.add(new Shapes("heavy single turned comma quotation mark ornament", 0x275b, "❛", "So", 0));
        symbols.add(new Shapes("heavy single comma quotation mark ornament", 0x275c, "❜", "So", 0));
        symbols.add(new Shapes("heavy double turned comma quotation mark ornament", 0x275d, "❝", "So", 0));
        symbols.add(new Shapes("heavy double comma quotation mark ornament", 0x275e, "❞", "So", 0));
        symbols.add(new Shapes("heavy low single comma quotation mark ornament", 0x275f, "❟", "So", 0));
        symbols.add(new Shapes("heavy low double comma quotation mark ornament", 0x2760, "❠", "So", 0));
        symbols.add(new Shapes("curved stem paragraph sign ornament", 0x2761, "❡", "So", 0));
        symbols.add(new Shapes("heavy exclamation mark ornament", 0x2762, "❢", "So", 0));
        symbols.add(new Shapes("heavy heart exclamation mark ornament", 0x2763, "❣", "So", 0));
        symbols.add(new Shapes("heavy black heart", 0x2764, "❤", "So", 0));
        symbols.add(new Shapes("rotated heavy black heart bullet", 0x2765, "❥", "So", 0));
        symbols.add(new Shapes("floral heart", 0x2766, "❦", "So", 0));
        symbols.add(new Shapes("rotated floral heart bullet", 0x2767, "❧", "So", 0));
        symbols.add(new Shapes("medium left parenthesis ornament", 0x2768, "❨", "Ps", 0));
        symbols.add(new Shapes("medium right parenthesis ornament", 0x2769, "❩", "Pe", 0));
        symbols.add(new Shapes("medium flattened left parenthesis ornament", 0x276a, "❪", "Ps", 0));
        symbols.add(new Shapes("medium flattened right parenthesis ornament", 0x276b, "❫", "Pe", 0));
        symbols.add(new Shapes("medium left-pointing angle bracket ornament", 0x276c, "❬", "Ps", 0));
        symbols.add(new Shapes("medium right-pointing angle bracket ornament", 0x276d, "❭", "Pe", 0));
        symbols.add(new Shapes("heavy left-pointing angle quotation mark ornament", 0x276e, "❮", "Ps", 0));
        symbols.add(new Shapes("heavy right-pointing angle quotation mark ornament", 0x276f, "❯", "Pe", 0));
        symbols.add(new Shapes("heavy left-pointing angle bracket ornament", 0x2770, "❰", "Ps", 0));
        symbols.add(new Shapes("heavy right-pointing angle bracket ornament", 0x2771, "❱", "Pe", 0));
        symbols.add(new Shapes("light left tortoise shell bracket ornament", 0x2772, "❲", "Ps", 0, "\\lbrbrak"));
        symbols.add(new Shapes("light right tortoise shell bracket ornament", 0x2773, "❳", "Pe", 0, "\\rbrbrak"));
        symbols.add(new Shapes("medium left curly bracket ornament", 0x2774, "❴", "Ps", 0));
        symbols.add(new Shapes("medium right curly bracket ornament", 0x2775, "❵", "Pe", 0));
        symbols.add(new Shapes("dingbat negative circled 1", 0x2776, "❶", "No", 0));
        symbols.add(new Shapes("dingbat negative circled 2", 0x2777, "❷", "No", 0));
        symbols.add(new Shapes("dingbat negative circled 3", 0x2778, "❸", "No", 0));
        symbols.add(new Shapes("dingbat negative circled 4", 0x2779, "❹", "No", 0));
        symbols.add(new Shapes("dingbat negative circled 5", 0x277a, "❺", "No", 0));
        symbols.add(new Shapes("dingbat negative circled 6", 0x277b, "❻", "No", 0));
        symbols.add(new Shapes("dingbat negative circled 7", 0x277c, "❼", "No", 0));
        symbols.add(new Shapes("dingbat negative circled 8", 0x277d, "❽", "No", 0));
        symbols.add(new Shapes("dingbat negative circled 9", 0x277e, "❾", "No", 0));
        symbols.add(new Shapes("dingbat negative circled number ten", 0x277f, "❿", "No", 0));
        symbols.add(new Shapes("dingbat circled sans-serif 1", 0x2780, "➀", "No", 0));
        symbols.add(new Shapes("dingbat circled sans-serif 2", 0x2781, "➁", "No", 0));
        symbols.add(new Shapes("dingbat circled sans-serif 3", 0x2782, "➂", "No", 0));
        symbols.add(new Shapes("dingbat circled sans-serif 4", 0x2783, "➃", "No", 0));
        symbols.add(new Shapes("dingbat circled sans-serif 5", 0x2784, "➄", "No", 0));
        symbols.add(new Shapes("dingbat circled sans-serif 6", 0x2785, "➅", "No", 0));
        symbols.add(new Shapes("dingbat circled sans-serif 7", 0x2786, "➆", "No", 0));
        symbols.add(new Shapes("dingbat circled sans-serif 8", 0x2787, "➇", "No", 0));
        symbols.add(new Shapes("dingbat circled sans-serif 9", 0x2788, "➈", "No", 0));
        symbols.add(new Shapes("dingbat circled sans-serif number ten", 0x2789, "➉", "No", 0));
        symbols.add(new Shapes("dingbat negative circled sans-serif 1", 0x278a, "➊", "No", 0));
        symbols.add(new Shapes("dingbat negative circled sans-serif 2", 0x278b, "➋", "No", 0));
        symbols.add(new Shapes("dingbat negative circled sans-serif 3", 0x278c, "➌", "No", 0));
        symbols.add(new Shapes("dingbat negative circled sans-serif 4", 0x278d, "➍", "No", 0));
        symbols.add(new Shapes("dingbat negative circled sans-serif 5", 0x278e, "➎", "No", 0));
        symbols.add(new Shapes("dingbat negative circled sans-serif 6", 0x278f, "➏", "No", 0));
        symbols.add(new Shapes("dingbat negative circled sans-serif 7", 0x2790, "➐", "No", 0));
        symbols.add(new Shapes("dingbat negative circled sans-serif 8", 0x2791, "➑", "No", 0));
        symbols.add(new Shapes("dingbat negative circled sans-serif 9", 0x2792, "➒", "No", 0));
        symbols.add(new Shapes("dingbat negative circled sans-serif number ten", 0x2793, "➓", "No", 0));
        symbols.add(new Shapes("heavy wide-headed rightwards arrow", 0x2794, "➔", "So", 0));
        symbols.add(new Shapes("heavy plus sign", 0x2795, "➕", "So", 0));
        symbols.add(new Shapes("heavy minus sign", 0x2796, "➖", "So", 0));
        symbols.add(new Shapes("heavy division sign", 0x2797, "➗", "So", 0));
        symbols.add(new Shapes("heavy south east arrow", 0x2798, "➘", "So", 0));
        symbols.add(new Shapes("heavy rightwards arrow", 0x2799, "➙", "So", 0));
        symbols.add(new Shapes("heavy north east arrow", 0x279a, "➚", "So", 0));
        symbols.add(new Shapes("drafting point rightwards arrow", 0x279b, "➛", "So", 0, "\\draftingarrow"));
        symbols.add(new Shapes("heavy round-tipped rightwards arrow", 0x279c, "➜", "So", 0));
        symbols.add(new Shapes("triangle-headed rightwards arrow", 0x279d, "➝", "So", 0));
        symbols.add(new Shapes("heavy triangle-headed rightwards arrow", 0x279e, "➞", "So", 0));
        symbols.add(new Shapes("dashed triangle-headed rightwards arrow", 0x279f, "➟", "So", 0));
        symbols.add(new Shapes("heavy dashed triangle-headed rightwards arrow", 0x27a0, "➠", "So", 0));
        symbols.add(new Shapes("black rightwards arrow", 0x27a1, "➡", "So", 0));
        symbols.add(new Shapes("three-d top-lighted rightwards arrowhead", 0x27a2, "➢", "So", 0));
        symbols.add(new Shapes("three-d bottom-lighted rightwards arrowhead", 0x27a3, "➣", "So", 0));
        symbols.add(new Shapes("black rightwards arrowhead", 0x27a4, "➤", "So", 0));
        symbols.add(new Shapes("heavy black curved downwards and rightwards arrow", 0x27a5, "➥", "So", 0));
        symbols.add(new Shapes("heavy black curved upwards and rightwards arrow", 0x27a6, "➦", "So", 0));
        symbols.add(new Shapes("squat black rightwards arrow", 0x27a7, "➧", "So", 0));
        symbols.add(new Shapes("heavy concave-pointed black rightwards arrow", 0x27a8, "➨", "So", 0));
        symbols.add(new Shapes("right-shaded white rightwards arrow", 0x27a9, "➩", "So", 0));
        symbols.add(new Shapes("left-shaded white rightwards arrow", 0x27aa, "➪", "So", 0));
        symbols.add(new Shapes("back-tilted shadowed white rightwards arrow", 0x27ab, "➫", "So", 0));
        symbols.add(new Shapes("front-tilted shadowed white rightwards arrow", 0x27ac, "➬", "So", 0));
        symbols.add(new Shapes("heavy lower right-shadowed white rightwards arrow", 0x27ad, "➭", "So", 0));
        symbols.add(new Shapes("heavy upper right-shadowed white rightwards arrow", 0x27ae, "➮", "So", 0));
        symbols.add(new Shapes("notched lower right-shadowed white rightwards arrow", 0x27af, "➯", "So", 0));
        symbols.add(new Shapes("curly loop", 0x27b0, "➰", "So", 0));
        symbols.add(new Shapes("notched upper right-shadowed white rightwards arrow", 0x27b1, "➱", "So", 0));
        symbols.add(new Shapes("circled heavy white rightwards arrow", 0x27b2, "➲", "So", 0));
        symbols.add(new Shapes("white-feathered rightwards arrow", 0x27b3, "➳", "So", 0));
        symbols.add(new Shapes("black-feathered south east arrow", 0x27b4, "➴", "So", 0));
        symbols.add(new Shapes("black-feathered rightwards arrow", 0x27b5, "➵", "So", 0));
        symbols.add(new Shapes("black-feathered north east arrow", 0x27b6, "➶", "So", 0));
        symbols.add(new Shapes("heavy black-feathered south east arrow", 0x27b7, "➷", "So", 0));
        symbols.add(new Shapes("heavy black-feathered rightwards arrow", 0x27b8, "➸", "So", 0));
        symbols.add(new Shapes("heavy black-feathered north east arrow", 0x27b9, "➹", "So", 0));
        symbols.add(new Shapes("teardrop-barbed rightwards arrow", 0x27ba, "➺", "So", 0));
        symbols.add(new Shapes("heavy teardrop-shanked rightwards arrow", 0x27bb, "➻", "So", 0));
        symbols.add(new Shapes("wedge-tailed rightwards arrow", 0x27bc, "➼", "So", 0));
        symbols.add(new Shapes("heavy wedge-tailed rightwards arrow", 0x27bd, "➽", "So", 0));
        symbols.add(new Shapes("open-outlined rightwards arrow", 0x27be, "➾", "So", 0));
        symbols.add(new Shapes("double curly loop", 0x27bf, "➿", "So", 0));
        symbols.add(new Shapes("north west pointing leaf", 0x1f650, "🙐", "So", 0));
        symbols.add(new Shapes("south west pointing leaf", 0x1f651, "🙑", "So", 0));
        symbols.add(new Shapes("north east pointing leaf", 0x1f652, "🙒", "So", 0));
        symbols.add(new Shapes("south east pointing leaf", 0x1f653, "🙓", "So", 0));
        symbols.add(new Shapes("turned north west pointing leaf", 0x1f654, "🙔", "So", 0));
        symbols.add(new Shapes("turned south west pointing leaf", 0x1f655, "🙕", "So", 0));
        symbols.add(new Shapes("turned north east pointing leaf", 0x1f656, "🙖", "So", 0));
        symbols.add(new Shapes("turned south east pointing leaf", 0x1f657, "🙗", "So", 0));
        symbols.add(new Shapes("north west pointing vine leaf", 0x1f658, "🙘", "So", 0));
        symbols.add(new Shapes("south west pointing vine leaf", 0x1f659, "🙙", "So", 0));
        symbols.add(new Shapes("north east pointing vine leaf", 0x1f65a, "🙚", "So", 0));
        symbols.add(new Shapes("south east pointing vine leaf", 0x1f65b, "🙛", "So", 0));
        symbols.add(new Shapes("heavy north west pointing vine leaf", 0x1f65c, "🙜", "So", 0));
        symbols.add(new Shapes("heavy south west pointing vine leaf", 0x1f65d, "🙝", "So", 0));
        symbols.add(new Shapes("heavy north east pointing vine leaf", 0x1f65e, "🙞", "So", 0));
        symbols.add(new Shapes("heavy south east pointing vine leaf", 0x1f65f, "🙟", "So", 0));
        symbols.add(new Shapes("north west pointing bud", 0x1f660, "🙠", "So", 0));
        symbols.add(new Shapes("south west pointing bud", 0x1f661, "🙡", "So", 0));
        symbols.add(new Shapes("north east pointing bud", 0x1f662, "🙢", "So", 0));
        symbols.add(new Shapes("south east pointing bud", 0x1f663, "🙣", "So", 0));
        symbols.add(new Shapes("heavy north west pointing bud", 0x1f664, "🙤", "So", 0));
        symbols.add(new Shapes("heavy south west pointing bud", 0x1f665, "🙥", "So", 0));
        symbols.add(new Shapes("heavy north east pointing bud", 0x1f666, "🙦", "So", 0));
        symbols.add(new Shapes("heavy south east pointing bud", 0x1f667, "🙧", "So", 0));
        symbols.add(new Shapes("hollow quilt square ornament", 0x1f668, "🙨", "So", 0));
        symbols.add(new Shapes("hollow quilt square ornament in black square", 0x1f669, "🙩", "So", 0));
        symbols.add(new Shapes("solid quilt square ornament", 0x1f66a, "🙪", "So", 0));
        symbols.add(new Shapes("solid quilt square ornament in black square", 0x1f66b, "🙫", "So", 0));
        symbols.add(new Shapes("leftwards rocket", 0x1f66c, "🙬", "So", 0));
        symbols.add(new Shapes("upwards rocket", 0x1f66d, "🙭", "So", 0));
        symbols.add(new Shapes("rightwards rocket", 0x1f66e, "🙮", "So", 0));
        symbols.add(new Shapes("downwards rocket", 0x1f66f, "🙯", "So", 0));
        symbols.add(new Shapes("script ligature et ornament", 0x1f670, "🙰", "So", 0));
        symbols.add(new Shapes("heavy script ligature et ornament", 0x1f671, "🙱", "So", 0));
        symbols.add(new Shapes("ligature open et ornament", 0x1f672, "🙲", "So", 0));
        symbols.add(new Shapes("heavy ligature open et ornament", 0x1f673, "🙳", "So", 0));
        symbols.add(new Shapes("heavy ampersand ornament", 0x1f674, "🙴", "So", 0));
        symbols.add(new Shapes("swash ampersand ornament", 0x1f675, "🙵", "So", 0));
        symbols.add(new Shapes("sans-serif heavy double turned comma quotation mark ornament", 0x1f676, "🙶", "So", 0));
        symbols.add(new Shapes("sans-serif heavy double comma quotation mark ornament", 0x1f677, "🙷", "So", 0));
        symbols.add(new Shapes("sans-serif heavy low double comma quotation mark ornament", 0x1f678, "🙸", "So", 0));
        symbols.add(new Shapes("heavy interrobang ornament", 0x1f679, "🙹", "So", 0));
        symbols.add(new Shapes("sans-serif interrobang ornament", 0x1f67a, "🙺", "So", 0));
        symbols.add(new Shapes("heavy sans-serif interrobang ornament", 0x1f67b, "🙻", "So", 0));
        symbols.add(new Shapes("very heavy solidus", 0x1f67c, "🙼", "So", 0));
        symbols.add(new Shapes("very heavy reverse solidus", 0x1f67d, "🙽", "So", 0));
        symbols.add(new Shapes("checker board", 0x1f67e, "🙾", "So", 0));
        symbols.add(new Shapes("reverse checker board", 0x1f67f, "🙿", "So", 0));
        symbols.add(new Shapes("alchemical for quintessence", 0x1f700, "🜀", "So", 0));
        symbols.add(new Shapes("alchemical for air", 0x1f701, "🜁", "So", 0));
        symbols.add(new Shapes("alchemical for fire", 0x1f702, "🜂", "So", 0));
        symbols.add(new Shapes("alchemical for earth", 0x1f703, "🜃", "So", 0));
        symbols.add(new Shapes("alchemical for water", 0x1f704, "🜄", "So", 0));
        symbols.add(new Shapes("alchemical for aquafortis", 0x1f705, "🜅", "So", 0));
        symbols.add(new Shapes("alchemical for aqua regia", 0x1f706, "🜆", "So", 0));
        symbols.add(new Shapes("alchemical for aqua regia-2", 0x1f707, "🜇", "So", 0));
        symbols.add(new Shapes("alchemical for aqua vitae", 0x1f708, "🜈", "So", 0));
        symbols.add(new Shapes("alchemical for aqua vitae-2", 0x1f709, "🜉", "So", 0));
        symbols.add(new Shapes("alchemical for vinegar", 0x1f70a, "🜊", "So", 0));
        symbols.add(new Shapes("alchemical for vinegar-2", 0x1f70b, "🜋", "So", 0));
        symbols.add(new Shapes("alchemical for vinegar-3", 0x1f70c, "🜌", "So", 0));
        symbols.add(new Shapes("alchemical for sulfur", 0x1f70d, "🜍", "So", 0));
        symbols.add(new Shapes("alchemical for philosophers sulfur", 0x1f70e, "🜎", "So", 0));
        symbols.add(new Shapes("alchemical for black sulfur", 0x1f70f, "🜏", "So", 0));
        symbols.add(new Shapes("alchemical for mercury sublimate", 0x1f710, "🜐", "So", 0));
        symbols.add(new Shapes("alchemical for mercury sublimate-2", 0x1f711, "🜑", "So", 0));
        symbols.add(new Shapes("alchemical for mercury sublimate-3", 0x1f712, "🜒", "So", 0));
        symbols.add(new Shapes("alchemical for cinnabar", 0x1f713, "🜓", "So", 0));
        symbols.add(new Shapes("alchemical for salt", 0x1f714, "🜔", "So", 0));
        symbols.add(new Shapes("alchemical for nitre", 0x1f715, "🜕", "So", 0));
        symbols.add(new Shapes("alchemical for vitriol", 0x1f716, "🜖", "So", 0));
        symbols.add(new Shapes("alchemical for vitriol-2", 0x1f717, "🜗", "So", 0));
        symbols.add(new Shapes("alchemical for rock salt", 0x1f718, "🜘", "So", 0));
        symbols.add(new Shapes("alchemical for rock salt-2", 0x1f719, "🜙", "So", 0));
        symbols.add(new Shapes("alchemical for gold", 0x1f71a, "🜚", "So", 0));
        symbols.add(new Shapes("alchemical for silver", 0x1f71b, "🜛", "So", 0));
        symbols.add(new Shapes("alchemical for iron ore", 0x1f71c, "🜜", "So", 0));
        symbols.add(new Shapes("alchemical for iron ore-2", 0x1f71d, "🜝", "So", 0));
        symbols.add(new Shapes("alchemical for crocus of iron", 0x1f71e, "🜞", "So", 0));
        symbols.add(new Shapes("alchemical for regulus of iron", 0x1f71f, "🜟", "So", 0));
        symbols.add(new Shapes("alchemical for copper ore", 0x1f720, "🜠", "So", 0));
        symbols.add(new Shapes("alchemical for iron-copper ore", 0x1f721, "🜡", "So", 0));
        symbols.add(new Shapes("alchemical for sublimate of copper", 0x1f722, "🜢", "So", 0));
        symbols.add(new Shapes("alchemical for crocus of copper", 0x1f723, "🜣", "So", 0));
        symbols.add(new Shapes("alchemical for crocus of copper-2", 0x1f724, "🜤", "So", 0));
        symbols.add(new Shapes("alchemical for copper antimoniate", 0x1f725, "🜥", "So", 0));
        symbols.add(new Shapes("alchemical for salt of copper antimoniate", 0x1f726, "🜦", "So", 0));
        symbols.add(new Shapes("alchemical for sublimate of salt of copper", 0x1f727, "🜧", "So", 0));
        symbols.add(new Shapes("alchemical for verdigris", 0x1f728, "🜨", "So", 0));
        symbols.add(new Shapes("alchemical for tin ore", 0x1f729, "🜩", "So", 0));
        symbols.add(new Shapes("alchemical for lead ore", 0x1f72a, "🜪", "So", 0));
        symbols.add(new Shapes("alchemical for antimony ore", 0x1f72b, "🜫", "So", 0));
        symbols.add(new Shapes("alchemical for sublimate of antimony", 0x1f72c, "🜬", "So", 0));
        symbols.add(new Shapes("alchemical for salt of antimony", 0x1f72d, "🜭", "So", 0));
        symbols.add(new Shapes("alchemical for sublimate of salt of antimony", 0x1f72e, "🜮", "So", 0));
        symbols.add(new Shapes("alchemical for vinegar of antimony", 0x1f72f, "🜯", "So", 0));
        symbols.add(new Shapes("alchemical for regulus of antimony", 0x1f730, "🜰", "So", 0));
        symbols.add(new Shapes("alchemical for regulus of antimony-2", 0x1f731, "🜱", "So", 0));
        symbols.add(new Shapes("alchemical for regulus", 0x1f732, "🜲", "So", 0));
        symbols.add(new Shapes("alchemical for regulus-2", 0x1f733, "🜳", "So", 0));
        symbols.add(new Shapes("alchemical for regulus-3", 0x1f734, "🜴", "So", 0));
        symbols.add(new Shapes("alchemical for regulus-4", 0x1f735, "🜵", "So", 0));
        symbols.add(new Shapes("alchemical for alkali", 0x1f736, "🜶", "So", 0));
        symbols.add(new Shapes("alchemical for alkali-2", 0x1f737, "🜷", "So", 0));
        symbols.add(new Shapes("alchemical for marcasite", 0x1f738, "🜸", "So", 0));
        symbols.add(new Shapes("alchemical for sal-ammoniac", 0x1f739, "🜹", "So", 0));
        symbols.add(new Shapes("alchemical for arsenic", 0x1f73a, "🜺", "So", 0));
        symbols.add(new Shapes("alchemical for realgar", 0x1f73b, "🜻", "So", 0));
        symbols.add(new Shapes("alchemical for realgar-2", 0x1f73c, "🜼", "So", 0));
        symbols.add(new Shapes("alchemical for auripigment", 0x1f73d, "🜽", "So", 0));
        symbols.add(new Shapes("alchemical for bismuth ore", 0x1f73e, "🜾", "So", 0));
        symbols.add(new Shapes("alchemical for tartar", 0x1f73f, "🜿", "So", 0));
        symbols.add(new Shapes("alchemical for tartar-2", 0x1f740, "🝀", "So", 0));
        symbols.add(new Shapes("alchemical for quick lime", 0x1f741, "🝁", "So", 0));
        symbols.add(new Shapes("alchemical for borax", 0x1f742, "🝂", "So", 0));
        symbols.add(new Shapes("alchemical for borax-2", 0x1f743, "🝃", "So", 0));
        symbols.add(new Shapes("alchemical for borax-3", 0x1f744, "🝄", "So", 0));
        symbols.add(new Shapes("alchemical for alum", 0x1f745, "🝅", "So", 0));
        symbols.add(new Shapes("alchemical for oil", 0x1f746, "🝆", "So", 0));
        symbols.add(new Shapes("alchemical for spirit", 0x1f747, "🝇", "So", 0));
        symbols.add(new Shapes("alchemical for tincture", 0x1f748, "🝈", "So", 0));
        symbols.add(new Shapes("alchemical for gum", 0x1f749, "🝉", "So", 0));
        symbols.add(new Shapes("alchemical for wax", 0x1f74a, "🝊", "So", 0));
        symbols.add(new Shapes("alchemical for powder", 0x1f74b, "🝋", "So", 0));
        symbols.add(new Shapes("alchemical for calx", 0x1f74c, "🝌", "So", 0));
        symbols.add(new Shapes("alchemical for tutty", 0x1f74d, "🝍", "So", 0));
        symbols.add(new Shapes("alchemical for caput mortuum", 0x1f74e, "🝎", "So", 0));
        symbols.add(new Shapes("alchemical for scepter of jove", 0x1f74f, "🝏", "So", 0));
        symbols.add(new Shapes("alchemical for caduceus", 0x1f750, "🝐", "So", 0));
        symbols.add(new Shapes("alchemical for trident", 0x1f751, "🝑", "So", 0));
        symbols.add(new Shapes("alchemical for starred trident", 0x1f752, "🝒", "So", 0));
        symbols.add(new Shapes("alchemical for lodestone", 0x1f753, "🝓", "So", 0));
        symbols.add(new Shapes("alchemical for soap", 0x1f754, "🝔", "So", 0));
        symbols.add(new Shapes("alchemical for urine", 0x1f755, "🝕", "So", 0));
        symbols.add(new Shapes("alchemical for horse dung", 0x1f756, "🝖", "So", 0));
        symbols.add(new Shapes("alchemical for ashes", 0x1f757, "🝗", "So", 0));
        symbols.add(new Shapes("alchemical for pot ashes", 0x1f758, "🝘", "So", 0));
        symbols.add(new Shapes("alchemical for brick", 0x1f759, "🝙", "So", 0));
        symbols.add(new Shapes("alchemical for powdered brick", 0x1f75a, "🝚", "So", 0));
        symbols.add(new Shapes("alchemical for amalgam", 0x1f75b, "🝛", "So", 0));
        symbols.add(new Shapes("alchemical for stratum super stratum", 0x1f75c, "🝜", "So", 0));
        symbols.add(new Shapes("alchemical for stratum super stratum-2", 0x1f75d, "🝝", "So", 0));
        symbols.add(new Shapes("alchemical for sublimation", 0x1f75e, "🝞", "So", 0));
        symbols.add(new Shapes("alchemical for precipitate", 0x1f75f, "🝟", "So", 0));
        symbols.add(new Shapes("alchemical for distill", 0x1f760, "🝠", "So", 0));
        symbols.add(new Shapes("alchemical for dissolve", 0x1f761, "🝡", "So", 0));
        symbols.add(new Shapes("alchemical for dissolve-2", 0x1f762, "🝢", "So", 0));
        symbols.add(new Shapes("alchemical for purify", 0x1f763, "🝣", "So", 0));
        symbols.add(new Shapes("alchemical for putrefaction", 0x1f764, "🝤", "So", 0));
        symbols.add(new Shapes("alchemical for crucible", 0x1f765, "🝥", "So", 0));
        symbols.add(new Shapes("alchemical for crucible-2", 0x1f766, "🝦", "So", 0));
        symbols.add(new Shapes("alchemical for crucible-3", 0x1f767, "🝧", "So", 0));
        symbols.add(new Shapes("alchemical for crucible-4", 0x1f768, "🝨", "So", 0));
        symbols.add(new Shapes("alchemical for crucible-5", 0x1f769, "🝩", "So", 0));
        symbols.add(new Shapes("alchemical for alembic", 0x1f76a, "🝪", "So", 0));
        symbols.add(new Shapes("alchemical for bath of mary", 0x1f76b, "🝫", "So", 0));
        symbols.add(new Shapes("alchemical for bath of vapours", 0x1f76c, "🝬", "So", 0));
        symbols.add(new Shapes("alchemical for retort", 0x1f76d, "🝭", "So", 0));
        symbols.add(new Shapes("alchemical for hour", 0x1f76e, "🝮", "So", 0));
        symbols.add(new Shapes("alchemical for night", 0x1f76f, "🝯", "So", 0));
        symbols.add(new Shapes("alchemical for day-night", 0x1f770, "🝰", "So", 0));
        symbols.add(new Shapes("alchemical for month", 0x1f771, "🝱", "So", 0));
        symbols.add(new Shapes("alchemical for half dram", 0x1f772, "🝲", "So", 0));
        symbols.add(new Shapes("alchemical for half ounce", 0x1f773, "🝳", "So", 0));
        symbols.add(new Shapes("black left-pointing isosceles right triangle", 0x1f780, "🞀", "So", 0));
        symbols.add(new Shapes("black up-pointing isosceles right triangle", 0x1f781, "🞁", "So", 0));
        symbols.add(new Shapes("black right-pointing isosceles right triangle", 0x1f782, "🞂", "So", 0));
        symbols.add(new Shapes("black down-pointing isosceles right triangle", 0x1f783, "🞃", "So", 0));
        symbols.add(new Shapes("black slightly circle", 0x1f784, "🞄", "So", 0));
        symbols.add(new Shapes("medium bold white circle", 0x1f785, "🞅", "So", 0));
        symbols.add(new Shapes("bold white circle", 0x1f786, "🞆", "So", 0));
        symbols.add(new Shapes("heavy white circle", 0x1f787, "🞇", "So", 0));
        symbols.add(new Shapes("very heavy white circle", 0x1f788, "🞈", "So", 0));
        symbols.add(new Shapes("extremely heavy white circle", 0x1f789, "🞉", "So", 0));
        symbols.add(new Shapes("white circle containing black circle", 0x1f78a, "🞊", "So", 0));
        symbols.add(new Shapes("round target", 0x1f78b, "🞋", "So", 0));
        symbols.add(new Shapes("black tiny square", 0x1f78c, "🞌", "So", 0));
        symbols.add(new Shapes("black slightly square", 0x1f78d, "🞍", "So", 0));
        symbols.add(new Shapes("light white square", 0x1f78e, "🞎", "So", 0));
        symbols.add(new Shapes("medium white square", 0x1f78f, "🞏", "So", 0));
        symbols.add(new Shapes("bold white square", 0x1f790, "🞐", "So", 0));
        symbols.add(new Shapes("heavy white square", 0x1f791, "🞑", "So", 0));
        symbols.add(new Shapes("very heavy white square", 0x1f792, "🞒", "So", 0));
        symbols.add(new Shapes("extremely heavy white square", 0x1f793, "🞓", "So", 0));
        symbols.add(new Shapes("white square containing black very square", 0x1f794, "🞔", "So", 0));
        symbols.add(new Shapes("white square containing black medium square", 0x1f795, "🞕", "So", 0));
        symbols.add(new Shapes("square target", 0x1f796, "🞖", "So", 0));
        symbols.add(new Shapes("black tiny diamond", 0x1f797, "🞗", "So", 0));
        symbols.add(new Shapes("black very diamond", 0x1f798, "🞘", "So", 0));
        symbols.add(new Shapes("black medium diamond", 0x1f799, "🞙", "So", 0));
        symbols.add(new Shapes("white diamond containing black very diamond", 0x1f79a, "🞚", "So", 0));
        symbols.add(new Shapes("white diamond containing black medium diamond", 0x1f79b, "🞛", "So", 0));
        symbols.add(new Shapes("diamond target", 0x1f79c, "🞜", "So", 0));
        symbols.add(new Shapes("black tiny lozenge", 0x1f79d, "🞝", "So", 0));
        symbols.add(new Shapes("black very lozenge", 0x1f79e, "🞞", "So", 0));
        symbols.add(new Shapes("black medium lozenge", 0x1f79f, "🞟", "So", 0));
        symbols.add(new Shapes("white lozenge containing black lozenge", 0x1f7a0, "🞠", "So", 0));
        symbols.add(new Shapes("thin cross", 0x1f7a1, "🞡", "So", 0));
        symbols.add(new Shapes("light cross", 0x1f7a2, "🞢", "So", 0));
        symbols.add(new Shapes("medium cross", 0x1f7a3, "🞣", "So", 0));
        symbols.add(new Shapes("bold cross", 0x1f7a4, "🞤", "So", 0));
        symbols.add(new Shapes("very bold cross", 0x1f7a5, "🞥", "So", 0));
        symbols.add(new Shapes("very heavy cross", 0x1f7a6, "🞦", "So", 0));
        symbols.add(new Shapes("extremely heavy cross", 0x1f7a7, "🞧", "So", 0));
        symbols.add(new Shapes("thin saltire", 0x1f7a8, "🞨", "So", 0));
        symbols.add(new Shapes("light saltire", 0x1f7a9, "🞩", "So", 0));
        symbols.add(new Shapes("medium saltire", 0x1f7aa, "🞪", "So", 0));
        symbols.add(new Shapes("bold saltire", 0x1f7ab, "🞫", "So", 0));
        symbols.add(new Shapes("heavy saltire", 0x1f7ac, "🞬", "So", 0));
        symbols.add(new Shapes("very heavy saltire", 0x1f7ad, "🞭", "So", 0));
        symbols.add(new Shapes("extremely heavy saltire", 0x1f7ae, "🞮", "So", 0));
        symbols.add(new Shapes("light five spoked asterisk", 0x1f7af, "🞯", "So", 0));
        symbols.add(new Shapes("medium five spoked asterisk", 0x1f7b0, "🞰", "So", 0));
        symbols.add(new Shapes("bold five spoked asterisk", 0x1f7b1, "🞱", "So", 0));
        symbols.add(new Shapes("heavy five spoked asterisk", 0x1f7b2, "🞲", "So", 0));
        symbols.add(new Shapes("very heavy five spoked asterisk", 0x1f7b3, "🞳", "So", 0));
        symbols.add(new Shapes("extremely heavy five spoked asterisk", 0x1f7b4, "🞴", "So", 0));
        symbols.add(new Shapes("light six spoked asterisk", 0x1f7b5, "🞵", "So", 0));
        symbols.add(new Shapes("medium six spoked asterisk", 0x1f7b6, "🞶", "So", 0));
        symbols.add(new Shapes("bold six spoked asterisk", 0x1f7b7, "🞷", "So", 0));
        symbols.add(new Shapes("heavy six spoked asterisk", 0x1f7b8, "🞸", "So", 0));
        symbols.add(new Shapes("very heavy six spoked asterisk", 0x1f7b9, "🞹", "So", 0));
        symbols.add(new Shapes("extremely heavy six spoked asterisk", 0x1f7ba, "🞺", "So", 0));
        symbols.add(new Shapes("light eight spoked asterisk", 0x1f7bb, "🞻", "So", 0));
        symbols.add(new Shapes("medium eight spoked asterisk", 0x1f7bc, "🞼", "So", 0));
        symbols.add(new Shapes("bold eight spoked asterisk", 0x1f7bd, "🞽", "So", 0));
        symbols.add(new Shapes("heavy eight spoked asterisk", 0x1f7be, "🞾", "So", 0));
        symbols.add(new Shapes("very heavy eight spoked asterisk", 0x1f7bf, "🞿", "So", 0));
        symbols.add(new Shapes("light three pointed black star", 0x1f7c0, "🟀", "So", 0));
        symbols.add(new Shapes("medium three pointed black star", 0x1f7c1, "🟁", "So", 0));
        symbols.add(new Shapes("three pointed black star", 0x1f7c2, "🟂", "So", 0));
        symbols.add(new Shapes("medium three pointed pinwheel star", 0x1f7c3, "🟃", "So", 0));
        symbols.add(new Shapes("light four pointed black star", 0x1f7c4, "🟄", "So", 0));
        symbols.add(new Shapes("medium four pointed black star", 0x1f7c5, "🟅", "So", 0));
        symbols.add(new Shapes("four pointed black star", 0x1f7c6, "🟆", "So", 0));
        symbols.add(new Shapes("medium four pointed pinwheel star", 0x1f7c7, "🟇", "So", 0));
        symbols.add(new Shapes("reverse light four pointed pinwheel star", 0x1f7c8, "🟈", "So", 0));
        symbols.add(new Shapes("light five pointed black star", 0x1f7c9, "🟉", "So", 0));
        symbols.add(new Shapes("heavy five pointed black star", 0x1f7ca, "🟊", "So", 0));
        symbols.add(new Shapes("medium six pointed black star", 0x1f7cb, "🟋", "So", 0));
        symbols.add(new Shapes("heavy six pointed black star", 0x1f7cc, "🟌", "So", 0));
        symbols.add(new Shapes("six pointed pinwheel star", 0x1f7cd, "🟍", "So", 0));
        symbols.add(new Shapes("medium eight pointed black star", 0x1f7ce, "🟎", "So", 0));
        symbols.add(new Shapes("heavy eight pointed black star", 0x1f7cf, "🟏", "So", 0));
        symbols.add(new Shapes("very heavy eight pointed black star", 0x1f7d0, "🟐", "So", 0));
        symbols.add(new Shapes("heavy eight pointed pinwheel star", 0x1f7d1, "🟑", "So", 0));
        symbols.add(new Shapes("light twelve pointed black star", 0x1f7d2, "🟒", "So", 0));
        symbols.add(new Shapes("heavy twelve pointed black star", 0x1f7d3, "🟓", "So", 0));
        symbols.add(new Shapes("heavy twelve pointed pinwheel star", 0x1f7d4, "🟔", "So", 0));
        symbols.add(new Shapes("circled triangle", 0x1f7d5, "🟕", "So", 0));
        symbols.add(new Shapes("negative circled triangle", 0x1f7d6, "🟖", "So", 0));
        symbols.add(new Shapes("circled square", 0x1f7d7, "🟗", "So", 0));
        symbols.add(new Shapes("negative circled square", 0x1f7d8, "🟘", "So", 0));
        symbols.add(new Shapes("large orange circle", 0x1f7e0, "🟠", "So", 0));
        symbols.add(new Shapes("large yellow circle", 0x1f7e1, "🟡", "So", 0));
        symbols.add(new Shapes("large green circle", 0x1f7e2, "🟢", "So", 0));
        symbols.add(new Shapes("large purple circle", 0x1f7e3, "🟣", "So", 0));
        symbols.add(new Shapes("large brown circle", 0x1f7e4, "🟤", "So", 0));
        symbols.add(new Shapes("large red square", 0x1f7e5, "🟥", "So", 0));
        symbols.add(new Shapes("large blue square", 0x1f7e6, "🟦", "So", 0));
        symbols.add(new Shapes("large orange square", 0x1f7e7, "🟧", "So", 0));
        symbols.add(new Shapes("large yellow square", 0x1f7e8, "🟨", "So", 0));
        symbols.add(new Shapes("large green square", 0x1f7e9, "🟩", "So", 0));
        symbols.add(new Shapes("large purple square", 0x1f7ea, "🟪", "So", 0));
        symbols.add(new Shapes("large brown square", 0x1f7eb, "🟫", "So", 0));
    }
}