package net.mlcoder.unimath.category;

import lombok.Getter;
import lombok.ToString;
import lombok.experimental.Accessors;

import javax.annotation.Nullable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

@ToString @Getter @Accessors(fluent = true)
public class Arrow implements UniCode {
    public static final List<UniCode> symbols = new ArrayList<>();

    public final String desc;
    public final int codePoint;
    public final String codeStr;
    public final String chars;
    public final String generalCategory;
    public final int combiningClass;
    public final String[] tokenized;

    @Nullable
    public final String latex;

    @Nullable
    public final String ulatex;

    @Nullable
    public final String mathCategory;

    Arrow(int codePoint, String desc, String chars, String generalCategory, int combiningClass) {
        this(codePoint, desc, chars, generalCategory, combiningClass, null, null, null);
    }

    Arrow(int codePoint, String desc, String chars, String generalCategory, int combiningClass,
                 @Nullable String latex, @Nullable String ulatex, @Nullable String mathCategory) {
        this.codePoint = codePoint;
        this.codeStr = String.format("U+%04X", codePoint);
        this.desc = desc;
        this.generalCategory = generalCategory;
        this.combiningClass = combiningClass;
        this.chars = chars;
        this.latex = latex;
        this.ulatex = ulatex;
        this.mathCategory = mathCategory;

        String _latex = latex != null ? " " + latex.substring(1) : "";
        String _ulatex = ulatex != null ? " " + ulatex.substring(1) : "";
        String concanated = (_latex + _ulatex + " " + desc).trim();
        this.tokenized = Arrays.stream(concanated.split(" "))
            .filter(s -> s.length() != 0).toArray(String[]::new);
    }

    static {
        symbols.add(new Arrow(0x2190, "leftwards arrow", "←", "Sm", 0, "\\leftarrow", null, "relation"));
        symbols.add(new Arrow(0x2191, "upwards arrow", "↑", "Sm", 0, "\\uparrow", null, "relation"));
        symbols.add(new Arrow(0x2192, "rightwards arrow", "→", "Sm", 0, "\\rightarrow", null, "relation"));
        symbols.add(new Arrow(0x2193, "downwards arrow", "↓", "Sm", 0, "\\downarrow", null, "relation"));
        symbols.add(new Arrow(0x2194, "left right arrow", "↔", "Sm", 0, "\\leftrightarrow", null, "relation"));
        symbols.add(new Arrow(0x2195, "up down arrow", "↕", "So", 0, "\\updownarrow", null, "relation"));
        symbols.add(new Arrow(0x2196, "north west arrow", "↖", "So", 0, "\\nwarrow", null, "relation"));
        symbols.add(new Arrow(0x2197, "north east arrow", "↗", "So", 0, "\\nearrow", null, "relation"));
        symbols.add(new Arrow(0x2198, "south east arrow", "↘", "So", 0, "\\searrow", null, "relation"));
        symbols.add(new Arrow(0x2199, "south west arrow", "↙", "So", 0, "\\swarrow", null, "relation"));
        symbols.add(new Arrow(0x219A, "leftwards arrow with stroke", "↚", "Sm", 0, "\\nleftarrow", null, "relation"));
        symbols.add(new Arrow(0x219B, "rightwards arrow with stroke", "↛", "Sm", 0, "\\nrightarrow", null, "relation"));
        symbols.add(new Arrow(0x219C, "leftwards wave arrow", "↜", "So", 0, null, "\\leftwavearrow", "relation"));
        symbols.add(new Arrow(0x219D, "rightwards wave arrow", "↝", "So", 0, null, "\\rightwavearrow", "relation"));
        symbols.add(new Arrow(0x219E, "leftwards two headed arrow", "↞", "So", 0, "\\twoheadleftarrow", null, "relation"));
        symbols.add(new Arrow(0x219F, "upwards two headed arrow", "↟", "So", 0, null, "\\twoheaduparrow", "relation"));
        symbols.add(new Arrow(0x21A0, "rightwards two headed arrow", "↠", "Sm", 0, "\\twoheadrightarrow", null, "relation"));
        symbols.add(new Arrow(0x21A1, "downwards two headed arrow", "↡", "So", 0, null, "\\twoheaddownarrow", "relation"));
        symbols.add(new Arrow(0x21A2, "leftwards arrow with tail", "↢", "So", 0, "\\leftarrowtail", null, "relation"));
        symbols.add(new Arrow(0x21A3, "rightwards arrow with tail", "↣", "Sm", 0, "\\rightarrowtail", null, "relation"));
        symbols.add(new Arrow(0x21A4, "leftwards arrow from bar", "↤", "So", 0, "\\mapsfrom", null, "relation"));
        symbols.add(new Arrow(0x21A5, "upwards arrow from bar", "↥", "So", 0, "\\MapsUp", "\\mapsup", "relation"));
        symbols.add(new Arrow(0x21A6, "rightwards arrow from bar", "↦", "Sm", 0, "\\mapsto", null, "relation"));
        symbols.add(new Arrow(0x21A7, "downwards arrow from bar", "↧", "So", 0, "\\MapsDown", "\\mapsdown", "relation"));
        symbols.add(new Arrow(0x21A8, "up down arrow with base", "↨", "So", 0, null, "\\updownarrowbar", "ordinary"));
        symbols.add(new Arrow(0x21A9, "leftwards arrow with hook", "↩", "So", 0, "\\hookleftarrow", null, "relation"));
        symbols.add(new Arrow(0x21AA, "rightwards arrow with hook", "↪", "So", 0, "\\hookrightarrow", null, "relation"));
        symbols.add(new Arrow(0x21AB, "leftwards arrow with loop", "↫", "So", 0, "\\looparrowleft", null, "relation"));
        symbols.add(new Arrow(0x21AC, "rightwards arrow with loop", "↬", "So", 0, "\\looparrowright", null, "relation"));
        symbols.add(new Arrow(0x21AD, "left right wave arrow", "↭", "So", 0, "\\leftrightsquigarrow", null, "relation"));
        symbols.add(new Arrow(0x21AE, "left right arrow with stroke", "↮", "Sm", 0, "\\nleftrightarrow", null, "relation"));
        symbols.add(new Arrow(0x21AF, "downwards zigzag arrow", "↯", "So", 0, "\\lightning", "\\downzigzagarrow", "relation"));
        symbols.add(new Arrow(0x21B0, "upwards arrow with tip leftwards", "↰", "So", 0, "\\Lsh", null, "relation"));
        symbols.add(new Arrow(0x21B1, "upwards arrow with tip rightwards", "↱", "So", 0, "\\Rsh", null, "relation"));
        symbols.add(new Arrow(0x21B2, "downwards arrow with tip leftwards", "↲", "So", 0, "\\dlsh", "\\Ldsh", "relation"));
        symbols.add(new Arrow(0x21B3, "downwards arrow with tip rightwards", "↳", "So", 0, "\\drsh", "\\Rdsh", "relation"));
        symbols.add(new Arrow(0x21B4, "rightwards arrow with corner downwards", "↴", "So", 0, null, "\\linefeed", "ordinary"));
        symbols.add(new Arrow(0x21B5, "downwards arrow with corner leftwards", "↵", "So", 0, null, "\\carriagereturn", "ordinary"));
        symbols.add(new Arrow(0x21B6, "anticlockwise top semicircle arrow", "↶", "So", 0, "\\curvearrowleft", null, "relation"));
        symbols.add(new Arrow(0x21B7, "clockwise top semicircle arrow", "↷", "So", 0, "\\curvearrowright", null, "relation"));
        symbols.add(new Arrow(0x21B8, "north west arrow to long bar", "↸", "So", 0, null, "\\barovernorthwestarrow", "ordinary"));
        symbols.add(new Arrow(0x21B9, "leftwards arrow to bar over rightwards arrow to bar", "↹", "So", 0, null, "\\barleftarrowrightarrowbar", "ordinary"));
        symbols.add(new Arrow(0x21BA, "anticlockwise open circle arrow", "↺", "So", 0, "\\circlearrowleft", "\\acwopencirclearrow", "ordinary"));
        symbols.add(new Arrow(0x21BB, "clockwise open circle arrow", "↻", "So", 0, "\\circlearrowright", "\\cwopencirclearrow", "ordinary"));
        symbols.add(new Arrow(0x21BC, "leftwards harpoon with barb upwards", "↼", "So", 0, "\\leftharpoonup", null, "relation"));
        symbols.add(new Arrow(0x21BD, "leftwards harpoon with barb downwards", "↽", "So", 0, "\\leftharpoondown", null, "relation"));
        symbols.add(new Arrow(0x21BE, "upwards harpoon with barb rightwards", "↾", "So", 0, "\\upharpoonright", null, "relation"));
        symbols.add(new Arrow(0x21BF, "upwards harpoon with barb leftwards", "↿", "So", 0, "\\upharpoonleft", null, "relation"));
        symbols.add(new Arrow(0x21C0, "rightwards harpoon with barb upwards", "⇀", "So", 0, "\\rightharpoonup", null, "relation"));
        symbols.add(new Arrow(0x21C1, "rightwards harpoon with barb downwards", "⇁", "So", 0, "\\rightharpoondown", null, "relation"));
        symbols.add(new Arrow(0x21C2, "downwards harpoon with barb rightwards", "⇂", "So", 0, "\\downharpoonright", null, "relation"));
        symbols.add(new Arrow(0x21C3, "downwards harpoon with barb leftwards", "⇃", "So", 0, "\\downharpoonleft", null, "relation"));
        symbols.add(new Arrow(0x21C4, "rightwards arrow over leftwards arrow", "⇄", "So", 0, "\\rightleftarrows", null, "relation"));
        symbols.add(new Arrow(0x21C5, "upwards arrow leftwards of downwards arrow", "⇅", "So", 0, "\\updownarrows", null, "relation"));
        symbols.add(new Arrow(0x21C6, "leftwards arrow over rightwards arrow", "⇆", "So", 0, "\\leftrightarrows", null, "relation"));
        symbols.add(new Arrow(0x21C7, "leftwards paired arrows", "⇇", "So", 0, "\\leftleftarrows", null, "relation"));
        symbols.add(new Arrow(0x21C8, "upwards paired arrows", "⇈", "So", 0, "\\upuparrows", null, "relation"));
        symbols.add(new Arrow(0x21C9, "rightwards paired arrows", "⇉", "So", 0, "\\rightrightarrows", null, "relation"));
        symbols.add(new Arrow(0x21CA, "downwards paired arrows", "⇊", "So", 0, "\\downdownarrows", null, "relation"));
        symbols.add(new Arrow(0x21CB, "leftwards harpoon over rightwards harpoon", "⇋", "So", 0, "\\leftrightharpoons", null, "relation"));
        symbols.add(new Arrow(0x21CC, "rightwards harpoon over leftwards harpoon", "⇌", "So", 0, "\\rightleftharpoons", null, "relation"));
        symbols.add(new Arrow(0x21CD, "leftwards double arrow with stroke", "⇍", "So", 0, "\\nLeftarrow", null, "relation"));
        symbols.add(new Arrow(0x21CE, "left right double arrow with stroke", "⇎", "Sm", 0, "\\nLeftrightarrow", null, "relation"));
        symbols.add(new Arrow(0x21CF, "rightwards double arrow with stroke", "⇏", "Sm", 0, "\\nRightarrow", null, "relation"));
        symbols.add(new Arrow(0x21D0, "leftwards double arrow", "⇐", "So", 0, "\\Leftarrow", null, "relation"));
        symbols.add(new Arrow(0x21D1, "upwards double arrow", "⇑", "So", 0, "\\Uparrow", null, "relation"));
        symbols.add(new Arrow(0x21D2, "rightwards double arrow", "⇒", "Sm", 0, "\\Rightarrow", null, "relation"));
        symbols.add(new Arrow(0x21D3, "downwards double arrow", "⇓", "So", 0, "\\Downarrow", null, "relation"));
        symbols.add(new Arrow(0x21D4, "left right double arrow", "⇔", "Sm", 0, "\\Leftrightarrow", null, "relation"));
        symbols.add(new Arrow(0x21D5, "up down double arrow", "⇕", "So", 0, "\\Updownarrow", null, "relation"));
        symbols.add(new Arrow(0x21D6, "north west double arrow", "⇖", "So", 0, "\\Nwarrow", null, "relation"));
        symbols.add(new Arrow(0x21D7, "north east double arrow", "⇗", "So", 0, "\\Nearrow", null, "relation"));
        symbols.add(new Arrow(0x21D8, "south east double arrow", "⇘", "So", 0, "\\Searrow", null, "relation"));
        symbols.add(new Arrow(0x21D9, "south west double arrow", "⇙", "So", 0, "\\Swarrow", null, "relation"));
        symbols.add(new Arrow(0x21DA, "leftwards triple arrow", "⇚", "So", 0, "\\Lleftarrow", null, "relation"));
        symbols.add(new Arrow(0x21DB, "rightwards triple arrow", "⇛", "So", 0, "\\Rrightarrow", null, "relation"));
        symbols.add(new Arrow(0x21DC, "leftwards squiggle arrow", "⇜", "So", 0, "\\leftsquigarrow", null, "relation"));
        symbols.add(new Arrow(0x21DD, "rightwards squiggle arrow", "⇝", "So", 0, "\\rightsquigarrow", null, "relation"));
        symbols.add(new Arrow(0x21DE, "upwards arrow with double stroke", "⇞", "So", 0, null, "\\nHuparrow", "ordinary"));
        symbols.add(new Arrow(0x21DF, "downwards arrow with double stroke", "⇟", "So", 0, null, "\\nHdownarrow", "ordinary"));
        symbols.add(new Arrow(0x21E0, "leftwards dashed arrow", "⇠", "So", 0, "\\dashleftarrow", "\\leftdasharrow", "ordinary"));
        symbols.add(new Arrow(0x21E1, "upwards dashed arrow", "⇡", "So", 0, null, "\\updasharrow", "ordinary"));
        symbols.add(new Arrow(0x21E2, "rightwards dashed arrow", "⇢", "So", 0, "\\dashrightarrow", "\\rightdasharrow", "ordinary"));
        symbols.add(new Arrow(0x21E3, "downwards dashed arrow", "⇣", "So", 0, null, "\\downdasharrow", "ordinary"));
        symbols.add(new Arrow(0x21E4, "leftwards arrow to bar", "⇤", "So", 0, "\\LeftArrowBar", "\\barleftarrow", "relation"));
        symbols.add(new Arrow(0x21E5, "rightwards arrow to bar", "⇥", "So", 0, "\\RightArrowBar", "\\rightarrowbar", "relation"));
        symbols.add(new Arrow(0x21E6, "leftwards white arrow", "⇦", "So", 0, null, "\\leftwhitearrow", "ordinary"));
        symbols.add(new Arrow(0x21E7, "upwards white arrow", "⇧", "So", 0, null, "\\upwhitearrow", "ordinary"));
        symbols.add(new Arrow(0x21E8, "rightwards white arrow", "⇨", "So", 0, null, "\\rightwhitearrow", "ordinary"));
        symbols.add(new Arrow(0x21E9, "downwards white arrow", "⇩", "So", 0, null, "\\downwhitearrow", "ordinary"));
        symbols.add(new Arrow(0x21EA, "upwards white arrow from bar", "⇪", "So", 0, null, "\\whitearrowupfrombar", "ordinary"));
        symbols.add(new Arrow(0x21EB, "upwards white arrow on pedestal", "⇫", "So", 0));
        symbols.add(new Arrow(0x21EC, "upwards white arrow on pedestal with horizontal bar", "⇬", "So", 0));
        symbols.add(new Arrow(0x21ED, "upwards white arrow on pedestal with vertical bar", "⇭", "So", 0));
        symbols.add(new Arrow(0x21EE, "upwards white double arrow", "⇮", "So", 0));
        symbols.add(new Arrow(0x21EF, "upwards white double arrow on pedestal", "⇯", "So", 0));
        symbols.add(new Arrow(0x21F0, "rightwards white arrow from wall", "⇰", "So", 0));
        symbols.add(new Arrow(0x21F1, "north west arrow to corner", "⇱", "So", 0));
        symbols.add(new Arrow(0x21F2, "south east arrow to corner", "⇲", "So", 0));
        symbols.add(new Arrow(0x21F3, "up down white arrow", "⇳", "So", 0));
        symbols.add(new Arrow(0x21F4, "right arrow with small circle", "⇴", "Sm", 0, null, "\\circleonrightarrow", "relation"));
        symbols.add(new Arrow(0x21F5, "downwards arrow leftwards of upwards arrow", "⇵", "Sm", 0, "\\downuparrows", null, "relation"));
        symbols.add(new Arrow(0x21F6, "three rightwards arrows", "⇶", "Sm", 0, null, "\\rightthreearrows", "relation"));
        symbols.add(new Arrow(0x21F7, "leftwards arrow with vertical stroke", "⇷", "Sm", 0, null, "\\nvleftarrow", "relation"));
        symbols.add(new Arrow(0x21F8, "rightwards arrow with vertical stroke", "⇸", "Sm", 0, "\\pfun", "\\nvrightarrow", "relation"));
        symbols.add(new Arrow(0x21F9, "left right arrow with vertical stroke", "⇹", "Sm", 0, null, "\\nvleftrightarrow", "relation"));
        symbols.add(new Arrow(0x21FA, "leftwards arrow with double vertical stroke", "⇺", "Sm", 0, null, "\\nVleftarrow", "relation"));
        symbols.add(new Arrow(0x21FB, "rightwards arrow with double vertical stroke", "⇻", "Sm", 0, "\\ffun", "\\nVrightarrow", "relation"));
        symbols.add(new Arrow(0x21FC, "left right arrow with double vertical stroke", "⇼", "Sm", 0, null, "\\nVleftrightarrow", "relation"));
        symbols.add(new Arrow(0x21FD, "leftwards open-headed arrow", "⇽", "Sm", 0, "\\leftarrowtriangle", null, "relation"));
        symbols.add(new Arrow(0x21FE, "rightwards open-headed arrow", "⇾", "Sm", 0, "\\rightarrowtriangle", null, "relation"));
        symbols.add(new Arrow(0x21FF, "left right open-headed arrow", "⇿", "Sm", 0, "\\leftrightarrowtriangle", null, "relation"));
        symbols.add(new Arrow(0x27F0, "upwards quadruple arrow", "⟰", "Sm", 0, null, "\\UUparrow", "relation"));
        symbols.add(new Arrow(0x27F1, "downwards quadruple arrow", "⟱", "Sm", 0, null, "\\DDownarrow", "relation"));
        symbols.add(new Arrow(0x27F2, "anticlockwise gapped circle arrow", "⟲", "Sm", 0, null, "\\acwgapcirclearrow", "relation"));
        symbols.add(new Arrow(0x27F3, "clockwise gapped circle arrow", "⟳", "Sm", 0, null, "\\cwgapcirclearrow", "relation"));
        symbols.add(new Arrow(0x27F4, "right arrow with circled +", "⟴", "Sm", 0, null, "\\rightarrowonoplus", "relation"));
        symbols.add(new Arrow(0x27F5, "long leftwards arrow", "⟵", "Sm", 0, "\\longleftarrow", null, "relation"));
        symbols.add(new Arrow(0x27F6, "long rightwards arrow", "⟶", "Sm", 0, "\\longrightarrow", null, "relation"));
        symbols.add(new Arrow(0x27F7, "long left right arrow", "⟷", "Sm", 0, "\\longleftrightarrow", null, "relation"));
        symbols.add(new Arrow(0x27F8, "long leftwards double arrow", "⟸", "Sm", 0, "\\Longleftarrow", null, "relation"));
        symbols.add(new Arrow(0x27F9, "long rightwards double arrow", "⟹", "Sm", 0, "\\Longrightarrow", null, "relation"));
        symbols.add(new Arrow(0x27FA, "long left right double arrow", "⟺", "Sm", 0, "\\Longleftrightarrow", null, "relation"));
        symbols.add(new Arrow(0x27FB, "long leftwards arrow from bar", "⟻", "Sm", 0, "\\longmapsfrom", null, "relation"));
        symbols.add(new Arrow(0x27FC, "long rightwards arrow from bar", "⟼", "Sm", 0, "\\longmapsto", null, "relation"));
        symbols.add(new Arrow(0x27FD, "long leftwards double arrow from bar", "⟽", "Sm", 0, "\\Longmapsfrom", null, "relation"));
        symbols.add(new Arrow(0x27FE, "long rightwards double arrow from bar", "⟾", "Sm", 0, "\\Longmapsto", null, "relation"));
        symbols.add(new Arrow(0x27FF, "long rightwards squiggle arrow", "⟿", "Sm", 0, null, "\\longrightsquigarrow", "relation"));
        symbols.add(new Arrow(0x2900, "rightwards two-headed arrow with vertical stroke", "⤀", "Sm", 0, "\\psur", "\\nvtwoheadrightarrow", "relation"));
        symbols.add(new Arrow(0x2901, "rightwards two-headed arrow with double vertical stroke", "⤁", "Sm", 0, null, "\\nVtwoheadrightarrow", "relation"));
        symbols.add(new Arrow(0x2902, "leftwards double arrow with vertical stroke", "⤂", "Sm", 0, null, "\\nvLeftarrow", "relation"));
        symbols.add(new Arrow(0x2903, "rightwards double arrow with vertical stroke", "⤃", "Sm", 0, null, "\\nvRightarrow", "relation"));
        symbols.add(new Arrow(0x2904, "left right double arrow with vertical stroke", "⤄", "Sm", 0, null, "\\nvLeftrightarrow", "relation"));
        symbols.add(new Arrow(0x2905, "rightwards two-headed arrow from bar", "⤅", "Sm", 0, null, "\\twoheadmapsto", "relation"));
        symbols.add(new Arrow(0x2906, "leftwards double arrow from bar", "⤆", "Sm", 0, "\\Mapsfrom", null, "relation"));
        symbols.add(new Arrow(0x2907, "rightwards double arrow from bar", "⤇", "Sm", 0, "\\Mapsto", null, "relation"));
        symbols.add(new Arrow(0x2908, "downwards arrow with horizontal stroke", "⤈", "Sm", 0, null, "\\downarrowbarred", "relation"));
        symbols.add(new Arrow(0x2909, "upwards arrow with horizontal stroke", "⤉", "Sm", 0, null, "\\uparrowbarred", "relation"));
        symbols.add(new Arrow(0x290A, "upwards triple arrow", "⤊", "Sm", 0, null, "\\Uuparrow", "relation"));
        symbols.add(new Arrow(0x290B, "downwards triple arrow", "⤋", "Sm", 0, null, "\\Ddownarrow", "relation"));
        symbols.add(new Arrow(0x290C, "leftwards double dash arrow", "⤌", "Sm", 0, null, "\\leftbkarrow", "relation"));
        symbols.add(new Arrow(0x290D, "rightwards double dash arrow", "⤍", "Sm", 0, null, "\\rightbkarrow", "relation"));
        symbols.add(new Arrow(0x290E, "leftwards triple dash arrow", "⤎", "Sm", 0, null, "\\leftdbkarrow", "relation"));
        symbols.add(new Arrow(0x290F, "rightwards triple dash arrow", "⤏", "Sm", 0, null, "\\dbkarrow", "relation"));
        symbols.add(new Arrow(0x2910, "rightwards two-headed triple dash arrow", "⤐", "Sm", 0, null, "\\drbkarrow", "relation"));
        symbols.add(new Arrow(0x2911, "rightwards arrow with dotted stem", "⤑", "Sm", 0, null, "\\rightdotarrow", "relation"));
        symbols.add(new Arrow(0x2912, "upwards arrow to bar", "⤒", "Sm", 0, "\\UpArrowBar", "\\baruparrow", "relation"));
        symbols.add(new Arrow(0x2913, "downwards arrow to bar", "⤓", "Sm", 0, "\\DownArrowBar", "\\downarrowbar", "relation"));
        symbols.add(new Arrow(0x2914, "rightwards arrow with tail with vertical stroke", "⤔", "Sm", 0, "\\pinj", "\\nvrightarrowtail", "relation"));
        symbols.add(new Arrow(0x2915, "rightwards arrow with tail with double vertical stroke", "⤕", "Sm", 0, "\\finj", "\\nVrightarrowtail", "relation"));
        symbols.add(new Arrow(0x2916, "rightwards two-headed arrow with tail", "⤖", "Sm", 0, "\\bij", "\\twoheadrightarrowtail", "relation"));
        symbols.add(new Arrow(0x2917, "rightwards two-headed arrow with tail with vertical stroke", "⤗", "Sm", 0, null, "\\nvtwoheadrightarrowtail", "relation"));
        symbols.add(new Arrow(0x2918, "rightwards two-headed arrow with tail with double vertical stroke", "⤘", "Sm", 0, null, "\\nVtwoheadrightarrowtail", "relation"));
        symbols.add(new Arrow(0x2919, "leftwards arrow-tail", "⤙", "Sm", 0, null, "\\lefttail", "relation"));
        symbols.add(new Arrow(0x291A, "rightwards arrow-tail", "⤚", "Sm", 0, null, "\\righttail", "relation"));
        symbols.add(new Arrow(0x291B, "leftwards double arrow-tail", "⤛", "Sm", 0, null, "\\leftdbltail", "relation"));
        symbols.add(new Arrow(0x291C, "rightwards double arrow-tail", "⤜", "Sm", 0, null, "\\rightdbltail", "relation"));
        symbols.add(new Arrow(0x291D, "leftwards arrow to black diamond", "⤝", "Sm", 0, null, "\\diamondleftarrow", "relation"));
        symbols.add(new Arrow(0x291E, "rightwards arrow to black diamond", "⤞", "Sm", 0, null, "\\rightarrowdiamond", "relation"));
        symbols.add(new Arrow(0x291F, "leftwards arrow from bar to black diamond", "⤟", "Sm", 0, null, "\\diamondleftarrowbar", "relation"));
        symbols.add(new Arrow(0x2920, "rightwards arrow from bar to black diamond", "⤠", "Sm", 0, null, "\\barrightarrowdiamond", "relation"));
        symbols.add(new Arrow(0x2921, "north west and south east arrow", "⤡", "Sm", 0, null, "\\nwsearrow", "relation"));
        symbols.add(new Arrow(0x2922, "north east and south west arrow", "⤢", "Sm", 0, null, "\\neswarrow", "relation"));
        symbols.add(new Arrow(0x2923, "north west arrow with hook", "⤣", "Sm", 0, null, "\\hknwarrow", "relation"));
        symbols.add(new Arrow(0x2924, "north east arrow with hook", "⤤", "Sm", 0, null, "\\hknearrow", "relation"));
        symbols.add(new Arrow(0x2925, "south east arrow with hook", "⤥", "Sm", 0, null, "\\hksearrow", "relation"));
        symbols.add(new Arrow(0x2926, "south west arrow with hook", "⤦", "Sm", 0, null, "\\hkswarrow", "relation"));
        symbols.add(new Arrow(0x2927, "north west arrow and north east arrow", "⤧", "Sm", 0, null, "\\tona", "relation"));
        symbols.add(new Arrow(0x2928, "north east arrow and south east arrow", "⤨", "Sm", 0, null, "\\toea", "relation"));
        symbols.add(new Arrow(0x2929, "south east arrow and south west arrow", "⤩", "Sm", 0, null, "\\tosa", "relation"));
        symbols.add(new Arrow(0x292A, "south west arrow and north west arrow", "⤪", "Sm", 0, null, "\\towa", "relation"));
        symbols.add(new Arrow(0x292B, "rising diagonal crossing falling diagonal", "⤫", "Sm", 0, null, "\\rdiagovfdiag", "ordinary"));
        symbols.add(new Arrow(0x292C, "falling diagonal crossing rising diagonal", "⤬", "Sm", 0, null, "\\fdiagovrdiag", "ordinary"));
        symbols.add(new Arrow(0x292D, "south east arrow crossing north east arrow", "⤭", "Sm", 0, null, "\\seovnearrow", "ordinary"));
        symbols.add(new Arrow(0x292E, "north east arrow crossing south east arrow", "⤮", "Sm", 0, null, "\\neovsearrow", "ordinary"));
        symbols.add(new Arrow(0x292F, "falling diagonal crossing north east arrow", "⤯", "Sm", 0, null, "\\fdiagovnearrow", "ordinary"));
        symbols.add(new Arrow(0x2930, "rising diagonal crossing south east arrow", "⤰", "Sm", 0, null, "\\rdiagovsearrow", "ordinary"));
        symbols.add(new Arrow(0x2931, "north east arrow crossing north west arrow", "⤱", "Sm", 0, null, "\\neovnwarrow", "ordinary"));
        symbols.add(new Arrow(0x2932, "north west arrow crossing north east arrow", "⤲", "Sm", 0, null, "\\nwovnearrow", "ordinary"));
        symbols.add(new Arrow(0x2933, "wave arrow pointing directly right", "⤳", "Sm", 0, "\\leadsto", "\\rightcurvedarrow", "relation"));
        symbols.add(new Arrow(0x2934, "arrow pointing rightwards then curving upwards", "⤴", "Sm", 0, null, "\\uprightcurvearrow", "ordinary"));
        symbols.add(new Arrow(0x2935, "arrow pointing rightwards then curving downwards", "⤵", "Sm", 0, null, "\\downrightcurvedarrow", "ordinary"));
        symbols.add(new Arrow(0x2936, "arrow pointing downwards then curving leftwards", "⤶", "Sm", 0, null, "\\leftdowncurvedarrow", "relation"));
        symbols.add(new Arrow(0x2937, "arrow pointing downwards then curving rightwards", "⤷", "Sm", 0, null, "\\rightdowncurvedarrow", "relation"));
        symbols.add(new Arrow(0x2938, "right-side arc clockwise arrow", "⤸", "Sm", 0, null, "\\cwrightarcarrow", "relation"));
        symbols.add(new Arrow(0x2939, "left-side arc anticlockwise arrow", "⤹", "Sm", 0, null, "\\acwleftarcarrow", "relation"));
        symbols.add(new Arrow(0x293A, "top arc anticlockwise arrow", "⤺", "Sm", 0, null, "\\acwoverarcarrow", "relation"));
        symbols.add(new Arrow(0x293B, "bottom arc anticlockwise arrow", "⤻", "Sm", 0, null, "\\acwunderarcarrow", "relation"));
        symbols.add(new Arrow(0x293C, "top arc clockwise arrow with -", "⤼", "Sm", 0, null, "\\curvearrowrightminus", "relation"));
        symbols.add(new Arrow(0x293D, "top arc anticlockwise arrow with +", "⤽", "Sm", 0, null, "\\curvearrowleftplus", "relation"));
        symbols.add(new Arrow(0x293E, "lower right semicircular clockwise arrow", "⤾", "Sm", 0, null, "\\cwundercurvearrow", "relation"));
        symbols.add(new Arrow(0x293F, "lower left semicircular anticlockwise arrow", "⤿", "Sm", 0, null, "\\ccwundercurvearrow", "relation"));
        symbols.add(new Arrow(0x2940, "anticlockwise closed circle arrow", "⥀", "Sm", 0, null, "\\acwcirclearrow", "relation"));
        symbols.add(new Arrow(0x2941, "clockwise closed circle arrow", "⥁", "Sm", 0, null, "\\cwcirclearrow", "relation"));
        symbols.add(new Arrow(0x2942, "rightwards arrow above short leftwards arrow", "⥂", "Sm", 0, null, "\\rightarrowshortleftarrow", "relation"));
        symbols.add(new Arrow(0x2943, "leftwards arrow above short rightwards arrow", "⥃", "Sm", 0, null, "\\leftarrowshortrightarrow", "relation"));
        symbols.add(new Arrow(0x2944, "short rightwards arrow above leftwards arrow", "⥄", "Sm", 0, null, "\\shortrightarrowleftarrow", "relation"));
        symbols.add(new Arrow(0x2945, "rightwards arrow with plus below", "⥅", "Sm", 0, null, "\\rightarrowplus", "relation"));
        symbols.add(new Arrow(0x2946, "leftwards arrow with plus below", "⥆", "Sm", 0, null, "\\leftarrowplus", "relation"));
        symbols.add(new Arrow(0x2947, "rightwards arrow through x", "⥇", "Sm", 0, null, "\\rightarrowx", "relation"));
        symbols.add(new Arrow(0x2948, "left right arrow through small circle", "⥈", "Sm", 0, null, "\\leftrightarrowcircle", "relation"));
        symbols.add(new Arrow(0x2949, "upwards two-headed arrow from small circle", "⥉", "Sm", 0, null, "\\twoheaduparrowcircle", "relation"));
        symbols.add(new Arrow(0x294A, "left barb up right barb down harpoon", "⥊", "Sm", 0, "\\leftrightharpoon", "\\leftrightharpoonupdown", "relation"));
        symbols.add(new Arrow(0x294B, "left barb down right barb up harpoon", "⥋", "Sm", 0, "\\rightleftharpoon", "\\leftrightharpoondownup", "relation"));
        symbols.add(new Arrow(0x294C, "up barb right down barb left harpoon", "⥌", "Sm", 0, null, "\\updownharpoonrightleft", "relation"));
        symbols.add(new Arrow(0x294D, "up barb left down barb right harpoon", "⥍", "Sm", 0, null, "\\updownharpoonleftright", "relation"));
        symbols.add(new Arrow(0x294E, "left barb up right barb up harpoon", "⥎", "Sm", 0, "\\leftrightharpoonup", "\\leftrightharpoonupup", "relation"));
        symbols.add(new Arrow(0x294F, "up barb right down barb right harpoon", "⥏", "Sm", 0, "\\rightupdownharpoon", "\\updownharpoonrightright", "relation"));
        symbols.add(new Arrow(0x2950, "left barb down right barb down harpoon", "⥐", "Sm", 0, "\\leftrightharpoondown", "\\leftrightharpoondowndown", "relation"));
        symbols.add(new Arrow(0x2951, "up barb left down barb left harpoon", "⥑", "Sm", 0, "\\leftupdownharpoon", "\\updownharpoonleftleft", "relation"));
        symbols.add(new Arrow(0x2952, "leftwards harpoon with barb up to bar", "⥒", "Sm", 0, "\\LeftVectorBar", "\\barleftharpoonup", "relation"));
        symbols.add(new Arrow(0x2953, "rightwards harpoon with barb up to bar", "⥓", "Sm", 0, "\\RightVectorBar", "\\rightharpoonupbar", "relation"));
        symbols.add(new Arrow(0x2954, "upwards harpoon with barb right to bar", "⥔", "Sm", 0, "\\RightUpVectorBar", "\\barupharpoonright", "relation"));
        symbols.add(new Arrow(0x2955, "downwards harpoon with barb right to bar", "⥕", "Sm", 0, "\\RightDownVectorBar", "\\downharpoonrightbar", "relation"));
        symbols.add(new Arrow(0x2956, "leftwards harpoon with barb down to bar", "⥖", "Sm", 0, "\\DownLeftVectorBar", "\\barleftharpoondown", "relation"));
        symbols.add(new Arrow(0x2957, "rightwards harpoon with barb down to bar", "⥗", "Sm", 0, "\\DownRightVectorBar", "\\rightharpoondownbar", "relation"));
        symbols.add(new Arrow(0x2958, "upwards harpoon with barb left to bar", "⥘", "Sm", 0, "\\LeftUpVectorBar", "\\barupharpoonleft", "relation"));
        symbols.add(new Arrow(0x2959, "downwards harpoon with barb left to bar", "⥙", "Sm", 0, "\\LeftDownVectorBar", "\\downharpoonleftbar", "relation"));
        symbols.add(new Arrow(0x295A, "leftwards harpoon with barb up from bar", "⥚", "Sm", 0, "\\LeftTeeVector", "\\leftharpoonupbar", "relation"));
        symbols.add(new Arrow(0x295B, "rightwards harpoon with barb up from bar", "⥛", "Sm", 0, "\\RightTeeVector", "\\barrightharpoonup", "relation"));
        symbols.add(new Arrow(0x295C, "upwards harpoon with barb right from bar", "⥜", "Sm", 0, "\\RightUpTeeVector", "\\upharpoonrightbar", "relation"));
        symbols.add(new Arrow(0x295D, "downwards harpoon with barb right from bar", "⥝", "Sm", 0, "\\RightDownTeeVector", "\\bardownharpoonright", "relation"));
        symbols.add(new Arrow(0x295E, "leftwards harpoon with barb down from bar", "⥞", "Sm", 0, "\\DownLeftTeeVector", "\\leftharpoondownbar", "relation"));
        symbols.add(new Arrow(0x295F, "rightwards harpoon with barb down from bar", "⥟", "Sm", 0, "\\DownRightTeeVector", "\\barrightharpoondown", "relation"));
        symbols.add(new Arrow(0x2960, "upwards harpoon with barb left from bar", "⥠", "Sm", 0, "\\LeftUpTeeVector", "\\upharpoonleftbar", "relation"));
        symbols.add(new Arrow(0x2961, "downwards harpoon with barb left from bar", "⥡", "Sm", 0, "\\LeftDownTeeVector", "\\bardownharpoonleft", "relation"));
        symbols.add(new Arrow(0x2962, "leftwards harpoon with barb up above leftwards harpoon with barb down", "⥢", "Sm", 0, "\\leftleftharpoons", "\\leftharpoonsupdown", "relation"));
        symbols.add(new Arrow(0x2963, "upwards harpoon with barb left beside upwards harpoon with barb right", "⥣", "Sm", 0, "\\upupharpoons", "\\upharpoonsleftright", "relation"));
        symbols.add(new Arrow(0x2964, "rightwards harpoon with barb up above rightwards harpoon with barb down", "⥤", "Sm", 0, "\\rightrightharpoons", "\\rightharpoonsupdown", "relation"));
        symbols.add(new Arrow(0x2965, "downwards harpoon with barb left beside downwards harpoon with barb right", "⥥", "Sm", 0, "\\downdownharpoons", "\\downharpoonsleftright", "relation"));
        symbols.add(new Arrow(0x2966, "leftwards harpoon with barb up above rightwards harpoon with barb up", "⥦", "Sm", 0, null, "\\leftrightharpoonsup", "relation"));
        symbols.add(new Arrow(0x2967, "leftwards harpoon with barb down above rightwards harpoon with barb down", "⥧", "Sm", 0, null, "\\leftrightharpoonsdown", "relation"));
        symbols.add(new Arrow(0x2968, "rightwards harpoon with barb up above leftwards harpoon with barb up", "⥨", "Sm", 0, null, "\\rightleftharpoonsup", "relation"));
        symbols.add(new Arrow(0x2969, "rightwards harpoon with barb down above leftwards harpoon with barb down", "⥩", "Sm", 0, null, "\\rightleftharpoonsdown", "relation"));
        symbols.add(new Arrow(0x296A, "leftwards harpoon with barb up above long dash", "⥪", "Sm", 0, "\\leftbarharpoon", "\\leftharpoonupdash", "relation"));
        symbols.add(new Arrow(0x296B, "leftwards harpoon with barb down below long dash", "⥫", "Sm", 0, "\\barleftharpoon", "\\dashleftharpoondown", "relation"));
        symbols.add(new Arrow(0x296C, "rightwards harpoon with barb up above long dash", "⥬", "Sm", 0, "\\rightbarharpoon", "\\rightharpoonupdash", "relation"));
        symbols.add(new Arrow(0x296D, "rightwards harpoon with barb down below long dash", "⥭", "Sm", 0, "\\barrightharpoon", "\\dashrightharpoondown", "relation"));
        symbols.add(new Arrow(0x296E, "upwards harpoon with barb left beside downwards harpoon with barb right", "⥮", "Sm", 0, "\\updownharpoons", "\\updownharpoonsleftright", "relation"));
        symbols.add(new Arrow(0x296F, "downwards harpoon with barb left beside upwards harpoon with barb right", "⥯", "Sm", 0, "\\downupharpoons", "\\downupharpoonsleftright", "relation"));
        symbols.add(new Arrow(0x2970, "right double arrow with rounded head", "⥰", "Sm", 0, null, "\\rightimply", "relation"));
        symbols.add(new Arrow(0x2971, "equals sign above rightwards arrow", "⥱", "Sm", 0, null, "\\equalrightarrow", "relation"));
        symbols.add(new Arrow(0x2972, "tilde operator above rightwards arrow", "⥲", "Sm", 0, null, "\\similarrightarrow", "relation"));
        symbols.add(new Arrow(0x2973, "leftwards arrow above tilde operator", "⥳", "Sm", 0, null, "\\leftarrowsimilar", "relation"));
        symbols.add(new Arrow(0x2974, "rightwards arrow above tilde operator", "⥴", "Sm", 0, null, "\\rightarrowsimilar", "relation"));
        symbols.add(new Arrow(0x2975, "rightwards arrow above almost equal to", "⥵", "Sm", 0, null, "\\rightarrowapprox", "relation"));
        symbols.add(new Arrow(0x2976, "less-than above leftwards arrow", "⥶", "Sm", 0, null, "\\ltlarr", "relation"));
        symbols.add(new Arrow(0x2977, "leftwards arrow through less-than", "⥷", "Sm", 0, null, "\\leftarrowless", "relation"));
        symbols.add(new Arrow(0x2978, "greater-than above rightwards arrow", "⥸", "Sm", 0, null, "\\gtrarr", "relation"));
        symbols.add(new Arrow(0x2979, "subset above rightwards arrow", "⥹", "Sm", 0, null, "\\subrarr", "relation"));
        symbols.add(new Arrow(0x297A, "leftwards arrow through subset", "⥺", "Sm", 0, null, "\\leftarrowsubset", "relation"));
        symbols.add(new Arrow(0x297B, "superset above leftwards arrow", "⥻", "Sm", 0, null, "\\suplarr", "relation"));
        symbols.add(new Arrow(0x297C, "left fish tail", "⥼", "Sm", 0, "\\strictfi", "\\leftfishtail", "relation"));
        symbols.add(new Arrow(0x297D, "right fish tail", "⥽", "Sm", 0, "\\strictif", "\\rightfishtail", "relation"));
        symbols.add(new Arrow(0x297E, "up fish tail", "⥾", "Sm", 0, null, "\\upfishtail", "relation"));
        symbols.add(new Arrow(0x297F, "down fish tail", "⥿", "Sm", 0, null, "\\downfishtail", "relation"));
        symbols.add(new Arrow(0x2B00, "north east white arrow", "⬀", "So", 0));
        symbols.add(new Arrow(0x2B01, "north west white arrow", "⬁", "So", 0));
        symbols.add(new Arrow(0x2B02, "south east white arrow", "⬂", "So", 0));
        symbols.add(new Arrow(0x2B03, "south west white arrow", "⬃", "So", 0));
        symbols.add(new Arrow(0x2B04, "left right white arrow", "⬄", "So", 0));
        symbols.add(new Arrow(0x2B05, "leftwards black arrow", "⬅", "So", 0));
        symbols.add(new Arrow(0x2B06, "upwards black arrow", "⬆", "So", 0));
        symbols.add(new Arrow(0x2B07, "downwards black arrow", "⬇", "So", 0));
        symbols.add(new Arrow(0x2B08, "north east black arrow", "⬈", "So", 0));
        symbols.add(new Arrow(0x2B09, "north west black arrow", "⬉", "So", 0));
        symbols.add(new Arrow(0x2B0A, "south east black arrow", "⬊", "So", 0));
        symbols.add(new Arrow(0x2B0B, "south west black arrow", "⬋", "So", 0));
        symbols.add(new Arrow(0x2B0C, "left right black arrow", "⬌", "So", 0));
        symbols.add(new Arrow(0x2B0D, "up down black arrow", "⬍", "So", 0));
        symbols.add(new Arrow(0x2B0E, "rightwards arrow with tip downwards", "⬎", "So", 0));
        symbols.add(new Arrow(0x2B0F, "rightwards arrow with tip upwards", "⬏", "So", 0));
        symbols.add(new Arrow(0x2B10, "leftwards arrow with tip downwards", "⬐", "So", 0));
        symbols.add(new Arrow(0x2B11, "leftwards arrow with tip upwards", "⬑", "So", 0));
        symbols.add(new Arrow(0x2B12, "square with top half black", "⬒", "So", 0, null, "\\squaretopblack", "ordinary"));
        symbols.add(new Arrow(0x2B13, "square with bottom half black", "⬓", "So", 0, null, "\\squarebotblack", "ordinary"));
        symbols.add(new Arrow(0x2B14, "square with upper right diagonal half black", "⬔", "So", 0, null, "\\squareurblack", "ordinary"));
        symbols.add(new Arrow(0x2B15, "square with lower left diagonal half black", "⬕", "So", 0, null, "\\squarellblack", "ordinary"));
        symbols.add(new Arrow(0x2B16, "diamond with left half black", "⬖", "So", 0, null, "\\diamondleftblack", "ordinary"));
        symbols.add(new Arrow(0x2B17, "diamond with right half black", "⬗", "So", 0, null, "\\diamondrightblack", "ordinary"));
        symbols.add(new Arrow(0x2B18, "diamond with top half black", "⬘", "So", 0, null, "\\diamondtopblack", "ordinary"));
        symbols.add(new Arrow(0x2B19, "diamond with bottom half black", "⬙", "So", 0, null, "\\diamondbotblack", "ordinary"));
        symbols.add(new Arrow(0x2B1A, "dotted square", "⬚", "So", 0, null, "\\dottedsquare", "ordinary"));
        symbols.add(new Arrow(0x2B1B, "black large square", "⬛", "So", 0, "\\blacksquare", "\\lgblksquare", "ordinary"));
        symbols.add(new Arrow(0x2B1C, "white large square", "⬜", "So", 0, "\\square", "\\lgwhtsquare", "ordinary"));
        symbols.add(new Arrow(0x2B1D, "black very small square", "⬝", "So", 0, null, "\\vysmblksquare", "ordinary"));
        symbols.add(new Arrow(0x2B1E, "white very small square", "⬞", "So", 0, null, "\\vysmwhtsquare", "ordinary"));
        symbols.add(new Arrow(0x2B1F, "black pentagon", "⬟", "So", 0, null, "\\pentagonblack", "ordinary"));
        symbols.add(new Arrow(0x2B20, "white pentagon", "⬠", "So", 0, null, "\\pentagon", "ordinary"));
        symbols.add(new Arrow(0x2B21, "white hexagon", "⬡", "So", 0, null, "\\varhexagon", "ordinary"));
        symbols.add(new Arrow(0x2B22, "black hexagon", "⬢", "So", 0, null, "\\varhexagonblack", "ordinary"));
        symbols.add(new Arrow(0x2B23, "horizontal black hexagon", "⬣", "So", 0, null, "\\hexagonblack", "ordinary"));
        symbols.add(new Arrow(0x2B24, "black large circle", "⬤", "So", 0, null, "\\lgblkcircle", "ordinary"));
        symbols.add(new Arrow(0x2B25, "black medium diamond", "⬥", "So", 0, null, "\\mdblkdiamond", "ordinary"));
        symbols.add(new Arrow(0x2B26, "white medium diamond", "⬦", "So", 0, null, "\\mdwhtdiamond", "ordinary"));
        symbols.add(new Arrow(0x2B27, "black medium lozenge", "⬧", "So", 0, null, "\\mdblklozenge", "ordinary"));
        symbols.add(new Arrow(0x2B28, "white medium lozenge", "⬨", "So", 0, null, "\\mdwhtlozenge", "ordinary"));
        symbols.add(new Arrow(0x2B29, "black small diamond", "⬩", "So", 0, null, "\\smblkdiamond", "ordinary"));
        symbols.add(new Arrow(0x2B2A, "black small lozenge", "⬪", "So", 0, null, "\\smblklozenge", "ordinary"));
        symbols.add(new Arrow(0x2B2B, "white small lozenge", "⬫", "So", 0, null, "\\smwhtlozenge", "ordinary"));
        symbols.add(new Arrow(0x2B2C, "black horizontal ellipse", "⬬", "So", 0, null, "\\blkhorzoval", "ordinary"));
        symbols.add(new Arrow(0x2B2D, "white horizontal ellipse", "⬭", "So", 0, null, "\\whthorzoval", "ordinary"));
        symbols.add(new Arrow(0x2B2E, "black vertical ellipse", "⬮", "So", 0, null, "\\blkvertoval", "ordinary"));
        symbols.add(new Arrow(0x2B2F, "white vertical ellipse", "⬯", "So", 0, null, "\\whtvertoval", "ordinary"));
        symbols.add(new Arrow(0x2B30, "left arrow with small circle", "⬰", "Sm", 0, null, "\\circleonleftarrow", "relation"));
        symbols.add(new Arrow(0x2B31, "three leftwards arrows", "⬱", "Sm", 0, null, "\\leftthreearrows", "relation"));
        symbols.add(new Arrow(0x2B32, "left arrow with circled +", "⬲", "Sm", 0, null, "\\leftarrowonoplus", "relation"));
        symbols.add(new Arrow(0x2B33, "long leftwards squiggle arrow", "⬳", "Sm", 0, null, "\\longleftsquigarrow", "relation"));
        symbols.add(new Arrow(0x2B34, "leftwards two-headed arrow with vertical stroke", "⬴", "Sm", 0, null, "\\nvtwoheadleftarrow", "relation"));
        symbols.add(new Arrow(0x2B35, "leftwards two-headed arrow with double vertical stroke", "⬵", "Sm", 0, null, "\\nVtwoheadleftarrow", "relation"));
        symbols.add(new Arrow(0x2B36, "leftwards two-headed arrow from bar", "⬶", "Sm", 0, null, "\\twoheadmapsfrom", "relation"));
        symbols.add(new Arrow(0x2B37, "leftwards two-headed triple dash arrow", "⬷", "Sm", 0, null, "\\twoheadleftdbkarrow", "relation"));
        symbols.add(new Arrow(0x2B38, "leftwards arrow with dotted stem", "⬸", "Sm", 0, null, "\\leftdotarrow", "relation"));
        symbols.add(new Arrow(0x2B39, "leftwards arrow with tail with vertical stroke", "⬹", "Sm", 0, null, "\\nvleftarrowtail", "relation"));
        symbols.add(new Arrow(0x2B3A, "leftwards arrow with tail with double vertical stroke", "⬺", "Sm", 0, null, "\\nVleftarrowtail", "relation"));
        symbols.add(new Arrow(0x2B3B, "leftwards two-headed arrow with tail", "⬻", "Sm", 0, null, "\\twoheadleftarrowtail", "relation"));
        symbols.add(new Arrow(0x2B3C, "leftwards two-headed arrow with tail with vertical stroke", "⬼", "Sm", 0, null, "\\nvtwoheadleftarrowtail", "relation"));
        symbols.add(new Arrow(0x2B3D, "leftwards two-headed arrow with tail with double vertical stroke", "⬽", "Sm", 0, null, "\\nVtwoheadleftarrowtail", "relation"));
        symbols.add(new Arrow(0x2B3E, "leftwards arrow through x", "⬾", "Sm", 0, null, "\\leftarrowx", "relation"));
        symbols.add(new Arrow(0x2B3F, "wave arrow pointing directly left", "⬿", "Sm", 0, null, "\\leftcurvedarrow", "relation"));
        symbols.add(new Arrow(0x2B40, "equals sign above leftwards arrow", "⭀", "Sm", 0, null, "\\equalleftarrow", "relation"));
        symbols.add(new Arrow(0x2B41, "reverse tilde operator above leftwards arrow", "⭁", "Sm", 0, null, "\\bsimilarleftarrow", "relation"));
        symbols.add(new Arrow(0x2B42, "leftwards arrow above reverse almost equal to", "⭂", "Sm", 0, null, "\\leftarrowbackapprox", "relation"));
        symbols.add(new Arrow(0x2B43, "rightwards arrow through greater-than", "⭃", "Sm", 0, null, "\\rightarrowgtr", "relation"));
        symbols.add(new Arrow(0x2B44, "rightwards arrow through superset", "⭄", "Sm", 0, null, "\\rightarrowsupset", "relation"));
        symbols.add(new Arrow(0x2B45, "leftwards quadruple arrow", "⭅", "So", 0, null, "\\LLeftarrow", "relation"));
        symbols.add(new Arrow(0x2B46, "rightwards quadruple arrow", "⭆", "So", 0, null, "\\RRightarrow", "relation"));
        symbols.add(new Arrow(0x2B47, "reverse tilde operator above rightwards arrow", "⭇", "Sm", 0, null, "\\bsimilarrightarrow", "relation"));
        symbols.add(new Arrow(0x2B48, "rightwards arrow above reverse almost equal to", "⭈", "Sm", 0, null, "\\rightarrowbackapprox", "relation"));
        symbols.add(new Arrow(0x2B49, "tilde operator above leftwards arrow", "⭉", "Sm", 0, null, "\\similarleftarrow", "relation"));
        symbols.add(new Arrow(0x2B4A, "leftwards arrow above almost equal to", "⭊", "Sm", 0, null, "\\leftarrowapprox", "relation"));
        symbols.add(new Arrow(0x2B4B, "leftwards arrow above reverse tilde operator", "⭋", "Sm", 0, null, "\\leftarrowbsimilar", "relation"));
        symbols.add(new Arrow(0x2B4C, "rightwards arrow above reverse tilde operator", "⭌", "Sm", 0, null, "\\rightarrowbsimilar", "relation"));
        symbols.add(new Arrow(0x2B4D, "downwards triangle-headed zigzag arrow", "⭍", "So", 0));
        symbols.add(new Arrow(0x2B4E, "short slanted north arrow", "⭎", "So", 0));
        symbols.add(new Arrow(0x2B4F, "short backslanted south arrow", "⭏", "So", 0));
        symbols.add(new Arrow(0x2B50, "white medium star", "⭐", "So", 0, null, "\\medwhitestar", "ordinary"));
        symbols.add(new Arrow(0x2B51, "black small star", "⭑", "So", 0, null, "\\medblackstar", "ordinary"));
        symbols.add(new Arrow(0x2B52, "white small star", "⭒", "So", 0, null, "\\smwhitestar", "ordinary"));
        symbols.add(new Arrow(0x2B53, "black right-pointing pentagon", "⭓", "So", 0, null, "\\rightpentagonblack", "ordinary"));
        symbols.add(new Arrow(0x2B54, "white right-pointing pentagon", "⭔", "So", 0, null, "\\rightpentagon", "ordinary"));
        symbols.add(new Arrow(0x2B55, "heavy large circle", "⭕", "So", 0));
        symbols.add(new Arrow(0x2B56, "heavy oval with oval inside", "⭖", "So", 0));
        symbols.add(new Arrow(0x2B57, "heavy circle with circle inside", "⭗", "So", 0));
        symbols.add(new Arrow(0x2B58, "heavy circle", "⭘", "So", 0));
        symbols.add(new Arrow(0x2B59, "heavy circled saltire", "⭙", "So", 0));
        symbols.add(new Arrow(0x2B5A, "slanted north arrow with hooked head", "⭚", "So", 0));
        symbols.add(new Arrow(0x2B5B, "backslanted south arrow with hooked tail", "⭛", "So", 0));
        symbols.add(new Arrow(0x2B5C, "slanted north arrow with horizontal tail", "⭜", "So", 0));
        symbols.add(new Arrow(0x2B5D, "backslanted south arrow with horizontal tail", "⭝", "So", 0));
        symbols.add(new Arrow(0x2B5E, "bent arrow pointing downwards then north east", "⭞", "So", 0));
        symbols.add(new Arrow(0x2B5F, "short bent arrow pointing downwards then north east", "⭟", "So", 0));
        symbols.add(new Arrow(0x2B60, "leftwards triangle-headed arrow", "⭠", "So", 0));
        symbols.add(new Arrow(0x2B61, "upwards triangle-headed arrow", "⭡", "So", 0));
        symbols.add(new Arrow(0x2B62, "rightwards triangle-headed arrow", "⭢", "So", 0));
        symbols.add(new Arrow(0x2B63, "downwards triangle-headed arrow", "⭣", "So", 0));
        symbols.add(new Arrow(0x2B64, "left right triangle-headed arrow", "⭤", "So", 0));
        symbols.add(new Arrow(0x2B65, "up down triangle-headed arrow", "⭥", "So", 0));
        symbols.add(new Arrow(0x2B66, "north west triangle-headed arrow", "⭦", "So", 0));
        symbols.add(new Arrow(0x2B67, "north east triangle-headed arrow", "⭧", "So", 0));
        symbols.add(new Arrow(0x2B68, "south east triangle-headed arrow", "⭨", "So", 0));
        symbols.add(new Arrow(0x2B69, "south west triangle-headed arrow", "⭩", "So", 0));
        symbols.add(new Arrow(0x2B6A, "leftwards triangle-headed dashed arrow", "⭪", "So", 0));
        symbols.add(new Arrow(0x2B6B, "upwards triangle-headed dashed arrow", "⭫", "So", 0));
        symbols.add(new Arrow(0x2B6C, "rightwards triangle-headed dashed arrow", "⭬", "So", 0));
        symbols.add(new Arrow(0x2B6D, "downwards triangle-headed dashed arrow", "⭭", "So", 0));
        symbols.add(new Arrow(0x2B6E, "clockwise triangle-headed open circle arrow", "⭮", "So", 0));
        symbols.add(new Arrow(0x2B6F, "anticlockwise triangle-headed open circle arrow", "⭯", "So", 0));
        symbols.add(new Arrow(0x2B70, "leftwards triangle-headed arrow to bar", "⭰", "So", 0));
        symbols.add(new Arrow(0x2B71, "upwards triangle-headed arrow to bar", "⭱", "So", 0));
        symbols.add(new Arrow(0x2B72, "rightwards triangle-headed arrow to bar", "⭲", "So", 0));
        symbols.add(new Arrow(0x2B73, "downwards triangle-headed arrow to bar", "⭳", "So", 0));
        symbols.add(new Arrow(0x2B76, "north west triangle-headed arrow to bar", "⭶", "So", 0));
        symbols.add(new Arrow(0x2B77, "north east triangle-headed arrow to bar", "⭷", "So", 0));
        symbols.add(new Arrow(0x2B78, "south east triangle-headed arrow to bar", "⭸", "So", 0));
        symbols.add(new Arrow(0x2B79, "south west triangle-headed arrow to bar", "⭹", "So", 0));
        symbols.add(new Arrow(0x2B7A, "leftwards triangle-headed arrow with double horizontal stroke", "⭺", "So", 0));
        symbols.add(new Arrow(0x2B7B, "upwards triangle-headed arrow with double horizontal stroke", "⭻", "So", 0));
        symbols.add(new Arrow(0x2B7C, "rightwards triangle-headed arrow with double horizontal stroke", "⭼", "So", 0));
        symbols.add(new Arrow(0x2B7D, "downwards triangle-headed arrow with double horizontal stroke", "⭽", "So", 0));
        symbols.add(new Arrow(0x2B7E, "horizontal tab key", "⭾", "So", 0));
        symbols.add(new Arrow(0x2B7F, "vertical tab key", "⭿", "So", 0));
        symbols.add(new Arrow(0x2B80, "leftwards triangle-headed arrow over rightwards triangle-headed arrow", "⮀", "So", 0));
        symbols.add(new Arrow(0x2B81, "upwards triangle-headed arrow leftwards of downwards triangle-headed arrow", "⮁", "So", 0));
        symbols.add(new Arrow(0x2B82, "rightwards triangle-headed arrow over leftwards triangle-headed arrow", "⮂", "So", 0));
        symbols.add(new Arrow(0x2B83, "downwards triangle-headed arrow leftwards of upwards triangle-headed arrow", "⮃", "So", 0));
        symbols.add(new Arrow(0x2B84, "leftwards triangle-headed paired arrows", "⮄", "So", 0));
        symbols.add(new Arrow(0x2B85, "upwards triangle-headed paired arrows", "⮅", "So", 0));
        symbols.add(new Arrow(0x2B86, "rightwards triangle-headed paired arrows", "⮆", "So", 0));
        symbols.add(new Arrow(0x2B87, "downwards triangle-headed paired arrows", "⮇", "So", 0));
        symbols.add(new Arrow(0x2B88, "leftwards black circled white arrow", "⮈", "So", 0));
        symbols.add(new Arrow(0x2B89, "upwards black circled white arrow", "⮉", "So", 0));
        symbols.add(new Arrow(0x2B8A, "rightwards black circled white arrow", "⮊", "So", 0));
        symbols.add(new Arrow(0x2B8B, "downwards black circled white arrow", "⮋", "So", 0));
        symbols.add(new Arrow(0x2B8C, "anticlockwise triangle-headed right u-shaped arrow", "⮌", "So", 0));
        symbols.add(new Arrow(0x2B8D, "anticlockwise triangle-headed bottom u-shaped arrow", "⮍", "So", 0));
        symbols.add(new Arrow(0x2B8E, "anticlockwise triangle-headed left u-shaped arrow", "⮎", "So", 0));
        symbols.add(new Arrow(0x2B8F, "anticlockwise triangle-headed top u-shaped arrow", "⮏", "So", 0));
        symbols.add(new Arrow(0x2B90, "return left", "⮐", "So", 0));
        symbols.add(new Arrow(0x2B91, "return right", "⮑", "So", 0));
        symbols.add(new Arrow(0x2B92, "newline left", "⮒", "So", 0));
        symbols.add(new Arrow(0x2B93, "newline right", "⮓", "So", 0));
        symbols.add(new Arrow(0x2B94, "four corner arrows circling anticlockwise", "⮔", "So", 0));
        symbols.add(new Arrow(0x2B95, "rightwards black arrow", "⮕", "So", 0));
        symbols.add(new Arrow(0x2B97, "for type a electronics", "⮗", "So", 0));
        symbols.add(new Arrow(0x2B98, "three-d top-lighted leftwards equilateral arrowhead", "⮘", "So", 0));
        symbols.add(new Arrow(0x2B99, "three-d right-lighted upwards equilateral arrowhead", "⮙", "So", 0));
        symbols.add(new Arrow(0x2B9A, "three-d top-lighted rightwards equilateral arrowhead", "⮚", "So", 0));
        symbols.add(new Arrow(0x2B9B, "three-d left-lighted downwards equilateral arrowhead", "⮛", "So", 0));
        symbols.add(new Arrow(0x2B9C, "black leftwards equilateral arrowhead", "⮜", "So", 0));
        symbols.add(new Arrow(0x2B9D, "black upwards equilateral arrowhead", "⮝", "So", 0));
        symbols.add(new Arrow(0x2B9E, "black rightwards equilateral arrowhead", "⮞", "So", 0));
        symbols.add(new Arrow(0x2B9F, "black downwards equilateral arrowhead", "⮟", "So", 0));
        symbols.add(new Arrow(0x2BA0, "downwards triangle-headed arrow with long tip leftwards", "⮠", "So", 0));
        symbols.add(new Arrow(0x2BA1, "downwards triangle-headed arrow with long tip rightwards", "⮡", "So", 0));
        symbols.add(new Arrow(0x2BA2, "upwards triangle-headed arrow with long tip leftwards", "⮢", "So", 0));
        symbols.add(new Arrow(0x2BA3, "upwards triangle-headed arrow with long tip rightwards", "⮣", "So", 0));
        symbols.add(new Arrow(0x2BA4, "leftwards triangle-headed arrow with long tip upwards", "⮤", "So", 0));
        symbols.add(new Arrow(0x2BA5, "rightwards triangle-headed arrow with long tip upwards", "⮥", "So", 0));
        symbols.add(new Arrow(0x2BA6, "leftwards triangle-headed arrow with long tip downwards", "⮦", "So", 0));
        symbols.add(new Arrow(0x2BA7, "rightwards triangle-headed arrow with long tip downwards", "⮧", "So", 0));
        symbols.add(new Arrow(0x2BA8, "black curved downwards and leftwards arrow", "⮨", "So", 0));
        symbols.add(new Arrow(0x2BA9, "black curved downwards and rightwards arrow", "⮩", "So", 0));
        symbols.add(new Arrow(0x2BAA, "black curved upwards and leftwards arrow", "⮪", "So", 0));
        symbols.add(new Arrow(0x2BAB, "black curved upwards and rightwards arrow", "⮫", "So", 0));
        symbols.add(new Arrow(0x2BAC, "black curved leftwards and upwards arrow", "⮬", "So", 0));
        symbols.add(new Arrow(0x2BAD, "black curved rightwards and upwards arrow", "⮭", "So", 0));
        symbols.add(new Arrow(0x2BAE, "black curved leftwards and downwards arrow", "⮮", "So", 0));
        symbols.add(new Arrow(0x2BAF, "black curved rightwards and downwards arrow", "⮯", "So", 0));
        symbols.add(new Arrow(0x2BB0, "ribbon arrow down left", "⮰", "So", 0));
        symbols.add(new Arrow(0x2BB1, "ribbon arrow down right", "⮱", "So", 0));
        symbols.add(new Arrow(0x2BB2, "ribbon arrow up left", "⮲", "So", 0));
        symbols.add(new Arrow(0x2BB3, "ribbon arrow up right", "⮳", "So", 0));
        symbols.add(new Arrow(0x2BB4, "ribbon arrow left up", "⮴", "So", 0));
        symbols.add(new Arrow(0x2BB5, "ribbon arrow right up", "⮵", "So", 0));
        symbols.add(new Arrow(0x2BB6, "ribbon arrow left down", "⮶", "So", 0));
        symbols.add(new Arrow(0x2BB7, "ribbon arrow right down", "⮷", "So", 0));
        symbols.add(new Arrow(0x2BB8, "upwards white arrow from bar with horizontal bar", "⮸", "So", 0));
        symbols.add(new Arrow(0x2BB9, "up arrowhead in a rectangle box", "⮹", "So", 0));
        symbols.add(new Arrow(0x2BBA, "overlapping white squares", "⮺", "So", 0));
        symbols.add(new Arrow(0x2BBB, "overlapping white and black squares", "⮻", "So", 0));
        symbols.add(new Arrow(0x2BBC, "overlapping black squares", "⮼", "So", 0));
        symbols.add(new Arrow(0x2BBD, "ballot box with light x", "⮽", "So", 0));
        symbols.add(new Arrow(0x2BBE, "circled x", "⮾", "So", 0));
        symbols.add(new Arrow(0x2BBF, "circled bold x", "⮿", "So", 0));
        symbols.add(new Arrow(0x2BC0, "black square centred", "⯀", "So", 0));
        symbols.add(new Arrow(0x2BC1, "black diamond centred", "⯁", "So", 0));
        symbols.add(new Arrow(0x2BC2, "turned black pentagon", "⯂", "So", 0));
        symbols.add(new Arrow(0x2BC3, "horizontal black octagon", "⯃", "So", 0));
        symbols.add(new Arrow(0x2BC4, "black octagon", "⯄", "So", 0));
        symbols.add(new Arrow(0x2BC5, "black medium up-pointing triangle centred", "⯅", "So", 0));
        symbols.add(new Arrow(0x2BC6, "black medium down-pointing triangle centred", "⯆", "So", 0));
        symbols.add(new Arrow(0x2BC7, "black medium left-pointing triangle centred", "⯇", "So", 0));
        symbols.add(new Arrow(0x2BC8, "black medium right-pointing triangle centred", "⯈", "So", 0));
        symbols.add(new Arrow(0x2BC9, "neptune form two", "⯉", "So", 0));
        symbols.add(new Arrow(0x2BCA, "top half black circle", "⯊", "So", 0));
        symbols.add(new Arrow(0x2BCB, "bottom half black circle", "⯋", "So", 0));
        symbols.add(new Arrow(0x2BCC, "light four pointed black cusp", "⯌", "So", 0));
        symbols.add(new Arrow(0x2BCD, "rotated light four pointed black cusp", "⯍", "So", 0));
        symbols.add(new Arrow(0x2BCE, "white four pointed cusp", "⯎", "So", 0));
        symbols.add(new Arrow(0x2BCF, "rotated white four pointed cusp", "⯏", "So", 0));
        symbols.add(new Arrow(0x2BD0, "square position indicator", "⯐", "So", 0));
        symbols.add(new Arrow(0x2BD1, "uncertainty sign", "⯑", "So", 0));
        symbols.add(new Arrow(0x2BD2, "group mark", "⯒", "So", 0));
        symbols.add(new Arrow(0x2BD3, "pluto form two", "⯓", "So", 0));
        symbols.add(new Arrow(0x2BD4, "pluto form three", "⯔", "So", 0));
        symbols.add(new Arrow(0x2BD5, "pluto form four", "⯕", "So", 0));
        symbols.add(new Arrow(0x2BD6, "pluto form five", "⯖", "So", 0));
        symbols.add(new Arrow(0x2BD7, "transpluto", "⯗", "So", 0));
        symbols.add(new Arrow(0x2BD8, "proserpina", "⯘", "So", 0));
        symbols.add(new Arrow(0x2BD9, "astraea", "⯙", "So", 0));
        symbols.add(new Arrow(0x2BDA, "hygiea", "⯚", "So", 0));
        symbols.add(new Arrow(0x2BDB, "pholus", "⯛", "So", 0));
        symbols.add(new Arrow(0x2BDC, "nessus", "⯜", "So", 0));
        symbols.add(new Arrow(0x2BDD, "white moon selena", "⯝", "So", 0));
        symbols.add(new Arrow(0x2BDE, "black diamond on cross", "⯞", "So", 0));
        symbols.add(new Arrow(0x2BDF, "true light moon arta", "⯟", "So", 0));
        symbols.add(new Arrow(0x2BE0, "cupido", "⯠", "So", 0));
        symbols.add(new Arrow(0x2BE1, "hades", "⯡", "So", 0));
        symbols.add(new Arrow(0x2BE2, "zeus", "⯢", "So", 0));
        symbols.add(new Arrow(0x2BE3, "kronos", "⯣", "So", 0));
        symbols.add(new Arrow(0x2BE4, "apollon", "⯤", "So", 0));
        symbols.add(new Arrow(0x2BE5, "admetos", "⯥", "So", 0));
        symbols.add(new Arrow(0x2BE6, "vulcanus", "⯦", "So", 0));
        symbols.add(new Arrow(0x2BE7, "poseidon", "⯧", "So", 0));
        symbols.add(new Arrow(0x2BE8, "left half black star", "⯨", "So", 0));
        symbols.add(new Arrow(0x2BE9, "right half black star", "⯩", "So", 0));
        symbols.add(new Arrow(0x2BEA, "star with left half black", "⯪", "So", 0));
        symbols.add(new Arrow(0x2BEB, "star with right half black", "⯫", "So", 0));
        symbols.add(new Arrow(0x2BEC, "leftwards two-headed arrow with triangle arrowheads", "⯬", "So", 0));
        symbols.add(new Arrow(0x2BED, "upwards two-headed arrow with triangle arrowheads", "⯭", "So", 0));
        symbols.add(new Arrow(0x2BEE, "rightwards two-headed arrow with triangle arrowheads", "⯮", "So", 0));
        symbols.add(new Arrow(0x2BEF, "downwards two-headed arrow with triangle arrowheads", "⯯", "So", 0));
        symbols.add(new Arrow(0x2BF0, "eris form one", "⯰", "So", 0));
        symbols.add(new Arrow(0x2BF1, "eris form two", "⯱", "So", 0));
        symbols.add(new Arrow(0x2BF2, "sedna", "⯲", "So", 0));
        symbols.add(new Arrow(0x2BF3, "russian astrological vigintile", "⯳", "So", 0));
        symbols.add(new Arrow(0x2BF4, "russian astrological novile", "⯴", "So", 0));
        symbols.add(new Arrow(0x2BF5, "russian astrological quintile", "⯵", "So", 0));
        symbols.add(new Arrow(0x2BF6, "russian astrological binovile", "⯶", "So", 0));
        symbols.add(new Arrow(0x2BF7, "russian astrological sentagon", "⯷", "So", 0));
        symbols.add(new Arrow(0x2BF8, "russian astrological tredecile", "⯸", "So", 0));
        symbols.add(new Arrow(0x2BF9, "equals sign with infinity below", "⯹", "So", 0));
        symbols.add(new Arrow(0x2BFA, "united", "⯺", "So", 0));
        symbols.add(new Arrow(0x2BFB, "separated", "⯻", "So", 0));
        symbols.add(new Arrow(0x2BFC, "doubled", "⯼", "So", 0));
        symbols.add(new Arrow(0x2BFD, "passed", "⯽", "So", 0));
        symbols.add(new Arrow(0x2BFE, "reversed right angle", "⯾", "So", 0));
        symbols.add(new Arrow(0x2BFF, "hellschreiber pause", "⯿", "So", 0));
        symbols.add(new Arrow(0x1F800, "leftwards arrow with small triangle arrowhead", "🠀", "So", 0));
        symbols.add(new Arrow(0x1F801, "upwards arrow with small triangle arrowhead", "🠁", "So", 0));
        symbols.add(new Arrow(0x1F802, "rightwards arrow with small triangle arrowhead", "🠂", "So", 0));
        symbols.add(new Arrow(0x1F803, "downwards arrow with small triangle arrowhead", "🠃", "So", 0));
        symbols.add(new Arrow(0x1F804, "leftwards arrow with medium triangle arrowhead", "🠄", "So", 0));
        symbols.add(new Arrow(0x1F805, "upwards arrow with medium triangle arrowhead", "🠅", "So", 0));
        symbols.add(new Arrow(0x1F806, "rightwards arrow with medium triangle arrowhead", "🠆", "So", 0));
        symbols.add(new Arrow(0x1F807, "downwards arrow with medium triangle arrowhead", "🠇", "So", 0));
        symbols.add(new Arrow(0x1F808, "leftwards arrow with large triangle arrowhead", "🠈", "So", 0));
        symbols.add(new Arrow(0x1F809, "upwards arrow with large triangle arrowhead", "🠉", "So", 0));
        symbols.add(new Arrow(0x1F80A, "rightwards arrow with large triangle arrowhead", "🠊", "So", 0));
        symbols.add(new Arrow(0x1F80B, "downwards arrow with large triangle arrowhead", "🠋", "So", 0));
        symbols.add(new Arrow(0x1F810, "leftwards arrow with small equilateral arrowhead", "🠐", "So", 0));
        symbols.add(new Arrow(0x1F811, "upwards arrow with small equilateral arrowhead", "🠑", "So", 0));
        symbols.add(new Arrow(0x1F812, "rightwards arrow with small equilateral arrowhead", "🠒", "So", 0));
        symbols.add(new Arrow(0x1F813, "downwards arrow with small equilateral arrowhead", "🠓", "So", 0));
        symbols.add(new Arrow(0x1F814, "leftwards arrow with equilateral arrowhead", "🠔", "So", 0));
        symbols.add(new Arrow(0x1F815, "upwards arrow with equilateral arrowhead", "🠕", "So", 0));
        symbols.add(new Arrow(0x1F816, "rightwards arrow with equilateral arrowhead", "🠖", "So", 0));
        symbols.add(new Arrow(0x1F817, "downwards arrow with equilateral arrowhead", "🠗", "So", 0));
        symbols.add(new Arrow(0x1F818, "heavy leftwards arrow with equilateral arrowhead", "🠘", "So", 0));
        symbols.add(new Arrow(0x1F819, "heavy upwards arrow with equilateral arrowhead", "🠙", "So", 0));
        symbols.add(new Arrow(0x1F81A, "heavy rightwards arrow with equilateral arrowhead", "🠚", "So", 0));
        symbols.add(new Arrow(0x1F81B, "heavy downwards arrow with equilateral arrowhead", "🠛", "So", 0));
        symbols.add(new Arrow(0x1F81C, "heavy leftwards arrow with large equilateral arrowhead", "🠜", "So", 0));
        symbols.add(new Arrow(0x1F81D, "heavy upwards arrow with large equilateral arrowhead", "🠝", "So", 0));
        symbols.add(new Arrow(0x1F81E, "heavy rightwards arrow with large equilateral arrowhead", "🠞", "So", 0));
        symbols.add(new Arrow(0x1F81F, "heavy downwards arrow with large equilateral arrowhead", "🠟", "So", 0));
        symbols.add(new Arrow(0x1F820, "leftwards triangle-headed arrow with narrow shaft", "🠠", "So", 0));
        symbols.add(new Arrow(0x1F821, "upwards triangle-headed arrow with narrow shaft", "🠡", "So", 0));
        symbols.add(new Arrow(0x1F822, "rightwards triangle-headed arrow with narrow shaft", "🠢", "So", 0));
        symbols.add(new Arrow(0x1F823, "downwards triangle-headed arrow with narrow shaft", "🠣", "So", 0));
        symbols.add(new Arrow(0x1F824, "leftwards triangle-headed arrow with medium shaft", "🠤", "So", 0));
        symbols.add(new Arrow(0x1F825, "upwards triangle-headed arrow with medium shaft", "🠥", "So", 0));
        symbols.add(new Arrow(0x1F826, "rightwards triangle-headed arrow with medium shaft", "🠦", "So", 0));
        symbols.add(new Arrow(0x1F827, "downwards triangle-headed arrow with medium shaft", "🠧", "So", 0));
        symbols.add(new Arrow(0x1F828, "leftwards triangle-headed arrow with bold shaft", "🠨", "So", 0));
        symbols.add(new Arrow(0x1F829, "upwards triangle-headed arrow with bold shaft", "🠩", "So", 0));
        symbols.add(new Arrow(0x1F82A, "rightwards triangle-headed arrow with bold shaft", "🠪", "So", 0));
        symbols.add(new Arrow(0x1F82B, "downwards triangle-headed arrow with bold shaft", "🠫", "So", 0));
        symbols.add(new Arrow(0x1F82C, "leftwards triangle-headed arrow with heavy shaft", "🠬", "So", 0));
        symbols.add(new Arrow(0x1F82D, "upwards triangle-headed arrow with heavy shaft", "🠭", "So", 0));
        symbols.add(new Arrow(0x1F82E, "rightwards triangle-headed arrow with heavy shaft", "🠮", "So", 0));
        symbols.add(new Arrow(0x1F82F, "downwards triangle-headed arrow with heavy shaft", "🠯", "So", 0));
        symbols.add(new Arrow(0x1F830, "leftwards triangle-headed arrow with very heavy shaft", "🠰", "So", 0));
        symbols.add(new Arrow(0x1F831, "upwards triangle-headed arrow with very heavy shaft", "🠱", "So", 0));
        symbols.add(new Arrow(0x1F832, "rightwards triangle-headed arrow with very heavy shaft", "🠲", "So", 0));
        symbols.add(new Arrow(0x1F833, "downwards triangle-headed arrow with very heavy shaft", "🠳", "So", 0));
        symbols.add(new Arrow(0x1F834, "leftwards finger-post arrow", "🠴", "So", 0));
        symbols.add(new Arrow(0x1F835, "upwards finger-post arrow", "🠵", "So", 0));
        symbols.add(new Arrow(0x1F836, "rightwards finger-post arrow", "🠶", "So", 0));
        symbols.add(new Arrow(0x1F837, "downwards finger-post arrow", "🠷", "So", 0));
        symbols.add(new Arrow(0x1F838, "leftwards squared arrow", "🠸", "So", 0));
        symbols.add(new Arrow(0x1F839, "upwards squared arrow", "🠹", "So", 0));
        symbols.add(new Arrow(0x1F83A, "rightwards squared arrow", "🠺", "So", 0));
        symbols.add(new Arrow(0x1F83B, "downwards squared arrow", "🠻", "So", 0));
        symbols.add(new Arrow(0x1F83C, "leftwards compressed arrow", "🠼", "So", 0));
        symbols.add(new Arrow(0x1F83D, "upwards compressed arrow", "🠽", "So", 0));
        symbols.add(new Arrow(0x1F83E, "rightwards compressed arrow", "🠾", "So", 0));
        symbols.add(new Arrow(0x1F83F, "downwards compressed arrow", "🠿", "So", 0));
        symbols.add(new Arrow(0x1F840, "leftwards heavy compressed arrow", "🡀", "So", 0));
        symbols.add(new Arrow(0x1F841, "upwards heavy compressed arrow", "🡁", "So", 0));
        symbols.add(new Arrow(0x1F842, "rightwards heavy compressed arrow", "🡂", "So", 0));
        symbols.add(new Arrow(0x1F843, "downwards heavy compressed arrow", "🡃", "So", 0));
        symbols.add(new Arrow(0x1F844, "leftwards heavy arrow", "🡄", "So", 0));
        symbols.add(new Arrow(0x1F845, "upwards heavy arrow", "🡅", "So", 0));
        symbols.add(new Arrow(0x1F846, "rightwards heavy arrow", "🡆", "So", 0));
        symbols.add(new Arrow(0x1F847, "downwards heavy arrow", "🡇", "So", 0));
        symbols.add(new Arrow(0x1F850, "leftwards sans-serif arrow", "🡐", "So", 0));
        symbols.add(new Arrow(0x1F851, "upwards sans-serif arrow", "🡑", "So", 0));
        symbols.add(new Arrow(0x1F852, "rightwards sans-serif arrow", "🡒", "So", 0));
        symbols.add(new Arrow(0x1F853, "downwards sans-serif arrow", "🡓", "So", 0));
        symbols.add(new Arrow(0x1F854, "north west sans-serif arrow", "🡔", "So", 0));
        symbols.add(new Arrow(0x1F855, "north east sans-serif arrow", "🡕", "So", 0));
        symbols.add(new Arrow(0x1F856, "south east sans-serif arrow", "🡖", "So", 0));
        symbols.add(new Arrow(0x1F857, "south west sans-serif arrow", "🡗", "So", 0));
        symbols.add(new Arrow(0x1F858, "left right sans-serif arrow", "🡘", "So", 0));
        symbols.add(new Arrow(0x1F859, "up down sans-serif arrow", "🡙", "So", 0));
        symbols.add(new Arrow(0x1F860, "wide-headed leftwards light barb arrow", "🡠", "So", 0));
        symbols.add(new Arrow(0x1F861, "wide-headed upwards light barb arrow", "🡡", "So", 0));
        symbols.add(new Arrow(0x1F862, "wide-headed rightwards light barb arrow", "🡢", "So", 0));
        symbols.add(new Arrow(0x1F863, "wide-headed downwards light barb arrow", "🡣", "So", 0));
        symbols.add(new Arrow(0x1F864, "wide-headed north west light barb arrow", "🡤", "So", 0));
        symbols.add(new Arrow(0x1F865, "wide-headed north east light barb arrow", "🡥", "So", 0));
        symbols.add(new Arrow(0x1F866, "wide-headed south east light barb arrow", "🡦", "So", 0));
        symbols.add(new Arrow(0x1F867, "wide-headed south west light barb arrow", "🡧", "So", 0));
        symbols.add(new Arrow(0x1F868, "wide-headed leftwards barb arrow", "🡨", "So", 0));
        symbols.add(new Arrow(0x1F869, "wide-headed upwards barb arrow", "🡩", "So", 0));
        symbols.add(new Arrow(0x1F86A, "wide-headed rightwards barb arrow", "🡪", "So", 0));
        symbols.add(new Arrow(0x1F86B, "wide-headed downwards barb arrow", "🡫", "So", 0));
        symbols.add(new Arrow(0x1F86C, "wide-headed north west barb arrow", "🡬", "So", 0));
        symbols.add(new Arrow(0x1F86D, "wide-headed north east barb arrow", "🡭", "So", 0));
        symbols.add(new Arrow(0x1F86E, "wide-headed south east barb arrow", "🡮", "So", 0));
        symbols.add(new Arrow(0x1F86F, "wide-headed south west barb arrow", "🡯", "So", 0));
        symbols.add(new Arrow(0x1F870, "wide-headed leftwards medium barb arrow", "🡰", "So", 0));
        symbols.add(new Arrow(0x1F871, "wide-headed upwards medium barb arrow", "🡱", "So", 0));
        symbols.add(new Arrow(0x1F872, "wide-headed rightwards medium barb arrow", "🡲", "So", 0));
        symbols.add(new Arrow(0x1F873, "wide-headed downwards medium barb arrow", "🡳", "So", 0));
        symbols.add(new Arrow(0x1F874, "wide-headed north west medium barb arrow", "🡴", "So", 0));
        symbols.add(new Arrow(0x1F875, "wide-headed north east medium barb arrow", "🡵", "So", 0));
        symbols.add(new Arrow(0x1F876, "wide-headed south east medium barb arrow", "🡶", "So", 0));
        symbols.add(new Arrow(0x1F877, "wide-headed south west medium barb arrow", "🡷", "So", 0));
        symbols.add(new Arrow(0x1F878, "wide-headed leftwards heavy barb arrow", "🡸", "So", 0));
        symbols.add(new Arrow(0x1F879, "wide-headed upwards heavy barb arrow", "🡹", "So", 0));
        symbols.add(new Arrow(0x1F87A, "wide-headed rightwards heavy barb arrow", "🡺", "So", 0));
        symbols.add(new Arrow(0x1F87B, "wide-headed downwards heavy barb arrow", "🡻", "So", 0));
        symbols.add(new Arrow(0x1F87C, "wide-headed north west heavy barb arrow", "🡼", "So", 0));
        symbols.add(new Arrow(0x1F87D, "wide-headed north east heavy barb arrow", "🡽", "So", 0));
        symbols.add(new Arrow(0x1F87E, "wide-headed south east heavy barb arrow", "🡾", "So", 0));
        symbols.add(new Arrow(0x1F87F, "wide-headed south west heavy barb arrow", "🡿", "So", 0));
        symbols.add(new Arrow(0x1F880, "wide-headed leftwards very heavy barb arrow", "🢀", "So", 0));
        symbols.add(new Arrow(0x1F881, "wide-headed upwards very heavy barb arrow", "🢁", "So", 0));
        symbols.add(new Arrow(0x1F882, "wide-headed rightwards very heavy barb arrow", "🢂", "So", 0));
        symbols.add(new Arrow(0x1F883, "wide-headed downwards very heavy barb arrow", "🢃", "So", 0));
        symbols.add(new Arrow(0x1F884, "wide-headed north west very heavy barb arrow", "🢄", "So", 0));
        symbols.add(new Arrow(0x1F885, "wide-headed north east very heavy barb arrow", "🢅", "So", 0));
        symbols.add(new Arrow(0x1F886, "wide-headed south east very heavy barb arrow", "🢆", "So", 0));
        symbols.add(new Arrow(0x1F887, "wide-headed south west very heavy barb arrow", "🢇", "So", 0));
        symbols.add(new Arrow(0x1F890, "leftwards triangle arrowhead", "🢐", "So", 0));
        symbols.add(new Arrow(0x1F891, "upwards triangle arrowhead", "🢑", "So", 0));
        symbols.add(new Arrow(0x1F892, "rightwards triangle arrowhead", "🢒", "So", 0));
        symbols.add(new Arrow(0x1F893, "downwards triangle arrowhead", "🢓", "So", 0));
        symbols.add(new Arrow(0x1F894, "leftwards white arrow within triangle arrowhead", "🢔", "So", 0));
        symbols.add(new Arrow(0x1F895, "upwards white arrow within triangle arrowhead", "🢕", "So", 0));
        symbols.add(new Arrow(0x1F896, "rightwards white arrow within triangle arrowhead", "🢖", "So", 0));
        symbols.add(new Arrow(0x1F897, "downwards white arrow within triangle arrowhead", "🢗", "So", 0));
        symbols.add(new Arrow(0x1F898, "leftwards arrow with notched tail", "🢘", "So", 0));
        symbols.add(new Arrow(0x1F899, "upwards arrow with notched tail", "🢙", "So", 0));
        symbols.add(new Arrow(0x1F89A, "rightwards arrow with notched tail", "🢚", "So", 0));
        symbols.add(new Arrow(0x1F89B, "downwards arrow with notched tail", "🢛", "So", 0));
        symbols.add(new Arrow(0x1F89C, "heavy arrow shaft width one", "🢜", "So", 0));
        symbols.add(new Arrow(0x1F89D, "heavy arrow shaft width two thirds", "🢝", "So", 0));
        symbols.add(new Arrow(0x1F89E, "heavy arrow shaft width one half", "🢞", "So", 0));
        symbols.add(new Arrow(0x1F89F, "heavy arrow shaft width one third", "🢟", "So", 0));
        symbols.add(new Arrow(0x1F8A0, "leftwards bottom-shaded white arrow", "🢠", "So", 0));
        symbols.add(new Arrow(0x1F8A1, "rightwards bottom shaded white arrow", "🢡", "So", 0));
        symbols.add(new Arrow(0x1F8A2, "leftwards top shaded white arrow", "🢢", "So", 0));
        symbols.add(new Arrow(0x1F8A3, "rightwards top shaded white arrow", "🢣", "So", 0));
        symbols.add(new Arrow(0x1F8A4, "leftwards left-shaded white arrow", "🢤", "So", 0));
        symbols.add(new Arrow(0x1F8A5, "rightwards right-shaded white arrow", "🢥", "So", 0));
        symbols.add(new Arrow(0x1F8A6, "leftwards right-shaded white arrow", "🢦", "So", 0));
        symbols.add(new Arrow(0x1F8A7, "rightwards left-shaded white arrow", "🢧", "So", 0));
        symbols.add(new Arrow(0x1F8A8, "leftwards back-tilted shadowed white arrow", "🢨", "So", 0));
        symbols.add(new Arrow(0x1F8A9, "rightwards back-tilted shadowed white arrow", "🢩", "So", 0));
        symbols.add(new Arrow(0x1F8AA, "leftwards front-tilted shadowed white arrow", "🢪", "So", 0));
        symbols.add(new Arrow(0x1F8AB, "rightwards front-tilted shadowed white arrow", "🢫", "So", 0));
        symbols.add(new Arrow(0x1F8AC, "white arrow shaft width one", "🢬", "So", 0));
        symbols.add(new Arrow(0x1F8AD, "white arrow shaft width two thirds", "🢭", "So", 0));
        symbols.add(new Arrow(0x1F8B0, "arrow pointing upwards then north west", "🢰", "So", 0));
        symbols.add(new Arrow(0x1F8B1, "arrow pointing rightwards then curving south west", "🢱", "So", 0));
    }
}