package net.mlcoder.unimath.category;

import javax.annotation.Nullable;
import java.util.ArrayList;
import java.util.List;


public class MathOperator implements UniCode {
    public static final List<UniCode> symbols = new ArrayList<>();

    public final String desc;
    public final int codePoint;
    public final String chars;
    public final String generalCategory;
    public final int combiningClass;

    @Nullable
    public final String latex;

    @Nullable
    public final String ulatex;

    @Nullable
    public final String mathCategory;

    @Override
    public String desc() {
        return desc;
    }

    @Override
    public int codePoint() {
        return codePoint;
    }

    @Override
    public String chars() {
        return chars;
    }

    @Override
    public String generalCategory() {
        return generalCategory;
    }

    @Override
    public int combiningClass() {
        return combiningClass;
    }

    @Override @Nullable
    public String latex() {
        return latex;
    }

    @Override @Nullable
    public String ulatex() {
        return ulatex;
    }

    @Override @Nullable
    public String mathCategory() {
        return mathCategory;
    }

    MathOperator(int codePoint, String desc, String chars, String generalCategory, int combiningClass) {
        this(codePoint, desc, chars, generalCategory, combiningClass, null, null, null);
    }

    MathOperator(int codePoint, String desc, String chars, String generalCategory, int combiningClass, String latex, String ulatex, String mathCategory) {
        this.codePoint = codePoint;
        this.desc = desc;
        this.generalCategory = generalCategory;
        this.combiningClass = combiningClass;
        this.chars = chars;
        this.latex = latex;
        this.ulatex = ulatex;
        this.mathCategory = mathCategory;
    }

    @Override
    public String toString() {
        return "[(MathOperator)]{" +
            "codePoint=" + codePoint +
            ", desc='" + desc + '\'' +
            ", chars='" + chars + '\'' +
            ", generalCategory='" + generalCategory + '\'' +
            ", combiningClass=" + combiningClass +
            ", latex='" + latex + '\'' +
            ", ulatex='" + ulatex + '\'' +
        '}';
    }

    static {
        symbols.add(new MathOperator(0x2200, "for all", "∀", "Sm", 0, "\\forall", null, null));
        symbols.add(new MathOperator(0x2201, "complement", "∁", "Sm", 0, "\\complement", null, null));
        symbols.add(new MathOperator(0x2202, "partial differential", "∂", "Sm", 0, "\\partial", null, null));
        symbols.add(new MathOperator(0x2203, "there exists", "∃", "Sm", 0, "\\exists", null, null));
        symbols.add(new MathOperator(0x2204, "there does not exist", "∄", "Sm", 0, "\\nexists", null, null));
        symbols.add(new MathOperator(0x2205, "empty set", "∅", "Sm", 0, "\\varnothing", null, null));
        symbols.add(new MathOperator(0x2206, "increment", "∆", "Sm", 0, null, "\\increment", null));
        symbols.add(new MathOperator(0x2207, "nabla", "∇", "Sm", 0, "\\nabla", null, null));
        symbols.add(new MathOperator(0x2208, "element of", "∈", "Sm", 0, "\\in", null, null));
        symbols.add(new MathOperator(0x2209, "not an element of", "∉", "Sm", 0, "\\notin", null, null));
        symbols.add(new MathOperator(0x220A, "small element of", "∊", "Sm", 0, null, "\\smallin", null));
        symbols.add(new MathOperator(0x220B, "contains as member", "∋", "Sm", 0, "\\ni", null, null));
        symbols.add(new MathOperator(0x220C, "does not contain as member", "∌", "Sm", 0, "\\nni", null, null));
        symbols.add(new MathOperator(0x220D, "small contains as member", "∍", "Sm", 0, null, "\\smallni", null));
        symbols.add(new MathOperator(0x220E, "end of proof", "∎", "Sm", 0, null, "\\QED", null));
        symbols.add(new MathOperator(0x220F, "n-ary product", "∏", "Sm", 0, "\\prod", null, null));
        symbols.add(new MathOperator(0x2210, "n-ary coproduct", "∐", "Sm", 0, "\\coprod", null, null));
        symbols.add(new MathOperator(0x2211, "n-ary summation", "∑", "Sm", 0, "\\sum", null, null));
        symbols.add(new MathOperator(0x2212, "minus sign", "−", "Sm", 0, null, "\\minus", null));
        symbols.add(new MathOperator(0x2213, "minus-or-plus sign", "∓", "Sm", 0, "\\mp", null, null));
        symbols.add(new MathOperator(0x2214, "dot plus", "∔", "Sm", 0, "\\dotplus", null, null));
        symbols.add(new MathOperator(0x2215, "division slash", "∕", "Sm", 0, "\\slash", "\\divslash", null));
        symbols.add(new MathOperator(0x2216, "set minus", "∖", "Sm", 0, "\\smallsetminus", null, null));
        symbols.add(new MathOperator(0x2217, "asterisk operator", "∗", "Sm", 0, "\\ast", null, null));
        symbols.add(new MathOperator(0x2218, "ring operator", "∘", "Sm", 0, "\\circ", "\\vysmwhtcircle", null));
        symbols.add(new MathOperator(0x2219, "bullet operator", "∙", "Sm", 0, "\\bullet", "\\vysmblkcircle", null));
        symbols.add(new MathOperator(0x221A, "square root", "√", "Sm", 0, "\\sqrt", "\\surd", null));
        symbols.add(new MathOperator(0x221B, "cube root", "∛", "Sm", 0, "\\sqrt[3]", "\\cuberoot", null));
        symbols.add(new MathOperator(0x221C, "fourth root", "∜", "Sm", 0, "\\sqrt[4]", "\\fourthroot", null));
        symbols.add(new MathOperator(0x221D, "proportional to", "∝", "Sm", 0, "\\propto", null, null));
        symbols.add(new MathOperator(0x221E, "infinity", "∞", "Sm", 0, "\\infty", null, null));
        symbols.add(new MathOperator(0x221F, "right angle", "∟", "Sm", 0, "\\rightangle", null, null));
        symbols.add(new MathOperator(0x2220, "angle", "∠", "Sm", 0, "\\angle", null, null));
        symbols.add(new MathOperator(0x2221, "measured angle", "∡", "Sm", 0, "\\measuredangle", null, null));
        symbols.add(new MathOperator(0x2222, "spherical angle", "∢", "Sm", 0, "\\sphericalangle", null, null));
        symbols.add(new MathOperator(0x2223, "divides", "∣", "Sm", 0, "\\mid", null, null));
        symbols.add(new MathOperator(0x2224, "does not divide", "∤", "Sm", 0, "\\nmid", null, null));
        symbols.add(new MathOperator(0x2225, "parallel to", "∥", "Sm", 0, "\\parallel", null, null));
        symbols.add(new MathOperator(0x2226, "not parallel to", "∦", "Sm", 0, "\\nparallel", null, null));
        symbols.add(new MathOperator(0x2227, "logical and", "∧", "Sm", 0, "\\wedge", null, null));
        symbols.add(new MathOperator(0x2228, "logical or", "∨", "Sm", 0, "\\vee", null, null));
        symbols.add(new MathOperator(0x2229, "intersection", "∩", "Sm", 0, "\\cap", null, null));
        symbols.add(new MathOperator(0x222A, "union", "∪", "Sm", 0, "\\cup", null, null));
        symbols.add(new MathOperator(0x222B, "integral", "∫", "Sm", 0, "\\int", null, null));
        symbols.add(new MathOperator(0x222C, "double integral", "∬", "Sm", 0, "\\iint", null, null));
        symbols.add(new MathOperator(0x222D, "triple integral", "∭", "Sm", 0, "\\iiint", null, null));
        symbols.add(new MathOperator(0x222E, "contour integral", "∮", "Sm", 0, "\\oint", null, null));
        symbols.add(new MathOperator(0x222F, "surface integral", "∯", "Sm", 0, "\\oiint", null, null));
        symbols.add(new MathOperator(0x2230, "volume integral", "∰", "Sm", 0, "\\oiiint", null, null));
        symbols.add(new MathOperator(0x2231, "clockwise integral", "∱", "Sm", 0, null, "\\intclockwise", null));
        symbols.add(new MathOperator(0x2232, "clockwise contour integral", "∲", "Sm", 0, "\\varointclockwise", null, null));
        symbols.add(new MathOperator(0x2233, "anticlockwise contour integral", "∳", "Sm", 0, "\\ointctrclockwise", null, null));
        symbols.add(new MathOperator(0x2234, "therefore", "∴", "Sm", 0, "\\therefore", null, null));
        symbols.add(new MathOperator(0x2235, "because", "∵", "Sm", 0, "\\because", null, null));
        symbols.add(new MathOperator(0x2236, "ratio", "∶", "Sm", 0, null, "\\mathratio", null));
        symbols.add(new MathOperator(0x2237, "proportion", "∷", "Sm", 0, "\\Proportion", "\\Colon", null));
        symbols.add(new MathOperator(0x2238, "dot minus", "∸", "Sm", 0, null, "\\dotminus", null));
        symbols.add(new MathOperator(0x2239, "excess", "∹", "Sm", 0, "\\eqcolon", "\\dashcolon", null));
        symbols.add(new MathOperator(0x223A, "geometric proportion", "∺", "Sm", 0, null, "\\dotsminusdots", null));
        symbols.add(new MathOperator(0x223B, "homothetic", "∻", "Sm", 0, null, "\\kernelcontraction", null));
        symbols.add(new MathOperator(0x223C, "tilde operator", "∼", "Sm", 0, "\\sim", null, null));
        symbols.add(new MathOperator(0x223D, "reversed tilde", "∽", "Sm", 0, "\\backsim", null, null));
        symbols.add(new MathOperator(0x223E, "inverted lazy s", "∾", "Sm", 0, null, "\\invlazys", null));
        symbols.add(new MathOperator(0x223F, "sine wave", "∿", "Sm", 0, "\\AC", "\\sinewave", null));
        symbols.add(new MathOperator(0x2240, "wreath product", "≀", "Sm", 0, "\\wr", null, null));
        symbols.add(new MathOperator(0x2241, "not tilde", "≁", "Sm", 0, "\\nsim", null, null));
        symbols.add(new MathOperator(0x2242, "minus tilde", "≂", "Sm", 0, "\\eqsim", null, null));
        symbols.add(new MathOperator(0x2243, "asymptotically equal to", "≃", "Sm", 0, "\\simeq", "\\sime", null));
        symbols.add(new MathOperator(0x2244, "not asymptotically equal to", "≄", "Sm", 0, "\\nsimeq", null, null));
        symbols.add(new MathOperator(0x2245, "approximately equal to", "≅", "Sm", 0, "\\cong", null, null));
        symbols.add(new MathOperator(0x2246, "approximately but not actually equal to", "≆", "Sm", 0, null, "\\simneqq", null));
        symbols.add(new MathOperator(0x2247, "neither approximately nor actually equal to", "≇", "Sm", 0, "\\ncong", null, null));
        symbols.add(new MathOperator(0x2248, "almost equal to", "≈", "Sm", 0, "\\approx", null, null));
        symbols.add(new MathOperator(0x2249, "not almost equal to", "≉", "Sm", 0, "\\napprox", null, null));
        symbols.add(new MathOperator(0x224A, "almost equal or equal to", "≊", "Sm", 0, "\\approxeq", null, null));
        symbols.add(new MathOperator(0x224B, "triple tilde", "≋", "Sm", 0, null, "\\approxident", null));
        symbols.add(new MathOperator(0x224C, "all equal to", "≌", "Sm", 0, null, "\\backcong", null));
        symbols.add(new MathOperator(0x224D, "equivalent to", "≍", "Sm", 0, "\\asymp", null, null));
        symbols.add(new MathOperator(0x224E, "geometrically equivalent to", "≎", "Sm", 0, "\\Bumpeq", null, null));
        symbols.add(new MathOperator(0x224F, "difference between", "≏", "Sm", 0, "\\bumpeq", null, null));
        symbols.add(new MathOperator(0x2250, "approaches the limit", "≐", "Sm", 0, "\\doteq", null, null));
        symbols.add(new MathOperator(0x2251, "geometrically equal to", "≑", "Sm", 0, "\\Doteq", null, null));
        symbols.add(new MathOperator(0x2252, "approximately equal to or the image of", "≒", "Sm", 0, "\\fallingdotseq", null, null));
        symbols.add(new MathOperator(0x2253, "image of or approximately equal to", "≓", "Sm", 0, "\\risingdotseq", null, null));
        symbols.add(new MathOperator(0x2254, "colon equals", "≔", "Sm", 0, "\\coloneq", null, null));
        symbols.add(new MathOperator(0x2255, "equals colon", "≕", "Sm", 0, "\\eqcolon", null, null));
        symbols.add(new MathOperator(0x2256, "ring in equal to", "≖", "Sm", 0, "\\eqcirc", null, null));
        symbols.add(new MathOperator(0x2257, "ring equal to", "≗", "Sm", 0, "\\circeq", null, null));
        symbols.add(new MathOperator(0x2258, "corresponds to", "≘", "Sm", 0, null, "\\arceq", null));
        symbols.add(new MathOperator(0x2259, "estimates", "≙", "Sm", 0, "\\corresponds", "\\wedgeq", null));
        symbols.add(new MathOperator(0x225A, "equiangular to", "≚", "Sm", 0, null, "\\veeeq", null));
        symbols.add(new MathOperator(0x225B, "star equals", "≛", "Sm", 0, null, "\\stareq", null));
        symbols.add(new MathOperator(0x225C, "delta equal to", "≜", "Sm", 0, "\\triangleq", null, null));
        symbols.add(new MathOperator(0x225D, "equal to by definition", "≝", "Sm", 0, null, "\\eqdef", null));
        symbols.add(new MathOperator(0x225E, "measured by", "≞", "Sm", 0, null, "\\measeq", null));
        symbols.add(new MathOperator(0x225F, "questioned equal to", "≟", "Sm", 0, null, "\\questeq", null));
        symbols.add(new MathOperator(0x2260, "not equal to", "≠", "Sm", 0, "\\neq", "\\ne", null));
        symbols.add(new MathOperator(0x2261, "identical to", "≡", "Sm", 0, "\\equiv", null, null));
        symbols.add(new MathOperator(0x2262, "not identical to", "≢", "Sm", 0, "\\nequiv", null, null));
        symbols.add(new MathOperator(0x2263, "strictly equivalent to", "≣", "Sm", 0, null, "\\Equiv", null));
        symbols.add(new MathOperator(0x2264, "less-than or equal to", "≤", "Sm", 0, "\\leq", null, null));
        symbols.add(new MathOperator(0x2265, "greater-than or equal to", "≥", "Sm", 0, "\\geq", null, null));
        symbols.add(new MathOperator(0x2266, "less-than over equal to", "≦", "Sm", 0, "\\leqq", null, null));
        symbols.add(new MathOperator(0x2267, "greater-than over equal to", "≧", "Sm", 0, "\\geqq", null, null));
        symbols.add(new MathOperator(0x2268, "less-than but not equal to", "≨", "Sm", 0, "\\lneqq", null, null));
        symbols.add(new MathOperator(0x2269, "greater-than but not equal to", "≩", "Sm", 0, "\\gneqq", null, null));
        symbols.add(new MathOperator(0x226A, "much less-than", "≪", "Sm", 0, "\\ll", null, null));
        symbols.add(new MathOperator(0x226B, "much greater-than", "≫", "Sm", 0, "\\gg", null, null));
        symbols.add(new MathOperator(0x226C, "between", "≬", "Sm", 0, "\\between", null, null));
        symbols.add(new MathOperator(0x226D, "not equivalent to", "≭", "Sm", 0, "\\notasymp", "\\nasymp", null));
        symbols.add(new MathOperator(0x226E, "not less-than", "≮", "Sm", 0, "\\nless", null, null));
        symbols.add(new MathOperator(0x226F, "not greater-than", "≯", "Sm", 0, "\\ngtr", null, null));
        symbols.add(new MathOperator(0x2270, "neither less-than nor equal to", "≰", "Sm", 0, "\\nleq", null, null));
        symbols.add(new MathOperator(0x2271, "neither greater-than nor equal to", "≱", "Sm", 0, "\\ngeq", null, null));
        symbols.add(new MathOperator(0x2272, "less-than or equivalent to", "≲", "Sm", 0, "\\lesssim", null, null));
        symbols.add(new MathOperator(0x2273, "greater-than or equivalent to", "≳", "Sm", 0, "\\gtrsim", null, null));
        symbols.add(new MathOperator(0x2274, "neither less-than nor equivalent to", "≴", "Sm", 0, "\\NotLessTilde", "\\nlesssim", null));
        symbols.add(new MathOperator(0x2275, "neither greater-than nor equivalent to", "≵", "Sm", 0, "\\NotGreaterTilde", "\\ngtrsim", null));
        symbols.add(new MathOperator(0x2276, "less-than or greater-than", "≶", "Sm", 0, "\\lessgtr", null, null));
        symbols.add(new MathOperator(0x2277, "greater-than or less-than", "≷", "Sm", 0, "\\gtrless", null, null));
        symbols.add(new MathOperator(0x2278, "neither less-than nor greater-than", "≸", "Sm", 0, null, "\\nlessgtr", null));
        symbols.add(new MathOperator(0x2279, "neither greater-than nor less-than", "≹", "Sm", 0, "\\NotGreaterLess", "\\ngtrless", null));
        symbols.add(new MathOperator(0x227A, "precedes", "≺", "Sm", 0, "\\prec", null, null));
        symbols.add(new MathOperator(0x227B, "succeeds", "≻", "Sm", 0, "\\succ", null, null));
        symbols.add(new MathOperator(0x227C, "precedes or equal to", "≼", "Sm", 0, "\\preccurlyeq", null, null));
        symbols.add(new MathOperator(0x227D, "succeeds or equal to", "≽", "Sm", 0, "\\succcurlyeq", null, null));
        symbols.add(new MathOperator(0x227E, "precedes or equivalent to", "≾", "Sm", 0, "\\precsim", null, null));
        symbols.add(new MathOperator(0x227F, "succeeds or equivalent to", "≿", "Sm", 0, "\\succsim", null, null));
        symbols.add(new MathOperator(0x2280, "does not precede", "⊀", "Sm", 0, "\\nprec", null, null));
        symbols.add(new MathOperator(0x2281, "does not succeed", "⊁", "Sm", 0, "\\nsucc", null, null));
        symbols.add(new MathOperator(0x2282, "subset of", "⊂", "Sm", 0, "\\subset", null, null));
        symbols.add(new MathOperator(0x2283, "superset of", "⊃", "Sm", 0, "\\supset", null, null));
        symbols.add(new MathOperator(0x2284, "not a subset of", "⊄", "Sm", 0, "\\nsubset", null, null));
        symbols.add(new MathOperator(0x2285, "not a superset of", "⊅", "Sm", 0, "\\nsupset", null, null));
        symbols.add(new MathOperator(0x2286, "subset of or equal to", "⊆", "Sm", 0, "\\subseteq", null, null));
        symbols.add(new MathOperator(0x2287, "superset of or equal to", "⊇", "Sm", 0, "\\supseteq", null, null));
        symbols.add(new MathOperator(0x2288, "neither a subset of nor equal to", "⊈", "Sm", 0, "\\nsubseteq", null, null));
        symbols.add(new MathOperator(0x2289, "neither a superset of nor equal to", "⊉", "Sm", 0, "\\nsupseteq", null, null));
        symbols.add(new MathOperator(0x228A, "subset of with not equal to", "⊊", "Sm", 0, "\\subsetneq", null, null));
        symbols.add(new MathOperator(0x228B, "superset of with not equal to", "⊋", "Sm", 0, "\\supsetneq", null, null));
        symbols.add(new MathOperator(0x228C, "multiset", "⊌", "Sm", 0, null, "\\cupleftarrow", null));
        symbols.add(new MathOperator(0x228D, "multiset multiplication", "⊍", "Sm", 0, null, "\\cupdot", null));
        symbols.add(new MathOperator(0x228E, "multiset union", "⊎", "Sm", 0, "\\uplus", null, null));
        symbols.add(new MathOperator(0x228F, "square image of", "⊏", "Sm", 0, "\\sqsubset", null, null));
        symbols.add(new MathOperator(0x2290, "square original of", "⊐", "Sm", 0, "\\sqsupset", null, null));
        symbols.add(new MathOperator(0x2291, "square image of or equal to", "⊑", "Sm", 0, "\\sqsubseteq", null, null));
        symbols.add(new MathOperator(0x2292, "square original of or equal to", "⊒", "Sm", 0, "\\sqsupseteq", null, null));
        symbols.add(new MathOperator(0x2293, "square cap", "⊓", "Sm", 0, "\\sqcap", null, null));
        symbols.add(new MathOperator(0x2294, "square cup", "⊔", "Sm", 0, "\\sqcup", null, null));
        symbols.add(new MathOperator(0x2295, "circled plus", "⊕", "Sm", 0, "\\oplus", null, null));
        symbols.add(new MathOperator(0x2296, "circled minus", "⊖", "Sm", 0, "\\ominus", null, null));
        symbols.add(new MathOperator(0x2297, "circled times", "⊗", "Sm", 0, "\\otimes", null, null));
        symbols.add(new MathOperator(0x2298, "circled division slash", "⊘", "Sm", 0, "\\oslash", null, null));
        symbols.add(new MathOperator(0x2299, "circled dot operator", "⊙", "Sm", 0, "\\odot", null, null));
        symbols.add(new MathOperator(0x229A, "circled ring operator", "⊚", "Sm", 0, "\\circledcirc", null, null));
        symbols.add(new MathOperator(0x229B, "circled asterisk operator", "⊛", "Sm", 0, "\\circledast", null, null));
        symbols.add(new MathOperator(0x229C, "circled equals", "⊜", "Sm", 0, null, "\\circledequal", null));
        symbols.add(new MathOperator(0x229D, "circled dash", "⊝", "Sm", 0, "\\circleddash", null, null));
        symbols.add(new MathOperator(0x229E, "squared plus", "⊞", "Sm", 0, "\\boxplus", null, null));
        symbols.add(new MathOperator(0x229F, "squared minus", "⊟", "Sm", 0, "\\boxminus", null, null));
        symbols.add(new MathOperator(0x22A0, "squared times", "⊠", "Sm", 0, "\\boxtimes", null, null));
        symbols.add(new MathOperator(0x22A1, "squared dot operator", "⊡", "Sm", 0, "\\boxdot", null, null));
        symbols.add(new MathOperator(0x22A2, "right tack", "⊢", "Sm", 0, "\\vdash", null, null));
        symbols.add(new MathOperator(0x22A3, "left tack", "⊣", "Sm", 0, "\\dashv", null, null));
        symbols.add(new MathOperator(0x22A4, "down tack", "⊤", "Sm", 0, "\\top", null, null));
        symbols.add(new MathOperator(0x22A5, "up tack", "⊥", "Sm", 0, "\\bot", null, null));
        symbols.add(new MathOperator(0x22A6, "assertion", "⊦", "Sm", 0, null, "\\assert", null));
        symbols.add(new MathOperator(0x22A7, "models", "⊧", "Sm", 0, "\\models", null, null));
        symbols.add(new MathOperator(0x22A8, "true", "⊨", "Sm", 0, "\\vDash", null, null));
        symbols.add(new MathOperator(0x22A9, "forces", "⊩", "Sm", 0, "\\Vdash", null, null));
        symbols.add(new MathOperator(0x22AA, "triple vertical bar right turnstile", "⊪", "Sm", 0, "\\Vvdash", null, null));
        symbols.add(new MathOperator(0x22AB, "double vertical bar double right turnstile", "⊫", "Sm", 0, "\\VDash", null, null));
        symbols.add(new MathOperator(0x22AC, "does not prove", "⊬", "Sm", 0, "\\nvdash", null, null));
        symbols.add(new MathOperator(0x22AD, "not true", "⊭", "Sm", 0, "\\nvDash", null, null));
        symbols.add(new MathOperator(0x22AE, "does not force", "⊮", "Sm", 0, "\\nVdash", null, null));
        symbols.add(new MathOperator(0x22AF, "negated double vertical bar double right turnstile", "⊯", "Sm", 0, "\\nVDash", null, null));
        symbols.add(new MathOperator(0x22B0, "precedes under relation", "⊰", "Sm", 0, null, "\\prurel", null));
        symbols.add(new MathOperator(0x22B1, "succeeds under relation", "⊱", "Sm", 0, null, "\\scurel", null));
        symbols.add(new MathOperator(0x22B2, "normal subgroup of", "⊲", "Sm", 0, "\\vartriangleleft", null, null));
        symbols.add(new MathOperator(0x22B3, "contains as normal subgroup", "⊳", "Sm", 0, "\\vartriangleright", null, null));
        symbols.add(new MathOperator(0x22B4, "normal subgroup of or equal to", "⊴", "Sm", 0, "\\trianglelefteq", null, null));
        symbols.add(new MathOperator(0x22B5, "contains as normal subgroup or equal to", "⊵", "Sm", 0, "\\trianglerighteq", null, null));
        symbols.add(new MathOperator(0x22B6, "original of", "⊶", "Sm", 0, "\\multimapdotbothA", "\\origof", null));
        symbols.add(new MathOperator(0x22B7, "image of", "⊷", "Sm", 0, "\\multimapdotbothB", "\\imageof", null));
        symbols.add(new MathOperator(0x22B8, "multimap", "⊸", "Sm", 0, "\\multimap", null, null));
        symbols.add(new MathOperator(0x22B9, "hermitian conjugate matrix", "⊹", "Sm", 0, null, "\\hermitmatrix", null));
        symbols.add(new MathOperator(0x22BA, "intercalate", "⊺", "Sm", 0, "\\intercal", null, null));
        symbols.add(new MathOperator(0x22BB, "xor", "⊻", "Sm", 0, "\\veebar", null, null));
        symbols.add(new MathOperator(0x22BC, "nand", "⊼", "Sm", 0, "\\barwedge", null, null));
        symbols.add(new MathOperator(0x22BD, "nor", "⊽", "Sm", 0, null, "\\barvee", null));
        symbols.add(new MathOperator(0x22BE, "right angle with arc", "⊾", "Sm", 0, null, "\\measuredrightangle", null));
        symbols.add(new MathOperator(0x22BF, "right triangle", "⊿", "Sm", 0, null, "\\varlrtriangle", null));
        symbols.add(new MathOperator(0x22C0, "n-ary logical and", "⋀", "Sm", 0, "\\bigwedge", null, null));
        symbols.add(new MathOperator(0x22C1, "n-ary logical or", "⋁", "Sm", 0, "\\bigvee", null, null));
        symbols.add(new MathOperator(0x22C2, "n-ary intersection", "⋂", "Sm", 0, "\\bigcap", null, null));
        symbols.add(new MathOperator(0x22C3, "n-ary union", "⋃", "Sm", 0, "\\bigcup", null, null));
        symbols.add(new MathOperator(0x22C4, "diamond operator", "⋄", "Sm", 0, "\\diamond", "\\smwhtdiamond", null));
        symbols.add(new MathOperator(0x22C5, "dot operator", "⋅", "Sm", 0, "\\cdot", null, null));
        symbols.add(new MathOperator(0x22C6, "star operator", "⋆", "Sm", 0, "\\star", null, null));
        symbols.add(new MathOperator(0x22C7, "division times", "⋇", "Sm", 0, "\\divideontimes", null, null));
        symbols.add(new MathOperator(0x22C8, "bowtie", "⋈", "Sm", 0, "\\bowtie", null, null));
        symbols.add(new MathOperator(0x22C9, "left normal factor semidirect product", "⋉", "Sm", 0, "\\ltimes", null, null));
        symbols.add(new MathOperator(0x22CA, "right normal factor semidirect product", "⋊", "Sm", 0, "\\rtimes", null, null));
        symbols.add(new MathOperator(0x22CB, "left semidirect product", "⋋", "Sm", 0, "\\leftthreetimes", null, null));
        symbols.add(new MathOperator(0x22CC, "right semidirect product", "⋌", "Sm", 0, "\\rightthreetimes", null, null));
        symbols.add(new MathOperator(0x22CD, "reversed tilde equals", "⋍", "Sm", 0, "\\backsimeq", null, null));
        symbols.add(new MathOperator(0x22CE, "curly logical or", "⋎", "Sm", 0, "\\curlyvee", null, null));
        symbols.add(new MathOperator(0x22CF, "curly logical and", "⋏", "Sm", 0, "\\curlywedge", null, null));
        symbols.add(new MathOperator(0x22D0, "double subset", "⋐", "Sm", 0, "\\Subset", null, null));
        symbols.add(new MathOperator(0x22D1, "double superset", "⋑", "Sm", 0, "\\Supset", null, null));
        symbols.add(new MathOperator(0x22D2, "double intersection", "⋒", "Sm", 0, "\\Cap", null, null));
        symbols.add(new MathOperator(0x22D3, "double union", "⋓", "Sm", 0, "\\Cup", null, null));
        symbols.add(new MathOperator(0x22D4, "pitchfork", "⋔", "Sm", 0, "\\pitchfork", null, null));
        symbols.add(new MathOperator(0x22D5, "equal and parallel to", "⋕", "Sm", 0, "\\hash", "\\equalparallel", null));
        symbols.add(new MathOperator(0x22D6, "less-than with dot", "⋖", "Sm", 0, "\\lessdot", null, null));
        symbols.add(new MathOperator(0x22D7, "greater-than with dot", "⋗", "Sm", 0, "\\gtrdot", null, null));
        symbols.add(new MathOperator(0x22D8, "very much less-than", "⋘", "Sm", 0, "\\lll", null, null));
        symbols.add(new MathOperator(0x22D9, "very much greater-than", "⋙", "Sm", 0, "\\ggg", null, null));
        symbols.add(new MathOperator(0x22DA, "less-than equal to or greater-than", "⋚", "Sm", 0, "\\lesseqgtr", null, null));
        symbols.add(new MathOperator(0x22DB, "greater-than equal to or less-than", "⋛", "Sm", 0, "\\gtreqless", null, null));
        symbols.add(new MathOperator(0x22DC, "equal to or less-than", "⋜", "Sm", 0, null, "\\eqless", null));
        symbols.add(new MathOperator(0x22DD, "equal to or greater-than", "⋝", "Sm", 0, null, "\\eqgtr", null));
        symbols.add(new MathOperator(0x22DE, "equal to or precedes", "⋞", "Sm", 0, "\\curlyeqprec", null, null));
        symbols.add(new MathOperator(0x22DF, "equal to or succeeds", "⋟", "Sm", 0, "\\curlyeqsucc", null, null));
        symbols.add(new MathOperator(0x22E0, "does not precede or equal", "⋠", "Sm", 0, "\\npreceq", "\\npreccurlyeq", null));
        symbols.add(new MathOperator(0x22E1, "does not succeed or equal", "⋡", "Sm", 0, "\\nsucceq", "\\nsucccurlyeq", null));
        symbols.add(new MathOperator(0x22E2, "not square image of or equal to", "⋢", "Sm", 0, "\\nsqsubseteq", null, null));
        symbols.add(new MathOperator(0x22E3, "not square original of or equal to", "⋣", "Sm", 0, "\\nsqsupseteq", null, null));
        symbols.add(new MathOperator(0x22E4, "square image of or not equal to", "⋤", "Sm", 0, null, "\\sqsubsetneq", null));
        symbols.add(new MathOperator(0x22E5, "square original of or not equal to", "⋥", "Sm", 0, null, "\\sqsupsetneq", null));
        symbols.add(new MathOperator(0x22E6, "less-than but not equivalent to", "⋦", "Sm", 0, "\\lnsim", null, null));
        symbols.add(new MathOperator(0x22E7, "greater-than but not equivalent to", "⋧", "Sm", 0, "\\gnsim", null, null));
        symbols.add(new MathOperator(0x22E8, "precedes but not equivalent to", "⋨", "Sm", 0, "\\precnsim", null, null));
        symbols.add(new MathOperator(0x22E9, "succeeds but not equivalent to", "⋩", "Sm", 0, "\\succnsim", null, null));
        symbols.add(new MathOperator(0x22EA, "not normal subgroup of", "⋪", "Sm", 0, "\\ntriangleleft", "\\nvartriangleleft", null));
        symbols.add(new MathOperator(0x22EB, "does not contain as normal subgroup", "⋫", "Sm", 0, "\\ntriangleright", "\\nvartriangleright", null));
        symbols.add(new MathOperator(0x22EC, "not normal subgroup of or equal to", "⋬", "Sm", 0, "\\ntrianglelefteq", null, null));
        symbols.add(new MathOperator(0x22ED, "does not contain as normal subgroup or equal", "⋭", "Sm", 0, "\\ntrianglerighteq", null, null));
        symbols.add(new MathOperator(0x22EE, "vertical ellipsis", "⋮", "Sm", 0, "\\vdots", null, null));
        symbols.add(new MathOperator(0x22EF, "midline horizontal ellipsis", "⋯", "Sm", 0, "\\cdots", "\\unicodecdots", null));
        symbols.add(new MathOperator(0x22F0, "up right diagonal ellipsis", "⋰", "Sm", 0, "\\iddots", "\\adots", null));
        symbols.add(new MathOperator(0x22F1, "down right diagonal ellipsis", "⋱", "Sm", 0, "\\ddots", null, null));
        symbols.add(new MathOperator(0x22F2, "element of with long horizontal stroke", "⋲", "Sm", 0, null, "\\disin", null));
        symbols.add(new MathOperator(0x22F3, "element of with vertical bar at end of horizontal stroke", "⋳", "Sm", 0, null, "\\varisins", null));
        symbols.add(new MathOperator(0x22F4, "small element of with vertical bar at end of horizontal stroke", "⋴", "Sm", 0, null, "\\isins", null));
        symbols.add(new MathOperator(0x22F5, "element of with dot above", "⋵", "Sm", 0, null, "\\isindot", null));
        symbols.add(new MathOperator(0x22F6, "element of with overbar", "⋶", "Sm", 0, "\\barin", "\\varisinobar", null));
        symbols.add(new MathOperator(0x22F7, "small element of with overbar", "⋷", "Sm", 0, null, "\\isinobar", null));
        symbols.add(new MathOperator(0x22F8, "element of with underbar", "⋸", "Sm", 0, null, "\\isinvb", null));
        symbols.add(new MathOperator(0x22F9, "element of with two horizontal strokes", "⋹", "Sm", 0, null, "\\isinE", null));
        symbols.add(new MathOperator(0x22FA, "contains with long horizontal stroke", "⋺", "Sm", 0, null, "\\nisd", null));
        symbols.add(new MathOperator(0x22FB, "contains with vertical bar at end of horizontal stroke", "⋻", "Sm", 0, null, "\\varnis", null));
        symbols.add(new MathOperator(0x22FC, "small contains with vertical bar at end of horizontal stroke", "⋼", "Sm", 0, null, "\\nis", null));
        symbols.add(new MathOperator(0x22FD, "contains with overbar", "⋽", "Sm", 0, null, "\\varniobar", null));
        symbols.add(new MathOperator(0x22FE, "small contains with overbar", "⋾", "Sm", 0, null, "\\niobar", null));
        symbols.add(new MathOperator(0x22FF, "z notation bag membership", "⋿", "Sm", 0, null, "\\bagmember", null));
        symbols.add(new MathOperator(0x27C0, "three dimensional angle", "⟀", "Sm", 0, null, "\\threedangle", null));
        symbols.add(new MathOperator(0x27C1, "white triangle containing small white triangle", "⟁", "Sm", 0, null, "\\whiteinwhitetriangle", null));
        symbols.add(new MathOperator(0x27C2, "perpendicular", "⟂", "Sm", 0, "\\perp", null, null));
        symbols.add(new MathOperator(0x27C3, "open subset", "⟃", "Sm", 0, null, "\\subsetcirc", null));
        symbols.add(new MathOperator(0x27C4, "open superset", "⟄", "Sm", 0, null, "\\supsetcirc", null));
        symbols.add(new MathOperator(0x27C5, "left s-shaped bag delimiter", "⟅", "Ps", 0, "\\Lbag", "\\lbag", null));
        symbols.add(new MathOperator(0x27C6, "right s-shaped bag delimiter", "⟆", "Pe", 0, "\\Rbag", "\\rbag", null));
        symbols.add(new MathOperator(0x27C7, "or with dot inside", "⟇", "Sm", 0, null, "\\veedot", null));
        symbols.add(new MathOperator(0x27C8, "reverse solidus preceding subset", "⟈", "Sm", 0, null, "\\bsolhsub", null));
        symbols.add(new MathOperator(0x27C9, "superset preceding solidus", "⟉", "Sm", 0, null, "\\suphsol", null));
        symbols.add(new MathOperator(0x27CA, "vertical bar with horizontal stroke", "⟊", "Sm", 0));
        symbols.add(new MathOperator(0x27CB, "mathematical rising diagonal", "⟋", "Sm", 0));
        symbols.add(new MathOperator(0x27CC, "long division", "⟌", "Sm", 0, null, "\\longdivision", null));
        symbols.add(new MathOperator(0x27CD, "mathematical falling diagonal", "⟍", "Sm", 0));
        symbols.add(new MathOperator(0x27CE, "squared logical and", "⟎", "Sm", 0));
        symbols.add(new MathOperator(0x27CF, "squared logical or", "⟏", "Sm", 0));
        symbols.add(new MathOperator(0x27D0, "white diamond with centred dot", "⟐", "Sm", 0, "\\Diamonddot", "\\diamondcdot", null));
        symbols.add(new MathOperator(0x27D1, "and with dot", "⟑", "Sm", 0, null, "\\wedgedot", null));
        symbols.add(new MathOperator(0x27D2, "element of opening upwards", "⟒", "Sm", 0, null, "\\upin", null));
        symbols.add(new MathOperator(0x27D3, "lower right corner with dot", "⟓", "Sm", 0, null, "\\pullback", null));
        symbols.add(new MathOperator(0x27D4, "upper left corner with dot", "⟔", "Sm", 0, null, "\\pushout", null));
        symbols.add(new MathOperator(0x27D5, "left outer join", "⟕", "Sm", 0, null, "\\leftouterjoin", null));
        symbols.add(new MathOperator(0x27D6, "right outer join", "⟖", "Sm", 0, null, "\\rightouterjoin", null));
        symbols.add(new MathOperator(0x27D7, "full outer join", "⟗", "Sm", 0, null, "\\fullouterjoin", null));
        symbols.add(new MathOperator(0x27D8, "large up tack", "⟘", "Sm", 0, null, "\\bigbot", null));
        symbols.add(new MathOperator(0x27D9, "large down tack", "⟙", "Sm", 0, null, "\\bigtop", null));
        symbols.add(new MathOperator(0x27DA, "left and right double turnstile", "⟚", "Sm", 0, null, "\\DashVDash", null));
        symbols.add(new MathOperator(0x27DB, "left and right tack", "⟛", "Sm", 0, null, "\\dashVdash", null));
        symbols.add(new MathOperator(0x27DC, "left multimap", "⟜", "Sm", 0, "\\multimapinv", null, null));
        symbols.add(new MathOperator(0x27DD, "long right tack", "⟝", "Sm", 0, null, "\\vlongdash", null));
        symbols.add(new MathOperator(0x27DE, "long left tack", "⟞", "Sm", 0, null, "\\longdashv", null));
        symbols.add(new MathOperator(0x27DF, "up tack with circle above", "⟟", "Sm", 0, null, "\\cirbot", null));
        symbols.add(new MathOperator(0x27E0, "lozenge divided by horizontal rule", "⟠", "Sm", 0, null, "\\lozengeminus", null));
        symbols.add(new MathOperator(0x27E1, "white concave-sided diamond", "⟡", "Sm", 0, null, "\\concavediamond", null));
        symbols.add(new MathOperator(0x27E2, "white concave-sided diamond with leftwards tick", "⟢", "Sm", 0, null, "\\concavediamondtickleft", null));
        symbols.add(new MathOperator(0x27E3, "white concave-sided diamond with rightwards tick", "⟣", "Sm", 0, null, "\\concavediamondtickright", null));
        symbols.add(new MathOperator(0x27E4, "white square with leftwards tick", "⟤", "Sm", 0, null, "\\whitesquaretickleft", null));
        symbols.add(new MathOperator(0x27E5, "white square with rightwards tick", "⟥", "Sm", 0, null, "\\whitesquaretickright", null));
        symbols.add(new MathOperator(0x27E6, "mathematical left white square bracket", "⟦", "Ps", 0, "\\llbracket", "\\lBrack", null));
        symbols.add(new MathOperator(0x27E7, "mathematical right white square bracket", "⟧", "Pe", 0, "\\rrbracket", "\\rBrack", null));
        symbols.add(new MathOperator(0x27E8, "mathematical left angle bracket", "⟨", "Ps", 0, "\\langle", null, null));
        symbols.add(new MathOperator(0x27E9, "mathematical right angle bracket", "⟩", "Pe", 0, "\\rangle", null, null));
        symbols.add(new MathOperator(0x27EA, "mathematical left double angle bracket", "⟪", "Ps", 0, "\\lang", "\\lAngle", null));
        symbols.add(new MathOperator(0x27EB, "mathematical right double angle bracket", "⟫", "Pe", 0, "\\rang", "\\rAngle", null));
        symbols.add(new MathOperator(0x27EC, "mathematical left white tortoise shell bracket", "⟬", "Ps", 0, null, "\\Lbrbrak", null));
        symbols.add(new MathOperator(0x27ED, "mathematical right white tortoise shell bracket", "⟭", "Pe", 0, null, "\\Rbrbrak", null));
        symbols.add(new MathOperator(0x27EE, "mathematical left flattened parenthesis", "⟮", "Ps", 0, "\\lgroup", null, null));
        symbols.add(new MathOperator(0x27EF, "mathematical right flattened parenthesis", "⟯", "Pe", 0, "\\rgroup", null, null));
        symbols.add(new MathOperator(0x2980, "triple vertical bar delimiter", "⦀", "Sm", 0, "\\VERT", "\\Vvert", null));
        symbols.add(new MathOperator(0x2981, "z notation spot", "⦁", "Sm", 0, "\\spot", "\\mdsmblkcircle", null));
        symbols.add(new MathOperator(0x2982, "z notation type colon", "⦂", "Sm", 0, null, "\\typecolon", null));
        symbols.add(new MathOperator(0x2983, "left white curly bracket", "⦃", "Ps", 0, null, "\\lBrace", null));
        symbols.add(new MathOperator(0x2984, "right white curly bracket", "⦄", "Pe", 0, null, "\\rBrace", null));
        symbols.add(new MathOperator(0x2985, "left white parenthesis", "⦅", "Ps", 0, "\\Lparen", "\\lParen", null));
        symbols.add(new MathOperator(0x2986, "right white parenthesis", "⦆", "Pe", 0, "\\Rparen", "\\rParen", null));
        symbols.add(new MathOperator(0x2987, "z notation left image bracket", "⦇", "Ps", 0, "\\limg", "\\llparenthesis", null));
        symbols.add(new MathOperator(0x2988, "z notation right image bracket", "⦈", "Pe", 0, "\\rimg", "\\rrparenthesis", null));
        symbols.add(new MathOperator(0x2989, "z notation left binding bracket", "⦉", "Ps", 0, "\\lblot", "\\llangle", null));
        symbols.add(new MathOperator(0x298A, "z notation right binding bracket", "⦊", "Pe", 0, "\\rblot", "\\rrangle", null));
        symbols.add(new MathOperator(0x298B, "left square bracket with underbar", "⦋", "Ps", 0, null, "\\lbrackubar", null));
        symbols.add(new MathOperator(0x298C, "right square bracket with underbar", "⦌", "Pe", 0, null, "\\rbrackubar", null));
        symbols.add(new MathOperator(0x298D, "left square bracket with tick in top corner", "⦍", "Ps", 0, null, "\\lbrackultick", null));
        symbols.add(new MathOperator(0x298E, "right square bracket with tick in bottom corner", "⦎", "Pe", 0, null, "\\rbracklrtick", null));
        symbols.add(new MathOperator(0x298F, "left square bracket with tick in bottom corner", "⦏", "Ps", 0, null, "\\lbracklltick", null));
        symbols.add(new MathOperator(0x2990, "right square bracket with tick in top corner", "⦐", "Pe", 0, null, "\\rbrackurtick", null));
        symbols.add(new MathOperator(0x2991, "left angle bracket with dot", "⦑", "Ps", 0, null, "\\langledot", null));
        symbols.add(new MathOperator(0x2992, "right angle bracket with dot", "⦒", "Pe", 0, null, "\\rangledot", null));
        symbols.add(new MathOperator(0x2993, "left arc less-than bracket", "⦓", "Ps", 0, null, "\\lparenless", null));
        symbols.add(new MathOperator(0x2994, "right arc greater-than bracket", "⦔", "Pe", 0, null, "\\rparengtr", null));
        symbols.add(new MathOperator(0x2995, "double left arc greater-than bracket", "⦕", "Ps", 0, null, "\\Lparengtr", null));
        symbols.add(new MathOperator(0x2996, "double right arc less-than bracket", "⦖", "Pe", 0, null, "\\Rparenless", null));
        symbols.add(new MathOperator(0x2997, "left black tortoise shell bracket", "⦗", "Ps", 0, null, "\\lblkbrbrak", null));
        symbols.add(new MathOperator(0x2998, "right black tortoise shell bracket", "⦘", "Pe", 0, null, "\\rblkbrbrak", null));
        symbols.add(new MathOperator(0x2999, "dotted fence", "⦙", "Sm", 0, null, "\\fourvdots", null));
        symbols.add(new MathOperator(0x299A, "vertical zigzag line", "⦚", "Sm", 0, null, "\\vzigzag", null));
        symbols.add(new MathOperator(0x299B, "measured angle opening left", "⦛", "Sm", 0, null, "\\measuredangleleft", null));
        symbols.add(new MathOperator(0x299C, "right angle variant with square", "⦜", "Sm", 0, null, "\\rightanglesqr", null));
        symbols.add(new MathOperator(0x299D, "measured right angle with dot", "⦝", "Sm", 0, null, "\\rightanglemdot", null));
        symbols.add(new MathOperator(0x299E, "angle with s inside", "⦞", "Sm", 0, null, "\\angles", null));
        symbols.add(new MathOperator(0x299F, "acute angle", "⦟", "Sm", 0, null, "\\angdnr", null));
        symbols.add(new MathOperator(0x29A0, "spherical angle opening left", "⦠", "Sm", 0, null, "\\gtlpar", null));
        symbols.add(new MathOperator(0x29A1, "spherical angle opening up", "⦡", "Sm", 0, null, "\\sphericalangleup", null));
        symbols.add(new MathOperator(0x29A2, "turned angle", "⦢", "Sm", 0, null, "\\turnangle", null));
        symbols.add(new MathOperator(0x29A3, "reversed angle", "⦣", "Sm", 0, null, "\\revangle", null));
        symbols.add(new MathOperator(0x29A4, "angle with underbar", "⦤", "Sm", 0, null, "\\angleubar", null));
        symbols.add(new MathOperator(0x29A5, "reversed angle with underbar", "⦥", "Sm", 0, null, "\\revangleubar", null));
        symbols.add(new MathOperator(0x29A6, "oblique angle opening up", "⦦", "Sm", 0, null, "\\wideangledown", null));
        symbols.add(new MathOperator(0x29A7, "oblique angle opening down", "⦧", "Sm", 0, null, "\\wideangleup", null));
        symbols.add(new MathOperator(0x29A8, "measured angle with open arm ending in arrow pointing up and right", "⦨", "Sm", 0, null, "\\measanglerutone", null));
        symbols.add(new MathOperator(0x29A9, "measured angle with open arm ending in arrow pointing up and left", "⦩", "Sm", 0, null, "\\measanglelutonw", null));
        symbols.add(new MathOperator(0x29AA, "measured angle with open arm ending in arrow pointing down and right", "⦪", "Sm", 0, null, "\\measanglerdtose", null));
        symbols.add(new MathOperator(0x29AB, "measured angle with open arm ending in arrow pointing down and left", "⦫", "Sm", 0, null, "\\measangleldtosw", null));
        symbols.add(new MathOperator(0x29AC, "measured angle with open arm ending in arrow pointing right and up", "⦬", "Sm", 0, null, "\\measangleurtone", null));
        symbols.add(new MathOperator(0x29AD, "measured angle with open arm ending in arrow pointing left and up", "⦭", "Sm", 0, null, "\\measangleultonw", null));
        symbols.add(new MathOperator(0x29AE, "measured angle with open arm ending in arrow pointing right and down", "⦮", "Sm", 0, null, "\\measangledrtose", null));
        symbols.add(new MathOperator(0x29AF, "measured angle with open arm ending in arrow pointing left and down", "⦯", "Sm", 0, null, "\\measangledltosw", null));
        symbols.add(new MathOperator(0x29B0, "reversed empty set", "⦰", "Sm", 0, null, "\\revemptyset", null));
        symbols.add(new MathOperator(0x29B1, "empty set with overbar", "⦱", "Sm", 0, null, "\\emptysetobar", null));
        symbols.add(new MathOperator(0x29B2, "empty set with small circle above", "⦲", "Sm", 0, null, "\\emptysetocirc", null));
        symbols.add(new MathOperator(0x29B3, "empty set with right arrow above", "⦳", "Sm", 0, null, "\\emptysetoarr", null));
        symbols.add(new MathOperator(0x29B4, "empty set with left arrow above", "⦴", "Sm", 0, null, "\\emptysetoarrl", null));
        symbols.add(new MathOperator(0x29B5, "circle with horizontal bar", "⦵", "Sm", 0, null, "\\circlehbar", null));
        symbols.add(new MathOperator(0x29B6, "circled vertical bar", "⦶", "Sm", 0, null, "\\circledvert", null));
        symbols.add(new MathOperator(0x29B7, "circled parallel", "⦷", "Sm", 0, null, "\\circledparallel", null));
        symbols.add(new MathOperator(0x29B8, "circled reverse solidus", "⦸", "Sm", 0, "\\circledbslash", "\\obslash", null));
        symbols.add(new MathOperator(0x29B9, "circled perpendicular", "⦹", "Sm", 0, null, "\\operp", null));
        symbols.add(new MathOperator(0x29BA, "circle divided by horizontal bar and top half divided by vertical bar", "⦺", "Sm", 0, null, "\\obot", null));
        symbols.add(new MathOperator(0x29BB, "circle with superimposed x", "⦻", "Sm", 0, null, "\\olcross", null));
        symbols.add(new MathOperator(0x29BC, "circled anticlockwise-rotated division sign", "⦼", "Sm", 0, null, "\\odotslashdot", null));
        symbols.add(new MathOperator(0x29BD, "up arrow through circle", "⦽", "Sm", 0, null, "\\uparrowoncircle", null));
        symbols.add(new MathOperator(0x29BE, "circled white bullet", "⦾", "Sm", 0, null, "\\circledwhitebullet", null));
        symbols.add(new MathOperator(0x29BF, "circled bullet", "⦿", "Sm", 0, null, "\\circledbullet", null));
        symbols.add(new MathOperator(0x29C0, "circled less-than", "⧀", "Sm", 0, "\\circledless", "\\olessthan", null));
        symbols.add(new MathOperator(0x29C1, "circled greater-than", "⧁", "Sm", 0, "\\circledgtr", "\\ogreaterthan", null));
        symbols.add(new MathOperator(0x29C2, "circle with small circle to the right", "⧂", "Sm", 0, null, "\\cirscir", null));
        symbols.add(new MathOperator(0x29C3, "circle with two horizontal strokes to the right", "⧃", "Sm", 0, null, "\\cirE", null));
        symbols.add(new MathOperator(0x29C4, "squared rising diagonal slash", "⧄", "Sm", 0, "\\boxslash", "\\boxdiag", null));
        symbols.add(new MathOperator(0x29C5, "squared falling diagonal slash", "⧅", "Sm", 0, "\\boxbslash", null, null));
        symbols.add(new MathOperator(0x29C6, "squared asterisk", "⧆", "Sm", 0, "\\boxast", null, null));
        symbols.add(new MathOperator(0x29C7, "squared small circle", "⧇", "Sm", 0, "\\boxcircle", null, null));
        symbols.add(new MathOperator(0x29C8, "squared square", "⧈", "Sm", 0, "\\boxbox", null, null));
        symbols.add(new MathOperator(0x29C9, "two joined squares", "⧉", "Sm", 0, null, "\\boxonbox", null));
        symbols.add(new MathOperator(0x29CA, "triangle with dot above", "⧊", "Sm", 0, null, "\\triangleodot", null));
        symbols.add(new MathOperator(0x29CB, "triangle with underbar", "⧋", "Sm", 0, null, "\\triangleubar", null));
        symbols.add(new MathOperator(0x29CC, "s in triangle", "⧌", "Sm", 0, null, "\\triangles", null));
        symbols.add(new MathOperator(0x29CD, "triangle with serifs at bottom", "⧍", "Sm", 0, null, "\\triangleserifs", null));
        symbols.add(new MathOperator(0x29CE, "right triangle above left triangle", "⧎", "Sm", 0, null, "\\rtriltri", null));
        symbols.add(new MathOperator(0x29CF, "left triangle beside vertical bar", "⧏", "Sm", 0, "\\LeftTriangleBar", "\\ltrivb", null));
        symbols.add(new MathOperator(0x29D0, "vertical bar beside right triangle", "⧐", "Sm", 0, "\\RightTriangleBar", "\\vbrtri", null));
        symbols.add(new MathOperator(0x29D1, "bowtie with left half black", "⧑", "Sm", 0, null, "\\lfbowtie", null));
        symbols.add(new MathOperator(0x29D2, "bowtie with right half black", "⧒", "Sm", 0, null, "\\rfbowtie", null));
        symbols.add(new MathOperator(0x29D3, "black bowtie", "⧓", "Sm", 0, null, "\\fbowtie", null));
        symbols.add(new MathOperator(0x29D4, "times with left half black", "⧔", "Sm", 0, null, "\\lftimes", null));
        symbols.add(new MathOperator(0x29D5, "times with right half black", "⧕", "Sm", 0, null, "\\rftimes", null));
        symbols.add(new MathOperator(0x29D6, "white hourglass", "⧖", "Sm", 0, null, "\\hourglass", null));
        symbols.add(new MathOperator(0x29D7, "black hourglass", "⧗", "Sm", 0, null, "\\blackhourglass", null));
        symbols.add(new MathOperator(0x29D8, "left wiggly fence", "⧘", "Ps", 0, null, "\\lvzigzag", null));
        symbols.add(new MathOperator(0x29D9, "right wiggly fence", "⧙", "Pe", 0, null, "\\rvzigzag", null));
        symbols.add(new MathOperator(0x29DA, "left double wiggly fence", "⧚", "Ps", 0, null, "\\Lvzigzag", null));
        symbols.add(new MathOperator(0x29DB, "right double wiggly fence", "⧛", "Pe", 0, null, "\\Rvzigzag", null));
        symbols.add(new MathOperator(0x29DC, "incomplete infinity", "⧜", "Sm", 0, null, "\\iinfin", null));
        symbols.add(new MathOperator(0x29DD, "tie over infinity", "⧝", "Sm", 0, null, "\\tieinfty", null));
        symbols.add(new MathOperator(0x29DE, "infinity negated with vertical bar", "⧞", "Sm", 0, null, "\\nvinfty", null));
        symbols.add(new MathOperator(0x29DF, "double-ended multimap", "⧟", "Sm", 0, "\\multimapboth", "\\dualmap", null));
        symbols.add(new MathOperator(0x29E0, "square with contoured outline", "⧠", "Sm", 0, null, "\\laplac", null));
        symbols.add(new MathOperator(0x29E1, "increases as", "⧡", "Sm", 0, null, "\\lrtriangleeq", null));
        symbols.add(new MathOperator(0x29E2, "shuffle product", "⧢", "Sm", 0, null, "\\shuffle", null));
        symbols.add(new MathOperator(0x29E3, "equals sign and slanted parallel", "⧣", "Sm", 0, null, "\\eparsl", null));
        symbols.add(new MathOperator(0x29E4, "equals sign and slanted parallel with tilde above", "⧤", "Sm", 0, null, "\\smeparsl", null));
        symbols.add(new MathOperator(0x29E5, "identical to and slanted parallel", "⧥", "Sm", 0, null, "\\eqvparsl", null));
        symbols.add(new MathOperator(0x29E6, "gleich stark", "⧦", "Sm", 0, null, "\\gleichstark", null));
        symbols.add(new MathOperator(0x29E7, "thermodynamic", "⧧", "Sm", 0, null, "\\thermod", null));
        symbols.add(new MathOperator(0x29E8, "down-pointing triangle with left half black", "⧨", "Sm", 0, null, "\\downtriangleleftblack", null));
        symbols.add(new MathOperator(0x29E9, "down-pointing triangle with right half black", "⧩", "Sm", 0, null, "\\downtrianglerightblack", null));
        symbols.add(new MathOperator(0x29EA, "black diamond with down arrow", "⧪", "Sm", 0, null, "\\blackdiamonddownarrow", null));
        symbols.add(new MathOperator(0x29EB, "black lozenge", "⧫", "Sm", 0, "\\blacklozenge", "\\mdlgblklozenge", null));
        symbols.add(new MathOperator(0x29EC, "white circle with down arrow", "⧬", "Sm", 0, null, "\\circledownarrow", null));
        symbols.add(new MathOperator(0x29ED, "black circle with down arrow", "⧭", "Sm", 0, null, "\\blackcircledownarrow", null));
        symbols.add(new MathOperator(0x29EE, "error-barred white square", "⧮", "Sm", 0, null, "\\errbarsquare", null));
        symbols.add(new MathOperator(0x29EF, "error-barred black square", "⧯", "Sm", 0, null, "\\errbarblacksquare", null));
        symbols.add(new MathOperator(0x29F0, "error-barred white diamond", "⧰", "Sm", 0, null, "\\errbardiamond", null));
        symbols.add(new MathOperator(0x29F1, "error-barred black diamond", "⧱", "Sm", 0, null, "\\errbarblackdiamond", null));
        symbols.add(new MathOperator(0x29F2, "error-barred white circle", "⧲", "Sm", 0, null, "\\errbarcircle", null));
        symbols.add(new MathOperator(0x29F3, "error-barred black circle", "⧳", "Sm", 0, null, "\\errbarblackcircle", null));
        symbols.add(new MathOperator(0x29F4, "rule-delayed", "⧴", "Sm", 0, null, "\\ruledelayed", null));
        symbols.add(new MathOperator(0x29F5, "reverse solidus operator", "⧵", "Sm", 0, "\\setminus", null, null));
        symbols.add(new MathOperator(0x29F6, "solidus with overbar", "⧶", "Sm", 0, null, "\\dsol", null));
        symbols.add(new MathOperator(0x29F7, "reverse solidus with horizontal stroke", "⧷", "Sm", 0, null, "\\rsolbar", null));
        symbols.add(new MathOperator(0x29F8, "big solidus", "⧸", "Sm", 0, null, "\\xsol", null));
        symbols.add(new MathOperator(0x29F9, "big reverse solidus", "⧹", "Sm", 0, "\\zhide", "\\xbsol", null));
        symbols.add(new MathOperator(0x29FA, "double plus", "⧺", "Sm", 0, null, "\\doubleplus", null));
        symbols.add(new MathOperator(0x29FB, "triple plus", "⧻", "Sm", 0, null, "\\tripleplus", null));
        symbols.add(new MathOperator(0x29FC, "left-pointing curved angle bracket", "⧼", "Ps", 0, null, "\\lcurvyangle", null));
        symbols.add(new MathOperator(0x29FD, "right-pointing curved angle bracket", "⧽", "Pe", 0, null, "\\rcurvyangle", null));
        symbols.add(new MathOperator(0x29FE, "tiny", "⧾", "Sm", 0, null, "\\tplus", null));
        symbols.add(new MathOperator(0x29FF, "miny", "⧿", "Sm", 0, null, "\\tminus", null));
        symbols.add(new MathOperator(0x2A00, "n-ary circled dot operator", "⨀", "Sm", 0, "\\bigodot", null, null));
        symbols.add(new MathOperator(0x2A01, "n-ary circled plus operator", "⨁", "Sm", 0, "\\bigoplus", null, null));
        symbols.add(new MathOperator(0x2A02, "n-ary circled times operator", "⨂", "Sm", 0, "\\bigotimes", null, null));
        symbols.add(new MathOperator(0x2A03, "n-ary union operator with dot", "⨃", "Sm", 0, null, "\\bigcupdot", null));
        symbols.add(new MathOperator(0x2A04, "n-ary union operator with plus", "⨄", "Sm", 0, "\\biguplus", null, null));
        symbols.add(new MathOperator(0x2A05, "n-ary square intersection operator", "⨅", "Sm", 0, "\\bigsqcap", null, null));
        symbols.add(new MathOperator(0x2A06, "n-ary square union operator", "⨆", "Sm", 0, "\\bigsqcup", null, null));
        symbols.add(new MathOperator(0x2A07, "two logical and operator", "⨇", "Sm", 0, null, "\\conjquant", null));
        symbols.add(new MathOperator(0x2A08, "two logical or operator", "⨈", "Sm", 0, null, "\\disjquant", null));
        symbols.add(new MathOperator(0x2A09, "n-ary times operator", "⨉", "Sm", 0, "\\varprod", "\\bigtimes", null));
        symbols.add(new MathOperator(0x2A0A, "modulo two sum", "⨊", "Sm", 0, null, "\\modtwosum", null));
        symbols.add(new MathOperator(0x2A0B, "summation with integral", "⨋", "Sm", 0, null, "\\sumint", null));
        symbols.add(new MathOperator(0x2A0C, "quadruple integral operator", "⨌", "Sm", 0, "\\iiiint", null, null));
        symbols.add(new MathOperator(0x2A0D, "finite part integral", "⨍", "Sm", 0, null, "\\intbar", null));
        symbols.add(new MathOperator(0x2A0E, "integral with double stroke", "⨎", "Sm", 0, null, "\\intBar", null));
        symbols.add(new MathOperator(0x2A0F, "integral average with slash", "⨏", "Sm", 0, "\\fint", null, null));
        symbols.add(new MathOperator(0x2A10, "circulation function", "⨐", "Sm", 0, null, "\\cirfnint", null));
        symbols.add(new MathOperator(0x2A11, "anticlockwise integration", "⨑", "Sm", 0, null, "\\awint", null));
        symbols.add(new MathOperator(0x2A12, "line integration with rectangular path around pole", "⨒", "Sm", 0, null, "\\rppolint", null));
        symbols.add(new MathOperator(0x2A13, "line integration with semicircular path around pole", "⨓", "Sm", 0, null, "\\scpolint", null));
        symbols.add(new MathOperator(0x2A14, "line integration not including the pole", "⨔", "Sm", 0, null, "\\npolint", null));
        symbols.add(new MathOperator(0x2A15, "integral around a point operator", "⨕", "Sm", 0, null, "\\pointint", null));
        symbols.add(new MathOperator(0x2A16, "quaternion integral operator", "⨖", "Sm", 0, "\\sqint", null, null));
        symbols.add(new MathOperator(0x2A17, "integral with leftwards arrow with hook", "⨗", "Sm", 0, null, "\\intlarhk", null));
        symbols.add(new MathOperator(0x2A18, "integral with times sign", "⨘", "Sm", 0, null, "\\intx", null));
        symbols.add(new MathOperator(0x2A19, "integral with intersection", "⨙", "Sm", 0, null, "\\intcap", null));
        symbols.add(new MathOperator(0x2A1A, "integral with union", "⨚", "Sm", 0, null, "\\intcup", null));
        symbols.add(new MathOperator(0x2A1B, "integral with overbar", "⨛", "Sm", 0, null, "\\upint", null));
        symbols.add(new MathOperator(0x2A1C, "integral with underbar", "⨜", "Sm", 0, null, "\\lowint", null));
        symbols.add(new MathOperator(0x2A1D, "join", "⨝", "Sm", 0, "\\Join", null, null));
        symbols.add(new MathOperator(0x2A1E, "large left triangle operator", "⨞", "Sm", 0, null, "\\bigtriangleleft", null));
        symbols.add(new MathOperator(0x2A1F, "z notation schema composition", "⨟", "Sm", 0, "\\zcmp", null, null));
        symbols.add(new MathOperator(0x2A20, "z notation schema piping", "⨠", "Sm", 0, "\\zpipe", null, null));
        symbols.add(new MathOperator(0x2A21, "z notation schema projection", "⨡", "Sm", 0, "\\zproject", null, null));
        symbols.add(new MathOperator(0x2A22, "plus sign with small circle above", "⨢", "Sm", 0, null, "\\ringplus", null));
        symbols.add(new MathOperator(0x2A23, "plus sign with circumflex accent above", "⨣", "Sm", 0, null, "\\plushat", null));
        symbols.add(new MathOperator(0x2A24, "plus sign with tilde above", "⨤", "Sm", 0, null, "\\simplus", null));
        symbols.add(new MathOperator(0x2A25, "plus sign with dot below", "⨥", "Sm", 0, null, "\\plusdot", null));
        symbols.add(new MathOperator(0x2A26, "plus sign with tilde below", "⨦", "Sm", 0, null, "\\plussim", null));
        symbols.add(new MathOperator(0x2A27, "_plus sign with subscript two", "⨧", "Sm", 0, null, "\\plussubtwo", null));
        symbols.add(new MathOperator(0x2A28, "plus sign with black triangle", "⨨", "Sm", 0, null, "\\plustrif", null));
        symbols.add(new MathOperator(0x2A29, "minus sign with comma above", "⨩", "Sm", 0, null, "\\commaminus", null));
        symbols.add(new MathOperator(0x2A2A, "minus sign with dot below", "⨪", "Sm", 0, null, "\\minusdot", null));
        symbols.add(new MathOperator(0x2A2B, "minus sign with falling dots", "⨫", "Sm", 0, null, "\\minusfdots", null));
        symbols.add(new MathOperator(0x2A2C, "minus sign with rising dots", "⨬", "Sm", 0, null, "\\minusrdots", null));
        symbols.add(new MathOperator(0x2A2D, "plus sign in left half circle", "⨭", "Sm", 0, null, "\\opluslhrim", null));
        symbols.add(new MathOperator(0x2A2E, "plus sign in right half circle", "⨮", "Sm", 0, null, "\\oplusrhrim", null));
        symbols.add(new MathOperator(0x2A2F, "vector or cross product", "⨯", "Sm", 0, null, "\\vectimes", null));
        symbols.add(new MathOperator(0x2A30, "multiplication sign with dot above", "⨰", "Sm", 0, null, "\\dottimes", null));
        symbols.add(new MathOperator(0x2A31, "multiplication sign with underbar", "⨱", "Sm", 0, null, "\\timesbar", null));
        symbols.add(new MathOperator(0x2A32, "semidirect product with bottom closed", "⨲", "Sm", 0, null, "\\btimes", null));
        symbols.add(new MathOperator(0x2A33, "smash product", "⨳", "Sm", 0, null, "\\smashtimes", null));
        symbols.add(new MathOperator(0x2A34, "multiplication sign in left half circle", "⨴", "Sm", 0, null, "\\otimeslhrim", null));
        symbols.add(new MathOperator(0x2A35, "multiplication sign in right half circle", "⨵", "Sm", 0, null, "\\otimesrhrim", null));
        symbols.add(new MathOperator(0x2A36, "circled multiplication sign with circumflex accent", "⨶", "Sm", 0, null, "\\otimeshat", null));
        symbols.add(new MathOperator(0x2A37, "multiplication sign in double circle", "⨷", "Sm", 0, null, "\\Otimes", null));
        symbols.add(new MathOperator(0x2A38, "circled division sign", "⨸", "Sm", 0, null, "\\odiv", null));
        symbols.add(new MathOperator(0x2A39, "plus sign in triangle", "⨹", "Sm", 0, null, "\\triangleplus", null));
        symbols.add(new MathOperator(0x2A3A, "minus sign in triangle", "⨺", "Sm", 0, null, "\\triangleminus", null));
        symbols.add(new MathOperator(0x2A3B, "multiplication sign in triangle", "⨻", "Sm", 0, null, "\\triangletimes", null));
        symbols.add(new MathOperator(0x2A3C, "interior product", "⨼", "Sm", 0, null, "\\intprod", null));
        symbols.add(new MathOperator(0x2A3D, "righthand interior product", "⨽", "Sm", 0, null, "\\intprodr", null));
        symbols.add(new MathOperator(0x2A3E, "z notation relational composition", "⨾", "Sm", 0, "\\fcmp", null, null));
        symbols.add(new MathOperator(0x2A3F, "amalgamation or coproduct", "⨿", "Sm", 0, "\\amalg", null, null));
        symbols.add(new MathOperator(0x2A40, "intersection with dot", "⩀", "Sm", 0, null, "\\capdot", null));
        symbols.add(new MathOperator(0x2A41, "union with minus sign", "⩁", "Sm", 0, null, "\\uminus", null));
        symbols.add(new MathOperator(0x2A42, "union with overbar", "⩂", "Sm", 0, null, "\\barcup", null));
        symbols.add(new MathOperator(0x2A43, "intersection with overbar", "⩃", "Sm", 0, null, "\\barcap", null));
        symbols.add(new MathOperator(0x2A44, "intersection with logical and", "⩄", "Sm", 0, null, "\\capwedge", null));
        symbols.add(new MathOperator(0x2A45, "union with logical or", "⩅", "Sm", 0, null, "\\cupvee", null));
        symbols.add(new MathOperator(0x2A46, "union above intersection", "⩆", "Sm", 0, null, "\\cupovercap", null));
        symbols.add(new MathOperator(0x2A47, "intersection above union", "⩇", "Sm", 0, null, "\\capovercup", null));
        symbols.add(new MathOperator(0x2A48, "union above bar above intersection", "⩈", "Sm", 0, null, "\\cupbarcap", null));
        symbols.add(new MathOperator(0x2A49, "intersection above bar above union", "⩉", "Sm", 0, null, "\\capbarcup", null));
        symbols.add(new MathOperator(0x2A4A, "union beside and joined with union", "⩊", "Sm", 0, null, "\\twocups", null));
        symbols.add(new MathOperator(0x2A4B, "intersection beside and joined with intersection", "⩋", "Sm", 0, null, "\\twocaps", null));
        symbols.add(new MathOperator(0x2A4C, "closed union with serifs", "⩌", "Sm", 0, null, "\\closedvarcup", null));
        symbols.add(new MathOperator(0x2A4D, "closed intersection with serifs", "⩍", "Sm", 0, null, "\\closedvarcap", null));
        symbols.add(new MathOperator(0x2A4E, "double square intersection", "⩎", "Sm", 0, null, "\\Sqcap", null));
        symbols.add(new MathOperator(0x2A4F, "double square union", "⩏", "Sm", 0, null, "\\Sqcup", null));
        symbols.add(new MathOperator(0x2A50, "closed union with serifs and smash product", "⩐", "Sm", 0, null, "\\closedvarcupsmashprod", null));
        symbols.add(new MathOperator(0x2A51, "logical and with dot above", "⩑", "Sm", 0, null, "\\wedgeodot", null));
        symbols.add(new MathOperator(0x2A52, "logical or with dot above", "⩒", "Sm", 0, null, "\\veeodot", null));
        symbols.add(new MathOperator(0x2A53, "double logical and", "⩓", "Sm", 0, null, "\\Wedge", null));
        symbols.add(new MathOperator(0x2A54, "double logical or", "⩔", "Sm", 0, null, "\\Vee", null));
        symbols.add(new MathOperator(0x2A55, "two intersecting logical and", "⩕", "Sm", 0, null, "\\wedgeonwedge", null));
        symbols.add(new MathOperator(0x2A56, "two intersecting logical or", "⩖", "Sm", 0, null, "\\veeonvee", null));
        symbols.add(new MathOperator(0x2A57, "sloping large or", "⩗", "Sm", 0, null, "\\bigslopedvee", null));
        symbols.add(new MathOperator(0x2A58, "sloping large and", "⩘", "Sm", 0, null, "\\bigslopedwedge", null));
        symbols.add(new MathOperator(0x2A59, "logical or overlapping logical and", "⩙", "Sm", 0, null, "\\veeonwedge", null));
        symbols.add(new MathOperator(0x2A5A, "logical and with middle stem", "⩚", "Sm", 0, null, "\\wedgemidvert", null));
        symbols.add(new MathOperator(0x2A5B, "logical or with middle stem", "⩛", "Sm", 0, null, "\\veemidvert", null));
        symbols.add(new MathOperator(0x2A5C, "logical and with horizontal dash", "⩜", "Sm", 0, null, "\\midbarwedge", null));
        symbols.add(new MathOperator(0x2A5D, "logical or with horizontal dash", "⩝", "Sm", 0, null, "\\midbarvee", null));
        symbols.add(new MathOperator(0x2A5E, "logical and with double overbar", "⩞", "Sm", 0, "\\doublebarwedge", null, null));
        symbols.add(new MathOperator(0x2A5F, "logical and with underbar", "⩟", "Sm", 0, null, "\\wedgebar", null));
        symbols.add(new MathOperator(0x2A60, "logical and with double underbar", "⩠", "Sm", 0, null, "\\wedgedoublebar", null));
        symbols.add(new MathOperator(0x2A61, "small vee with underbar", "⩡", "Sm", 0, null, "\\varveebar", null));
        symbols.add(new MathOperator(0x2A62, "logical or with double overbar", "⩢", "Sm", 0, null, "\\doublebarvee", null));
        symbols.add(new MathOperator(0x2A63, "logical or with double underbar", "⩣", "Sm", 0, null, "\\veedoublebar", null));
        symbols.add(new MathOperator(0x2A64, "z notation domain antirestriction", "⩤", "Sm", 0, "\\dsub", null, null));
        symbols.add(new MathOperator(0x2A65, "z notation range antirestriction", "⩥", "Sm", 0, "\\rsub", null, null));
        symbols.add(new MathOperator(0x2A66, "equals sign with dot below", "⩦", "Sm", 0, null, "\\eqdot", null));
        symbols.add(new MathOperator(0x2A67, "identical with dot above", "⩧", "Sm", 0, null, "\\dotequiv", null));
        symbols.add(new MathOperator(0x2A68, "triple horizontal bar with double vertical stroke", "⩨", "Sm", 0, null, "\\equivVert", null));
        symbols.add(new MathOperator(0x2A69, "triple horizontal bar with triple vertical stroke", "⩩", "Sm", 0, null, "\\equivVvert", null));
        symbols.add(new MathOperator(0x2A6A, "tilde operator with dot above", "⩪", "Sm", 0, null, "\\dotsim", null));
        symbols.add(new MathOperator(0x2A6B, "tilde operator with rising dots", "⩫", "Sm", 0, null, "\\simrdots", null));
        symbols.add(new MathOperator(0x2A6C, "similar minus similar", "⩬", "Sm", 0, null, "\\simminussim", null));
        symbols.add(new MathOperator(0x2A6D, "congruent with dot above", "⩭", "Sm", 0, null, "\\congdot", null));
        symbols.add(new MathOperator(0x2A6E, "equals with asterisk", "⩮", "Sm", 0, null, "\\asteq", null));
        symbols.add(new MathOperator(0x2A6F, "almost equal to with circumflex accent", "⩯", "Sm", 0, null, "\\hatapprox", null));
        symbols.add(new MathOperator(0x2A70, "approximately equal or equal to", "⩰", "Sm", 0, null, "\\approxeqq", null));
        symbols.add(new MathOperator(0x2A71, "equals sign above plus sign", "⩱", "Sm", 0, null, "\\eqqplus", null));
        symbols.add(new MathOperator(0x2A72, "plus sign above equals sign", "⩲", "Sm", 0, null, "\\pluseqq", null));
        symbols.add(new MathOperator(0x2A73, "equals sign above tilde operator", "⩳", "Sm", 0, null, "\\eqqsim", null));
        symbols.add(new MathOperator(0x2A74, "double colon equal", "⩴", "Sm", 0, "\\Coloneqq", "\\Coloneq", null));
        symbols.add(new MathOperator(0x2A75, "two consecutive equals signs", "⩵", "Sm", 0, "\\Equal", "\\eqeq", null));
        symbols.add(new MathOperator(0x2A76, "three consecutive equals signs", "⩶", "Sm", 0, "\\Same", "\\eqeqeq", null));
        symbols.add(new MathOperator(0x2A77, "equals sign with two dots above and two dots below", "⩷", "Sm", 0, null, "\\ddotseq", null));
        symbols.add(new MathOperator(0x2A78, "equivalent with four dots above", "⩸", "Sm", 0, null, "\\equivDD", null));
        symbols.add(new MathOperator(0x2A79, "less-than with circle inside", "⩹", "Sm", 0, null, "\\ltcir", null));
        symbols.add(new MathOperator(0x2A7A, "greater-than with circle inside", "⩺", "Sm", 0, null, "\\gtcir", null));
        symbols.add(new MathOperator(0x2A7B, "less-than with question mark above", "⩻", "Sm", 0, null, "\\ltquest", null));
        symbols.add(new MathOperator(0x2A7C, "greater-than with question mark above", "⩼", "Sm", 0, null, "\\gtquest", null));
        symbols.add(new MathOperator(0x2A7D, "less-than or slanted equal to", "⩽", "Sm", 0, "\\leqslant", null, null));
        symbols.add(new MathOperator(0x2A7E, "greater-than or slanted equal to", "⩾", "Sm", 0, "\\geqslant", null, null));
        symbols.add(new MathOperator(0x2A7F, "less-than or slanted equal to with dot inside", "⩿", "Sm", 0, null, "\\lesdot", null));
        symbols.add(new MathOperator(0x2A80, "greater-than or slanted equal to with dot inside", "⪀", "Sm", 0, null, "\\gesdot", null));
        symbols.add(new MathOperator(0x2A81, "less-than or slanted equal to with dot above", "⪁", "Sm", 0, null, "\\lesdoto", null));
        symbols.add(new MathOperator(0x2A82, "greater-than or slanted equal to with dot above", "⪂", "Sm", 0, null, "\\gesdoto", null));
        symbols.add(new MathOperator(0x2A83, "less-than or slanted equal to with dot above right", "⪃", "Sm", 0, null, "\\lesdotor", null));
        symbols.add(new MathOperator(0x2A84, "greater-than or slanted equal to with dot above left", "⪄", "Sm", 0, null, "\\gesdotol", null));
        symbols.add(new MathOperator(0x2A85, "less-than or approximate", "⪅", "Sm", 0, "\\lessapprox", null, null));
        symbols.add(new MathOperator(0x2A86, "greater-than or approximate", "⪆", "Sm", 0, "\\gtrapprox", null, null));
        symbols.add(new MathOperator(0x2A87, "less-than and single-line not equal to", "⪇", "Sm", 0, "\\lneq", null, null));
        symbols.add(new MathOperator(0x2A88, "greater-than and single-line not equal to", "⪈", "Sm", 0, "\\gneq", null, null));
        symbols.add(new MathOperator(0x2A89, "less-than and not approximate", "⪉", "Sm", 0, "\\lnapprox", null, null));
        symbols.add(new MathOperator(0x2A8A, "greater-than and not approximate", "⪊", "Sm", 0, "\\gnapprox", null, null));
        symbols.add(new MathOperator(0x2A8B, "less-than above double-line equal above greater-than", "⪋", "Sm", 0, "\\lesseqqgtr", null, null));
        symbols.add(new MathOperator(0x2A8C, "greater-than above double-line equal above less-than", "⪌", "Sm", 0, "\\gtreqqless", null, null));
        symbols.add(new MathOperator(0x2A8D, "less-than above similar or equal", "⪍", "Sm", 0, null, "\\lsime", null));
        symbols.add(new MathOperator(0x2A8E, "greater-than above similar or equal", "⪎", "Sm", 0, null, "\\gsime", null));
        symbols.add(new MathOperator(0x2A8F, "less-than above similar above greater-than", "⪏", "Sm", 0, null, "\\lsimg", null));
        symbols.add(new MathOperator(0x2A90, "greater-than above similar above less-than", "⪐", "Sm", 0, null, "\\gsiml", null));
        symbols.add(new MathOperator(0x2A91, "less-than above greater-than above double-line equal", "⪑", "Sm", 0, null, "\\lgE", null));
        symbols.add(new MathOperator(0x2A92, "greater-than above less-than above double-line equal", "⪒", "Sm", 0, null, "\\glE", null));
        symbols.add(new MathOperator(0x2A93, "less-than above slanted equal above greater-than above slanted equal", "⪓", "Sm", 0, null, "\\lesges", null));
        symbols.add(new MathOperator(0x2A94, "greater-than above slanted equal above less-than above slanted equal", "⪔", "Sm", 0, null, "\\gesles", null));
        symbols.add(new MathOperator(0x2A95, "slanted equal to or less-than", "⪕", "Sm", 0, "\\eqslantless", null, null));
        symbols.add(new MathOperator(0x2A96, "slanted equal to or greater-than", "⪖", "Sm", 0, "\\eqslantgtr", null, null));
        symbols.add(new MathOperator(0x2A97, "slanted equal to or less-than with dot inside", "⪗", "Sm", 0, null, "\\elsdot", null));
        symbols.add(new MathOperator(0x2A98, "slanted equal to or greater-than with dot inside", "⪘", "Sm", 0, null, "\\egsdot", null));
        symbols.add(new MathOperator(0x2A99, "double-line equal to or less-than", "⪙", "Sm", 0, null, "\\eqqless", null));
        symbols.add(new MathOperator(0x2A9A, "double-line equal to or greater-than", "⪚", "Sm", 0, null, "\\eqqgtr", null));
        symbols.add(new MathOperator(0x2A9B, "double-line slanted equal to or less-than", "⪛", "Sm", 0, null, "\\eqqslantless", null));
        symbols.add(new MathOperator(0x2A9C, "double-line slanted equal to or greater-than", "⪜", "Sm", 0, null, "\\eqqslantgtr", null));
        symbols.add(new MathOperator(0x2A9D, "similar or less-than", "⪝", "Sm", 0, null, "\\simless", null));
        symbols.add(new MathOperator(0x2A9E, "similar or greater-than", "⪞", "Sm", 0, null, "\\simgtr", null));
        symbols.add(new MathOperator(0x2A9F, "similar above less-than above equals sign", "⪟", "Sm", 0, null, "\\simlE", null));
        symbols.add(new MathOperator(0x2AA0, "similar above greater-than above equals sign", "⪠", "Sm", 0, null, "\\simgE", null));
        symbols.add(new MathOperator(0x2AA1, "double nested less-than", "⪡", "Sm", 0, "\\NestedLessLess", "\\Lt", null));
        symbols.add(new MathOperator(0x2AA2, "double nested greater-than", "⪢", "Sm", 0, "\\NestedGreaterGreater", "\\Gt", null));
        symbols.add(new MathOperator(0x2AA3, "double nested less-than with underbar", "⪣", "Sm", 0, null, "\\partialmeetcontraction", null));
        symbols.add(new MathOperator(0x2AA4, "greater-than overlapping less-than", "⪤", "Sm", 0, null, "\\glj", null));
        symbols.add(new MathOperator(0x2AA5, "greater-than beside less-than", "⪥", "Sm", 0, null, "\\gla", null));
        symbols.add(new MathOperator(0x2AA6, "less-than closed by curve", "⪦", "Sm", 0, "\\leftslice", "\\ltcc", null));
        symbols.add(new MathOperator(0x2AA7, "greater-than closed by curve", "⪧", "Sm", 0, "\\rightslice", "\\gtcc", null));
        symbols.add(new MathOperator(0x2AA8, "less-than closed by curve above slanted equal", "⪨", "Sm", 0, null, "\\lescc", null));
        symbols.add(new MathOperator(0x2AA9, "greater-than closed by curve above slanted equal", "⪩", "Sm", 0, null, "\\gescc", null));
        symbols.add(new MathOperator(0x2AAA, "smaller than", "⪪", "Sm", 0, null, "\\smt", null));
        symbols.add(new MathOperator(0x2AAB, "larger than", "⪫", "Sm", 0, null, "\\lat", null));
        symbols.add(new MathOperator(0x2AAC, "smaller than or equal to", "⪬", "Sm", 0, null, "\\smte", null));
        symbols.add(new MathOperator(0x2AAD, "larger than or equal to", "⪭", "Sm", 0, null, "\\late", null));
        symbols.add(new MathOperator(0x2AAE, "equals sign with bumpy above", "⪮", "Sm", 0, null, "\\bumpeqq", null));
        symbols.add(new MathOperator(0x2AAF, "precedes above single-line equals sign", "⪯", "Sm", 0, "\\preceq", null, null));
        symbols.add(new MathOperator(0x2AB0, "succeeds above single-line equals sign", "⪰", "Sm", 0, "\\succeq", null, null));
        symbols.add(new MathOperator(0x2AB1, "precedes above single-line not equal to", "⪱", "Sm", 0, null, "\\precneq", null));
        symbols.add(new MathOperator(0x2AB2, "succeeds above single-line not equal to", "⪲", "Sm", 0, null, "\\succneq", null));
        symbols.add(new MathOperator(0x2AB3, "precedes above equals sign", "⪳", "Sm", 0, "\\preceqq", null, null));
        symbols.add(new MathOperator(0x2AB4, "succeeds above equals sign", "⪴", "Sm", 0, "\\succeqq", null, null));
        symbols.add(new MathOperator(0x2AB5, "precedes above not equal to", "⪵", "Sm", 0, null, "\\precneqq", null));
        symbols.add(new MathOperator(0x2AB6, "succeeds above not equal to", "⪶", "Sm", 0, null, "\\succneqq", null));
        symbols.add(new MathOperator(0x2AB7, "precedes above almost equal to", "⪷", "Sm", 0, "\\precapprox", null, null));
        symbols.add(new MathOperator(0x2AB8, "succeeds above almost equal to", "⪸", "Sm", 0, "\\succapprox", null, null));
        symbols.add(new MathOperator(0x2AB9, "precedes above not almost equal to", "⪹", "Sm", 0, "\\precnapprox", null, null));
        symbols.add(new MathOperator(0x2ABA, "succeeds above not almost equal to", "⪺", "Sm", 0, "\\succnapprox", null, null));
        symbols.add(new MathOperator(0x2ABB, "double precedes", "⪻", "Sm", 0, "\\llcurly", "\\Prec", null));
        symbols.add(new MathOperator(0x2ABC, "double succeeds", "⪼", "Sm", 0, "\\ggcurly", "\\Succ", null));
        symbols.add(new MathOperator(0x2ABD, "subset with dot", "⪽", "Sm", 0, null, "\\subsetdot", null));
        symbols.add(new MathOperator(0x2ABE, "superset with dot", "⪾", "Sm", 0, null, "\\supsetdot", null));
        symbols.add(new MathOperator(0x2ABF, "subset with plus sign below", "⪿", "Sm", 0, null, "\\subsetplus", null));
        symbols.add(new MathOperator(0x2AC0, "superset with plus sign below", "⫀", "Sm", 0, null, "\\supsetplus", null));
        symbols.add(new MathOperator(0x2AC1, "subset with multiplication sign below", "⫁", "Sm", 0, null, "\\submult", null));
        symbols.add(new MathOperator(0x2AC2, "superset with multiplication sign below", "⫂", "Sm", 0, null, "\\supmult", null));
        symbols.add(new MathOperator(0x2AC3, "subset of or equal to with dot above", "⫃", "Sm", 0, null, "\\subedot", null));
        symbols.add(new MathOperator(0x2AC4, "superset of or equal to with dot above", "⫄", "Sm", 0, null, "\\supedot", null));
        symbols.add(new MathOperator(0x2AC5, "subset of above equals sign", "⫅", "Sm", 0, "\\subseteqq", null, null));
        symbols.add(new MathOperator(0x2AC6, "superset of above equals sign", "⫆", "Sm", 0, "\\supseteqq", null, null));
        symbols.add(new MathOperator(0x2AC7, "subset of above tilde operator", "⫇", "Sm", 0, null, "\\subsim", null));
        symbols.add(new MathOperator(0x2AC8, "superset of above tilde operator", "⫈", "Sm", 0, null, "\\supsim", null));
        symbols.add(new MathOperator(0x2AC9, "subset of above almost equal to", "⫉", "Sm", 0, null, "\\subsetapprox", null));
        symbols.add(new MathOperator(0x2ACA, "superset of above almost equal to", "⫊", "Sm", 0, null, "\\supsetapprox", null));
        symbols.add(new MathOperator(0x2ACB, "subset of above not equal to", "⫋", "Sm", 0, "\\subsetneqq", null, null));
        symbols.add(new MathOperator(0x2ACC, "superset of above not equal to", "⫌", "Sm", 0, "\\supsetneqq", null, null));
        symbols.add(new MathOperator(0x2ACD, "square left open box operator", "⫍", "Sm", 0, null, "\\lsqhook", null));
        symbols.add(new MathOperator(0x2ACE, "square right open box operator", "⫎", "Sm", 0, null, "\\rsqhook", null));
        symbols.add(new MathOperator(0x2ACF, "closed subset", "⫏", "Sm", 0, null, "\\csub", null));
        symbols.add(new MathOperator(0x2AD0, "closed superset", "⫐", "Sm", 0, null, "\\csup", null));
        symbols.add(new MathOperator(0x2AD1, "closed subset or equal to", "⫑", "Sm", 0, null, "\\csube", null));
        symbols.add(new MathOperator(0x2AD2, "closed superset or equal to", "⫒", "Sm", 0, null, "\\csupe", null));
        symbols.add(new MathOperator(0x2AD3, "subset above superset", "⫓", "Sm", 0, null, "\\subsup", null));
        symbols.add(new MathOperator(0x2AD4, "superset above subset", "⫔", "Sm", 0, null, "\\supsub", null));
        symbols.add(new MathOperator(0x2AD5, "subset above subset", "⫕", "Sm", 0, null, "\\subsub", null));
        symbols.add(new MathOperator(0x2AD6, "superset above superset", "⫖", "Sm", 0, null, "\\supsup", null));
        symbols.add(new MathOperator(0x2AD7, "superset beside subset", "⫗", "Sm", 0, null, "\\suphsub", null));
        symbols.add(new MathOperator(0x2AD8, "superset beside and joined by dash with subset", "⫘", "Sm", 0, null, "\\supdsub", null));
        symbols.add(new MathOperator(0x2AD9, "element of opening downwards", "⫙", "Sm", 0, null, "\\forkv", null));
        symbols.add(new MathOperator(0x2ADA, "pitchfork with tee top", "⫚", "Sm", 0, null, "\\topfork", null));
        symbols.add(new MathOperator(0x2ADB, "transversal intersection", "⫛", "Sm", 0, null, "\\mlcp", null));
        symbols.add(new MathOperator(0x2ADC, "forking", "⫝̸", "Sm", 0, null, "\\forks", null));
        symbols.add(new MathOperator(0x2ADD, "nonforking", "⫝", "Sm", 0, null, "\\forksnot", null));
        symbols.add(new MathOperator(0x2ADE, "short left tack", "⫞", "Sm", 0, null, "\\shortlefttack", null));
        symbols.add(new MathOperator(0x2ADF, "short down tack", "⫟", "Sm", 0, null, "\\shortdowntack", null));
        symbols.add(new MathOperator(0x2AE0, "short up tack", "⫠", "Sm", 0, null, "\\shortuptack", null));
        symbols.add(new MathOperator(0x2AE1, "perpendicular with s", "⫡", "Sm", 0, null, "\\perps", null));
        symbols.add(new MathOperator(0x2AE2, "vertical bar triple right turnstile", "⫢", "Sm", 0, null, "\\vDdash", null));
        symbols.add(new MathOperator(0x2AE3, "double vertical bar left turnstile", "⫣", "Sm", 0, null, "\\dashV", null));
        symbols.add(new MathOperator(0x2AE4, "vertical bar double left turnstile", "⫤", "Sm", 0, null, "\\Dashv", null));
        symbols.add(new MathOperator(0x2AE5, "double vertical bar double left turnstile", "⫥", "Sm", 0, null, "\\DashV", null));
        symbols.add(new MathOperator(0x2AE6, "long dash from left member of double vertical", "⫦", "Sm", 0, null, "\\varVdash", null));
        symbols.add(new MathOperator(0x2AE7, "short down tack with overbar", "⫧", "Sm", 0, null, "\\Barv", null));
        symbols.add(new MathOperator(0x2AE8, "short up tack with underbar", "⫨", "Sm", 0, null, "\\vBar", null));
        symbols.add(new MathOperator(0x2AE9, "short up tack above short down tack", "⫩", "Sm", 0, null, "\\vBarv", null));
        symbols.add(new MathOperator(0x2AEA, "double down tack", "⫪", "Sm", 0, "\\Top", "\\barV", null));
        symbols.add(new MathOperator(0x2AEB, "double up tack", "⫫", "Sm", 0, "\\Bot", "\\Vbar", null));
        symbols.add(new MathOperator(0x2AEC, "double stroke not sign", "⫬", "Sm", 0, null, "\\Not", null));
        symbols.add(new MathOperator(0x2AED, "reversed double stroke not sign", "⫭", "Sm", 0, null, "\\bNot", null));
        symbols.add(new MathOperator(0x2AEE, "does not divide with reversed negation slash", "⫮", "Sm", 0, null, "\\revnmid", null));
        symbols.add(new MathOperator(0x2AEF, "vertical line with circle above", "⫯", "Sm", 0, null, "\\cirmid", null));
        symbols.add(new MathOperator(0x2AF0, "vertical line with circle below", "⫰", "Sm", 0, null, "\\midcir", null));
        symbols.add(new MathOperator(0x2AF1, "down tack with circle below", "⫱", "Sm", 0, null, "\\topcir", null));
        symbols.add(new MathOperator(0x2AF2, "parallel with horizontal stroke", "⫲", "Sm", 0, null, "\\nhpar", null));
        symbols.add(new MathOperator(0x2AF3, "parallel with tilde operator", "⫳", "Sm", 0, null, "\\parsim", null));
        symbols.add(new MathOperator(0x2AF4, "triple vertical bar binary relation", "⫴", "Sm", 0, "\\interleave", null, null));
        symbols.add(new MathOperator(0x2AF5, "triple vertical bar with horizontal stroke", "⫵", "Sm", 0, null, "\\nhVvert", null));
        symbols.add(new MathOperator(0x2AF6, "triple colon operator", "⫶", "Sm", 0, null, "\\threedotcolon", null));
        symbols.add(new MathOperator(0x2AF7, "triple nested less-than", "⫷", "Sm", 0, null, "\\lllnest", null));
        symbols.add(new MathOperator(0x2AF8, "triple nested greater-than", "⫸", "Sm", 0, null, "\\gggnest", null));
        symbols.add(new MathOperator(0x2AF9, "double-line slanted less-than or equal to", "⫹", "Sm", 0, null, "\\leqqslant", null));
        symbols.add(new MathOperator(0x2AFA, "double-line slanted greater-than or equal to", "⫺", "Sm", 0, null, "\\geqqslant", null));
        symbols.add(new MathOperator(0x2AFB, "triple solidus binary relation", "⫻", "Sm", 0, null, "\\trslash", null));
        symbols.add(new MathOperator(0x2AFC, "large triple vertical bar operator", "⫼", "Sm", 0, "\\biginterleave", null, null));
        symbols.add(new MathOperator(0x2AFD, "double solidus operator", "⫽", "Sm", 0, "\\sslash", null, null));
        symbols.add(new MathOperator(0x2AFE, "white vertical bar", "⫾", "Sm", 0, "\\talloblong", null, null));
        symbols.add(new MathOperator(0x2AFF, "n-ary white vertical bar", "⫿", "Sm", 0, null, "\\bigtalloblong", null));
    }
}