package net.mlcoder.unimath.category;

import javax.annotation.Nullable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class Shapes implements UniCode {
    public static final List<UniCode> symbols = new ArrayList<>();

    public final String desc;
    public final int codePoint;
    public final String chars;
    public final String generalCategory;
    public final int combiningClass;
    public final String[] tokenized;

    @Nullable
    public final String latex;

    @Nullable
    public final String ulatex;

    @Nullable
    public final String mathCategory;

    @Override
    public String desc() {
        return desc;
    }

    @Override
    public int codePoint() {
        return codePoint;
    }

    @Override
    public String chars() {
        return chars;
    }

    @Override
    public String generalCategory() {
        return generalCategory;
    }

    @Override
    public int combiningClass() {
        return combiningClass;
    }

    @Override @Nullable
    public String latex() {
        return latex;
    }

    @Override @Nullable
    public String ulatex() {
        return ulatex;
    }

    @Override @Nullable
    public String mathCategory() {
        return mathCategory;
    }

    @Override @Nullable
    public String[] tokenized() {
        return tokenized;
    }

    Shapes(int codePoint, String desc, String chars, String generalCategory, int combiningClass) {
        this(codePoint, desc, chars, generalCategory, combiningClass, null, null, null);
    }

    Shapes(int codePoint, String desc, String chars, String generalCategory, int combiningClass,
                 @Nullable String latex, @Nullable String ulatex, @Nullable String mathCategory) {
        this.codePoint = codePoint;
        this.desc = desc;
        this.generalCategory = generalCategory;
        this.combiningClass = combiningClass;
        this.chars = chars;
        this.latex = latex;
        this.ulatex = ulatex;
        this.mathCategory = mathCategory;
        this.tokenized = Arrays.stream(desc.split(" "))
            .filter(s -> s.length() != 0).toArray(String[]::new);
    }

    @Override
    public String toString() {
        return "[(Shapes)]{" +
            "codePoint=" + codePoint +
            ", desc='" + desc + '\'' +
            ", chars='" + chars + '\'' +
            ", generalCategory='" + generalCategory + '\'' +
            ", combiningClass=" + combiningClass +
            ", latex='" + latex + '\'' +
            ", ulatex='" + ulatex + '\'' +
        '}';
    }

    static {
        symbols.add(new Shapes(0x2500, "box drawings light horizontal", "─", "So", 0));
        symbols.add(new Shapes(0x2501, "box drawings heavy horizontal", "━", "So", 0));
        symbols.add(new Shapes(0x2502, "box drawings light vertical", "│", "So", 0));
        symbols.add(new Shapes(0x2503, "box drawings heavy vertical", "┃", "So", 0));
        symbols.add(new Shapes(0x2504, "box drawings light triple dash horizontal", "┄", "So", 0));
        symbols.add(new Shapes(0x2505, "box drawings heavy triple dash horizontal", "┅", "So", 0));
        symbols.add(new Shapes(0x2506, "box drawings light triple dash vertical", "┆", "So", 0, null, "\\bdtriplevdash", null));
        symbols.add(new Shapes(0x2507, "box drawings heavy triple dash vertical", "┇", "So", 0));
        symbols.add(new Shapes(0x2508, "box drawings light quadruple dash horizontal", "┈", "So", 0));
        symbols.add(new Shapes(0x2509, "box drawings heavy quadruple dash horizontal", "┉", "So", 0));
        symbols.add(new Shapes(0x250A, "box drawings light quadruple dash vertical", "┊", "So", 0));
        symbols.add(new Shapes(0x250B, "box drawings heavy quadruple dash vertical", "┋", "So", 0));
        symbols.add(new Shapes(0x250C, "box drawings light down and right", "┌", "So", 0));
        symbols.add(new Shapes(0x250D, "box drawings down light and right heavy", "┍", "So", 0));
        symbols.add(new Shapes(0x250E, "box drawings down heavy and right light", "┎", "So", 0));
        symbols.add(new Shapes(0x250F, "box drawings heavy down and right", "┏", "So", 0));
        symbols.add(new Shapes(0x2510, "box drawings light down and left", "┐", "So", 0));
        symbols.add(new Shapes(0x2511, "box drawings down light and left heavy", "┑", "So", 0));
        symbols.add(new Shapes(0x2512, "box drawings down heavy and left light", "┒", "So", 0));
        symbols.add(new Shapes(0x2513, "box drawings heavy down and left", "┓", "So", 0));
        symbols.add(new Shapes(0x2514, "box drawings light up and right", "└", "So", 0));
        symbols.add(new Shapes(0x2515, "box drawings up light and right heavy", "┕", "So", 0));
        symbols.add(new Shapes(0x2516, "box drawings up heavy and right light", "┖", "So", 0));
        symbols.add(new Shapes(0x2517, "box drawings heavy up and right", "┗", "So", 0));
        symbols.add(new Shapes(0x2518, "box drawings light up and left", "┘", "So", 0));
        symbols.add(new Shapes(0x2519, "box drawings up light and left heavy", "┙", "So", 0));
        symbols.add(new Shapes(0x251A, "box drawings up heavy and left light", "┚", "So", 0));
        symbols.add(new Shapes(0x251B, "box drawings heavy up and left", "┛", "So", 0));
        symbols.add(new Shapes(0x251C, "box drawings light vertical and right", "├", "So", 0));
        symbols.add(new Shapes(0x251D, "box drawings vertical light and right heavy", "┝", "So", 0));
        symbols.add(new Shapes(0x251E, "box drawings up heavy and right down light", "┞", "So", 0));
        symbols.add(new Shapes(0x251F, "box drawings down heavy and right up light", "┟", "So", 0));
        symbols.add(new Shapes(0x2520, "box drawings vertical heavy and right light", "┠", "So", 0));
        symbols.add(new Shapes(0x2521, "box drawings down light and right up heavy", "┡", "So", 0));
        symbols.add(new Shapes(0x2522, "box drawings up light and right down heavy", "┢", "So", 0));
        symbols.add(new Shapes(0x2523, "box drawings heavy vertical and right", "┣", "So", 0));
        symbols.add(new Shapes(0x2524, "box drawings light vertical and left", "┤", "So", 0));
        symbols.add(new Shapes(0x2525, "box drawings vertical light and left heavy", "┥", "So", 0));
        symbols.add(new Shapes(0x2526, "box drawings up heavy and left down light", "┦", "So", 0));
        symbols.add(new Shapes(0x2527, "box drawings down heavy and left up light", "┧", "So", 0));
        symbols.add(new Shapes(0x2528, "box drawings vertical heavy and left light", "┨", "So", 0));
        symbols.add(new Shapes(0x2529, "box drawings down light and left up heavy", "┩", "So", 0));
        symbols.add(new Shapes(0x252A, "box drawings up light and left down heavy", "┪", "So", 0));
        symbols.add(new Shapes(0x252B, "box drawings heavy vertical and left", "┫", "So", 0));
        symbols.add(new Shapes(0x252C, "box drawings light down and horizontal", "┬", "So", 0));
        symbols.add(new Shapes(0x252D, "box drawings left heavy and right down light", "┭", "So", 0));
        symbols.add(new Shapes(0x252E, "box drawings right heavy and left down light", "┮", "So", 0));
        symbols.add(new Shapes(0x252F, "box drawings down light and horizontal heavy", "┯", "So", 0));
        symbols.add(new Shapes(0x2530, "box drawings down heavy and horizontal light", "┰", "So", 0));
        symbols.add(new Shapes(0x2531, "box drawings right light and left down heavy", "┱", "So", 0));
        symbols.add(new Shapes(0x2532, "box drawings left light and right down heavy", "┲", "So", 0));
        symbols.add(new Shapes(0x2533, "box drawings heavy down and horizontal", "┳", "So", 0));
        symbols.add(new Shapes(0x2534, "box drawings light up and horizontal", "┴", "So", 0));
        symbols.add(new Shapes(0x2535, "box drawings left heavy and right up light", "┵", "So", 0));
        symbols.add(new Shapes(0x2536, "box drawings right heavy and left up light", "┶", "So", 0));
        symbols.add(new Shapes(0x2537, "box drawings up light and horizontal heavy", "┷", "So", 0));
        symbols.add(new Shapes(0x2538, "box drawings up heavy and horizontal light", "┸", "So", 0));
        symbols.add(new Shapes(0x2539, "box drawings right light and left up heavy", "┹", "So", 0));
        symbols.add(new Shapes(0x253A, "box drawings left light and right up heavy", "┺", "So", 0));
        symbols.add(new Shapes(0x253B, "box drawings heavy up and horizontal", "┻", "So", 0));
        symbols.add(new Shapes(0x253C, "box drawings light vertical and horizontal", "┼", "So", 0));
        symbols.add(new Shapes(0x253D, "box drawings left heavy and right vertical light", "┽", "So", 0));
        symbols.add(new Shapes(0x253E, "box drawings right heavy and left vertical light", "┾", "So", 0));
        symbols.add(new Shapes(0x253F, "box drawings vertical light and horizontal heavy", "┿", "So", 0));
        symbols.add(new Shapes(0x2540, "box drawings up heavy and down horizontal light", "╀", "So", 0));
        symbols.add(new Shapes(0x2541, "box drawings down heavy and up horizontal light", "╁", "So", 0));
        symbols.add(new Shapes(0x2542, "box drawings vertical heavy and horizontal light", "╂", "So", 0));
        symbols.add(new Shapes(0x2543, "box drawings left up heavy and right down light", "╃", "So", 0));
        symbols.add(new Shapes(0x2544, "box drawings right up heavy and left down light", "╄", "So", 0));
        symbols.add(new Shapes(0x2545, "box drawings left down heavy and right up light", "╅", "So", 0));
        symbols.add(new Shapes(0x2546, "box drawings right down heavy and left up light", "╆", "So", 0));
        symbols.add(new Shapes(0x2547, "box drawings down light and up horizontal heavy", "╇", "So", 0));
        symbols.add(new Shapes(0x2548, "box drawings up light and down horizontal heavy", "╈", "So", 0));
        symbols.add(new Shapes(0x2549, "box drawings right light and left vertical heavy", "╉", "So", 0));
        symbols.add(new Shapes(0x254A, "box drawings left light and right vertical heavy", "╊", "So", 0));
        symbols.add(new Shapes(0x254B, "box drawings heavy vertical and horizontal", "╋", "So", 0));
        symbols.add(new Shapes(0x254C, "box drawings light double dash horizontal", "╌", "So", 0));
        symbols.add(new Shapes(0x254D, "box drawings heavy double dash horizontal", "╍", "So", 0));
        symbols.add(new Shapes(0x254E, "box drawings light double dash vertical", "╎", "So", 0));
        symbols.add(new Shapes(0x254F, "box drawings heavy double dash vertical", "╏", "So", 0));
        symbols.add(new Shapes(0x2550, "box drawings double horizontal", "═", "So", 0));
        symbols.add(new Shapes(0x2551, "box drawings double vertical", "║", "So", 0));
        symbols.add(new Shapes(0x2552, "box drawings down single and right double", "╒", "So", 0));
        symbols.add(new Shapes(0x2553, "box drawings down double and right single", "╓", "So", 0));
        symbols.add(new Shapes(0x2554, "box drawings double down and right", "╔", "So", 0));
        symbols.add(new Shapes(0x2555, "box drawings down single and left double", "╕", "So", 0));
        symbols.add(new Shapes(0x2556, "box drawings down double and left single", "╖", "So", 0));
        symbols.add(new Shapes(0x2557, "box drawings double down and left", "╗", "So", 0));
        symbols.add(new Shapes(0x2558, "box drawings up single and right double", "╘", "So", 0));
        symbols.add(new Shapes(0x2559, "box drawings up double and right single", "╙", "So", 0));
        symbols.add(new Shapes(0x255A, "box drawings double up and right", "╚", "So", 0));
        symbols.add(new Shapes(0x255B, "box drawings up single and left double", "╛", "So", 0));
        symbols.add(new Shapes(0x255C, "box drawings up double and left single", "╜", "So", 0));
        symbols.add(new Shapes(0x255D, "box drawings double up and left", "╝", "So", 0));
        symbols.add(new Shapes(0x255E, "box drawings vertical single and right double", "╞", "So", 0));
        symbols.add(new Shapes(0x255F, "box drawings vertical double and right single", "╟", "So", 0));
        symbols.add(new Shapes(0x2560, "box drawings double vertical and right", "╠", "So", 0));
        symbols.add(new Shapes(0x2561, "box drawings vertical single and left double", "╡", "So", 0));
        symbols.add(new Shapes(0x2562, "box drawings vertical double and left single", "╢", "So", 0));
        symbols.add(new Shapes(0x2563, "box drawings double vertical and left", "╣", "So", 0));
        symbols.add(new Shapes(0x2564, "box drawings down single and horizontal double", "╤", "So", 0));
        symbols.add(new Shapes(0x2565, "box drawings down double and horizontal single", "╥", "So", 0));
        symbols.add(new Shapes(0x2566, "box drawings double down and horizontal", "╦", "So", 0));
        symbols.add(new Shapes(0x2567, "box drawings up single and horizontal double", "╧", "So", 0));
        symbols.add(new Shapes(0x2568, "box drawings up double and horizontal single", "╨", "So", 0));
        symbols.add(new Shapes(0x2569, "box drawings double up and horizontal", "╩", "So", 0));
        symbols.add(new Shapes(0x256A, "box drawings vertical single and horizontal double", "╪", "So", 0));
        symbols.add(new Shapes(0x256B, "box drawings vertical double and horizontal single", "╫", "So", 0));
        symbols.add(new Shapes(0x256C, "box drawings double vertical and horizontal", "╬", "So", 0));
        symbols.add(new Shapes(0x256D, "box drawings light arc down and right", "╭", "So", 0));
        symbols.add(new Shapes(0x256E, "box drawings light arc down and left", "╮", "So", 0));
        symbols.add(new Shapes(0x256F, "box drawings light arc up and left", "╯", "So", 0));
        symbols.add(new Shapes(0x2570, "box drawings light arc up and right", "╰", "So", 0));
        symbols.add(new Shapes(0x2571, "box drawings light diagonal upper right to lower left", "╱", "So", 0));
        symbols.add(new Shapes(0x2572, "box drawings light diagonal upper left to lower right", "╲", "So", 0));
        symbols.add(new Shapes(0x2573, "box drawings light diagonal cross", "╳", "So", 0));
        symbols.add(new Shapes(0x2574, "box drawings light left", "╴", "So", 0));
        symbols.add(new Shapes(0x2575, "box drawings light up", "╵", "So", 0));
        symbols.add(new Shapes(0x2576, "box drawings light right", "╶", "So", 0));
        symbols.add(new Shapes(0x2577, "box drawings light down", "╷", "So", 0));
        symbols.add(new Shapes(0x2578, "box drawings heavy left", "╸", "So", 0));
        symbols.add(new Shapes(0x2579, "box drawings heavy up", "╹", "So", 0));
        symbols.add(new Shapes(0x257A, "box drawings heavy right", "╺", "So", 0));
        symbols.add(new Shapes(0x257B, "box drawings heavy down", "╻", "So", 0));
        symbols.add(new Shapes(0x257C, "box drawings light left and heavy right", "╼", "So", 0));
        symbols.add(new Shapes(0x257D, "box drawings light up and heavy down", "╽", "So", 0));
        symbols.add(new Shapes(0x257E, "box drawings heavy left and light right", "╾", "So", 0));
        symbols.add(new Shapes(0x257F, "box drawings heavy up and light down", "╿", "So", 0));
        symbols.add(new Shapes(0x2580, "upper half block", "▀", "So", 0, null, "\\blockuphalf", null));
        symbols.add(new Shapes(0x2581, "lower one eighth block", "▁", "So", 0));
        symbols.add(new Shapes(0x2582, "lower one quarter block", "▂", "So", 0));
        symbols.add(new Shapes(0x2583, "lower three eighths block", "▃", "So", 0));
        symbols.add(new Shapes(0x2584, "lower half block", "▄", "So", 0, null, "\\blocklowhalf", null));
        symbols.add(new Shapes(0x2585, "lower five eighths block", "▅", "So", 0));
        symbols.add(new Shapes(0x2586, "lower three quarters block", "▆", "So", 0));
        symbols.add(new Shapes(0x2587, "lower seven eighths block", "▇", "So", 0));
        symbols.add(new Shapes(0x2588, "full block", "█", "So", 0, null, "\\blockfull", null));
        symbols.add(new Shapes(0x2589, "left seven eighths block", "▉", "So", 0));
        symbols.add(new Shapes(0x258A, "left three quarters block", "▊", "So", 0));
        symbols.add(new Shapes(0x258B, "left five eighths block", "▋", "So", 0));
        symbols.add(new Shapes(0x258C, "left half block", "▌", "So", 0, null, "\\blocklefthalf", null));
        symbols.add(new Shapes(0x258D, "left three eighths block", "▍", "So", 0));
        symbols.add(new Shapes(0x258E, "left one quarter block", "▎", "So", 0));
        symbols.add(new Shapes(0x258F, "left one eighth block", "▏", "So", 0));
        symbols.add(new Shapes(0x2590, "right half block", "▐", "So", 0, null, "\\blockrighthalf", null));
        symbols.add(new Shapes(0x2591, "light shade", "░", "So", 0, null, "\\blockqtrshaded", null));
        symbols.add(new Shapes(0x2592, "medium shade", "▒", "So", 0, null, "\\blockhalfshaded", null));
        symbols.add(new Shapes(0x2593, "dark shade", "▓", "So", 0, null, "\\blockthreeqtrshaded", null));
        symbols.add(new Shapes(0x2594, "upper one eighth block", "▔", "So", 0));
        symbols.add(new Shapes(0x2595, "right one eighth block", "▕", "So", 0));
        symbols.add(new Shapes(0x2596, "quadrant lower left", "▖", "So", 0));
        symbols.add(new Shapes(0x2597, "quadrant lower right", "▗", "So", 0));
        symbols.add(new Shapes(0x2598, "quadrant upper left", "▘", "So", 0));
        symbols.add(new Shapes(0x2599, "quadrant upper left and lower left and lower right", "▙", "So", 0));
        symbols.add(new Shapes(0x259A, "quadrant upper left and lower right", "▚", "So", 0));
        symbols.add(new Shapes(0x259B, "quadrant upper left and upper right and lower left", "▛", "So", 0));
        symbols.add(new Shapes(0x259C, "quadrant upper left and upper right and lower right", "▜", "So", 0));
        symbols.add(new Shapes(0x259D, "quadrant upper right", "▝", "So", 0));
        symbols.add(new Shapes(0x259E, "quadrant upper right and lower left", "▞", "So", 0));
        symbols.add(new Shapes(0x259F, "quadrant upper right and lower left and lower right", "▟", "So", 0));
        symbols.add(new Shapes(0x25A0, "black square", "■", "So", 0, null, "\\mdlgblksquare", null));
        symbols.add(new Shapes(0x25A1, "white square", "□", "So", 0, null, "\\mdlgwhtsquare", null));
        symbols.add(new Shapes(0x25A2, "white square with rounded corners", "▢", "So", 0, null, "\\squoval", null));
        symbols.add(new Shapes(0x25A3, "white square containing black small square", "▣", "So", 0, null, "\\blackinwhitesquare", null));
        symbols.add(new Shapes(0x25A4, "square with horizontal fill", "▤", "So", 0, null, "\\squarehfill", null));
        symbols.add(new Shapes(0x25A5, "square with vertical fill", "▥", "So", 0, null, "\\squarevfill", null));
        symbols.add(new Shapes(0x25A6, "square with orthogonal crosshatch fill", "▦", "So", 0, null, "\\squarehvfill", null));
        symbols.add(new Shapes(0x25A7, "square with upper left to lower right fill", "▧", "So", 0, null, "\\squarenwsefill", null));
        symbols.add(new Shapes(0x25A8, "square with upper right to lower left fill", "▨", "So", 0, null, "\\squareneswfill", null));
        symbols.add(new Shapes(0x25A9, "square with diagonal crosshatch fill", "▩", "So", 0, null, "\\squarecrossfill", null));
        symbols.add(new Shapes(0x25AA, "black small square", "▪", "So", 0, null, "\\smblksquare", null));
        symbols.add(new Shapes(0x25AB, "white small square", "▫", "So", 0, null, "\\smwhtsquare", null));
        symbols.add(new Shapes(0x25AC, "black rectangle", "▬", "So", 0, null, "\\hrectangleblack", null));
        symbols.add(new Shapes(0x25AD, "white rectangle", "▭", "So", 0, null, "\\hrectangle", null));
        symbols.add(new Shapes(0x25AE, "black vertical rectangle", "▮", "So", 0, null, "\\vrectangleblack", null));
        symbols.add(new Shapes(0x25AF, "white vertical rectangle", "▯", "So", 0, null, "\\vrectangle", null));
        symbols.add(new Shapes(0x25B0, "black parallelogram", "▰", "So", 0, null, "\\parallelogramblack", null));
        symbols.add(new Shapes(0x25B1, "white parallelogram", "▱", "So", 0, null, "\\parallelogram", null));
        symbols.add(new Shapes(0x25B2, "black up-pointing triangle", "▲", "So", 0, null, "\\bigblacktriangleup", null));
        symbols.add(new Shapes(0x25B3, "white up-pointing triangle", "△", "So", 0, "\\bigtriangleup", null, null));
        symbols.add(new Shapes(0x25B4, "black up-pointing small triangle", "▴", "So", 0, "\\blacktriangleup", "\\blacktriangle", null));
        symbols.add(new Shapes(0x25B5, "white up-pointing small triangle", "▵", "So", 0, "\\smalltriangleup", "\\vartriangle", null));
        symbols.add(new Shapes(0x25B6, "black right-pointing triangle", "▶", "So", 0, "\\RHD", "\\blacktriangleright", null));
        symbols.add(new Shapes(0x25B7, "white right-pointing triangle", "▷", "Sm", 0, "\\rhd", "\\triangleright", null));
        symbols.add(new Shapes(0x25B8, "black right-pointing small triangle", "▸", "So", 0, "\\blacktriangleright", "\\smallblacktriangleright", null));
        symbols.add(new Shapes(0x25B9, "white right-pointing small triangle", "▹", "So", 0, "\\smalltriangleright", null, null));
        symbols.add(new Shapes(0x25BA, "black right-pointing pointer", "►", "So", 0, null, "\\blackpointerright", null));
        symbols.add(new Shapes(0x25BB, "white right-pointing pointer", "▻", "So", 0, null, "\\whitepointerright", null));
        symbols.add(new Shapes(0x25BC, "black down-pointing triangle", "▼", "So", 0, null, "\\bigblacktriangledown", null));
        symbols.add(new Shapes(0x25BD, "white down-pointing triangle", "▽", "So", 0, "\\bigtriangledown", null, null));
        symbols.add(new Shapes(0x25BE, "black down-pointing small triangle", "▾", "So", 0, "\\blacktriangledown", null, null));
        symbols.add(new Shapes(0x25BF, "white down-pointing small triangle", "▿", "So", 0, "\\smalltriangledown", "\\triangledown", null));
        symbols.add(new Shapes(0x25C0, "black left-pointing triangle", "◀", "So", 0, "\\LHD", "\\blacktriangleleft", null));
        symbols.add(new Shapes(0x25C1, "white left-pointing triangle", "◁", "Sm", 0, "\\lhd", "\\triangleleft", null));
        symbols.add(new Shapes(0x25C2, "black left-pointing small triangle", "◂", "So", 0, "\\blacktriangleleft", "\\smallblacktriangleleft", null));
        symbols.add(new Shapes(0x25C3, "white left-pointing small triangle", "◃", "So", 0, "\\smalltriangleleft", null, null));
        symbols.add(new Shapes(0x25C4, "black left-pointing pointer", "◄", "So", 0, null, "\\blackpointerleft", null));
        symbols.add(new Shapes(0x25C5, "white left-pointing pointer", "◅", "So", 0, null, "\\whitepointerleft", null));
        symbols.add(new Shapes(0x25C6, "black diamond", "◆", "So", 0, "\\Diamondblack", "\\mdlgblkdiamond", null));
        symbols.add(new Shapes(0x25C7, "white diamond", "◇", "So", 0, "\\Diamond", "\\mdlgwhtdiamond", null));
        symbols.add(new Shapes(0x25C8, "white diamond containing black small diamond", "◈", "So", 0, null, "\\blackinwhitediamond", null));
        symbols.add(new Shapes(0x25C9, "fisheye", "◉", "So", 0, null, "\\fisheye", null));
        symbols.add(new Shapes(0x25CA, "lozenge", "◊", "So", 0, "\\lozenge", "\\mdlgwhtlozenge", null));
        symbols.add(new Shapes(0x25CB, "white circle", "○", "So", 0, "\\Circle", "\\mdlgwhtcircle", null));
        symbols.add(new Shapes(0x25CC, "dotted circle", "◌", "So", 0, null, "\\dottedcircle", null));
        symbols.add(new Shapes(0x25CD, "circle with vertical fill", "◍", "So", 0, null, "\\circlevertfill", null));
        symbols.add(new Shapes(0x25CE, "bullseye", "◎", "So", 0, null, "\\bullseye", null));
        symbols.add(new Shapes(0x25CF, "black circle", "●", "So", 0, "\\CIRCLE", "\\mdlgblkcircle", null));
        symbols.add(new Shapes(0x25D0, "circle with left half black", "◐", "So", 0, "\\LEFTcircle", "\\circlelefthalfblack", null));
        symbols.add(new Shapes(0x25D1, "circle with right half black", "◑", "So", 0, "\\RIGHTcircle", "\\circlerighthalfblack", null));
        symbols.add(new Shapes(0x25D2, "circle with lower half black", "◒", "So", 0, null, "\\circlebottomhalfblack", null));
        symbols.add(new Shapes(0x25D3, "circle with upper half black", "◓", "So", 0, null, "\\circletophalfblack", null));
        symbols.add(new Shapes(0x25D4, "circle with upper right quadrant black", "◔", "So", 0, null, "\\circleurquadblack", null));
        symbols.add(new Shapes(0x25D5, "circle with all but upper left quadrant black", "◕", "So", 0, null, "\\blackcircleulquadwhite", null));
        symbols.add(new Shapes(0x25D6, "left half black circle", "◖", "So", 0, "\\LEFTCIRCLE", "\\blacklefthalfcircle", null));
        symbols.add(new Shapes(0x25D7, "right half black circle", "◗", "So", 0, "\\RIGHTCIRCLE", "\\blackrighthalfcircle", null));
        symbols.add(new Shapes(0x25D8, "inverse bullet", "◘", "So", 0, null, "\\inversebullet", null));
        symbols.add(new Shapes(0x25D9, "inverse white circle", "◙", "So", 0, null, "\\inversewhitecircle", null));
        symbols.add(new Shapes(0x25DA, "upper half inverse white circle", "◚", "So", 0, null, "\\invwhiteupperhalfcircle", null));
        symbols.add(new Shapes(0x25DB, "lower half inverse white circle", "◛", "So", 0, null, "\\invwhitelowerhalfcircle", null));
        symbols.add(new Shapes(0x25DC, "upper left quadrant circular arc", "◜", "So", 0, null, "\\ularc", null));
        symbols.add(new Shapes(0x25DD, "upper right quadrant circular arc", "◝", "So", 0, null, "\\urarc", null));
        symbols.add(new Shapes(0x25DE, "lower right quadrant circular arc", "◞", "So", 0, null, "\\lrarc", null));
        symbols.add(new Shapes(0x25DF, "lower left quadrant circular arc", "◟", "So", 0, null, "\\llarc", null));
        symbols.add(new Shapes(0x25E0, "upper half circle", "◠", "So", 0, null, "\\topsemicircle", null));
        symbols.add(new Shapes(0x25E1, "lower half circle", "◡", "So", 0, null, "\\botsemicircle", null));
        symbols.add(new Shapes(0x25E2, "black lower right triangle", "◢", "So", 0, null, "\\lrblacktriangle", null));
        symbols.add(new Shapes(0x25E3, "black lower left triangle", "◣", "So", 0, null, "\\llblacktriangle", null));
        symbols.add(new Shapes(0x25E4, "black upper left triangle", "◤", "So", 0, null, "\\ulblacktriangle", null));
        symbols.add(new Shapes(0x25E5, "black upper right triangle", "◥", "So", 0, null, "\\urblacktriangle", null));
        symbols.add(new Shapes(0x25E6, "white bullet", "◦", "So", 0, null, "\\smwhtcircle", null));
        symbols.add(new Shapes(0x25E7, "square with left half black", "◧", "So", 0, null, "\\squareleftblack", null));
        symbols.add(new Shapes(0x25E8, "square with right half black", "◨", "So", 0, null, "\\squarerightblack", null));
        symbols.add(new Shapes(0x25E9, "square with upper left diagonal half black", "◩", "So", 0, null, "\\squareulblack", null));
        symbols.add(new Shapes(0x25EA, "square with lower right diagonal half black", "◪", "So", 0, null, "\\squarelrblack", null));
        symbols.add(new Shapes(0x25EB, "white square with vertical bisecting line", "◫", "So", 0, "\\boxbar", null, null));
        symbols.add(new Shapes(0x25EC, "white up-pointing triangle with dot", "◬", "So", 0, null, "\\trianglecdot", null));
        symbols.add(new Shapes(0x25ED, "up-pointing triangle with left half black", "◭", "So", 0, null, "\\triangleleftblack", null));
        symbols.add(new Shapes(0x25EE, "up-pointing triangle with right half black", "◮", "So", 0, null, "\\trianglerightblack", null));
        symbols.add(new Shapes(0x25EF, "large circle", "◯", "So", 0, null, "\\lgwhtcircle", null));
        symbols.add(new Shapes(0x25F0, "white square with upper left quadrant", "◰", "So", 0, null, "\\squareulquad", null));
        symbols.add(new Shapes(0x25F1, "white square with lower left quadrant", "◱", "So", 0, null, "\\squarellquad", null));
        symbols.add(new Shapes(0x25F2, "white square with lower right quadrant", "◲", "So", 0, null, "\\squarelrquad", null));
        symbols.add(new Shapes(0x25F3, "white square with upper right quadrant", "◳", "So", 0, null, "\\squareurquad", null));
        symbols.add(new Shapes(0x25F4, "white circle with upper left quadrant", "◴", "So", 0, null, "\\circleulquad", null));
        symbols.add(new Shapes(0x25F5, "white circle with lower left quadrant", "◵", "So", 0, null, "\\circlellquad", null));
        symbols.add(new Shapes(0x25F6, "white circle with lower right quadrant", "◶", "So", 0, null, "\\circlelrquad", null));
        symbols.add(new Shapes(0x25F7, "white circle with upper right quadrant", "◷", "So", 0, null, "\\circleurquad", null));
        symbols.add(new Shapes(0x25F8, "upper left triangle", "◸", "Sm", 0, null, "\\ultriangle", null));
        symbols.add(new Shapes(0x25F9, "upper right triangle", "◹", "Sm", 0, null, "\\urtriangle", null));
        symbols.add(new Shapes(0x25FA, "lower left triangle", "◺", "Sm", 0, null, "\\lltriangle", null));
        symbols.add(new Shapes(0x25FB, "white medium square", "◻", "Sm", 0, "\\square", "\\mdwhtsquare", null));
        symbols.add(new Shapes(0x25FC, "black medium square", "◼", "Sm", 0, "\\blacksquare", "\\mdblksquare", null));
        symbols.add(new Shapes(0x25FD, "white medium small square", "◽", "Sm", 0, null, "\\mdsmwhtsquare", null));
        symbols.add(new Shapes(0x25FE, "black medium small square", "◾", "Sm", 0, null, "\\mdsmblksquare", null));
        symbols.add(new Shapes(0x25FF, "lower right triangle", "◿", "Sm", 0, null, "\\lrtriangle", null));
        symbols.add(new Shapes(0x2700, "black safety scissors", "✀", "So", 0));
        symbols.add(new Shapes(0x2701, "upper blade scissors", "✁", "So", 0));
        symbols.add(new Shapes(0x2702, "black scissors", "✂", "So", 0));
        symbols.add(new Shapes(0x2703, "lower blade scissors", "✃", "So", 0));
        symbols.add(new Shapes(0x2704, "white scissors", "✄", "So", 0));
        symbols.add(new Shapes(0x2705, "white heavy check mark", "✅", "So", 0));
        symbols.add(new Shapes(0x2706, "telephone location sign", "✆", "So", 0));
        symbols.add(new Shapes(0x2707, "tape drive", "✇", "So", 0));
        symbols.add(new Shapes(0x2708, "airplane", "✈", "So", 0));
        symbols.add(new Shapes(0x2709, "envelope", "✉", "So", 0));
        symbols.add(new Shapes(0x270A, "raised fist", "✊", "So", 0));
        symbols.add(new Shapes(0x270B, "raised hand", "✋", "So", 0));
        symbols.add(new Shapes(0x270C, "victory hand", "✌", "So", 0));
        symbols.add(new Shapes(0x270D, "writing hand", "✍", "So", 0));
        symbols.add(new Shapes(0x270E, "lower right pencil", "✎", "So", 0, "\\pencil", null, null));
        symbols.add(new Shapes(0x270F, "pencil", "✏", "So", 0));
        symbols.add(new Shapes(0x2710, "upper right pencil", "✐", "So", 0));
        symbols.add(new Shapes(0x2711, "white nib", "✑", "So", 0));
        symbols.add(new Shapes(0x2712, "black nib", "✒", "So", 0));
        symbols.add(new Shapes(0x2713, "check mark", "✓", "So", 0, "\\checkmark", null, null));
        symbols.add(new Shapes(0x2714, "heavy check mark", "✔", "So", 0));
        symbols.add(new Shapes(0x2715, "multiplication x", "✕", "So", 0));
        symbols.add(new Shapes(0x2716, "heavy multiplication x", "✖", "So", 0));
        symbols.add(new Shapes(0x2717, "ballot x", "✗", "So", 0, "\\ballotx", null, null));
        symbols.add(new Shapes(0x2718, "heavy ballot x", "✘", "So", 0));
        symbols.add(new Shapes(0x2719, "outlined cross", "✙", "So", 0));
        symbols.add(new Shapes(0x271A, "heavy cross", "✚", "So", 0));
        symbols.add(new Shapes(0x271B, "open centre cross", "✛", "So", 0));
        symbols.add(new Shapes(0x271C, "heavy open centre cross", "✜", "So", 0));
        symbols.add(new Shapes(0x271D, "latin cross", "✝", "So", 0));
        symbols.add(new Shapes(0x271E, "shadowed white latin cross", "✞", "So", 0));
        symbols.add(new Shapes(0x271F, "outlined latin cross", "✟", "So", 0));
        symbols.add(new Shapes(0x2720, "maltese cross", "✠", "So", 0, "\\maltese", null, null));
        symbols.add(new Shapes(0x2721, "star of david", "✡", "So", 0));
        symbols.add(new Shapes(0x2722, "four teardrop-spoked asterisk", "✢", "So", 0));
        symbols.add(new Shapes(0x2723, "four balloon-spoked asterisk", "✣", "So", 0));
        symbols.add(new Shapes(0x2724, "heavy four balloon-spoked asterisk", "✤", "So", 0));
        symbols.add(new Shapes(0x2725, "four club-spoked asterisk", "✥", "So", 0));
        symbols.add(new Shapes(0x2726, "black four pointed star", "✦", "So", 0));
        symbols.add(new Shapes(0x2727, "white four pointed star", "✧", "So", 0));
        symbols.add(new Shapes(0x2728, "sparkles", "✨", "So", 0));
        symbols.add(new Shapes(0x2729, "stress outlined white star", "✩", "So", 0));
        symbols.add(new Shapes(0x272A, "circled white star", "✪", "So", 0, null, "\\circledstar", null));
        symbols.add(new Shapes(0x272B, "open centre black star", "✫", "So", 0));
        symbols.add(new Shapes(0x272C, "black centre white star", "✬", "So", 0));
        symbols.add(new Shapes(0x272D, "outlined black star", "✭", "So", 0));
        symbols.add(new Shapes(0x272E, "heavy outlined black star", "✮", "So", 0));
        symbols.add(new Shapes(0x272F, "pinwheel star", "✯", "So", 0));
        symbols.add(new Shapes(0x2730, "shadowed white star", "✰", "So", 0));
        symbols.add(new Shapes(0x2731, "heavy asterisk", "✱", "So", 0));
        symbols.add(new Shapes(0x2732, "open centre asterisk", "✲", "So", 0));
        symbols.add(new Shapes(0x2733, "eight spoked asterisk", "✳", "So", 0));
        symbols.add(new Shapes(0x2734, "eight pointed black star", "✴", "So", 0));
        symbols.add(new Shapes(0x2735, "eight pointed pinwheel star", "✵", "So", 0));
        symbols.add(new Shapes(0x2736, "six pointed black star", "✶", "So", 0, null, "\\varstar", null));
        symbols.add(new Shapes(0x2737, "eight pointed rectilinear black star", "✷", "So", 0));
        symbols.add(new Shapes(0x2738, "heavy eight pointed rectilinear black star", "✸", "So", 0));
        symbols.add(new Shapes(0x2739, "twelve pointed black star", "✹", "So", 0));
        symbols.add(new Shapes(0x273A, "sixteen pointed asterisk", "✺", "So", 0));
        symbols.add(new Shapes(0x273B, "teardrop-spoked asterisk", "✻", "So", 0));
        symbols.add(new Shapes(0x273C, "open centre teardrop-spoked asterisk", "✼", "So", 0));
        symbols.add(new Shapes(0x273D, "heavy teardrop-spoked asterisk", "✽", "So", 0, null, "\\dingasterisk", null));
        symbols.add(new Shapes(0x273E, "six petalled black and white florette", "✾", "So", 0));
        symbols.add(new Shapes(0x273F, "black florette", "✿", "So", 0));
        symbols.add(new Shapes(0x2740, "white florette", "❀", "So", 0));
        symbols.add(new Shapes(0x2741, "eight petalled outlined black florette", "❁", "So", 0));
        symbols.add(new Shapes(0x2742, "circled open centre eight pointed star", "❂", "So", 0));
        symbols.add(new Shapes(0x2743, "heavy teardrop-spoked pinwheel asterisk", "❃", "So", 0));
        symbols.add(new Shapes(0x2744, "snowflake", "❄", "So", 0));
        symbols.add(new Shapes(0x2745, "tight trifoliate snowflake", "❅", "So", 0));
        symbols.add(new Shapes(0x2746, "heavy chevron snowflake", "❆", "So", 0));
        symbols.add(new Shapes(0x2747, "sparkle", "❇", "So", 0));
        symbols.add(new Shapes(0x2748, "heavy sparkle", "❈", "So", 0));
        symbols.add(new Shapes(0x2749, "balloon-spoked asterisk", "❉", "So", 0));
        symbols.add(new Shapes(0x274A, "eight teardrop-spoked propeller asterisk", "❊", "So", 0));
        symbols.add(new Shapes(0x274B, "heavy eight teardrop-spoked propeller asterisk", "❋", "So", 0));
        symbols.add(new Shapes(0x274C, "cross mark", "❌", "So", 0));
        symbols.add(new Shapes(0x274D, "shadowed white circle", "❍", "So", 0));
        symbols.add(new Shapes(0x274E, "negative squared cross mark", "❎", "So", 0));
        symbols.add(new Shapes(0x274F, "lower right drop-shadowed white square", "❏", "So", 0));
        symbols.add(new Shapes(0x2750, "upper right drop-shadowed white square", "❐", "So", 0));
        symbols.add(new Shapes(0x2751, "lower right shadowed white square", "❑", "So", 0));
        symbols.add(new Shapes(0x2752, "upper right shadowed white square", "❒", "So", 0));
        symbols.add(new Shapes(0x2753, "black question mark ornament", "❓", "So", 0));
        symbols.add(new Shapes(0x2754, "white question mark ornament", "❔", "So", 0));
        symbols.add(new Shapes(0x2755, "white exclamation mark ornament", "❕", "So", 0));
        symbols.add(new Shapes(0x2756, "black diamond minus white x", "❖", "So", 0));
        symbols.add(new Shapes(0x2757, "heavy exclamation mark", "❗", "So", 0));
        symbols.add(new Shapes(0x2758, "light vertical bar", "❘", "So", 0));
        symbols.add(new Shapes(0x2759, "medium vertical bar", "❙", "So", 0));
        symbols.add(new Shapes(0x275A, "heavy vertical bar", "❚", "So", 0));
        symbols.add(new Shapes(0x275B, "heavy single turned comma quotation mark ornament", "❛", "So", 0));
        symbols.add(new Shapes(0x275C, "heavy single comma quotation mark ornament", "❜", "So", 0));
        symbols.add(new Shapes(0x275D, "heavy double turned comma quotation mark ornament", "❝", "So", 0));
        symbols.add(new Shapes(0x275E, "heavy double comma quotation mark ornament", "❞", "So", 0));
        symbols.add(new Shapes(0x275F, "heavy low single comma quotation mark ornament", "❟", "So", 0));
        symbols.add(new Shapes(0x2760, "heavy low double comma quotation mark ornament", "❠", "So", 0));
        symbols.add(new Shapes(0x2761, "curved stem paragraph sign ornament", "❡", "So", 0));
        symbols.add(new Shapes(0x2762, "heavy exclamation mark ornament", "❢", "So", 0));
        symbols.add(new Shapes(0x2763, "heavy heart exclamation mark ornament", "❣", "So", 0));
        symbols.add(new Shapes(0x2764, "heavy black heart", "❤", "So", 0));
        symbols.add(new Shapes(0x2765, "rotated heavy black heart bullet", "❥", "So", 0));
        symbols.add(new Shapes(0x2766, "floral heart", "❦", "So", 0));
        symbols.add(new Shapes(0x2767, "rotated floral heart bullet", "❧", "So", 0));
        symbols.add(new Shapes(0x2768, "medium left parenthesis ornament", "❨", "Ps", 0));
        symbols.add(new Shapes(0x2769, "medium right parenthesis ornament", "❩", "Pe", 0));
        symbols.add(new Shapes(0x276A, "medium flattened left parenthesis ornament", "❪", "Ps", 0));
        symbols.add(new Shapes(0x276B, "medium flattened right parenthesis ornament", "❫", "Pe", 0));
        symbols.add(new Shapes(0x276C, "medium left-pointing angle bracket ornament", "❬", "Ps", 0));
        symbols.add(new Shapes(0x276D, "medium right-pointing angle bracket ornament", "❭", "Pe", 0));
        symbols.add(new Shapes(0x276E, "heavy left-pointing angle quotation mark ornament", "❮", "Ps", 0));
        symbols.add(new Shapes(0x276F, "heavy right-pointing angle quotation mark ornament", "❯", "Pe", 0));
        symbols.add(new Shapes(0x2770, "heavy left-pointing angle bracket ornament", "❰", "Ps", 0));
        symbols.add(new Shapes(0x2771, "heavy right-pointing angle bracket ornament", "❱", "Pe", 0));
        symbols.add(new Shapes(0x2772, "light left tortoise shell bracket ornament", "❲", "Ps", 0, null, "\\lbrbrak", null));
        symbols.add(new Shapes(0x2773, "light right tortoise shell bracket ornament", "❳", "Pe", 0, null, "\\rbrbrak", null));
        symbols.add(new Shapes(0x2774, "medium left curly bracket ornament", "❴", "Ps", 0));
        symbols.add(new Shapes(0x2775, "medium right curly bracket ornament", "❵", "Pe", 0));
        symbols.add(new Shapes(0x2776, "dingbat negative circled 1", "❶", "No", 0));
        symbols.add(new Shapes(0x2777, "dingbat negative circled 2", "❷", "No", 0));
        symbols.add(new Shapes(0x2778, "dingbat negative circled 3", "❸", "No", 0));
        symbols.add(new Shapes(0x2779, "dingbat negative circled 4", "❹", "No", 0));
        symbols.add(new Shapes(0x277A, "dingbat negative circled 5", "❺", "No", 0));
        symbols.add(new Shapes(0x277B, "dingbat negative circled 6", "❻", "No", 0));
        symbols.add(new Shapes(0x277C, "dingbat negative circled 7", "❼", "No", 0));
        symbols.add(new Shapes(0x277D, "dingbat negative circled 8", "❽", "No", 0));
        symbols.add(new Shapes(0x277E, "dingbat negative circled 9", "❾", "No", 0));
        symbols.add(new Shapes(0x277F, "dingbat negative circled number ten", "❿", "No", 0));
        symbols.add(new Shapes(0x2780, "dingbat circled sans-serif 1", "➀", "No", 0));
        symbols.add(new Shapes(0x2781, "dingbat circled sans-serif 2", "➁", "No", 0));
        symbols.add(new Shapes(0x2782, "dingbat circled sans-serif 3", "➂", "No", 0));
        symbols.add(new Shapes(0x2783, "dingbat circled sans-serif 4", "➃", "No", 0));
        symbols.add(new Shapes(0x2784, "dingbat circled sans-serif 5", "➄", "No", 0));
        symbols.add(new Shapes(0x2785, "dingbat circled sans-serif 6", "➅", "No", 0));
        symbols.add(new Shapes(0x2786, "dingbat circled sans-serif 7", "➆", "No", 0));
        symbols.add(new Shapes(0x2787, "dingbat circled sans-serif 8", "➇", "No", 0));
        symbols.add(new Shapes(0x2788, "dingbat circled sans-serif 9", "➈", "No", 0));
        symbols.add(new Shapes(0x2789, "dingbat circled sans-serif number ten", "➉", "No", 0));
        symbols.add(new Shapes(0x278A, "dingbat negative circled sans-serif 1", "➊", "No", 0));
        symbols.add(new Shapes(0x278B, "dingbat negative circled sans-serif 2", "➋", "No", 0));
        symbols.add(new Shapes(0x278C, "dingbat negative circled sans-serif 3", "➌", "No", 0));
        symbols.add(new Shapes(0x278D, "dingbat negative circled sans-serif 4", "➍", "No", 0));
        symbols.add(new Shapes(0x278E, "dingbat negative circled sans-serif 5", "➎", "No", 0));
        symbols.add(new Shapes(0x278F, "dingbat negative circled sans-serif 6", "➏", "No", 0));
        symbols.add(new Shapes(0x2790, "dingbat negative circled sans-serif 7", "➐", "No", 0));
        symbols.add(new Shapes(0x2791, "dingbat negative circled sans-serif 8", "➑", "No", 0));
        symbols.add(new Shapes(0x2792, "dingbat negative circled sans-serif 9", "➒", "No", 0));
        symbols.add(new Shapes(0x2793, "dingbat negative circled sans-serif number ten", "➓", "No", 0));
        symbols.add(new Shapes(0x2794, "heavy wide-headed rightwards arrow", "➔", "So", 0));
        symbols.add(new Shapes(0x2795, "heavy plus sign", "➕", "So", 0));
        symbols.add(new Shapes(0x2796, "heavy minus sign", "➖", "So", 0));
        symbols.add(new Shapes(0x2797, "heavy division sign", "➗", "So", 0));
        symbols.add(new Shapes(0x2798, "heavy south east arrow", "➘", "So", 0));
        symbols.add(new Shapes(0x2799, "heavy rightwards arrow", "➙", "So", 0));
        symbols.add(new Shapes(0x279A, "heavy north east arrow", "➚", "So", 0));
        symbols.add(new Shapes(0x279B, "drafting point rightwards arrow", "➛", "So", 0, null, "\\draftingarrow", null));
        symbols.add(new Shapes(0x279C, "heavy round-tipped rightwards arrow", "➜", "So", 0));
        symbols.add(new Shapes(0x279D, "triangle-headed rightwards arrow", "➝", "So", 0));
        symbols.add(new Shapes(0x279E, "heavy triangle-headed rightwards arrow", "➞", "So", 0));
        symbols.add(new Shapes(0x279F, "dashed triangle-headed rightwards arrow", "➟", "So", 0));
        symbols.add(new Shapes(0x27A0, "heavy dashed triangle-headed rightwards arrow", "➠", "So", 0));
        symbols.add(new Shapes(0x27A1, "black rightwards arrow", "➡", "So", 0));
        symbols.add(new Shapes(0x27A2, "three-d top-lighted rightwards arrowhead", "➢", "So", 0, "\\arrowbullet", null, null));
        symbols.add(new Shapes(0x27A3, "three-d bottom-lighted rightwards arrowhead", "➣", "So", 0));
        symbols.add(new Shapes(0x27A4, "black rightwards arrowhead", "➤", "So", 0));
        symbols.add(new Shapes(0x27A5, "heavy black curved downwards and rightwards arrow", "➥", "So", 0));
        symbols.add(new Shapes(0x27A6, "heavy black curved upwards and rightwards arrow", "➦", "So", 0));
        symbols.add(new Shapes(0x27A7, "squat black rightwards arrow", "➧", "So", 0));
        symbols.add(new Shapes(0x27A8, "heavy concave-pointed black rightwards arrow", "➨", "So", 0));
        symbols.add(new Shapes(0x27A9, "right-shaded white rightwards arrow", "➩", "So", 0));
        symbols.add(new Shapes(0x27AA, "left-shaded white rightwards arrow", "➪", "So", 0));
        symbols.add(new Shapes(0x27AB, "back-tilted shadowed white rightwards arrow", "➫", "So", 0));
        symbols.add(new Shapes(0x27AC, "front-tilted shadowed white rightwards arrow", "➬", "So", 0));
        symbols.add(new Shapes(0x27AD, "heavy lower right-shadowed white rightwards arrow", "➭", "So", 0));
        symbols.add(new Shapes(0x27AE, "heavy upper right-shadowed white rightwards arrow", "➮", "So", 0));
        symbols.add(new Shapes(0x27AF, "notched lower right-shadowed white rightwards arrow", "➯", "So", 0));
        symbols.add(new Shapes(0x27B0, "curly loop", "➰", "So", 0));
        symbols.add(new Shapes(0x27B1, "notched upper right-shadowed white rightwards arrow", "➱", "So", 0));
        symbols.add(new Shapes(0x27B2, "circled heavy white rightwards arrow", "➲", "So", 0));
        symbols.add(new Shapes(0x27B3, "white-feathered rightwards arrow", "➳", "So", 0));
        symbols.add(new Shapes(0x27B4, "black-feathered south east arrow", "➴", "So", 0));
        symbols.add(new Shapes(0x27B5, "black-feathered rightwards arrow", "➵", "So", 0));
        symbols.add(new Shapes(0x27B6, "black-feathered north east arrow", "➶", "So", 0));
        symbols.add(new Shapes(0x27B7, "heavy black-feathered south east arrow", "➷", "So", 0));
        symbols.add(new Shapes(0x27B8, "heavy black-feathered rightwards arrow", "➸", "So", 0));
        symbols.add(new Shapes(0x27B9, "heavy black-feathered north east arrow", "➹", "So", 0));
        symbols.add(new Shapes(0x27BA, "teardrop-barbed rightwards arrow", "➺", "So", 0));
        symbols.add(new Shapes(0x27BB, "heavy teardrop-shanked rightwards arrow", "➻", "So", 0));
        symbols.add(new Shapes(0x27BC, "wedge-tailed rightwards arrow", "➼", "So", 0));
        symbols.add(new Shapes(0x27BD, "heavy wedge-tailed rightwards arrow", "➽", "So", 0));
        symbols.add(new Shapes(0x27BE, "open-outlined rightwards arrow", "➾", "So", 0));
        symbols.add(new Shapes(0x27BF, "double curly loop", "➿", "So", 0));
        symbols.add(new Shapes(0x1F650, "north west pointing leaf", "🙐", "So", 0));
        symbols.add(new Shapes(0x1F651, "south west pointing leaf", "🙑", "So", 0));
        symbols.add(new Shapes(0x1F652, "north east pointing leaf", "🙒", "So", 0));
        symbols.add(new Shapes(0x1F653, "south east pointing leaf", "🙓", "So", 0));
        symbols.add(new Shapes(0x1F654, "turned north west pointing leaf", "🙔", "So", 0));
        symbols.add(new Shapes(0x1F655, "turned south west pointing leaf", "🙕", "So", 0));
        symbols.add(new Shapes(0x1F656, "turned north east pointing leaf", "🙖", "So", 0));
        symbols.add(new Shapes(0x1F657, "turned south east pointing leaf", "🙗", "So", 0));
        symbols.add(new Shapes(0x1F658, "north west pointing vine leaf", "🙘", "So", 0));
        symbols.add(new Shapes(0x1F659, "south west pointing vine leaf", "🙙", "So", 0));
        symbols.add(new Shapes(0x1F65A, "north east pointing vine leaf", "🙚", "So", 0));
        symbols.add(new Shapes(0x1F65B, "south east pointing vine leaf", "🙛", "So", 0));
        symbols.add(new Shapes(0x1F65C, "heavy north west pointing vine leaf", "🙜", "So", 0));
        symbols.add(new Shapes(0x1F65D, "heavy south west pointing vine leaf", "🙝", "So", 0));
        symbols.add(new Shapes(0x1F65E, "heavy north east pointing vine leaf", "🙞", "So", 0));
        symbols.add(new Shapes(0x1F65F, "heavy south east pointing vine leaf", "🙟", "So", 0));
        symbols.add(new Shapes(0x1F660, "north west pointing bud", "🙠", "So", 0));
        symbols.add(new Shapes(0x1F661, "south west pointing bud", "🙡", "So", 0));
        symbols.add(new Shapes(0x1F662, "north east pointing bud", "🙢", "So", 0));
        symbols.add(new Shapes(0x1F663, "south east pointing bud", "🙣", "So", 0));
        symbols.add(new Shapes(0x1F664, "heavy north west pointing bud", "🙤", "So", 0));
        symbols.add(new Shapes(0x1F665, "heavy south west pointing bud", "🙥", "So", 0));
        symbols.add(new Shapes(0x1F666, "heavy north east pointing bud", "🙦", "So", 0));
        symbols.add(new Shapes(0x1F667, "heavy south east pointing bud", "🙧", "So", 0));
        symbols.add(new Shapes(0x1F668, "hollow quilt square ornament", "🙨", "So", 0));
        symbols.add(new Shapes(0x1F669, "hollow quilt square ornament in black square", "🙩", "So", 0));
        symbols.add(new Shapes(0x1F66A, "solid quilt square ornament", "🙪", "So", 0));
        symbols.add(new Shapes(0x1F66B, "solid quilt square ornament in black square", "🙫", "So", 0));
        symbols.add(new Shapes(0x1F66C, "leftwards rocket", "🙬", "So", 0));
        symbols.add(new Shapes(0x1F66D, "upwards rocket", "🙭", "So", 0));
        symbols.add(new Shapes(0x1F66E, "rightwards rocket", "🙮", "So", 0));
        symbols.add(new Shapes(0x1F66F, "downwards rocket", "🙯", "So", 0));
        symbols.add(new Shapes(0x1F670, "script ligature et ornament", "🙰", "So", 0));
        symbols.add(new Shapes(0x1F671, "heavy script ligature et ornament", "🙱", "So", 0));
        symbols.add(new Shapes(0x1F672, "ligature open et ornament", "🙲", "So", 0));
        symbols.add(new Shapes(0x1F673, "heavy ligature open et ornament", "🙳", "So", 0));
        symbols.add(new Shapes(0x1F674, "heavy ampersand ornament", "🙴", "So", 0));
        symbols.add(new Shapes(0x1F675, "swash ampersand ornament", "🙵", "So", 0));
        symbols.add(new Shapes(0x1F676, "sans-serif heavy double turned comma quotation mark ornament", "🙶", "So", 0));
        symbols.add(new Shapes(0x1F677, "sans-serif heavy double comma quotation mark ornament", "🙷", "So", 0));
        symbols.add(new Shapes(0x1F678, "sans-serif heavy low double comma quotation mark ornament", "🙸", "So", 0));
        symbols.add(new Shapes(0x1F679, "heavy interrobang ornament", "🙹", "So", 0));
        symbols.add(new Shapes(0x1F67A, "sans-serif interrobang ornament", "🙺", "So", 0));
        symbols.add(new Shapes(0x1F67B, "heavy sans-serif interrobang ornament", "🙻", "So", 0));
        symbols.add(new Shapes(0x1F67C, "very heavy solidus", "🙼", "So", 0));
        symbols.add(new Shapes(0x1F67D, "very heavy reverse solidus", "🙽", "So", 0));
        symbols.add(new Shapes(0x1F67E, "checker board", "🙾", "So", 0));
        symbols.add(new Shapes(0x1F67F, "reverse checker board", "🙿", "So", 0));
        symbols.add(new Shapes(0x1F700, "alchemical for quintessence", "🜀", "So", 0));
        symbols.add(new Shapes(0x1F701, "alchemical for air", "🜁", "So", 0));
        symbols.add(new Shapes(0x1F702, "alchemical for fire", "🜂", "So", 0));
        symbols.add(new Shapes(0x1F703, "alchemical for earth", "🜃", "So", 0));
        symbols.add(new Shapes(0x1F704, "alchemical for water", "🜄", "So", 0));
        symbols.add(new Shapes(0x1F705, "alchemical for aquafortis", "🜅", "So", 0));
        symbols.add(new Shapes(0x1F706, "alchemical for aqua regia", "🜆", "So", 0));
        symbols.add(new Shapes(0x1F707, "alchemical for aqua regia-2", "🜇", "So", 0));
        symbols.add(new Shapes(0x1F708, "alchemical for aqua vitae", "🜈", "So", 0));
        symbols.add(new Shapes(0x1F709, "alchemical for aqua vitae-2", "🜉", "So", 0));
        symbols.add(new Shapes(0x1F70A, "alchemical for vinegar", "🜊", "So", 0));
        symbols.add(new Shapes(0x1F70B, "alchemical for vinegar-2", "🜋", "So", 0));
        symbols.add(new Shapes(0x1F70C, "alchemical for vinegar-3", "🜌", "So", 0));
        symbols.add(new Shapes(0x1F70D, "alchemical for sulfur", "🜍", "So", 0));
        symbols.add(new Shapes(0x1F70E, "alchemical for philosophers sulfur", "🜎", "So", 0));
        symbols.add(new Shapes(0x1F70F, "alchemical for black sulfur", "🜏", "So", 0));
        symbols.add(new Shapes(0x1F710, "alchemical for mercury sublimate", "🜐", "So", 0));
        symbols.add(new Shapes(0x1F711, "alchemical for mercury sublimate-2", "🜑", "So", 0));
        symbols.add(new Shapes(0x1F712, "alchemical for mercury sublimate-3", "🜒", "So", 0));
        symbols.add(new Shapes(0x1F713, "alchemical for cinnabar", "🜓", "So", 0));
        symbols.add(new Shapes(0x1F714, "alchemical for salt", "🜔", "So", 0));
        symbols.add(new Shapes(0x1F715, "alchemical for nitre", "🜕", "So", 0));
        symbols.add(new Shapes(0x1F716, "alchemical for vitriol", "🜖", "So", 0));
        symbols.add(new Shapes(0x1F717, "alchemical for vitriol-2", "🜗", "So", 0));
        symbols.add(new Shapes(0x1F718, "alchemical for rock salt", "🜘", "So", 0));
        symbols.add(new Shapes(0x1F719, "alchemical for rock salt-2", "🜙", "So", 0));
        symbols.add(new Shapes(0x1F71A, "alchemical for gold", "🜚", "So", 0));
        symbols.add(new Shapes(0x1F71B, "alchemical for silver", "🜛", "So", 0));
        symbols.add(new Shapes(0x1F71C, "alchemical for iron ore", "🜜", "So", 0));
        symbols.add(new Shapes(0x1F71D, "alchemical for iron ore-2", "🜝", "So", 0));
        symbols.add(new Shapes(0x1F71E, "alchemical for crocus of iron", "🜞", "So", 0));
        symbols.add(new Shapes(0x1F71F, "alchemical for regulus of iron", "🜟", "So", 0));
        symbols.add(new Shapes(0x1F720, "alchemical for copper ore", "🜠", "So", 0));
        symbols.add(new Shapes(0x1F721, "alchemical for iron-copper ore", "🜡", "So", 0));
        symbols.add(new Shapes(0x1F722, "alchemical for sublimate of copper", "🜢", "So", 0));
        symbols.add(new Shapes(0x1F723, "alchemical for crocus of copper", "🜣", "So", 0));
        symbols.add(new Shapes(0x1F724, "alchemical for crocus of copper-2", "🜤", "So", 0));
        symbols.add(new Shapes(0x1F725, "alchemical for copper antimoniate", "🜥", "So", 0));
        symbols.add(new Shapes(0x1F726, "alchemical for salt of copper antimoniate", "🜦", "So", 0));
        symbols.add(new Shapes(0x1F727, "alchemical for sublimate of salt of copper", "🜧", "So", 0));
        symbols.add(new Shapes(0x1F728, "alchemical for verdigris", "🜨", "So", 0));
        symbols.add(new Shapes(0x1F729, "alchemical for tin ore", "🜩", "So", 0));
        symbols.add(new Shapes(0x1F72A, "alchemical for lead ore", "🜪", "So", 0));
        symbols.add(new Shapes(0x1F72B, "alchemical for antimony ore", "🜫", "So", 0));
        symbols.add(new Shapes(0x1F72C, "alchemical for sublimate of antimony", "🜬", "So", 0));
        symbols.add(new Shapes(0x1F72D, "alchemical for salt of antimony", "🜭", "So", 0));
        symbols.add(new Shapes(0x1F72E, "alchemical for sublimate of salt of antimony", "🜮", "So", 0));
        symbols.add(new Shapes(0x1F72F, "alchemical for vinegar of antimony", "🜯", "So", 0));
        symbols.add(new Shapes(0x1F730, "alchemical for regulus of antimony", "🜰", "So", 0));
        symbols.add(new Shapes(0x1F731, "alchemical for regulus of antimony-2", "🜱", "So", 0));
        symbols.add(new Shapes(0x1F732, "alchemical for regulus", "🜲", "So", 0));
        symbols.add(new Shapes(0x1F733, "alchemical for regulus-2", "🜳", "So", 0));
        symbols.add(new Shapes(0x1F734, "alchemical for regulus-3", "🜴", "So", 0));
        symbols.add(new Shapes(0x1F735, "alchemical for regulus-4", "🜵", "So", 0));
        symbols.add(new Shapes(0x1F736, "alchemical for alkali", "🜶", "So", 0));
        symbols.add(new Shapes(0x1F737, "alchemical for alkali-2", "🜷", "So", 0));
        symbols.add(new Shapes(0x1F738, "alchemical for marcasite", "🜸", "So", 0));
        symbols.add(new Shapes(0x1F739, "alchemical for sal-ammoniac", "🜹", "So", 0));
        symbols.add(new Shapes(0x1F73A, "alchemical for arsenic", "🜺", "So", 0));
        symbols.add(new Shapes(0x1F73B, "alchemical for realgar", "🜻", "So", 0));
        symbols.add(new Shapes(0x1F73C, "alchemical for realgar-2", "🜼", "So", 0));
        symbols.add(new Shapes(0x1F73D, "alchemical for auripigment", "🜽", "So", 0));
        symbols.add(new Shapes(0x1F73E, "alchemical for bismuth ore", "🜾", "So", 0));
        symbols.add(new Shapes(0x1F73F, "alchemical for tartar", "🜿", "So", 0));
        symbols.add(new Shapes(0x1F740, "alchemical for tartar-2", "🝀", "So", 0));
        symbols.add(new Shapes(0x1F741, "alchemical for quick lime", "🝁", "So", 0));
        symbols.add(new Shapes(0x1F742, "alchemical for borax", "🝂", "So", 0));
        symbols.add(new Shapes(0x1F743, "alchemical for borax-2", "🝃", "So", 0));
        symbols.add(new Shapes(0x1F744, "alchemical for borax-3", "🝄", "So", 0));
        symbols.add(new Shapes(0x1F745, "alchemical for alum", "🝅", "So", 0));
        symbols.add(new Shapes(0x1F746, "alchemical for oil", "🝆", "So", 0));
        symbols.add(new Shapes(0x1F747, "alchemical for spirit", "🝇", "So", 0));
        symbols.add(new Shapes(0x1F748, "alchemical for tincture", "🝈", "So", 0));
        symbols.add(new Shapes(0x1F749, "alchemical for gum", "🝉", "So", 0));
        symbols.add(new Shapes(0x1F74A, "alchemical for wax", "🝊", "So", 0));
        symbols.add(new Shapes(0x1F74B, "alchemical for powder", "🝋", "So", 0));
        symbols.add(new Shapes(0x1F74C, "alchemical for calx", "🝌", "So", 0));
        symbols.add(new Shapes(0x1F74D, "alchemical for tutty", "🝍", "So", 0));
        symbols.add(new Shapes(0x1F74E, "alchemical for caput mortuum", "🝎", "So", 0));
        symbols.add(new Shapes(0x1F74F, "alchemical for scepter of jove", "🝏", "So", 0));
        symbols.add(new Shapes(0x1F750, "alchemical for caduceus", "🝐", "So", 0));
        symbols.add(new Shapes(0x1F751, "alchemical for trident", "🝑", "So", 0));
        symbols.add(new Shapes(0x1F752, "alchemical for starred trident", "🝒", "So", 0));
        symbols.add(new Shapes(0x1F753, "alchemical for lodestone", "🝓", "So", 0));
        symbols.add(new Shapes(0x1F754, "alchemical for soap", "🝔", "So", 0));
        symbols.add(new Shapes(0x1F755, "alchemical for urine", "🝕", "So", 0));
        symbols.add(new Shapes(0x1F756, "alchemical for horse dung", "🝖", "So", 0));
        symbols.add(new Shapes(0x1F757, "alchemical for ashes", "🝗", "So", 0));
        symbols.add(new Shapes(0x1F758, "alchemical for pot ashes", "🝘", "So", 0));
        symbols.add(new Shapes(0x1F759, "alchemical for brick", "🝙", "So", 0));
        symbols.add(new Shapes(0x1F75A, "alchemical for powdered brick", "🝚", "So", 0));
        symbols.add(new Shapes(0x1F75B, "alchemical for amalgam", "🝛", "So", 0));
        symbols.add(new Shapes(0x1F75C, "alchemical for stratum super stratum", "🝜", "So", 0));
        symbols.add(new Shapes(0x1F75D, "alchemical for stratum super stratum-2", "🝝", "So", 0));
        symbols.add(new Shapes(0x1F75E, "alchemical for sublimation", "🝞", "So", 0));
        symbols.add(new Shapes(0x1F75F, "alchemical for precipitate", "🝟", "So", 0));
        symbols.add(new Shapes(0x1F760, "alchemical for distill", "🝠", "So", 0));
        symbols.add(new Shapes(0x1F761, "alchemical for dissolve", "🝡", "So", 0));
        symbols.add(new Shapes(0x1F762, "alchemical for dissolve-2", "🝢", "So", 0));
        symbols.add(new Shapes(0x1F763, "alchemical for purify", "🝣", "So", 0));
        symbols.add(new Shapes(0x1F764, "alchemical for putrefaction", "🝤", "So", 0));
        symbols.add(new Shapes(0x1F765, "alchemical for crucible", "🝥", "So", 0));
        symbols.add(new Shapes(0x1F766, "alchemical for crucible-2", "🝦", "So", 0));
        symbols.add(new Shapes(0x1F767, "alchemical for crucible-3", "🝧", "So", 0));
        symbols.add(new Shapes(0x1F768, "alchemical for crucible-4", "🝨", "So", 0));
        symbols.add(new Shapes(0x1F769, "alchemical for crucible-5", "🝩", "So", 0));
        symbols.add(new Shapes(0x1F76A, "alchemical for alembic", "🝪", "So", 0));
        symbols.add(new Shapes(0x1F76B, "alchemical for bath of mary", "🝫", "So", 0));
        symbols.add(new Shapes(0x1F76C, "alchemical for bath of vapours", "🝬", "So", 0));
        symbols.add(new Shapes(0x1F76D, "alchemical for retort", "🝭", "So", 0));
        symbols.add(new Shapes(0x1F76E, "alchemical for hour", "🝮", "So", 0));
        symbols.add(new Shapes(0x1F76F, "alchemical for night", "🝯", "So", 0));
        symbols.add(new Shapes(0x1F770, "alchemical for day-night", "🝰", "So", 0));
        symbols.add(new Shapes(0x1F771, "alchemical for month", "🝱", "So", 0));
        symbols.add(new Shapes(0x1F772, "alchemical for half dram", "🝲", "So", 0));
        symbols.add(new Shapes(0x1F773, "alchemical for half ounce", "🝳", "So", 0));
        symbols.add(new Shapes(0x1F780, "black left-pointing isosceles right triangle", "🞀", "So", 0));
        symbols.add(new Shapes(0x1F781, "black up-pointing isosceles right triangle", "🞁", "So", 0));
        symbols.add(new Shapes(0x1F782, "black right-pointing isosceles right triangle", "🞂", "So", 0));
        symbols.add(new Shapes(0x1F783, "black down-pointing isosceles right triangle", "🞃", "So", 0));
        symbols.add(new Shapes(0x1F784, "black slightly small circle", "🞄", "So", 0));
        symbols.add(new Shapes(0x1F785, "medium bold white circle", "🞅", "So", 0));
        symbols.add(new Shapes(0x1F786, "bold white circle", "🞆", "So", 0));
        symbols.add(new Shapes(0x1F787, "heavy white circle", "🞇", "So", 0));
        symbols.add(new Shapes(0x1F788, "very heavy white circle", "🞈", "So", 0));
        symbols.add(new Shapes(0x1F789, "extremely heavy white circle", "🞉", "So", 0));
        symbols.add(new Shapes(0x1F78A, "white circle containing black small circle", "🞊", "So", 0));
        symbols.add(new Shapes(0x1F78B, "round target", "🞋", "So", 0));
        symbols.add(new Shapes(0x1F78C, "black tiny square", "🞌", "So", 0));
        symbols.add(new Shapes(0x1F78D, "black slightly small square", "🞍", "So", 0));
        symbols.add(new Shapes(0x1F78E, "light white square", "🞎", "So", 0));
        symbols.add(new Shapes(0x1F78F, "medium white square", "🞏", "So", 0));
        symbols.add(new Shapes(0x1F790, "bold white square", "🞐", "So", 0));
        symbols.add(new Shapes(0x1F791, "heavy white square", "🞑", "So", 0));
        symbols.add(new Shapes(0x1F792, "very heavy white square", "🞒", "So", 0));
        symbols.add(new Shapes(0x1F793, "extremely heavy white square", "🞓", "So", 0));
        symbols.add(new Shapes(0x1F794, "white square containing black very small square", "🞔", "So", 0));
        symbols.add(new Shapes(0x1F795, "white square containing black medium square", "🞕", "So", 0));
        symbols.add(new Shapes(0x1F796, "square target", "🞖", "So", 0));
        symbols.add(new Shapes(0x1F797, "black tiny diamond", "🞗", "So", 0));
        symbols.add(new Shapes(0x1F798, "black very small diamond", "🞘", "So", 0));
        symbols.add(new Shapes(0x1F799, "black medium small diamond", "🞙", "So", 0));
        symbols.add(new Shapes(0x1F79A, "white diamond containing black very small diamond", "🞚", "So", 0));
        symbols.add(new Shapes(0x1F79B, "white diamond containing black medium diamond", "🞛", "So", 0));
        symbols.add(new Shapes(0x1F79C, "diamond target", "🞜", "So", 0));
        symbols.add(new Shapes(0x1F79D, "black tiny lozenge", "🞝", "So", 0));
        symbols.add(new Shapes(0x1F79E, "black very small lozenge", "🞞", "So", 0));
        symbols.add(new Shapes(0x1F79F, "black medium small lozenge", "🞟", "So", 0));
        symbols.add(new Shapes(0x1F7A0, "white lozenge containing black small lozenge", "🞠", "So", 0));
        symbols.add(new Shapes(0x1F7A1, "thin cross", "🞡", "So", 0));
        symbols.add(new Shapes(0x1F7A2, "light cross", "🞢", "So", 0));
        symbols.add(new Shapes(0x1F7A3, "medium cross", "🞣", "So", 0));
        symbols.add(new Shapes(0x1F7A4, "bold cross", "🞤", "So", 0));
        symbols.add(new Shapes(0x1F7A5, "very bold cross", "🞥", "So", 0));
        symbols.add(new Shapes(0x1F7A6, "very heavy cross", "🞦", "So", 0));
        symbols.add(new Shapes(0x1F7A7, "extremely heavy cross", "🞧", "So", 0));
        symbols.add(new Shapes(0x1F7A8, "thin saltire", "🞨", "So", 0));
        symbols.add(new Shapes(0x1F7A9, "light saltire", "🞩", "So", 0));
        symbols.add(new Shapes(0x1F7AA, "medium saltire", "🞪", "So", 0));
        symbols.add(new Shapes(0x1F7AB, "bold saltire", "🞫", "So", 0));
        symbols.add(new Shapes(0x1F7AC, "heavy saltire", "🞬", "So", 0));
        symbols.add(new Shapes(0x1F7AD, "very heavy saltire", "🞭", "So", 0));
        symbols.add(new Shapes(0x1F7AE, "extremely heavy saltire", "🞮", "So", 0));
        symbols.add(new Shapes(0x1F7AF, "light five spoked asterisk", "🞯", "So", 0));
        symbols.add(new Shapes(0x1F7B0, "medium five spoked asterisk", "🞰", "So", 0));
        symbols.add(new Shapes(0x1F7B1, "bold five spoked asterisk", "🞱", "So", 0));
        symbols.add(new Shapes(0x1F7B2, "heavy five spoked asterisk", "🞲", "So", 0));
        symbols.add(new Shapes(0x1F7B3, "very heavy five spoked asterisk", "🞳", "So", 0));
        symbols.add(new Shapes(0x1F7B4, "extremely heavy five spoked asterisk", "🞴", "So", 0));
        symbols.add(new Shapes(0x1F7B5, "light six spoked asterisk", "🞵", "So", 0));
        symbols.add(new Shapes(0x1F7B6, "medium six spoked asterisk", "🞶", "So", 0));
        symbols.add(new Shapes(0x1F7B7, "bold six spoked asterisk", "🞷", "So", 0));
        symbols.add(new Shapes(0x1F7B8, "heavy six spoked asterisk", "🞸", "So", 0));
        symbols.add(new Shapes(0x1F7B9, "very heavy six spoked asterisk", "🞹", "So", 0));
        symbols.add(new Shapes(0x1F7BA, "extremely heavy six spoked asterisk", "🞺", "So", 0));
        symbols.add(new Shapes(0x1F7BB, "light eight spoked asterisk", "🞻", "So", 0));
        symbols.add(new Shapes(0x1F7BC, "medium eight spoked asterisk", "🞼", "So", 0));
        symbols.add(new Shapes(0x1F7BD, "bold eight spoked asterisk", "🞽", "So", 0));
        symbols.add(new Shapes(0x1F7BE, "heavy eight spoked asterisk", "🞾", "So", 0));
        symbols.add(new Shapes(0x1F7BF, "very heavy eight spoked asterisk", "🞿", "So", 0));
        symbols.add(new Shapes(0x1F7C0, "light three pointed black star", "🟀", "So", 0));
        symbols.add(new Shapes(0x1F7C1, "medium three pointed black star", "🟁", "So", 0));
        symbols.add(new Shapes(0x1F7C2, "three pointed black star", "🟂", "So", 0));
        symbols.add(new Shapes(0x1F7C3, "medium three pointed pinwheel star", "🟃", "So", 0));
        symbols.add(new Shapes(0x1F7C4, "light four pointed black star", "🟄", "So", 0));
        symbols.add(new Shapes(0x1F7C5, "medium four pointed black star", "🟅", "So", 0));
        symbols.add(new Shapes(0x1F7C6, "four pointed black star", "🟆", "So", 0));
        symbols.add(new Shapes(0x1F7C7, "medium four pointed pinwheel star", "🟇", "So", 0));
        symbols.add(new Shapes(0x1F7C8, "reverse light four pointed pinwheel star", "🟈", "So", 0));
        symbols.add(new Shapes(0x1F7C9, "light five pointed black star", "🟉", "So", 0));
        symbols.add(new Shapes(0x1F7CA, "heavy five pointed black star", "🟊", "So", 0));
        symbols.add(new Shapes(0x1F7CB, "medium six pointed black star", "🟋", "So", 0));
        symbols.add(new Shapes(0x1F7CC, "heavy six pointed black star", "🟌", "So", 0));
        symbols.add(new Shapes(0x1F7CD, "six pointed pinwheel star", "🟍", "So", 0));
        symbols.add(new Shapes(0x1F7CE, "medium eight pointed black star", "🟎", "So", 0));
        symbols.add(new Shapes(0x1F7CF, "heavy eight pointed black star", "🟏", "So", 0));
        symbols.add(new Shapes(0x1F7D0, "very heavy eight pointed black star", "🟐", "So", 0));
        symbols.add(new Shapes(0x1F7D1, "heavy eight pointed pinwheel star", "🟑", "So", 0));
        symbols.add(new Shapes(0x1F7D2, "light twelve pointed black star", "🟒", "So", 0));
        symbols.add(new Shapes(0x1F7D3, "heavy twelve pointed black star", "🟓", "So", 0));
        symbols.add(new Shapes(0x1F7D4, "heavy twelve pointed pinwheel star", "🟔", "So", 0));
        symbols.add(new Shapes(0x1F7D5, "circled triangle", "🟕", "So", 0));
        symbols.add(new Shapes(0x1F7D6, "negative circled triangle", "🟖", "So", 0));
        symbols.add(new Shapes(0x1F7D7, "circled square", "🟗", "So", 0));
        symbols.add(new Shapes(0x1F7D8, "negative circled square", "🟘", "So", 0));
        symbols.add(new Shapes(0x1F7E0, "large orange circle", "🟠", "So", 0));
        symbols.add(new Shapes(0x1F7E1, "large yellow circle", "🟡", "So", 0));
        symbols.add(new Shapes(0x1F7E2, "large green circle", "🟢", "So", 0));
        symbols.add(new Shapes(0x1F7E3, "large purple circle", "🟣", "So", 0));
        symbols.add(new Shapes(0x1F7E4, "large brown circle", "🟤", "So", 0));
        symbols.add(new Shapes(0x1F7E5, "large red square", "🟥", "So", 0));
        symbols.add(new Shapes(0x1F7E6, "large blue square", "🟦", "So", 0));
        symbols.add(new Shapes(0x1F7E7, "large orange square", "🟧", "So", 0));
        symbols.add(new Shapes(0x1F7E8, "large yellow square", "🟨", "So", 0));
        symbols.add(new Shapes(0x1F7E9, "large green square", "🟩", "So", 0));
        symbols.add(new Shapes(0x1F7EA, "large purple square", "🟪", "So", 0));
        symbols.add(new Shapes(0x1F7EB, "large brown square", "🟫", "So", 0));
    }
}